cypress-io/cypress-documentation

source/api/utilities/blob.md
- for https://github.com/cypress-io/cypress/pull/7795
-  (plus cleaning up some docs to be clearer)
=> Updates for blob from 5.0

source/_changelogs/4.10.0.md
=> 4.10.0 Release

source/guides/guides/command-line.md
Link to instructions on how to change cache path under print cache CLI command
=> Link to change cache folder

source/_data/courses.yml
Added reference to Cypress course on Coursinator: https://coursinator.com/course/the-ultimate-cypress-testing-hands-on-guide
=> Added Cypress course on Coursinator.com

source/api/commands/route.md, source/api/commands/server.md
=> Fix broken links to Don't Stub Responses

source/faq/questions/general-questions-faq.md
=> updates mobile testing FAQ to close issue-2975

source/guides/guides/environment-variables.md, source/guides/references/configuration.md
- closes #2980 
I also extended the recipe here https://github.com/cypress-io/cypress-example-recipes/commit/8b5cb040ca6435fde441dbc56c8238f3a2848269 and https://github.com/cypress-io/cypress-example-recipes/pull/530
=> few tweaks to env variable

source/guides/guides/command-line.md
=> add section explaining exit codes

source/_data/plugins.yml
Add my library to the plugins yml
=> Add cypress-autostub plugin

source/api/commands/scrollto.md
- For https://github.com/cypress-io/cypress/pull/8003
- Alphabetize options
- Add example of ignoring error checking
=> Add ensureScrollable option

source/api/plugins/writing-a-plugin.md
Related to cypress-io/cypress#6352
=> The explanation about the version number property in config of the plugin

source/guides/guides/debugging.md, source/guides/references/error-messages.md
because they are good examples
=> add a few links to our blog posts

source/_data/blogs.yml
Updated the 2 links that needed to be updated.
Sorry for a bit of a mess (4 commits) - my editor 'prettified' the double quotes so I went back and undid that and then I added the new link that was given to me just now.
7Daytheory
=> Updated links on line 820 and 828 in blogs.yml

source/guides/guides/parallelization.md
=> remove aws codebuild id as this is not detected in Cypress

source/faq/questions/using-cypress-faq.md
=> adds FAQ for testing charts to resolve issue-2699

source/_data/webinars.yml
=> adds webinar to resolve issue-2977

source/guides/guides/parallelization.md
For https://github.com/cypress-io/cypress/pull/8159
=> Add AWS build id to parallel docs

source/_changelogs/4.12.1.md
=> 4.12.1 Release

lib/tags/usage.js, source/api/commands/click.md, source/api/commands/dblclick.md, source/api/commands/rightclick.md, source/api/commands/type.md
Related to cypress-io/cypress#8114
=> Add doc for click modifiers.

source/_data/plugins.yml
This adds the newly released Bison template to the plugins page.
=> Add Bison to plugins page

source/guides/getting-started/installing-cypress.md, source/guides/references/migration-guide.md
From https://github.com/cypress-io/cypress/issues/8429
=> Be more specific about Node.js 11 not being supported in Cypress.

source/api/commands/route2.md
- Closes cypress-io/cypress#8489
- Closes cypress-io/cypress#8468
=> docs: network stubbing v2

source/_data/plugins.yml
https://github.com/bahmutov/cypress-extends
=> Add @bahmutov/cypress-extends plugin

source/api/commands/route2.md
=> docs(route2): note followRedirect

source/api/commands/route2.md
Reverts cypress-io/cypress-documentation#3132
=> Revert "docs(route2): note followRedirect"

source/api/commands/route2.md, source/api/plugins/browser-launch-api.md
- to the recipe
- to the open and closed issues
=> Add route2 links

source/api/commands/route2.md
For https://github.com/cypress-io/cypress/pull/8109
=> docs(route2): document delayMs and throttleKbps for StaticResponses

gulpfile.js, package-lock.json, package.json
An attempt to fix the revisioning task running the machine out of memory .
=> Break up gulp revision tasks

source/_data/plugins.yml
tested, open-source, documented
=> Add cypress-expect to the list of plugins

source/faq/questions/using-cypress-faq.md
since people are asking about it
=> add cucumber question to our faq

source/api/commands/task.md
- https://github.com/cypress-io/cypress/issues/5539
- https://github.com/cypress-io/cypress/issues/4980
=> add note about task argument

source/faq/questions/using-cypress-faq.md
mostly for Algolia search sake
=> add React testing app FAQ

source/guides/references/migration-guide.md
Changes "Dev" to "Dec" (December).
=> Fix typo in Migration Guide

source/guides/guides/cross-browser-testing.md, source/guides/guides/launching-browsers.md, source/guides/references/configuration.md, source/guides/references/error-messages.md
for https://github.com/cypress-io/cypress/pull/8586
=> docs: remove Firefox beta status, update firefoxGcInterval docs

source/api/commands/route2.md
https://github.com/cypress-io/cypress/pull/8698
=> docs: update route2 req types

source/guides/core-concepts/conditional-testing.md
Zone.js repository has moved. The original location is archived.
=> update link to zone.js

source/guides/core-concepts/introduction-to-cypress.md
=> Fix incorrect comment in code sample

source/_partial/allowed_test_config.md, source/guides/core-concepts/writing-and-organizing-tests.md
=> clarify test config values

source/faq/questions/using-cypress-faq.md
=> add faq answer about graphql

source/faq/questions/using-cypress-faq.md
=> add question about model-based testing

source/guides/guides/command-line.md
https://github.com/cypress-io/cypress/pull/8766
=> docs(command-line): document cypress cache prune

source/api/commands/viewport.md
Add 3 iPhone model in viewportPresets.
@close https://github.com/cypress-io/cypress/pull/8624#pullrequestreview-505439887
=> reflect PR#8624 change to Docs

source/guides/guides/command-line.md, source/guides/guides/launching-browsers.md, source/guides/references/troubleshooting.md, themes/cypress/source/css/_media_queries.scss
https://github.com/cypress-io/cypress/issues/6389
https://github.com/cypress-io/cypress/pull/8743
=> Update command-line to include new browser option

source/guides/guides/command-line.md
https://github.com/cypress-io/cypress/pull/8689
=> docs for CYPRESS_NO_COMMAND_LOG

source/api/commands/get.md
=> Clarify cy.get() behavior since it's diverted from jQuery

source/api/utilities/blob.md
Other way to upload an image fixture without using jquery plugin
=> Using an image fixture for upload

source/_data/courses.yml
Hey, @bahmutov, I have just launched a course of test automation with Cypress and Percy on my online school (soon also on Udemy), and I'd love to have it listed here, as my other two courses.
Cheers!
=> Add new course of Cypress and Percy

source/guides/guides/parallelization.md
=> Fix reference to incorrect CircleID

source/guides/references/troubleshooting.md
=> Add note about Windows DEBUG command prompt

source/guides/core-concepts/introduction-to-cypress.md
=> Fix sentence construction of what cypress commands yield/chain

source/guides/references/configuration.md
=> Reference correct supportFile config

source/api/cypress-api/cookies.md
=> Rephrase 'log out' within cookies doc to say 'log' or 'generate logs'

source/faq/questions/using-cypress-faq.md
=> add FAQ question about performance testing

source/guides/references/configuration.md
To clarify the common question https://github.com/cypress-io/cypress/issues/9078
=> add note about system node for native modules

source/api/commands/route2.md
for https://github.com/cypress-io/cypress/pull/8974
=> docs(route2): document dynamic request aliasing

circle.yml, source/api/commands/clock.md, source/api/commands/tick.md
- stops the CI build if found any stray hexo tags
- closes #3309 (clock page)
- found and fixed escaped hexo tag on tick page
=> fix a few stray hexo tags

source/api/commands/task.md, source/api/events/catalog-of-events.md, source/faq/questions/using-cypress-faq.md, source/guides/dashboard/projects.md, source/guides/guides/continuous-integration.md, source/guides/guides/network-requests.md, source/guides/tooling/visual-testing.md
=> add more blog post links

source/guides/guides/command-line.md
Not sure why all the extra commits in this PR, is this "master" vs "develop" artifacts?
=> Document printing electron / node version from Cypress

source/guides/references/migration-guide.md
For https://github.com/cypress-io/cypress/pull/9266
=> docs(migration-guide): document cy.wait(alias) type change

source/api/commands/wait.md
Correct minor spelling issue in docs
=> Correct spelling for responseTimeout

source/faq/questions/using-cypress-faq.md
since it came up in my conversations
=> add faq question about jest snapshots

source/guides/references/migration-guide.md
=> Fixed typos

source/_data/plugins.yml
PR to add the cypress-teamcity-reporter to the list of plugins.
=> add plugin cypress-teamcity-reporter

source/api/commands/intercept.md
to clarify confusing parts for our users
=> add small notes to the cy.intercept doc page

source/api/cypress-api/dom.md
to tell people how to debug problems
=> add link to the debugging blog post

source/api/commands/intercept.md
Because people are confused https://gitter.im/cypress-io/cypress?at=5fca2e8556507459cc614484
=> add note that every intercept is reset before each test

lib/tags/usage.js, source/_changelogs/6.1.0.md, source/_partial/allowed_test_config.md, source/api/commands/check.md, source/api/commands/clear.md, source/api/commands/click.md, source/api/commands/dblclick.md, source/api/commands/rightclick.md, source/api/commands/trigger.md, source/api/commands/type.md, source/api/commands/uncheck.md, source/api/utilities/moment.md, source/guides/core-concepts/interacting-with-elements.md, source/guides/references/configuration.md
=> 6.1.0 Release

source/api/commands/wait.md
=> Fix `status` prop on cy.wait() to work for intercept

source/api/commands/intercept.md
For https://github.com/cypress-io/cypress/pull/9603
=> docs(intercept): add error property to yielded cy.intercept object

source/_data/plugins.yml
- docs(plugins): Add cypress-fail-fast plugin
=> Add cypress-fail-fast plugin

source/api/commands/intercept.md
=> add more explicit list of topics to cy.intercept external link

cypress/integration/sidebar_spec.js, scripts/helpers.js
=> fix: highlight sidebar link by full page path

source/api/commands/task.md
- closes #3407
Trying to use a realistic example, J
=> explain the single argument in cy.task

source/faq/questions/using-cypress-faq.md
- closes #3408
- expand the answer about uploading file to have keyword "attachFile" that our users search for
- add FAQ answer about testing library - our users search for a lot of the methods that come from that library
=> fill missing attach file text

source/guides/core-concepts/writing-and-organizing-tests.md
To make finding the root cause of https://github.com/cypress-io/cypress/issues/14226 easier
=> add note about troubleshooting finding specs

circle.yml, cypress.json, cypress/integration/examples/blogs/images_spec.js, cypress/integration/examples/blogs/links_spec.js, cypress/integration/examples/blogs/urls_spec.js, cypress/integration/examples/examples_spec.js, cypress/integration/examples/utils.js, cypress/plugins/index.js, package-lock.json, package.json
closes #3399 
cuts the CI testing time from 2 minutes to under 1 minute
I have written a blog showing how to split a long spec into shorter ones https://glebbahmutov.com/blog/split-spec/
=> refactor the examples spec

source/_data/sidebar.yml, source/api/plugins/after-spec-api.md, source/api/plugins/before-run-api.md, source/api/plugins/before-spec-api.md, source/api/plugins/writing-a-plugin.md, source/guides/references/experiments.md, source/guides/tooling/plugins-guide.md, themes/cypress/languages/en.yml
For https://github.com/cypress-io/cypress/pull/14238
=> Add doc for before:run event

source/api/commands/intercept.md
For https://github.com/cypress-io/cypress/pull/14241
=> docs(intercept): document matchUrlAgainstPath

source/_data/sidebar.yml, source/api/plugins/after-run-api.md, source/api/plugins/after-spec-api.md, source/api/plugins/before-run-api.md, source/api/plugins/before-spec-api.md, source/api/plugins/writing-a-plugin.md, source/guides/references/experiments.md, source/guides/tooling/plugins-guide.md, themes/cypress/languages/en.yml
For https://github.com/cypress-io/cypress/pull/14263
=> Add doc for after:run event

source/faq/questions/general-questions-faq.md
Had a couple of people ask in the chat when the next release of Cypress is happening
=> add an faq question about releases

source/faq/questions/dashboard-faq.md
=> Update FAQ on usage limit being reached

source/guides/getting-started/installing-cypress.md
=> Installing Cypress, Fix Missing Space

source/guides/component-testing/introduction.md
This PR fixes a broken link in the docs
=> fix(component-testing): broken link inn docs

source/guides/component-testing/introduction.md
=> Update introduction.md - Vue GitHub repo URL

source/api/cypress-api/custom-commands.md, source/api/utilities/moment.md, source/guides/references/configuration.md
a few answers and additional links
=> add note about interactive mode in the config

source/api/commands/intercept.md, source/guides/references/migration-guide.md
Closes https://github.com/cypress-io/cypress-documentation/issues/3403. See https://github.com/cypress-io/cypress/issues/9302#issuecomment-745518565
=> document breaking change between cy.route & cy.intercept

source/guides/core-concepts/introduction-to-cypress.md
=> Fix order of args to map

source/_changelogs/6.2.1.md
=> 6.2.1 Release

source/guides/references/configuration.md
To answer this https://github.com/cypress-io/cypress/discussions/14414
=> Explain how to see the bundled Node version

source/_data/courses.yml
I've just launched a new course on Udemy, and I'd like to have it listed here, together with my other courses.
Also, I have changed the title of one of my courses, so I'm updating it here.
=> Add new course and fix another course title

source/guides/tooling/code-coverage.md
=> Add link to the backend code coverage

source/faq/questions/using-cypress-faq.md
=> Update example for default required input versus custom validation msg

source/api/commands/task.md
I saw similar questions several times, and after reading `cy.task` API doc think it was confusing. Also, having examples as h2 helps with links
=> explain cy.task result better

source/guides/references/migration-guide.md
Addressing confusion in https://github.com/cypress-io/cypress/issues/14461 and https://github.com/cypress-io/cypress/issues/14458
=> Add example for migration when url arg + fix links in addendum

source/api/events/catalog-of-events.md, source/guides/references/troubleshooting.md
Due to changes from https://github.com/cypress-io/cypress/pull/14583
=> Debug updates - need 'Verbose' logging

source/api/commands/eq.md, source/api/commands/intercept.md
To answer https://github.com/cypress-io/cypress/discussions/14631
=> add note about cy.request bypassing cy.intercept

source/api/commands/intercept.md
Just add a little comma that was missing
=> docs(intercept): fix little missing comma

source/faq/questions/general-questions-faq.md
I get this question periodically, it would be nice to help users
https://twitter.com/OliinykI/status/1349806732013432834
=> add faq question about javascript learning resources

cypress/integration/examples/examples_spec.js, cypress/integration/examples/talks_spec.js
to speed up running in parallel
=> split examples spec into two

source/guides/core-concepts/cypress-studio.md
=> fix: broken link to RWA example

index.js, package-lock.json, package.json
Moment.js is no longer maintained. Replace its usage with dayjs.
=> Replace moment dep (no longer maintained) with dayjs

source/api/cypress-api/custom-commands.md, source/guides/references/assertions.md
=> explain negative assertions

source/guides/references/assertions.md
=> add multiple assertion advice

circle.yml, cypress/integration/examples/examples_spec.js, cypress/integration/examples/talks_spec.js, package-lock.json, package.json, source/api/commands/intercept.md, source/faq/questions/general-questions-faq.md, source/guides/core-concepts/cypress-studio.md
For https://github.com/cypress-io/cypress/pull/14709
=> docs: note removal of cy.route2 alias

source/guides/guides/command-line.md, source/guides/guides/module-api.md
for confusion reported by the user https://github.com/cypress-io/cypress/issues/14532
=> clarify spec parameter is relative to the current working directory

source/_data/plugins.yml, source/api/commands/hover.md
=> Adding cypress-real-events plugin

source/_data/webinars.yml
=> add link to Cypress webinars youtube playlist

source/guides/guides/continuous-integration.md
weird that we never had them in our CI docs
=> add sections about github actions and netlify

source/guides/references/configuration.md
Should help with https://github.com/cypress-io/circleci-orb/issues/328
=> add note how to debug specs not found error

source/api/commands/visit.md
To remove the confusion described in https://github.com/cypress-io/cypress/issues/4450#issuecomment-778110994
=> explain visit and local files better

source/faq/questions/general-questions-faq.md
to answer questions like https://twitter.com/a081286/status/1361290739473207299
=> explain the issues that are pending release

source/guides/references/troubleshooting.md
watching files, calling a task, fixtures
=> add a few more debug sources

source/api/commands/intercept.md
to resolve the confusion https://github.com/cypress-io/cypress/issues/15139
=> clarify adding headers in cy.intercept

source/guides/references/configuration.md
=> docs: document `redirectionLimit`

source/_data/courses.yml
I worked very hard to cover everything in my new course, I hope that you will add it :)
=> Add my Udemy Course :)

source/guides/component-testing/introduction.md
The react documentation was still using the old plugin references. I changed that to the current state of the project.
=> Changed the react documentation

source/api/plugins/browser-launch-api.md
Since we never had such an example, comes from https://glebbahmutov.com/blog/anchor-ping/
=> add example of setting Firefox flag when launching

source/guides/references/troubleshooting.md
=> explain how to debug the cy.request command

source/api/commands/within.md
=> explain how to temporarily escape within context

package-lock.json, source/guides/testing-strategies/amazon-cognito-authentication.md, source/guides/testing-strategies/auth0-authentication.md, source/guides/testing-strategies/okta-authentication.md
Per https://github.com/cypress-io/cypress-realworld-app/issues/793
=> Reference RWA commands for starting auth branches in auth guides

.husky/commit-msg, .husky/pre-commit, package.json
- the lint-staged command was running in the commit message validation hook
- lint-staged automatically stages updated files to the commit so I removed git add from the config
=> fix: lint staged needs to happen pre commit

content/api/events/catalog-of-events.md, content/guides/references/error-messages.md
For https://github.com/cypress-io/cypress/pull/14826. Wait until it's merged to merge this.
=> Uncaught exception handling updates

content/guides/getting-started/installing-cypress.md
For https://github.com/cypress-io/cypress/pull/15165
=> Update min node version to 12+

.eslintrc.js, .nuxtignore, components/global/CodeGroup.vue
=> fix: various fixes

source/api/plugins/after-run-api.md, source/api/plugins/after-spec-api.md, source/api/plugins/before-run-api.md, source/api/plugins/before-spec-api.md, source/guides/references/experiments.md
For https://github.com/cypress-io/cypress/pull/15276
=> Remove experimentalRunEvents flag

source/api/plugins/browser-launch-api.md, source/guides/core-concepts/retry-ability.md, source/guides/dashboard/flaky-test-management.md
- add link to the latest blog post about video resolution
- add links to the blog posts about flake
=> more links to the blog posts

source/api/commands/get.md, source/guides/core-concepts/retry-ability.md, source/guides/references/troubleshooting.md, source/guides/tooling/visual-testing.md
- a few more blog links
- add an example that answers https://github.com/cypress-io/cypress/discussions/15322
=> add more links and cy.get examples

source/guides/dashboard/projects.md
This is a small fix to display numbered list correctly.
=> Fix missing number in numbered list

source/_data/plugins.yml
=> add cypress-recurse plugin

components/sidebar/CollapsibleSidebarSection.vue, pages/api/_.vue, pages/examples/_.vue, pages/faq/_.vue, pages/guides/_.vue
Fixes this issue w/ new docs:
Now we get:
=> fix: sidebar selects only active page

styles/content.scss
=> fix: font-weight 600 for bold items in Alerts

nuxt.config.js, package.json, yarn.lock
Enable GTM by setting a `GOOGLE_TAG_MANAGER_ID` env var when building
=> feat: google tag manager setup

source/faq/questions/dashboard-faq.md, source/guides/dashboard/runs.md, source/guides/dashboard/users.md, source/guides/guides/test-retries.md
=> Refactor "test recordings" to "test results"

source/guides/references/best-practices.md
I had to go searching for the right syntax for this as I wasn't sure what "an only" referred to. Linked to source docs for `it.only` to make it super easy for anyone unfamiliar with jest.
=> Make the meaning of "put an .only" clear

source/api/commands/check.md, source/api/commands/select.md, source/api/commands/should.md
because I saw users asking about it https://gitter.im/cypress-io/cypress?at=60488e4a457d6b4a94b5fff7 and we had nothing
=> add example with selected and checked selector

source/_data/plugins.yml
https://github.com/bahmutov/cypress-markdown-preprocessor finally supports watch mode, so deserves to be here
=> add markdown preprocessor plugin

source/guides/testing-strategies/amazon-cognito-authentication.md
`loginByOktaApi` was used wrongly in the example
=> Use the correct command name

source/guides/references/assertions.md
since users are confused https://twitter.com/manekinekko/status/1370406934063558658
=> add assertion example disabled and enabled

source/api/commands/task.md
Good example repo, this question comes up again and again
=> add link to cypress-db-example repo

source/_data/plugins.yml
This PR is a reopen for the previous one [#3654 ](https://github.com/cypress-io/cypress-documentation/pull/3654) which missed the test file for this plugin itself.
Now test file is added, please review, thanks.
=> [Again] Update to add a visual testing plugin

source/_changelogs/6.7.1.md
=> 6.7.1 Release

source/_data/courses.yml
I already have other courses listed here, and now that my advanced Cypress course is live, I'm adding it here too.
=> Update list with new course

source/_data/plugins.yml
=> add esbuild preprocessors

content/_changelogs/6.8.0.md, content/_data/plugins.json
Includes latest content as of 92b032f5cb30d5d145786eefb910753d5621859f
=> docs: update to latest docs content

components/PluginsList.vue, content/_data/plugins.json
=> fix: plugins page url renders as anchor tag

content/api/commands/intercept.md
Restore throttle example missing from merge of #3742
=> restore setThrottle example from #3742

content/guides/references/assertions.md
text search in our docs returned no meaningful results
=> add example assertion with text and regular expression

components/AppSearchAlgolia.vue
=> fix: #3822 blog links link correctly to blog posts in algolia search results

content/examples/examples/recipes.md
reported by https://github.com/cypress-io/cypress/discussions/15836
=> remove old link, add link to the announcement

content/guides/component-testing/introduction.md
Improves the clarity and adds missing dependencies of the component testing intro documentation.
=> fix: Improved CT introduction documentation

content/api/commands/its.md, content/guides/references/troubleshooting.md
=> Add note about NODE_DEBUG

content/api/commands/contains.md, content/faq/questions/using-cypress-faq.md, content/guides/references/assertions.md
Better links for relevant info about non-breaking space
=> expand links and examples for text matching

content/guides/tooling/typescript-support.md
to better answer https://github.com/cypress-io/cypress/issues/15872
=> describe how to solve jest types clashes

content/api/commands/as.md, content/guides/core-concepts/variables-and-aliases.md
=> Add note how aliases are reset before each test

components/global/Badge.vue
=> style: badges no longer span full width of container and appear rounded

styles/content.css
=> fix: #3856 regression

content/faq/questions/using-cypress-faq.md
to make https://github.com/cypress-io/cypress/discussions/16033 more discoverable in our docs
=> add link between https warning

scripts/partials.js
=> Fix links in in route() deprecation note

content/_changelogs/7.2.0.md
=> 7.2.0 release

content/_changelogs/7.2.0.md
Some items were missing from the 7.2.0 changelog.
=> Add missing items from the changelog of 7.2.0

content/api/utilities/promise.md
- updates minor grammar to make docs easier to understand.
=> minor grammar fix to docs

content/faq/questions/general-questions-faq.md
=> explain that Cypress can do API testing

content/guides/continuous-integration/introduction.md
for https://github.com/cypress-io/cypress/pull/16233
=> add link to LayerCI example

content/api/plugins/after-spec-api.md
Inspired by https://github.com/cypress-io/cypress/issues/16377 and https://github.com/cypress-io/cypress/issues/14706
=> Add example of how to delete recorded video for specs with no retries

content/guides/component-testing/framework-configuration.md
Some additional changes that did not get into the initial PR: https://github.com/cypress-io/cypress-documentation/pull/3883
=> docs: minor improvements to CT framework config docs

content/api/commands/intercept.md
For https://github.com/cypress-io/cypress/pull/14513
=> docs(cy.intercept): add `times` option to `RouteMatcher`

content/guides/continuous-integration/ci-provider-examples.md
=> DX-198 Update CI providers initial copy

content/guides/continuous-integration/aws-codebuild.md
Per https://github.com/cypress-io/cypress-realworld-app/pull/925
=> Update AWS CodeBuild Guide to set Git COMMIT_INFO variables

content/api/commands/then.md
#3730 was closed without migration. So, I created a new one.
=> fix: add HTMLElement related cy.then doc.

content/guides/references/migration-guide.md
Fix npmjs pathes in migration guide
=> Fix npmjs pathes in migration guide

content/guides/testing-strategies/amazon-cognito-authentication.md
Reference: https://github.com/cypress-io/cypress-realworld-app/blob/develop/package.json
=> Fix typo: cognito

content/_data/courses.json
- add Test automation university course
- delete the old Udemy course
=> Update course list

nuxt.config.js, plugins/fullstory.client.js, plugins/fullstory.js
Updated fullstory to correctly initialize.
=> fix: [DX-220] update fullstory plugin to init correctly

content/_data/plugins.json
Adds new @cypress/schematic to plugins list.
=> doc: add cypress schematic to plugins list

content/api/commands/intercept.md
=> DX-85 improving examples

content/api/commands/intercept.md
=> Update intercept docs about StaticResponse

content/api/commands/intercept.md
=> DX-382 API: Intercept - Fix the comments so they're not cut off

content/api/commands/intercept.md
=> DX-374 API: Intercept: Examples - "With RouteMatcher" examples are confusing

content/guides/core-concepts/variables-and-aliases.md
=> DX-390 Guides: Core Concepts: Routes - update with intercept content

content/api/commands/intercept.md
=> DX-190 API: Intercept - Update section, 'Request/Response Modification with `routeHandler`' with links to examples

content/api/commands/as.md, content/api/commands/wait.md
=> DX-338 Update `as` `get` and `wait`

content/api/commands/intercept.md
=> DX-360 API: Intercept - Intercept signature and args are difficult to reason about

content/_changelogs/7.7.0.md
=> 7.7.0 Release

.circleci/config.yml
Should be every 12 hours, but it's set to [every minute](https://crontab.guru/#0_0,12_*_*_*).
=> Fix sanity-scheduled-content-check cron schedule

content/guides/references/error-messages.md
I've attempted to document this, please let me know if anything is inaccurate or could be better presented. Thanks!
https://deploy-preview-4021--cypress-docs.netlify.app/guides/references/error-messages#Whoops-we-can-t-run-your-tests
=> DX-313 Add documentation for the "Whoops, we can't run your tests." error.

nuxt.config.js
=> fix: remove live edit in dev mode

content/guides/continuous-integration/introduction.md
As noted in the original PR for this feature, we’re not fully testing it so should note it as experimental. https://github.com/cypress-io/cypress/pull/16537#pullrequestreview-701384541
Inspired by https://github.com/cypress-io/cypress/issues/17412
=> Add note about Electron run as node being experimental

content/api/commands/server.md, content/api/cypress-api/cypress-server.md, content/api/plugins/after-run-api.md, content/api/plugins/after-screenshot-api.md, content/api/plugins/after-spec-api.md, content/api/plugins/before-run-api.md, content/api/plugins/before-spec-api.md, content/api/plugins/browser-launch-api.md, content/api/plugins/configuration-api.md, content/api/plugins/preprocessors-api.md, content/faq/questions/general-questions-faq.md, content/guides/guides/environment-variables.md, content/guides/tooling/plugins-guide.md
=> Fix links that had .html at end of it

content/_changelogs/8.3.0.md, content/api/commands/route.md
=> 8.3.0 Release

content/_data/courses.json
I've launched this new course today, and I'd like to have it listed here, as all my other courses.
=> Add my brand new course on the list

content/guides/guides/environment-variables.md
I intentionally didn't add 6 so it can be flexible for the future!
=> Remove wrong number

content/api/commands/url.md
Related to cypress-io/cypress#17399
=> Add decode option to cy.url() doc

content/api/commands/screenshot.md
=> Fix screenshot clip example

content/api/commands/screenshot.md
fix https://github.com/cypress-io/cypress-documentation/pull/4079#issuecomment-917013221
=> fix: screenshot clip example

content/_changelogs/8.4.0.md, content/api/commands/url.md
=> 8.4.0 Release

content/_changelogs/8.4.1.md
=> 8.4.1 Release

content/api/commands/request.md, content/api/commands/viewport.md, content/api/commands/visit.md, content/api/cypress-api/config.md, content/api/cypress-api/env.md, content/faq/questions/using-cypress-faq.md, content/guides/core-concepts/cypress-studio.md, content/guides/dashboard/projects.md, content/guides/getting-started/testing-your-app.md, content/guides/guides/screenshots-and-videos.md, content/guides/guides/web-security.md, content/guides/references/best-practices.md, content/guides/references/configuration.md, content/guides/references/error-messages.md, content/guides/tooling/code-coverage.md, content/guides/tooling/reporters.md, scripts/directives/cypress-config-example.js, scripts/remark-directives.js
https://cypress-io.atlassian.net/browse/UNIFY-326
Added config example directive and updated all references to show tabbed UI
=> UNIFY-326 Update all inline cypress.json examples

content/_data/sidebar.json, content/guides/references/legacy-configuration.md, cypress/fixtures/sidebar-overrides.json
https://cypress-io.atlassian.net/browse/UNIFY-318
Notes:
- I added 2 alerts, one at the top of the legacy page, and one in the "Plugins" section. Do they both make sense? Should I change the wording? I want to reuse these two alerts wherever possible throughout these changes.
=> UNIFY-318 Add Legacy Configuration page

nuxt.config.js, package.json, scripts/remark-directives.js, scripts/remark-directives.test.js, yarn.lock
Allow directives to know the file path for better debugging, so if there's an error, you see a line like what's at the bottom of this image instead of having to guess what file it's in:
=> Better directive error handling

content/_changelogs/8.5.0.md, content/api/commands/select.md, content/guides/getting-started/installing-cypress.md
=> 8.5.0 Release

scripts/remark-directives.js
=> Reduce directive log spam

components/global/Alert.vue, components/global/CodeBlock.vue, package.json, scripts/directives/cypress-config-example.js, scripts/directives/cypress-plugin-example.js, scripts/directives/helpers/example-helpers.js, scripts/remark-directives.js, yarn.lock
Preview https://deploy-preview-4132--cypress-docs.netlify.app/guides/component-testing/framework-configuration#Next-js-Webpack-4
Preview https://deploy-preview-4132--cypress-docs.netlify.app/guides/tooling/reporters#Cypress-configuration-3
=> Improve example deprecation with much clearer notice

content/api/commands/exec.md, content/api/commands/readfile.md, content/api/plugins/configuration-api.md, content/guides/component-testing/framework-configuration.md, content/guides/component-testing/introduction.md, content/guides/guides/command-line.md, content/guides/references/client-certificates.md
https://cypress-io.atlassian.net/browse/UNIFY-366
Small updates made after discussing nuanced implementation + assorted feedback.
=> UNIFY-366 update special configuration refs

content/guides/tooling/IDE-integration.md
https://cypress-io.atlassian.net/browse/UNIFY-322
=> UNIFY-322-update-IDE-integration-page

content/_changelogs/3.5.0.md, content/guides/guides/command-line.md, content/guides/guides/test-retries.md, content/guides/references/configuration.md, content/guides/references/legacy-configuration.md, scripts/directives/cypress-config-example.js, scripts/directives/helpers/example-helpers.js
Preview
Whole page:
* https://deploy-preview-4131--cypress-docs.netlify.app/guides/references/configuration
Specific sections:
* https://deploy-preview-4131--cypress-docs.netlify.app/guides/guides/command-line#cypress-run-config-lt-config-gt
* https://deploy-preview-4131--cypress-docs.netlify.app/guides/guides/command-line#cypress-open-config-lt-config-gt
* https://deploy-preview-4131--cypress-docs.netlify.app/guides/references/legacy-configuration#History
TODOs
=> [UNIFY-319] Update configuration page

content/api/commands/children.md, content/api/commands/clear.md, content/api/commands/closest.md, content/api/commands/each.md, content/api/commands/filter.md, content/api/commands/log.md, content/api/commands/nextuntil.md, content/api/commands/not.md, content/api/commands/parents.md, content/api/commands/parentsuntil.md, content/api/commands/select.md, content/api/commands/siblings.md, content/api/commands/spread.md, content/api/commands/trigger.md, content/api/commands/type.md, content/guides/core-concepts/variables-and-aliases.md, content/guides/core-concepts/writing-and-organizing-tests.md, content/guides/references/error-messages.md
https://cypress-io.atlassian.net/browse/UNIFY-499
=> UNIFY-499-replace-superfluous-E2E-methods

content/_changelogs/8.8.0.md, content/api/commands/fixture.md, content/api/commands/readfile.md, content/api/commands/writefile.md
=> 8.8.0 Release

content/_changelogs/9.0.0.md, content/api/commands/fixture.md, content/api/commands/readfile.md, content/api/commands/writefile.md, content/api/plugins/writing-a-plugin.md, content/faq/questions/using-cypress-faq.md, content/guides/getting-started/installing-cypress.md, content/guides/references/configuration.md, content/guides/tooling/plugins-guide.md
=> 9.0 Release

components/MainContentHeader.vue, components/global/Badge.vue, components/global/E2EOnlyBadge.vue, content/api/commands/clearcookie.md, content/api/commands/clearcookies.md, content/api/commands/wrap.md, content/api/cypress-api/custom-commands.md, content/api/events/catalog-of-events.md, content/faq/questions/general-questions-faq.md, content/faq/questions/using-cypress-faq.md, content/guides/core-concepts/conditional-testing.md, content/guides/core-concepts/test-runner.md, content/guides/references/best-practices.md, styles/content.css
https://cypress-io.atlassian.net/browse/UNIFY-523
=> UNIFY-523-E2E-content-callouts

content/api/commands/reload.md, content/api/commands/request.md, content/api/commands/url.md, content/api/commands/visit.md, content/api/cypress-api/config.md, content/guides/core-concepts/writing-and-organizing-tests.md, content/guides/references/best-practices.md, content/guides/references/configuration.md
Reverts cypress-io/cypress-documentation#4202
=> Revert "chore: add additional information around Cypress configuration"

content/_data/sidebar.json, content/guides/overview/choosing-e2e-or-ct.md, content/guides/overview/choosing-testing-type.md
Jira:
https://cypress-io.atlassian.net/browse/UNIFY-391
Preview:
https://deploy-preview-4206--cypress-docs.netlify.app/guides/overview/choosing-testing-type
=> Unify 391 choosing testing type page

content/api/cypress-api/testing-type.md, content/api/plugins/configuration-api.md, content/faq/questions/using-cypress-faq.md, content/guides/guides/command-line.md, content/guides/overview/why-cypress.md, content/guides/references/configuration.md, content/guides/references/legacy-configuration.md, content/guides/tooling/visual-testing.md, netlify.toml
https://cypress-io.atlassian.net/browse/UNIFY-399
=> UNIFY-399-ct-page-redirects

components/global/ComponentOnlyBadge.vue, content/api/commands/session.md
JIRA
https://cypress-io.atlassian.net/browse/UNIFY-520
Deploy preview
https://deploy-preview-4216--cypress-docs.netlify.app/api/commands/session
=> UNIFY-520 Add component testing content to `cy.session()` docs

content/api/commands/stub.md, content/faq/questions/using-cypress-faq.md, scripts/directives/cypress-stub-example.js, scripts/directives/e2e-component-example.js, scripts/remark-directives.js
https://cypress-io.atlassian.net/browse/UNIFY-525
=> UNIFY-525-e2e-component-directive

content/api/commands/clock.md, content/api/commands/visit.md, content/api/utilities/$.md, content/guides/core-concepts/introduction-to-cypress.md, content/guides/core-concepts/retry-ability.md, content/guides/guides/debugging.md, content/guides/guides/stubs-spies-and-clocks.md
https://cypress-io.atlassian.net/browse/UNIFY-522
=> UNIFY-522-add-CT-concepts

content/_changelogs/9.1.0.md, content/faq/questions/using-cypress-faq.md
=> 9.1.0 Release

content/guides/tooling/typescript-support.md
Fix https://github.com/cypress-io/cypress/issues/18239#issuecomment-927000283
=> Add `declare global` to type argument snippet

components/global/CodeGroup.vue, components/global/componentSync.js, content/guides/getting-started/writing-your-first-component-test.md, nuxt.config.js, package.json, scripts/directives/helpers/example-helpers.js, scripts/directives/react-vue-example.js, scripts/remark-directives.js, yarn.lock
Jira:
https://cypress-io.atlassian.net/browse/UNIFY-394
Preview:
https://deploy-preview-4201--cypress-docs.netlify.app/guides/getting-started/writing-your-first-component-test
If you want to follow along, where it says "follow the instructions at the top of the README of either of the following folders to get started" in the green "Follow along!" box near the top of the page, do the following (we haven't written those READMEs yet):
React version:
- clone https://github.com/cypress-io/cypress-component-testing-examples
- check out the `example-react` branch
- `cd` into the `example-react` folder
- delete the `src/components/LoginForm.cy.js` file
- run `yarn` and then `npx cypress open-ct`
- follow the instructions in the guide
Vue version:
- clone …
=> UNIFY-394 Writing Your First Component Test

content/guides/testing-strategies/google-authentication.md
This paragraph is duplicated which might confuse the reader. and add extra text!
=> Documentation - remove duplicate text in google authentication

components/MainContentHeader.vue, components/global/Badge.vue, components/global/ComponentOnlyBadge.vue, components/global/E2EOnlyBadge.vue, styles/content.css
https://cypress-io.atlassian.net/browse/UNIFY-504
=> UNIFY-504-test-type-badge-links

content/api/commands/intercept.md
Simple PR to fix anchor link which is broken.
=> docs: fix anchor link

components/sidebar/CollapsibleSidebarSection.vue
https://cypress-io.atlassian.net/browse/UNIFY-474
=> UNIFY-474-sidebar-nav

content/_changelogs/9.1.1.md
=> 9.1.1 Release

content/guides/getting-started/testing-your-app.md
Fix a sentence from the `Testing Your App` page in the `Getting Started Section` with grammatical mistakes.
=> Fix grammatical error

content/_changelogs/7.0.0.md
Fix typo, change **yoru** to **your**.
=> docs: fix typo

content/guides/guides/command-line.md, content/guides/guides/module-api.md, content/guides/references/configuration.md
https://cypress-io.atlassian.net/browse/UNIFY-666
=> UNIFY-666-config-file-command-updates

content/_changelogs/9.2.1.md
=> 9.2.1 Release

content/_changelogs/9.3.1.md
Add a change log for the 9.3.1 emergency release.
=> 9.3.1 Release

components/PluginsList.vue, components/global/DocsImage.vue
A pair of minor updates to address lint warnings blocking some PRS from merging.
=> Minor updates to address lint warnings

components/AppSidebar.vue, components/TableOfContents.vue, styles/content.css
Closes issue #4318 
http://localhost:3000/guides/overview/why-cypress
http://localhost:3000/examples/examples/recipes
- Navigate to the following links
- Shrink the window between 1024px and 1400px
- Click around the side navigation items and dropdowns
- Ensure that the side navigation items are accessible on smaller screens.
=> DX-813: Making navigation items accessible

content/guides/references/configuration.md, content/guides/references/legacy-configuration.md, content/guides/references/migration-guide.md, content/guides/tooling/plugins-guide.md, content/partials/warning-cypress-json.md, content/partials/warning-plugins-file.md, scripts/directives/cypress-config-example.js, scripts/directives/cypress-config-plugin-example.js, scripts/directives/cypress-env-example.js, scripts/directives/cypress-plugin-example.js, scripts/remark-directives.fixtures.js
https://cypress-io.atlassian.net/browse/UDX-9
=> UDX-9-cypress-json-ref-updates

content/api/commands/fixture.md, content/api/commands/screenshot.md, content/api/commands/window.md, content/api/cypress-api/custom-commands.md, content/api/cypress-api/env.md, content/api/cypress-api/spec.md, content/api/plugins/after-spec-api.md, content/api/plugins/before-run-api.md, content/api/plugins/before-spec-api.md, content/guides/core-concepts/cypress-studio.md, content/guides/core-concepts/writing-and-organizing-tests.md, content/guides/getting-started/testing-your-app.md, content/guides/getting-started/writing-your-first-end-to-end-test.md, content/guides/guides/command-line.md, content/guides/guides/cross-browser-testing.md, content/guides/guides/environment-variables.md, content/guides/guides/module-api.md, content/guides/guides/parallelization.md, content/guides/references/best-practices.md, content/guides/testing-strategies/working-with-graphql.md, content/guides/tooling/code-coverage.md, content/guides/tooling/typescript-support.md
This PR renames all `.spec.{js,ts}` & `_spec.{js,ts}` files to `.cy.{js,ts}`
Closes UDX-103
=> Rename all .spec files to .cy

content/api/commands/clock.md, content/api/commands/session.md, content/guides/core-concepts/introduction-to-cypress.md
Pages updated include:
- `api/commands/clock`
- `api/commands/session`
- `guides/core-concepts/introduction-to-cypress`
=> UDX-61: update mount/visit to be listed in alphabetical order where relevant

content/guides/core-concepts/writing-and-organizing-tests.md
This PR updates the writing and organizing tests guide to reflect the new folder structure in `10.0`
_Note:_ There are screenshots and videos that need updated to reflect new structure and UI which are not part of this PR
Closes UDX-100
=> docs: update writing and organizing tests guide to reflect new folder structure

content/_changelogs/9.5.1.md
Waiting on this regression fix:
- https://github.com/cypress-io/cypress/pull/20335
=> 9.5.1 Release

content/api/commands/hover.md, content/api/commands/mount.md, content/api/cypress-api/custom-commands.md
https://cypress-io.atlassian.net/browse/UDX-69
=> UDX-69-cyadd-hover-mount

content/guides/dashboard/gitlab-integration.md
This PR adds a Limited Preview announcement for GitLab Self-managed to the GitLab Integration page.
=> CLOUD-482: Update GitLab Self-managed documentation with limited preview messaging

content/api/cypress-api/selector-playground-api.md, content/guides/core-concepts/cypress-app.md, content/guides/guides/debugging.md, content/partials/anatomy-of-an-error.md, content/partials/default-selector-priority.md
Moving repeated content into reusable partials.
=> Create content partials & replace on associated pages

content/api/cypress-api/custom-commands.md
Related with cypress-io/cypress#18886.
=> docs: Document Cypress.Commands.addAll()

content/guides/references/error-messages.md
=> docs: document new maximum path length error

content/_data/plugins.json, content/faq/questions/using-cypress-faq.md
Ref. https://github.com/badeball/cypress-cucumber-preprocessor/issues/689.
=> Update links to reflect ownership transfer

content/api/commands/session.md
Update the details of the feature flag & the changes that it activates.
=> Update cy.session command API page

content/api/commands/origin.md
Some small copy changes suggested by reviewers that didn't make it in before release.
=> Update cy.origin API docs with last-minute changes

content/api/commands/filter.md, content/guides/core-concepts/cypress-app.md, content/guides/core-concepts/retry-ability.md, content/guides/core-concepts/variables-and-aliases.md, content/guides/core-concepts/writing-and-organizing-tests.md, content/guides/getting-started/installing-cypress.md, content/guides/getting-started/writing-your-first-end-to-end-test.md, content/guides/guides/debugging.md, content/guides/guides/network-requests.md, content/guides/overview/why-cypress.md, content/guides/references/assertions.md, content/guides/references/best-practices.md, content/guides/references/error-messages.md, content/guides/references/migration-guide.md, content/guides/references/roadmap.md
https://cypress-io.atlassian.net/browse/UDX-162
Additional pass at updating selectors in code examples to align with our best practices. Specifically, https://github.com/cypress-io/cypress-documentation/issues/4227.
=> UDX-162-guides-example-selector-updates

content/_changelogs/9.6.1.md
Open PR tagged for this release:
- https://github.com/cypress-io/cypress/pull/21373
=> 9.6.1 Release

content/guides/getting-started/component-test-troubleshooting.md
Just what it says on the tin ☝️
=> CT troubleshooting updates

content/_data/sidebar.json, content/guides/getting-started/component-framework-configuration.md, content/guides/getting-started/component-setup.md, content/guides/getting-started/component-testing.md, content/guides/getting-started/devs-vs-users.md, content/guides/getting-started/mounting-react.md, content/guides/getting-started/quickstart-react.md, content/guides/getting-started/quickstart-vue.md, content/guides/getting-started/styling-components.md, content/guides/references/migration-guide.md, scripts/remark-directives.fixtures.js
Feedback and bugs by the documentation squad for the [Cypress 10 Final Run Through](https://docs.google.com/document/d/1UVQsaSB8yro1A2Xft9hZa5FfM2QSV3GGyZnzTVEPEds/edit#heading=h.wpuoyneiby8l)
=> 10.0 Final Run-Through Feedback

content/faq/questions/using-cypress-faq.md, content/guides/guides/command-line.md, content/guides/references/migration-guide.md, content/partials/intellisense-code-completion.md
=> docs: document changes in cypress open behavior

content/guides/guides/test-retries.md, content/guides/testing-strategies/working-with-graphql.md, content/guides/tooling/typescript-support.md
=> fix lint errors

content/_changelogs/10.0.0.md
- updated minor typos/duplicate words
- updated instances of Cypress App to Cypress app
=> Minor 10.0.0 changelog typo updates

content/_data/sidebar.json, content/api/commands/and.md, content/api/commands/should.md, content/api/commands/spy.md, content/api/utilities/$.md, content/api/utilities/_.md, content/api/utilities/blob.md, content/api/utilities/buffer.md, content/api/utilities/minimatch.md, content/api/utilities/promise.md, content/api/utilities/sinon.md, content/guides/core-concepts/introduction-to-cypress.md, content/guides/core-concepts/writing-and-organizing-tests.md, content/guides/end-to-end-testing/writing-your-first-end-to-end-test.md, content/guides/references/bundled-libraries.md, content/guides/tooling/typescript-support.md
=> UDX-226: Rename 'Bundled Tools' to 'Bundled Libraries'

netlify.toml, redirects.js
Bundled tools became bundled libraries.
=> Add bundled tools redirect

content/_data/sidebar.json, content/guides/end-to-end-testing/writing-your-first-end-to-end-test.md
This PR retitles the "Writing Your First End-to-End Test" to use "E2E" instead. Although this goes against the principles I outlined in https://github.com/cypress-io/cypress-documentation/pull/4527 it make the sidebar look neater.
=> UDX-165: Use 'E2E Test' in sidebar for width

content/guides/dashboard/introduction.md
Copy cleanup & v10 screenshot.
=> Fix Dashboard page typo

content/_data/courses.json
Add my new course to cypress documentation
=> Add new course

content/guides/getting-started/installing-cypress.md
For https://github.com/cypress-io/cypress/pull/20686 and https://github.com/cypress-io/cypress/pull/22252
Todo
=> docs(guides): add darwin/linux arm64 to OS requirements

content/_changelogs/10.2.0.md, content/guides/getting-started/installing-cypress.md
Includes CHANGELOG updates and installation guide updates for new m1/arm64 support
=> docs: 10.2.0 release

content/_changelogs/10.3.0.md, content/api/plugins/configuration-api.md
=> fix: broken links on config page.

docusaurus.config.js
- updated syntax highlighting theme to "nightOwl" for both light and dark themes.
=> updated syntax highlighting theme for both dark and light themes

docs/guides/overview/why-cypress.mdx, docusaurus.config.js
- fixe bug where the guides link in the nav was always active and selected.
=> added baseRegex to guides nav link to fix active highlighting bug

content/_changelogs/10.5.0.md
=> 10.5.0 changelog

docs/guides/component-testing/diving-deeper/_category_.json, docs/guides/component-testing/introduction/_category_.json, docs/guides/component-testing/react/_category_.json, docs/guides/component-testing/vue/_category_.json, docs/guides/end-to-end-testing/introduction/_category_.json, docs/guides/end-to-end-testing/migration/_category_.json, docs/guides/end-to-end-testing/testing-strategies/_category_.json, src/css/custom.css
Keep test type categories expanded in sidebar & adjust size, etc.
=> Update sidebar styles

src/theme/NotFound/index.tsx, src/theme/NotFound/style.module.css
Just like it says on the tin ☝️
=> Style 404 page like production

content/guides/references/experiments.md
per: https://cypressio.slack.com/archives/C03STSRDZU1/p1661270190081439
=> specify testing-type experiments

content/guides/dashboard/introduction.md
One of the all-time great PRs right here
=> Change unnecessarily uppercased 'Cancel' to 'cancel'

content/guides/component-testing/quickstart-react.md
Fixing the discrepancy between the scaffold command and directory
=> docs: Update my-react-app to my-awesome-app

content/guides/references/best-practices.md
This addresses #4700.
Adds a Best Practices section suggesting use of the Dashboard to reduce test duration / load.
=> Add section about Smart Orchestration to the Best Practices page

content/guides/dashboard/runs.md
=> Add para calling out app-cloud integration to dashboard runs page

docs/guides/references/error-messages.mdx, src/components/icon/index.tsx, src/components/icon/types.d.ts, src/css/custom.css, src/theme/NotFound/index.tsx, src/theme/TOCInline/index.tsx
Style inline table of contents to match current site on all FAQ Error Message pages.
=> Style error message inline TOC

content/guides/continuous-integration/aws-codebuild.md
=> Add note about git metadata issues to AWS CodeBuild page

docs/guides/core-concepts/interacting-with-elements.mdx, docs/guides/core-concepts/variables-and-aliases.mdx, docs/guides/core-concepts/writing-and-organizing-tests.mdx, docs/guides/references/best-practices.mdx, docs/guides/tooling/visual-testing.mdx, src/components/icon/index.tsx
Add better comments and some content updates based on MDX v1 parsing issue.
=> mdx render issue

docs/api/commands/fixture.mdx, docs/api/commands/intercept.mdx, docs/api/cypress-api/custom-commands.mdx, docs/api/cypress-api/env.mdx, docs/api/plugins/writing-a-plugin.mdx, docs/examples/recipes.mdx, docs/examples/tutorials.mdx, docs/faq/questions/using-cypress-faq.mdx, docs/guides/core-concepts/testing-types.mdx, docs/guides/core-concepts/writing-and-organizing-tests.mdx, docs/guides/end-to-end-testing/introduction/testing-your-app.mdx, docs/guides/end-to-end-testing/introduction/writing-your-first-end-to-end-test.mdx, docs/guides/end-to-end-testing/migration/protractor-to-cypress.mdx, docs/guides/getting-started/opening-the-app.mdx, docs/guides/guides/environment-variables.mdx, docs/guides/guides/test-retries.mdx, docs/guides/overview/why-cypress.mdx, docs/guides/references/best-practices.mdx, docs/guides/references/bundled-libraries.mdx, docs/guides/references/changelog.mdx, docs/guides/references/configuration.mdx, docs/guides/references/migration-guide.mdx, docs/guides/tooling/plugins-guide.mdx, docs/guides/tooling/visual-testing.mdx, yarn.lock
- fix non-CT broken URLs noted in Docusaurus broken link checker output
- fresh dependency/package.lock to clear out _Unable to build website for locale en_ build error
=> Build test fixes

docusaurus.config.js, src/css/custom.css, src/theme/prism-material-oceanic/index.cjs.js, src/theme/prism-material-oceanic/index.js, src/theme/prism-material-oceanic/package.json
=> Update prism theme

content/_changelogs/11.0.1.md
The times, they keep on changing.
=> V11.0.1 change log

content/guides/continuous-integration/ci-provider-examples.md
=> Update link from CI Provider Examples page to RWA GitLab config

docs/guides/core-concepts/writing-and-organizing-tests.mdx, docusaurus.config.js, package.json, src/components/docs-image/index.tsx, src/components/icon/index.tsx, src/components/plugins-list/index.tsx, src/css/custom.css, src/theme/prism-material-oceanic/index.cjs.js, src/theme/prism-material-oceanic/index.js, yarn.lock
Handful of UX, a11y & code 🧹💨 updates
=> Additional tweaks

content/guides/guides/command-line.md
Closes #4701
Adds a little more detail and links with additional context.
=> Update 'cypress run --record' documentation

content/_data/courses.json
Added "Cypress with TypeScript" on Test automation university and Component testing course on egghead.io
=> Add my latest courses

content/api/commands/origin.md
=> Small update to cy.origin API docs for v12

content/guides/guides/cross-origin-testing.md, content/guides/guides/web-security.md
quick follow up to address @debrisapron 's feedback
=> chore: address docs feedback post merge

content/_data/sidebar.json, content/api/commands/clearallcookies.md, content/api/commands/clearalllocalstorage.md, content/api/commands/clearcookie.md, content/api/commands/clearcookies.md, content/api/commands/clearlocalstorage.md, content/api/commands/getallcookies.md, content/api/commands/getcookie.md, content/api/commands/getcookies.md, content/api/commands/setcookie.md
For https://github.com/cypress-io/cypress/pull/25012
=> Add new cookie commands

content/guides/references/troubleshooting.md
Discord invite link has been updated, so the discord link was updated
=> update discord invite link

content/guides/continuous-integration/github-actions.md
Little housekeeping to keep examples reflecting the latest.
=> Bump GHA versions in examples to latest

content/_changelogs/11.2.0.md, content/_changelogs/7.0.0.md, content/api/plugins/writing-a-plugin.md, content/faq/questions/cloud-faq.md, content/guides/component-testing/component-test-troubleshooting.md, content/guides/component-testing/faq.md, content/guides/core-concepts/cypress-app.md, content/guides/end-to-end-testing/testing-your-app.md, content/guides/references/migration-guide.md, content/guides/references/release-stages.md
=> Fix link #4947

content/_changelogs/12.3.0.md, content/_data/plugins.json, content/api/cypress-api/currentretry.md, content/guides/guides/test-retries.md
- https://github.com/cypress-io/cypress-documentation/pull/4949
=> 12.3.0 Release

content/_changelogs/12.3.0.md, content/_data/sidebar.json, content/guides/guides/test-retries.md, cypress/fixtures/sidebar-overrides.json
just what it says on the tin ☝️
=> fix broken currentretry links

content/guides/cloud/smart-orchestration.md
Resolves Jira ticket CYCLOUD-754
=> Add clarification that auto-cancellation happens after spec

content/api/cypress-api/session.md
Improves a developer copy and paste experience 😄
=> Remove Typo in session.md

docs/api/actions/actionability-guide.mdx, docs/api/assertions/assertions-reference.mdx, docs/api/queries/retriability-guide.mdx, src/theme/NotFound/index.tsx
Add correct links + minor clean up
=> Update 404 page links

docs/guides/continuous-integration/ci-provider-examples.mdx, docs/guides/core-concepts/introduction-to-cypress.mdx, docs/guides/end-to-end-testing/migration/protractor-to-cypress.mdx, docs/guides/overview/why-cypress.mdx, src/components/icon/index.tsx, src/css/custom.scss, src/css/markdown.scss, src/css/navbar.scss
Handful of minor styling tweaks 🥳
=> Post launch tweaks

docs/guides/component-testing/vue/overview.mdx
Updated the link to point to the right resources.
=> Fix the link to the example

docs/guides/end-to-end-testing/testing-strategies/azure-active-directory-authentication.mdx, docs/guides/end-to-end-testing/testing-strategies/social-authentication.mdx
correcting a few things missed in the social/aad guides
=> fix: fix broken link and spelling error

docs/guides/core-concepts/variables-and-aliases.mdx
fixed the reference in the alias example
=> fix ref in alias example

docs/guides/guides/cross-origin-testing.mdx, src/components/icon/index.tsx
Fix icon render issue & clarify fix comment
=> Fix icon render

docs/guides/references/error-messages.mdx
=> docs: update error messages guide with new auto cancellation errors

docs/guides/cloud/smart-orchestration.mdx
=> docs: update smart orchestration doc for auto cancel cli info

CONTRIBUTING.md, docs/plugins/index.mdx, src/components/plugins-list/index.tsx, src/components/projects-list/index.tsx, src/data/plugins.json
List Plugins in order:
- official
- verified
- community
- experimental
Added additional descriptions to direct users to our API docs / existing guides.
=> chore: organize and add details to plugins list

docs/guides/guides/launching-browsers.mdx
=> Add Edge Browsers Section

docs/faq/questions/using-cypress-faq.mdx
Add some verbiage around cucumber
=> Update Cucumber FAQ

src/data/courses.json
I'm focusing only on courses in PT-BR
The courses in English have been unpublished.
=> Remove unpublished courses

docs/guides/references/changelog.mdx
This PR updates the `CHANGELOG` for the `12.12.0` release
=> docs: update changelog for 12.12.0 release

docs/guides/component-testing/third-party-definitions.mdx
👆 Just what it says on the tin
=> Fix CT integration page display

docs/guides/cloud/account-management/_category_.json, docs/guides/cloud/analytics.mdx, docs/guides/cloud/flaky-test-management.mdx, docs/guides/cloud/integrations/_category_.json, docs/guides/cloud/recorded-runs.mdx
Adjust sidebar order & labels for optimal 🧠 & 👀
=> Cloud sidebar edits

docs/guides/component-testing/angular/overview.mdx
This PR adds an example app using Angular Standalone
=> Update example angular apps

docs/faq/questions/cloud-faq.mdx
Updating static IPs used by Cypress Cloud
=> Updating static IPs used by Cypress Cloud

docs/guides/component-testing/overview.mdx
Hi! I wanted to add Lit as a possible framework (library) to use with component testing. n.n
Thanks!
=> docs: add lit community framework support

docs/guides/references/best-practices.mdx
Update layout for clarity following the FAQ page updates. This PR removes some customization specific to this page and uses a list design pattern from other pages.
=> docs: best practices layout improvements

docs/guides/continuous-integration/introduction.mdx
docs(ci-introduction): add heading 4 to "Gotchas" section so it stands out more
=> docs(ci-introduction): add heading 4 to "Gotchas" section so it stands out more

docs/guides/getting-started/installing-cypress.mdx
- Closes #5396
This PR updates the list of supported Node.js versions [Getting Started > Installing Cypress > Node.js](https://docs.cypress.io/guides/getting-started/installing-cypress#Nodejs) to conform to the [Node.js release schedule](https://github.com/nodejs/release#release-schedule).
=> update supported Node.js versions

docs/guides/getting-started/installing-cypress.mdx
Add a few small `pnpm` refs to indicate support
This PR closes https://github.com/cypress-io/cypress-documentation/issues/5397
=> docs: add pnpm refs

docs/api/plugins/after-spec-api.mdx, docs/guides/guides/module-api.mdx
Related code PR: https://github.com/cypress-io/cypress/pull/27230
=> Update results for module API and after:spec handler

docs/guides/cloud/account-management/users.mdx
PR corrects a minor error in the documentation I discovered.
=> SEC-683 | Correcting documentation

src/css/custom.scss
Reverts cypress-io/cypress-documentation#5435
=> Revert "docs: add underline styles to admonition content"

docs/faq/questions/cloud-faq.mdx, docs/guides/cloud/debugging/test-replay.mdx
Adding additional FAQ & troubleshooting content.
=> docs: additional test replay content

docs/guides/cloud/debugging/test-replay.mdx
Just what it says on the tin ☝️
=> docs: add test replay safari troubleshooting

docs/guides/cloud/integrations/source-control/github.mdx, docs/guides/cloud/integrations/source-control/gitlab.mdx
This addresses some non-admin customer confusion while attempting the integration.
- https://app.clickup.com/t/18033298/PM-4162
- https://app.clickup.com/t/18033298/PM-2303
=> docs: add admin access callout

netlify.toml
=> docs: update redirects

docs/guides/cloud/branch-review.mdx
swap image and desc for consistency
=> docs: minor visual update

src/data/plugins.json
=> docs: add cypress-intercept-formdata to plugins.json

docs/guides/references/configuration.mdx
Documentation update for #5532
=> add:taskTimeout is configurable per Test Configuration

docs/guides/cloud/integrations/jira.mdx
Document that only one instance of Jira is supported
=> Document limitation of Jira installations

src/data/courses.json
Added new Cypress course by BigByte
=> Add new course by BigByte

docs/guides/getting-started/installing-cypress.mdx
Close https://github.com/cypress-io/cypress-documentation/issues/5614
=> docs: Add note about Cypress requiring Node.js to install

docs/guides/references/changelog.mdx
adds `13.6.4` release changelog
=> chore: add changelog for release 13.6.4

src/components/badge/style.module.css, src/components/plugins-list/style.module.css, src/css/custom.scss, src/theme/DocItem/Content/style.module.css
A few areas with badges were wonky following the design update. This fixes those and removes some related, unused styles. 
- https://share.cleanshot.com/tBczrFZR
- https://share.cleanshot.com/4mDbj5LD
- https://share.cleanshot.com/Zl0RS9Hf
=> fix: badges css fix

docs/faq/questions/cloud-faq.mdx, docs/guides/references/troubleshooting.mdx
Users will need to whitelist this url for test replay uploads
=> Update cloud-faq.mdx to show new s3 url

docs/faq/questions/cloud-faq.mdx, docs/guides/references/troubleshooting.mdx, docs/partials/_url_allowlist.mdx, src/theme/MDXComponents.js
Quick housekeeping task to keep these lists aligned.
=> chore: move urls to reusable partial

docs/guides/references/changelog.mdx
add release `13.6.6` changelog
=> chore: add changelog for 13.6.6 release

docs/guides/references/changelog.mdx
Adds the changelog for `13.7.1`
=> add changelog for 13.7.1

src/css/custom.scss
=> fix: scrollmargin to add to skipContent

docs/guides/core-concepts/introduction-to-cypress.mdx, docs/guides/getting-started/opening-the-app.mdx, docs/guides/references/troubleshooting.mdx, docs/guides/tooling/typescript-support.mdx
Some minor typos are corrected.
=> Fix miscellaneous typos

docs/guides/end-to-end-testing/migration/selenium-to-cypress.mdx
squash merge in another PR didn't reconcile this difference and main needs this to be fixed
=> Fix broken link that was merged in another PR

docs/guides/references/changelog.mdx
Adds the changelog for the 13.7.3 release
=> chore: add 13.7.3 changelog

docs/guides/references/changelog.mdx
adds the changelog for the Cypress 13.8.1 release
=> add changelog for cypress 13.8.1 release

docs/guides/core-concepts/test-isolation.mdx
replace "In **additional** to" with "In **addition** to"
=> docs: fix typo in test-isolation.mdx

docs/guides/component-testing/angular/api.mdx, docs/guides/component-testing/angular/examples.mdx
Adds documentation for angular signals feature #29621
=> feat: first pass at adding angular signals documentation

docs/guides/references/changelog.mdx
=> add 13.13.1 changelog

docs/guides/end-to-end-testing/introduction/writing-your-first-end-to-end-test.mdx
Simple typo fix: `with` -> `will`
=> Fix typo in writing-your-first-end-to-end-test.mdx

docs/guides/references/changelog.mdx
=> chore: add release 13.13.3 changelog

docs/guides/references/advanced-installation.mdx
Adding the flag from [this PR](https://github.com/cypress-io/cypress/pull/29836/commits) to the table of env var options
=> misc: add docs for `CYPRESS_SKIP_VERIFY` option

docs/guides/references/changelog.mdx
adds changelog for 13.14.1 release
=> chore: release 13.14.1 changelog

docs/guides/cloud/integrations/data-extract-api.mdx
Part of the big Enterprise Reporting release that launched the end of August.
=> Updating Cypress Cloud API spec

docs/guides/references/changelog.mdx
=> chore: add release 13.14.2 changelog

docs/guides/cloud/free-trial.mdx
We are now offering a trial of all features in Cloud for our existing customers.  Doc updates describe the process and what to expect.
=> Free Trial - New section for Existing Subscribers

netlify.toml
To address: https://github.com/cypress-io/cypress-documentation/pull/5949#issuecomment-2407808464
=> Add redirect for legacy config to go to config

docs/app/references/changelog.mdx
Adds the 13.15.1 Cypress App changelog
=> chore: add 13.15.1 app release changelog

docs/app/component-testing/get-started.mdx
Includes docs to include Vite 6
=> chore: update vite docs to include v6

docs/app/references/changelog.mdx
adds the Cypress `14.0.1` changelog
=> chore: add 14.0.1 changelog

docs/cloud/get-started/introduction.mdx
Should mention business plans here also.
=> Add Business to plans that also have SSO integration

docs/app/references/changelog.mdx
add the `14.5.1` documentation changelog
=> chore: add 14.5.1 changelog

docs/app/references/changelog.mdx
=> chore: add 14.5.2 changelog

docs/app/references/changelog.mdx
=> chore: add changelog for 14.5.4

docs/app/references/changelog.mdx
=> chore: add 15.4.0 changelog
