cypress/v0.0/documentation/0-Welcome/0-Guides.md, cypress/v0.0/documentation/4-References/1-Error Messages.md
=> Fixed typo: continous -> continuous

cypress/v0.0/documentation/1-Getting Started/1-Writing Your First Test.md, cypress/v0.0/documentation/4-Guides/11-Bundled Tools.md, cypress/v0.0/documentation/4-Guides/3-Making Assertions.md, cypress/v0.0/documentation/4-Guides/7-Stubs Spies and Clocks.md, cypress/v1.0/documentation/1-Commands/10-clock.md, cypress/v1.0/documentation/1-Commands/23-fixture.md, cypress/v1.0/documentation/1-Commands/27-getCookie.md, cypress/v1.0/documentation/1-Commands/31-hover.md, cypress/v1.0/documentation/1-Commands/32-invoke.md, cypress/v1.0/documentation/1-Commands/33-its.md, cypress/v1.0/documentation/1-Commands/45-request.md, cypress/v1.0/documentation/1-Commands/47-route.md, cypress/v1.0/documentation/1-Commands/55-spy.md, cypress/v1.0/documentation/1-Commands/56-stub.md, cypress/v1.0/documentation/1-Commands/59-tick.md, cypress/v1.0/documentation/1-Commands/61-type.md, cypress/v1.0/documentation/1-Commands/65-visit.md, cypress/v1.0/documentation/1-Commands/9-click.md, cypress/v1.0/documentation/3-Cypress API/0-config.md
=> Added more links to docs from recipes

CONTRIBUTING.md, cypress/integration/main_spec.coffee, lib/url_generator.js, package-lock.json, package.json
Also test loaded styles to catch missing CSS
=> Use Node8 compatible hexo node-sass forks

readme.md
=> add dashboard badge, close #71

source/guides/references/assertions.md
=> fix typo descendents to descendants

source/guides/guides/command-line.md
=> Add --project flag to command line doc

source/guides/guides/web-security.md
=> fixed incorrectly closed links that were causing web security page to be cut off.

source/dashboard/overview/projects-dashboard.md, source/dashboard/overview/runs-dashboard.md, source/faq/questions/dashboard-faq.md, source/faq/questions/using-cypress-faq.md, source/guides/getting-started/testing-your-app.md, source/guides/getting-started/why-cypress.md, source/guides/guides/continuous-integration.md, source/guides/references/error-messages.md
This pull request fixes Issue #91.
=> Fix Issue #91

source/examples/docker/docker-images.md
Add the link to the base image's docker hub page.
=> Update Docker Images page

lib/tags/video.js, scripts/tags.js, source/guides/getting-started/writing-your-first-test.md, themes/cypress/source/css/_partial/page.scss
closes #125 
* Added new custom tag for videos
* Added css to make video embed responsive
* Updated "Writing Your First Test" to use the new tag for the embedded video
=> Added video tag and styles for responsive behavior

source/guides/references/configuration.md
This will be required once this PR https://github.com/cypress-io/cypress/pull/731 is merged into the main repo
=> Update Configuration doc to explain the new videoUploadOnPassing setting

source/guides/core-concepts/launching-browsers.md
Changing wording on the launching browsers page.
=> launches => launch

themes/cypress/layout/partial/after_footer.swig, themes/cypress/layout/partial/footer.swig, themes/cypress/layout/partial/header.swig, themes/cypress/layout/partial/subscribe-form.swig, themes/cypress/source/css/_partial/footer.scss, themes/cypress/source/css/_variables.scss, themes/cypress/source/js/form-ac.js
- duplicate footer from public website
- update logo link to go to public website.
=> #95 links to cy website close #95

circle.yml, cy_scripts/deploy.js, package.json
Reuse same deploy utilities as `cypress.io`
=> Use @cypress/deploy-bits

source/api/commands/type.md
This should help avoid duplicate issues being opened.
=> Reference open issue for tabbing

_config.yml, cypress/integration/main_spec.coffee, cypress/integration/tutorials_spec.coffee, source/_data/main-menu.yml, source/_data/sidebar.yml, source/tutorials/test-a-react-todo-app/introduction-to-tutorials.md, themes/cypress/languages/en.yml
#	source/tutorials/test-a-react-todo-app/introduction-to-tutorials.md
- close #201
- close #202
=> Update tutorials filename + add redirects for tutorials

source/guides/getting-started/writing-your-first-test.md
=> Fix capitalization of Cycling

source/_data/sidebar.yml, source/tutorials/test-a-react-todo-app/introduction-to-tutorials.md, source/tutorials/test-a-react-todo-app/react-todo-app-init.md, themes/cypress/languages/en.yml
=> Adding page for data loading tutorial

source/guides/references/assertions.md
=> typo on "lower than" expectation

source/api/commands/visit.md
Removed the word "be", which was grammatically incorrect in this sentence.
=> Small grammar fix

source/_data/sidebar.yml, source/tutorials/test-a-react-todo-app/introduction-to-tutorials.md, source/tutorials/test-a-react-todo-app/react-todo-item-testing.md, themes/cypress/languages/en.yml
=> Adding tutorial page for todo item testing

source/guides/core-concepts/variables-and-aliases.md
No issues fixed. It's just a simple grammar correction
=> fix: correct grammar

source/guides/core-concepts/writing-and-organizing-tests.md
No issues fixed.  Just a simple punctuation correction.
=> fix: simple punctuation correction

source/guides/getting-started/writing-your-first-test.md
No issues fixed other than a grammatical error.
=> fix: correct grammatical mistake

source/tutorials/test-a-react-todo-app/introduction-to-tutorials.md
Oops! Created 2 number 5s on the tutorial table. Updated to 6.
=> Fix numbering on tutorial table

source/_data/plugins.yml, source/guides/getting-started/writing-your-first-test.md
=> Add ESLint note in guide and add to plugins page

source/faq/questions/using-cypress-faq.md
=> Update faq regarding ESLint plugin

source/examples/examples/tutorials.md
=> Adding footer video to tutorial

source/_data/sidebar.yml, source/api/cypress-api/arch.md, source/api/cypress-api/config.md, source/api/cypress-api/cookies.md, source/api/cypress-api/cypress-log.md, source/api/cypress-api/cypress-server.md, source/api/cypress-api/dom.md, source/api/cypress-api/env.md, source/api/cypress-api/platform.md, source/api/cypress-api/version.md, themes/cypress/languages/en.yml
For Cypress version 1.1.3 https://github.com/cypress-io/cypress/issues/824
=> Document version platform arch 288

source/api/cypress-api/custom-commands.md
=> Wording clarification

source/examples/examples/tutorials.md
=> Added links to completed code for each tutorial lesson

source/api/commands/spread.md
I didn't notice any issues filed against this, but I have verified the parenthesis are necessary.
=> Update spread.md usage example

source/guides/references/configuration.md
New section to explain the userAgent config with ilnk to specs on User-Agent MDN Documentation.
Issue: #328
=> Adding the new 'userAgent' on configuration docs

source/guides/getting-started/writing-your-first-test.md
Changes statement for clarity.
=> Remove 's' in title for clarity

package.json
=> fix(package): update hexo to version 3.4.4

lib/tags/yields.js, themes/cypress/layout/partial/footer.swig
=> Fix typo & Update copyright generation code

themes/cypress/source/css/_partial/footer.scss
=> fix distorted footer links in firefox

source/api/commands/get.md
=> Add spacing and fix typo

source/guides/core-concepts/interacting-with-elements.md
=> Add punctuation

source/guides/core-concepts/interacting-with-elements.md
=> Improve link

source/guides/core-concepts/introduction-to-cypress.md
=> Improve link and add punctuation

source/guides/guides/environment-variables.md
- updated overriding env variables wording to be clearer in source guide.
address #236
=> Update overriding env variables wording to be clearer

source/guides/core-concepts/variables-and-aliases.md
=> Add missing word

source/guides/getting-started/writing-your-first-test.md
=> Fixing typo

package-lock.json, source/guides/core-concepts/test-runner.md
- address search for ‘playground’ returning 0 results #26
=> Add section describing 'Selector Playground'

source/guides/core-concepts/variables-and-aliases.md
=> Typo fix :)

source/guides/guides/plugins-guide.md
=> Change ClosureScript to ClojureScript

source/guides/references/trade-offs.md
=> Fixed a typo

source/api/commands/select.md
Add assertion after select addressing #216
=> Add assertion after select

source/guides/references/best-practices.md
=> Add best practice around setting `baseUrl`

source/faq/questions/using-cypress-faq.md
Adding Selenium's getText() method to Using Cypress FAQ
=> add Selenium's getText for algolia search

source/faq/questions/using-cypress-faq.md
Add user question, *how to throttle network speeds*, to FAQ & satisfy algolia search
closes #511
=> Add network throttling to FAQ

source/faq/questions/using-cypress-faq.md
Add "Can I store an attribute's value in a constant or a variable for later use?" to `FAQ`
* link to `Variables and Aliases`
Fix typo, delete duplicate word *reference*
=> add faq question "can I store attr value in const or var"?

source/guides/tooling/typescript-support.md
=> fix typo change you to your

source/faq/questions/using-cypress-faq.md
Add *How can I make Cypress wait until something is visible in the DOM?* to `FAQ`
* Remind users of Core Concepts
* Link to Querying-Elements, Timeouts, Force, Introduction To Cypress
=> add 'How can I make Cypress wait until X is visible in the DOM?'

source/_data/talks.yml
=> Add Vue and React Component talks

source/_data/plugins.yml
Custom reporter publishes Cypress run results to TestRails
author Milutin Savovic
=> add cypress-testrail-reporter to plugins

_config.yml
=> more reroutes for incorrect old cached pages.

source/api/commands/then.md
=> Fix reversed argument order in docs for then

source/guides/references/configuration.md
=> Fix typo in IntelliSense section

themes/cypress/layout/page.swig
Comments were pushed out - wanted removed
=> Remove comment partial (#633)

circle.yml, package-lock.json, package.json
=> use Cypress v3

source/faq/questions/using-cypress-faq.md
add example from issue 624 to FAQ as assigned in issue 25
=> add example of testing head element

source/guides/guides/network-requests.md
=> Warn that Fetch is not currently supported

source/guides/getting-started/installing-cypress.md, source/guides/guides/continuous-integration.md
=> update CI docs for use with 3.0

source/api/commands/route.md
add note linking to wait command example of testing multiple requests from the same route
=> move example from wait doc to route doc

source/api/commands/server.md
I think this link was left over from the old docs, I updated it to use the hexo formatting, but I only _suspect_ that I linked the proper doc. Please let me know if otherwise.
=> update link to hexo format

source/guides/guides/continuous-integration.md, source/guides/references/error-messages.md
=> fix ci doc typo

source/api/commands/viewport.md
Updates documentation to match implementation change in cypress-io/cypress#100
=> Swap iPad viewport documentation to portrait

source/_data/talks.yml
... the previous one was a link to the talk of the complete track.
=> Adds direct link to "End to End Testing: The Game Has Changed" video

source/guides/guides/command-line.md
Hi,
This PR create as a fix for [issue-730](https://github.com/cypress-io/cypress-documentation/issues/730)
Improving docs by changing some of `command-lines` to valid ones for the sake of better understanding and presentation of the project
=> Issue 2032

package-lock.json, source/guides/guides/continuous-integration.md
=> Fix broken link in CI (invalid link)

source/_data/sidebar.yml, source/examples/examples/workshop.md, source/guides/guides/continuous-integration.md, themes/cypress/languages/en.yml
* add testing workshop page, close #723
* minor editing
* package-lock
* move testing workshop to examples
* concourse CI moved url
=> add testing workshop page, close #723 (#738)

source/guides/guides/command-line.md
=> update docs for --no-exit

source/guides/guides/command-line.md
=> cache commands

source/_data/sidebar.yml, source/api/cypress-api/browser.md, source/api/cypress-api/spec.md, themes/cypress/languages/en.yml
=> Add new docs Cypress.browser and Cypress.spec

package-lock.json, source/guides/guides/continuous-integration.md, source/guides/references/changelog.md
=> WIP - 3.0.2 changelog

package-lock.json, source/_data/sidebar.yml, source/api/commands/screenshot.md, source/api/plugins/after-screenshot-api.md, source/api/plugins/writing-a-plugin.md, source/guides/tooling/plugins-guide.md, themes/cypress/languages/en.yml
=> Add after:screenshot plugin event

source/guides/getting-started/installing-cypress.md
=> Add yarn install instructions

source/_data/plugins.yml
Request to add a ruby gem that makes cypress testing easier on Ruby on Rails application
=> Add cypress on rails gem to plugins list

source/guides/tooling/typescript-support.md
=> :memo: fix indent

source/_data/plugins.yml
Thought this would be helpful to add, let me know if I should change anything!
=> Add cypress-image-snapshot to plugins (closes #745)

source/guides/references/trade-offs.md
=> :memo: issue 684 was closed with `cy.task` API

CONTRIBUTING.md, package-lock.json, source/guides/getting-started/installing-cypress.md, source/guides/guides/command-line.md, source/guides/guides/continuous-integration.md, source/guides/guides/debugging.md, source/guides/guides/environment-variables.md, source/guides/guides/launching-browsers.md, source/guides/references/configuration.md, source/guides/tooling/reporters.md
=> Clean up shell code blocks

source/_data/plugins.yml
=> Add cypress-capybara

source/api/plugins/preprocessors-api.md
=> chore: small wording issue

source/api/commands/contains.md, source/api/commands/get.md, source/api/commands/request.md, source/api/commands/visit.md, source/api/utilities/blob.md, source/api/utilities/moment.md, source/guides/guides/web-security.md
@jennifer-shehane This is my resubmission of [a fork+PR](https://github.com/cypress-io/cypress-documentation/pull/792) that I blasted away in error.
Sorry for the noise, won't happen again 🤞 😊
=> Correct typos

source/guides/core-concepts/variables-and-aliases.md
Correcting `API's` to `APIs` plus a few smaller things in the same file.
=> Polish up some minor stuff like possessives

circle.yml, cypress/integration/api_spec.coffee, package-lock.json, package.json
- closes #842 
- uses workspaces to pass build artifacts from job to job in the workflow
=> Use workspace on circle ci 842

source/api/commands/as.md, source/guides/core-concepts/variables-and-aliases.md
=> [#722] More clearly explain the async nature of aliases

TAGS.md
=> [166] Document custom tags for Hexo

source/_data/plugins.yml
Hi guys! I just wrote an addon library for the Cucumber plugin, featuring a set of common phrases that are used in testing. The main motivation was to let Product Owners write all of our tests. In our application, our starting suite of 50 scenarios required 0 custom code thanks to Pickle!
Check out the website (and the presentation on the front page) for more information.
Please let me know what you think! This is my first official major open source contribution
=> Added PickleJS

TAGS.md
=> Fix typo and malformed anchor

source/_data/plugins.yml
Fixes a wee issue introduced in the merge of #871
=> Fix malformed YAML in plugin data

source/guides/getting-started/installing-cypress.md
=> [#708] Fix example with CYPRESS_CACHE_FOLDER

package-lock.json, source/guides/guides/continuous-integration.md
=> add BitBucket pipeline example to CI table

lib/tags/url.js, package-lock.json, themes/cypress/layout/toc-top.swig
=> Have max depth level of 2 also on pages where table of contents is top

source/api/cypress-api/env.md
=> [#901] Add example of getting env var from plugin

source/guides/guides/continuous-integration.md
- close #920 
Sorted CI by name
=> add VSTS and Shippable examples, close #920

source/guides/guides/continuous-integration.md
=> add Jenkins example link, close #930

source/guides/guides/parallelization.md
=> fix typo and missing parallel flags

CONTRIBUTING.md
The `[]` brackets aren't needed so don't even suggest 'em.
I've also added an example to help this "pop".
=> Fix ambiguity in PR instruction for closing issues

lib/tags/timeouts.js, package-lock.json, source/faq/questions/dashboard-faq.md, source/faq/questions/general-questions-faq.md, source/faq/questions/using-cypress-faq.md, source/guides/core-concepts/dashboard-service.md, source/guides/core-concepts/introduction-to-cypress.md, source/guides/guides/launching-browsers.md, source/guides/guides/network-requests.md, source/guides/guides/stubs-spies-and-clocks.md, source/guides/guides/web-security.md, source/guides/overview/why-cypress.md, source/guides/references/changelog.md
- Be clear on messaging about 'free, OS' versus 'Dashboard Service
- general copy cleanup
- close #588
=> [#588] Billing Docs

source/examples/examples/recipes.md
=> add env variables example, close #980

cypress/plugins/index.js
Should set env correctly in staging.
=> Fix baseUrl in Cypress plugin config

source/guides/guides/command-line.md, source/guides/guides/module-api.md
=> Link to parallelization doc flags in command line & module api

themes/cypress/source/css/_partial/page.scss
=> Scroll tables instead of overflowing into right nav

cy_scripts/deploy.js, cy_scripts/should-deploy.js, test/unit/should-deploy.spec.js
wrong environment value was used to compare
=> fix environment check

package-lock.json, package.json, source/_data/plugins.yml, source/faq/questions/dashboard-faq.md, source/faq/questions/general-questions-faq.md, source/faq/questions/using-cypress-faq.md
=> faq refresh

package.json, source/api/commands/fixture.md, source/api/commands/its.md, source/api/commands/task.md, source/api/commands/window.md
just a few examples to fill API commands I love to use
=> A few more examples

source/guides/guides/launching-browsers.md
=> Convert browser gifs to mp4s

source/_data/blogs.yml
added a blog link to blogs.yml  https://applitools.com/blog/comparing-javascript-browser-automation-frameworks
=> Update blogs.yml with new content issue #28

source/_data/blogs.yml
Adding: https://www.c-sharpcorner.com/article/getting-started-with-cypress-io/
=> Updating blogs for C# Corner (#28)

scripts/helpers.js
=> expand all categories in sidebar if 6 or less categories

source/api/commands/writefile.md
=> Update writeFile docs for flag option

themes/cypress/source/css/_partial/header.scss, themes/cypress/source/css/_partial/media_queries.scss
Based on the issue reported, the logo is now positioned accordingly and is the size expected.
closes #1032
=> fix(logo): Fixes position and size of logo

source/api/cypress-api/custom-commands.md
=> Updating comment to be more grammatically correct

source/_data/plugins.yml
=> Add Applitools and Percy to plugins file + alphabetize dev tools in plugins.

source/guides/guides/continuous-integration.md
=> Update Travis CI example to use new cache: npm setting

source/faq/questions/general-questions-faq.md
=> Redirect searches for whitepapers, Ionic

source/api/plugins/browser-launch-api.md
=> Add note about Electron not accepting flags in browser launch plugin

source/api/events/catalog-of-events.md
=> Update on 'fail' to describe how to continue to fail the test

source/api/commands/writefile.md
=> Change writeFile to yield null

source/faq/questions/using-cypress-faq.md, source/guides/guides/continuous-integration.md
=> Fix link to circleci orb example

source/_data/plugins.yml
Added [cypress-plugin-snapshots](https://github.com/meinaart/cypress-plugin-snapshots) to the plugins page.
- for #1124
=> Add `cypress-plugin-snapshots` to plugin page

source/guides/guides/continuous-integration.md
=> fix circleci example configs

source/_data/plugins.yml
closes #1124 
I added the remaining two entries, for cypress-axe and cyphell
=> Add cypress-axe and cyphell to plugins.yml

source/api/events/catalog-of-events.md
=> update arg to be 'error' so that 'error' is not later undefined

themes/cypress/source/css/_media_queries.scss, themes/cypress/source/css/_partial/examples.scss
=> Fixing overlapping titles in examples section 

themes/cypress/source/css/_media_queries.scss
=> Fixed overlapping sidebar

source/api/commands/visit.md
Closes #1154: cy.visit() documentation update
Added an anti-pattern warning with a link to the best practices page.
=> Update visit.md Documentation

source/faq/questions/general-questions-faq.md
- expand answer about code coverage with element and state coverage
- add new question and answer "When should I write a unit test and when should I write an end-to-end test?"
=> add note about code coverage and unit vs e2e tests

themes/cypress/source/css/_media_queries.scss
=> Reordered media queries 

source/_data/plugins.yml
* Adds link to [cypress-firebase](https://www.npmjs.com/package/cypress-firebase) within plugins.yml
=> Add cypress-firebase to plugins.yml

source/guides/references/assertions.md
=> Remove stray line from assertions page

source/api/commands/clock.md
I got stuck on this for quite a while as it didn't occur to me I should specify 'Date'
=> Explain how to override the date and not timers

scripts/helpers.js, source/_data/plugins.yml, themes/cypress/layout/plugins.swig
- cypress-pipe
- cypress-plugin-snapshots
- cypress-graphql-mock
- cypress-xpath
=> add a few new plugins to the list

package-lock.json, source/_data/plugins.yml
Added a plugin which allows tests to be run against various URLs at various viewport sizes
=> Add cy-view to list of plugins

themes/cypress/source/css/_partial/page.scss
Removed bottom padding that was causing the weirdness.
closes #1232
=> Fix underline on <em> tags

source/_data/talks.yml
=> add ng-be video by Dominic Elm

source/_data/plugins.yml
`cypress-xpath` is a good example, so other people should follow it when writing custom commands
=> add note to cypress-xpath plugin that this is a good example to follow

source/guides/getting-started/installing-cypress.md, source/guides/guides/continuous-integration.md
These two sections are related and need to be linked
=> add links for two caching sections in docs

source/api/cypress-api/custom-commands.md, source/guides/tooling/intelligent-code-completion.md
Improve our intellisense and custom commands doc by adding example repos that show how to use intellisense with custom commands
=> add typescript notes for intellisense and custom commands

source/examples/examples/docker.md
I have written https://github.com/cypress-io/cypress-example-docker-compose and adding a link
=> add docker-compose example repo

source/_data/plugins.yml
- closes #1276
Language for description could use some improvement
=> add scaffolding sections, close #1276

.vscode/settings.json, source/api/commands/window.md
=> add window property example

.vscode/settings.json, source/api/commands/get.md
- closes #1283
Related to https://github.com/cypress-io/cypress-example-kitchensink/pull/171
=> add data attribute get example

source/guides/references/configuration.md
Add testFiles option which seems to work, but is not documented.
=> Add testFiles option

source/api/commands/its.md, source/api/commands/window.md, source/guides/tooling/intelligent-code-completion.md
=> add links to custom properties on window, close #1306

source/_changelogs/3.1.1.md, source/api/commands/task.md
so I can close https://github.com/cypress-io/cypress/issues/411
=> add more examples to task command

package-lock.json, source/guides/core-concepts/introduction-to-cypress.md
=> Issue 1315 - malformed code block in note

source/_data/plugins.yml
As requested in https://github.com/cypress-io/cypress/issues/857#issuecomment-454432997
=> Adds cypress drag drop plugin.

source/api/commands/route.md, source/api/commands/server.md, source/api/commands/wait.md
=> Add more fetch warnings 1337

source/faq/questions/using-cypress-faq.md, source/guides/guides/command-line.md
=> Be more specific about how to run a subset of test files within a folder.

source/guides/guides/parallelization.md
=> Parallelization fixes 1356

ISSUE_TEMPLATE.md
I want to add an Issue Template so it is easier for everyone to raise an issue
This PR refer to issue #1360
This is my first ever contribution so please tell me if anything is not ok, I will update right away ^^
=> Add Issue Template

source/guides/guides/continuous-integration.md
=> change @1.0.0 to @1 for cypress orb name

source/_data/plugins.yml
=> Move visual plugins into 'Visual Testing' section

source/faq/questions/dashboard-faq.md
- also add question about deleting account
- close #1346
=> Add question about deleting run from the Dashboard

source/_data/plugins.yml
=> add note to knapsack plugin

source/api/commands/document.md, source/api/commands/its.md, source/api/commands/window.md
To answer hopefully question like https://twitter.com/TheRealPomax/status/1091047717965418496 and the follow up conversation
=> add a few links to blog posts

source/guides/guides/continuous-integration.md
a few tiny tweaks, just to finish with the feedback from the training section and make the docs consistent with circleorb readme
=> Update circle orb example 1366

source/guides/guides/launching-browsers.md
=> Add docs on launching chromium, canary

lib/tags/partial.js, package-lock.json, package.json, source/_partial/network_stubbing_warning.md, source/api/commands/route.md, source/api/commands/server.md, source/api/commands/wait.md, source/guides/guides/network-requests.md
=> better XHR warning

source/guides/guides/command-line.md
=> add example calling cypress from CLI through npm script

_config.yml, themes/cypress/layout/partial/error-reporting.swig
=> Add Sentry error reporting

_config.yml, package-lock.json, package.json, source/guides/guides/command-line.md, themes/cypress/layout/partial/error-reporting.swig
=> Add sentry reporting and additional CLI examples

themes/cypress/layout/partial/error-reporting.swig
=> ignore ResizeObserver errors

source/guides/guides/continuous-integration.md
=> Updating with new name of VSTS

source/_data/plugins.yml
=> Add watch reload plugin

lib/tags/changelog.js
=> tags: sort by dotted-decimal version in changelog

source/api/commands/visit.md
Depends on cypress-io/cypress#3489
Based off discussion from cypress-io/cypress#1500
=> 3.1.6: Add `visiting by POST` changes to cy.visit docs

source/guides/guides/continuous-integration.md
=> Update note to properly note what is cached in Travis CI

source/examples/examples/workshop.md
=> Updated some of the content for workshop

source/guides/references/roadmap.md
The roadmap for the Dashboard is a bit out-of-date. This PR removes some items that aren't in our near-term plans, and adds some new ones that are.
=> Update Dashboard roadmap

source/faq/questions/dashboard-faq.md
Add new FAQ (from users) and answer.
=>  Add question about downgrading and Dashboard effects

source/_data/plugins.yml, source/api/commands/wait.md
- add cypress-select-tests
- adds note to `cy.wait alias`, closes #1508
=> Add select plugin

themes/cypress/source/css/_partial/page.scss
Fixes #1183 
This visual bug has been bothering me more every time I notice it :sweat_smile: Is this a sufficient fix?
=> Fix table borders by making last th, td fill the remaining table width

source/_data/plugins.yml
I've added my new plugin to the list that allows you to generate a valid OTP token to be used in the tests.
=> I've developed an OTP generator plugin

TAGS.md, source/_data/plugins.yml, themes/cypress/layout/plugins.swig
Adds a link and escapes it from Markdown to generate HTML
=> use markdown tag to render plugin description

source/_data/plugins.yml
Submitting my cypress-jest-adapter plugin. Please see my repo for more information.
https://github.com/phongnd39/cypress-jest-adapter
=> add cypress-jest-adapter to plugins page

package-lock.json, package.json, source/_data/plugins.yml
Added cypress-commands to the list of plugins
=> Added cypress-commands to the list of plugins (#1529)

source/_data/plugins.yml
Submitting this plugin I've been working on! More details in the readme: [https://github.com/Nanciee/cypress-autorecord](https://github.com/Nanciee/cypress-autorecord)
=> Added cypress-autorecord to the plugin page

source/guides/references/proxy-configuration.md
=> guides: add details on environment variables in proxy configuration

source/guides/getting-started/writing-your-first-test.md
Replace "Now that we've got a page loading" with "Now that we've got a page loaded".
=> Fix typo in writing-your-first-test.md

source/faq/questions/dashboard-faq.md
/closes https://github.com/cypress-io/cypress-monorepo/issues/383
=> Revise "private test recordings" to "test recordings"

source/api/commands/task.md
I saw yesterday a user struggling in Gitter with async task - and we don't say anything about async tasks in `cy.task` doc!
=> cy.task should return Promise from async tasks

source/api/commands/fixture.md
since this can easily trip people up
=> add example with fixture and this test callback

source/api/commands/should.md
=> fix wrong variable name in should.md

source/guides/references/configuration.md
=> specify that video upload also applies to processing and compression of video

lib/tags/assertions.js, lib/tags/timeouts.js, source/api/commands/contains.md, source/api/commands/get.md, source/api/events/catalog-of-events.md, source/faq/questions/using-cypress-faq.md, source/guides/core-concepts/introduction-to-cypress.md, source/guides/references/assertions.md
=> Link to 'retry-ability' doc from within other pages (specifically when dealing with assertions)

source/api/commands/visit.md
=> Mention setting user-agent in configuration on cy.visit() page

source/api/commands/screenshot.md
=> Fix confusing description of args for screenshot callbacks

package-lock.json, source/guides/references/roadmap.md
=> Issue 1638 update roadmap

package-lock.json, package.json, source/guides/references/roadmap.md
* Update and reformat roadmap
* package-lock
=> Issue 1638 update roadmap (#1639)

lib/tags/assertions.js, package-lock.json
=> render tags in assertion tag

source/api/commands/stub.md, source/examples/examples/docker.md, source/guides/guides/stubs-spies-and-clocks.md, source/guides/tooling/typescript-support.md
filling all the links that were missing and often asked about
=> More links

source/guides/getting-started/installing-cypress.md
=> Improved phrasing and fixed typo

circle.yml, cypress/integration/guides_spec.js, lib/url_generator.js, package.json
Docker image `cypress/base:8.16.0` created in https://github.com/cypress-io/cypress-docker-images/pull/111
=> Update chinese translation test

.textlintrc, package-lock.json, source/_changelogs/0.14.0.md, source/_changelogs/0.20.0.md, source/_changelogs/1.4.1.md, source/_changelogs/3.3.0.md, source/zh-cn/3.3.0.md, source/zh-cn/_changelogs/0.14.0.md, source/zh-cn/_changelogs/0.20.0.md, source/zh-cn/_changelogs/1.4.1.md
- Added Xvfb to test linter
- As per X.Org, the proper capitalization is Xvfb https://www.x.org/releases/X11R7.7/doc/man/man1/Xvfb.1.xhtml
=> Fix Xvfb capitalization

source/_changelogs/3.3.0.md, source/_changelogs/3.3.1.md
=> 3.3.1 Release

package-lock.json, package.json, source/guides/tooling/visual-testing.md
- fixes #1711 
should be super fast now - lint only changed MD and JS files on commit, lints all files on push
I could remove the total lint on pre-push because we do it on CI anyway
=> Lint staged files for speed

source/_data/plugins.yml, source/ja/_data/plugins.yml, source/zh-cn/_data/plugins.yml
=> Add new plugins

source/api/commands/screenshot.md, source/api/cypress-api/screenshot-api.md, source/api/plugins/after-screenshot-api.md, source/guides/guides/screenshots-and-videos.md, source/guides/references/roadmap.md, source/ja/api/commands/screenshot.md, source/ja/api/cypress-api/screenshot-api.md, source/ja/api/plugins/after-screenshot-api.md, source/ja/guides/guides/screenshots-and-videos.md, source/ja/guides/references/roadmap.md, source/ja/guides/tooling/visual-testing.md, source/zh-cn/api/commands/screenshot.md, source/zh-cn/api/cypress-api/screenshot-api.md, source/zh-cn/api/plugins/after-screenshot-api.md, source/zh-cn/guides/guides/screenshots-and-videos.md, source/zh-cn/guides/references/roadmap.md, source/zh-cn/guides/tooling/visual-testing.md
- Also mention that video capturing is only supported in electron.
- close #1739
=> update area of screenshots and videos to link to visual testing guide

source/examples/examples/recipes.md
=> add logging in using JWT recipe link

source/_data/courses.yml, source/ja/_data/courses.yml, source/zh-cn/_data/courses.yml
=> add xebia training course

_config.yml, cypress/integration/i18n_spec.js, package-lock.json, package.json, source/guides/guides/command-line.md
* WIP: catch invalid language
* fix accidental Mandarin title in English guide
=> catch Mandarin language title in "Command Line" English guide (#1793)

.textlintrc, source/guides/tooling/typescript-support.md, source/ja/guides/tooling/typescript-support.md, source/zh-cn/guides/tooling/typescript-support.md
Adds a few more links to the TypeScript tooling page
=> expand TS example page

package-lock.json, package.json, source/api/commands/click.md, source/api/commands/exec.md, source/ja/api/commands/exec.md, source/zh-cn/api/commands/exec.md
=> Fix incorrect example in cy.exec + add link to cy.task in see also

source/_partial/chromium_download.md, source/guides/guides/debugging.md, source/guides/guides/launching-browsers.md, source/ja/_partial/chromium_download.md, source/ja/guides/guides/debugging.md, source/ja/guides/guides/launching-browsers.md, source/zh-cn/_partial/chromium_download.md, source/zh-cn/guides/guides/debugging.md, source/zh-cn/guides/guides/launching-browsers.md
- added partial and included from debugging and launching browsers pages
=> add link to chromium.cypress.io

source/zh-cn/guides/getting-started/installing-cypress.md
I just translated the docs to Chinese.
=> translated 'installing-cypress.md‘

lib/tags/usage.js, source/api/commands/get.md
To go along with https://github.com/cypress-io/cypress/pull/2791
=> Add withinSubject usage

source/guides/references/error-messages.md, source/ja/guides/references/error-messages.md, source/zh-cn/guides/references/error-messages.md
Added an error case that could help others avoid days spinning their wheels trying to find the problem like I did.
=> Update error-messages.md (Expected to find element...)

source/guides/tooling/typescript-support.md, source/ja/guides/tooling/typescript-support.md, source/zh-cn/guides/tooling/typescript-support.md
I have added link to Basarat's video that shows his TS repo
=> add Basarat's video

source/_data/screencasts.yml
=> Adding May screencasts

source/_data/blogs.yml
=> Adding May articles

source/_data/plugins.yml, source/ja/_data/plugins.yml, source/zh-cn/_data/plugins.yml
Added link to WordPress plugin boilerplate that includes Cypress E2E tests
=> add wordpress plugin boilerplate

lib/tags/usage.js, source/api/commands/request.md, source/api/commands/visit.md, source/ja/api/commands/request.md, source/ja/api/commands/visit.md, source/zh-cn/api/commands/request.md, source/zh-cn/api/commands/visit.md
=> Add retry details for 'retryOnStatusCodeFailure' and 'retryOnNetworkFailure'

source/guides/tooling/code-coverage.md, source/ja/guides/tooling/code-coverage.md, source/zh-cn/guides/tooling/code-coverage.md
=> add two code coverage example links

source/_data/plugins.yml
Added cypress-downloadfile plugin to the plugins file list.
=> added cypress downloadfile command

source/api/commands/then.md, source/ja/api/commands/then.md, source/zh-cn/api/commands/then.md
- close #1902 
- fix input -> button
=> write new copy and example to explain 'then' yield

source/api/commands/type.md, source/ja/api/commands/type.md, source/zh-cn/api/commands/type.md
=> Add example of setting 'parseSpecialCharSequences' to false

source/guides/guides/module-api.md, source/ja/guides/guides/module-api.md, source/zh-cn/guides/guides/module-api.md
=> Clarify some of the options available in Module API

package-lock.json, themes/cypress/source/css/_partial/base.scss, themes/cypress/source/css/_partial/header.scss, themes/cypress/source/js/banners_actualization.js, themes/cypress/source/js/mobile_nav.js
quick fix for mobile header/menu
=> Add mobile header fix

source/api/commands/readfile.md, source/api/commands/task.md
=> Update task examples to be coppastabley

cypress/integration/contentful_banners_spec.js, cypress/plugins/index.js, themes/cypress/layout/partial/after_footer.swig, themes/cypress/layout/partial/header.swig, themes/cypress/source/css/_partial/banners.scss, themes/cypress/source/css/_partial/header.scss, themes/cypress/source/css/_partial/sidebar.scss, themes/cypress/source/js/banners_actualization.js, themes/cypress/source/js/mobile_detect.js
=> Issues 1991, 1993

cypress/integration/contentful_banners_spec.js
remove all future or outdated banners in contentful_banners_spec test after readFileMaybe
close #2004
=> Issue-2004

themes/cypress/source/css/_partial/sidebar.scss, themes/cypress/source/css/_partial/toc.scss, themes/cypress/source/js/banners_actualization.js
close #2016 
style fixes for empty banners file
=> issue-2016

source/guides/overview/why-cypress.md
... that ~~helps~~ makes everyone happy.
=> Fix grammar in why-cypress.md

source/guides/core-concepts/introduction-to-cypress.md
=> Fixed a mismatch in an example's comments

source/_data/courses.yml
=> add test automation u course

source/_data/plugins.yml
=> Add cypress-rails mention

index.js
close: #2071 
contentful environment variable declaration based on ternary operator if hexo env eq "production" or not
=> issue 2071

source/_data/podcasts.yml
fix wrong podcast link
close #2074
=> wrong podcast link, close #2074

source/_data/plugins.yml
add link for vscode extension
https://marketplace.visualstudio.com/items?itemName=Shelex.vscode-cy-helper
=> add vscode extension

source/api/commands/its.md
=> Fix typo in cy.its documentation

index.js
close: #2067 
change banner content_type from topBanner to docsTopBanner
=> Issue-2067

index.js, source/api/commands/its.md, source/faq/questions/dashboard-faq.md, source/faq/questions/general-questions-faq.md, source/faq/questions/using-cypress-faq.md, source/guides/core-concepts/conditional-testing.md, source/guides/core-concepts/interacting-with-elements.md, source/guides/core-concepts/retry-ability.md
- Grammar fixes
- Typo on `cy.its` docs
- Top banner fixes and updates
=> Release-1: 09-26-2019

source/guides/guides/continuous-integration.md
=> Update Continuous Integration doc with details for AWS Amplify Console

_config.yml
=> add redirect

source/api/cypress-api/dom.md
Cypress.dom has a lot of methods undocumented. I have documented two of them as starters.
refs #52
=> Documented isDocument, isDom methods

source/_changelogs/3.5.0.md
=> 3.5.0 release fixes

source/api/cypress-api/dom.md
Documented another set of dom methods. This time jQuery related methods: wrap/unwrap.
refs #52
=> Documented wrap/unwrap dom methods

lib/tags/history.js, themes/cypress/source/css/_partial/page.scss
=> No longer collapse History section in doc

package-lock.json, source/_data/courses.yml, themes/cypress/layout/media.swig
=> add span and data to mark free Cypress courses

source/_data/plugins.yml
for doing things like `cy.skipOn('mac')` and `cy.onlyOn('chrome')`
=> add cypress-skip-test plugin

.textlintrc, source/_changelogs/3.5.0.md, source/_changelogs/3.6.1.md
=> 3.6.1 Release

source/_data/plugins.yml
=> Add cypress-laravel plugin

source/api/commands/get.md
=> Fix format error.

_config.yml, readme.md
=> Redirect old content 

source/_data/plugins.yml
=> Add cypress-dotenv plugin

source/_data/plugins.yml
=> add cy-api to the list of plugins

source/guides/tooling/reporters.md
I was running into difficulties understanding the Reporters documentation between missing information, formatting, and structure. I went through the document and removed duplicate information and normalized the structure of the document to be consistent across sections.
=> normalize and clean up reporter documentation

source/api/cypress-api/custom-commands.md
=> Add more examples of custom commands

source/guides/guides/command-line.md, source/guides/guides/launching-browsers.md, source/guides/guides/module-api.md
For cypress-io/cypress#832. TR PR: cypress-io/cypress#5676
=> Chrome headless docs

source/_data/projects.yml
=> Submit React Admin as project using Cypress

source/_data/talks.yml
=> A cypress talk that I gave recently at HolyJS Russia 🌹

source/api/commands/type.md, source/examples/examples/workshop.md, source/faq/questions/dashboard-faq.md, source/guides/dashboard/github-integration.md, source/guides/guides/continuous-integration.md, source/guides/guides/launching-browsers.md, source/guides/guides/module-api.md, source/guides/guides/parallelization.md, source/guides/references/error-messages.md, source/guides/tooling/visual-testing.md, source/plugins/index.md
=> Fix a lot of broken links

source/guides/references/best-practices.md
Use 'isolate' instead of 'insulate'.
=> Improve docs

source/guides/guides/parallelization.md
I finally found the broken link!
- close #2014
=> Fix the broken 'project' link

source/guides/core-concepts/writing-and-organizing-tests.md
Removed incorrect space from "Writing and Organizing Tests" document
=> Remove incorrect space

source/_data/courses.yml
I posted these new courses on Twitter and @bahmutov suggested adding them here.
=> Updated courses list with three new courses

.github/workflows/create-pr-develop-to-master.yml
- for #2356
- it is recommended to use specific commit of an action, or at least a major tag like `actions/checkout@v2` and not `actions/checkout@master`
=> try to clarify create pr workflow

.github/workflows/create-pr-develop-to-master.yml
=> hmm, try checking out develop

.github/workflows/create-pr-develop-to-master.yml
=> try fetching all branches

.github/workflows/create-pr-develop-to-master.yml
=> use v1 of checkout action

source/_data/plugins.yml
add new plugin
```js
const {plan} = require('cypress-expect-n-assertions')
it('has 2 expects', () => {
plan(2)
expect(1, 'one').to.equal(1)
expect(2, 'two').to.equal(2)
})
```
=> add plugin cypress-expect-n-assertions

source/_changelogs/3.8.2.md
=> 3.8.2 release

source/_data/plugins.yml
Add plugin cypress-plugin-livereload
https://github.com/unlocomqx/cypress-plugin-livereload
=> Add plugin cypress-plugin-livereload

source/api/plugins/browser-launch-api.md
=> add link to load extension blog post

source/api/cypress-api/custom-commands.md
Extra `)` at the end of the string
=> Typo on Create a user section

source/faq/questions/using-cypress-faq.md
=> fix broken link

source/pt-br/guides/overview/why-cypress.md
Correctly translates the Cypress ecosystem section and Our mission
=> Adjust the translation

source/api/commands/wrap.md
Continuing work from https://github.com/cypress-io/cypress-documentation/pull/2237 opened by @khoiphan21
=> Add note to async section of cy.wrap()

source/pt-br/guides/overview/why-cypress.md, themes/cypress/languages/pt-br.yml
Completed the translation of "Why Cypress?"
=> Translation pt-br

source/guides/guides/debugging.md
For https://github.com/cypress-io/cypress/pull/6171
=> Document process profiler

source/api/cypress-api/isbrowser.md, source/api/plugins/browser-launch-api.md, source/api/plugins/configuration-api.md, source/guides/guides/command-line.md, source/guides/guides/debugging.md, source/guides/guides/launching-browsers.md
Changes for https://github.com/cypress-io/cypress/issues/6243
=> Update docs for browser type changes

source/guides/dashboard/github-integration.md
=> Improve GH integration guide with project record tip and examples

source/guides/core-concepts/writing-and-organizing-tests.md
=> Fix small typo

source/_changelogs/4.0.1.md
=> 4.0.1 release

source/_data/courses.yml
Also, update other of my courses with https URL
=> Update courses page with new course

source/_data/courses.yml
=> Avindra Fernando Cypress Conference Talk

TAGS.md, lib/tags/requirements.js, source/api/commands/uncheck.md
- close #2498 
- also remove list of requirements and timeouts from TAGS.md as this
has and will go stale.
=> Add 'uncheckability' requirements that removes 'radio'

source/guides/references/roadmap.md
=> Update Test Runner Roadmap - Feb 2020

source/guides/references/roadmap.md
=> update roadmap PR link

source/_changelogs/4.0.2.md
=> 4.0.2 release

source/_data/projects.yml
Add Webiny and Userbase to open source projects page
=> Add Webiny and Userbase to open source projects page

source/faq/questions/company-faq.md
=> adds company name explanation to FAQ for issue 2531.

source/guides/guides/continuous-integration.md
Closes https://github.com/cypress-io/cypress-example-kitchensink/issues/373
=> Update amplify config to not pin version of mocha

source/faq/questions/using-cypress-faq.md
Cherry-picked https://github.com/cypress-io/cypress-documentation/pull/2542 - against `develop` branch
- added converting text to number example
=> add convert example

source/guides/getting-started/writing-your-first-test.md
Update the CSS class name to '.action-email' instead of '.actions-email'
=> Fix CSS class name

source/api/cypress-api/custom-commands.md
From https://github.com/cypress-io/cypress/issues/6564
=> Add example to overwrite contains command

source/_changelogs/4.1.0.md, source/guides/guides/command-line.md
- Add changelog for 4.1.0
- Document new `cypress info` command
=> 4.1.0 release

source/guides/tooling/reporters.md
Correct command line in part 'Merging reports across spec files'
=> Correct command line guide

package-lock.json, source/guides/core-concepts/introduction-to-cypress.md
I have to *very* frequently point out to users that they cannot mix async and sync code. I've been linking them to the `Commands are Asynchrnous` section of our docs, but I've found this lacking in *actual* examples of mixing async/sync code, why this is not a good idea, and how to fix them. 
This adds examples of mixing async/sync code, why it doesn't work, and suggested code to fix it.
=> Add more examples of mixing async/sync commands and why its bad

source/guides/guides/command-line.md, source/guides/guides/screenshots-and-videos.md
=> Document Electron --headed video recording

source/_data/plugins.yml
https://github.com/UnlyEd/next-right-now
Following https://github.com/cypress-io/cypress/issues/6635#event-3096083502
=> Add Next Right Now - Next.js Boilerplate

source/guides/guides/environment-variables.md
=> Add note about reserved CYPRESS_INTERNAL_ENV env var

source/guides/guides/command-line.md, source/guides/references/troubleshooting.md
to help people when a browser is not found like https://github.com/cypress-io/cypress/issues/6669
=> add tips for browser detection

package-lock.json, source/_data/sidebar.yml, source/api/utilities/$.md, source/api/utilities/_.md, source/api/utilities/blob.md, source/api/utilities/minimatch.md, source/api/utilities/moment.md, source/api/utilities/promise.md, source/api/utilities/sinon.md, source/guides/references/bundled-tools.md, themes/cypress/languages/en.yml, themes/cypress/languages/ja.yml, themes/cypress/languages/pt-br.yml, themes/cypress/languages/ru.yml, themes/cypress/languages/zh-cn.yml
=> Add Cypress.sinon doc

source/faq/questions/dashboard-faq.md
=> adds definition of what counts as a user to dashboard FAQ

cypress/integration/i18n_spec.js
=> Fix another test with full url comparison that's failing in staging

source/examples/examples/recipes.md
=> Adds links to Recipes page to match cypress-example-recipes repo

source/api/commands/wait.md
=> adds explanation of timeout behavior when passing an array of aliases

source/_data/webinars.yml, source/api/commands/hover.md
=> Adds Gatsby webinar to list

source/api/cypress-api/cypress-log.md
=> Fix typo in cy.log command documentation

source/guides/core-concepts/conditional-testing.md
Makes them more explicit and also puts some of them into the code sample (the only thing many people actually read)
=> Improves not-valid code warnings

source/api/cypress-api/cypress-log.md
=> Fix typo in cypress-log.md code comment

source/api/commands/invoke.md
small typo, nothing much to add ;)
=> Fix typo in invoke.md

source/guides/tooling/code-coverage.md
=> Fix a few small typos

source/api/commands/task.md
- close #2656 
Hopefully self explanatory. Open to suggestions where this is confusing.
=> Add example for saving variable across domain visits

cy_scripts/deploy.js
=> return deploy promise

source/_data/webinars.yml
Added CircleCI webinar and slides
Used the "small" media type to add links to subscribe to email updates or to follow on Twitter
Close #2229
=> adds CircleCI webinar and adds links to get update notifications

source/guides/guides/continuous-integration.md
=> adds /dev/shm workaround to Docker common problems section in CI 

source/_data/plugins.yml
One more plugin that does a really good job, example repo https://github.com/happo/happo-cypress-example-todomvc
=> add Happo visual testing plugin

source/guides/guides/stubs-spies-and-clocks.md
weird that we did not have a link yet
=> add link to Kitchensink stubs and spies page

source/_data/courses.yml
=> Add Outside-In Frontend Development to courses

source/_data/webinars.yml
I added some webinars that were not on the list :)
I think this closes #2480
=> Adding some webinars already done.

source/_partial/vpn_whitelist_list.md, source/faq/questions/dashboard-faq.md, source/guides/references/troubleshooting.md
Hey guys, this is my first contribution for cypress, so I picked the first thing I felt most comfortable with.
I think this closes #2653 :)
I'm opened to feedback.
Thanks!
=> Adding vpn/whitelist information on FAQ and Troubleshooting pages

source/api/plugins/preprocessors-api.md, source/examples/examples/recipes.md, source/faq/questions/using-cypress-faq.md, source/guides/tooling/plugins-guide.md, source/guides/tooling/typescript-support.md
- Docs for https://github.com/cypress-io/cypress/pull/5906
- Remove mention of needed own transpilation with preprocessors
- Mention needing to install TypeScript package
- Add 'history' section to TypeScript doc
---
=> Update docs for changes required for out of box TS support

source/4.4.0.md, source/api/plugins/preprocessors-api.md, source/examples/examples/recipes.md, source/faq/questions/using-cypress-faq.md, source/guides/tooling/plugins-guide.md, source/guides/tooling/typescript-support.md
- 4.4.0 changelog
- Updates for TypeScript out-of-the-box support https://github.com/cypress-io/cypress-documentation/pull/2710
=> 4.4.0 Release

source/guides/guides/parallelization.md
Trivial typo correction.
closes #2717
=> Trivial typo correction.

source/faq/questions/general-questions-faq.md
Hey, guys, I think this closes #2661 at least partially.
I thought about the notification about new releases, I will continue this discussion at issue.
=> FAQ: discovering new versions of cypress

source/_changelogs/4.4.1.md
=> 4.4.1 Release

source/guides/guides/continuous-integration.md
- it would be nice to add CircleCI webinar link as well
=> add CI webinar link

source/guides/guides/continuous-integration.md
Fix typo in continuous integration guide.
=> Fix typo in continuous integration guide

source/api/plugins/browser-launch-api.md, source/zh-cn/guides/dashboard/introduction.md, source/zh-cn/guides/getting-started/writing-your-first-test.md, themes/cypress/languages/zh-cn.yml
Fix some uncompleted translations
modified:   source/zh-cn/guides/dashboard/introduction.md
modified:   source/zh-cn/guides/getting-started/writing-your-first-test.md
modified:   themes/cypress/languages/zh-cn.yml
=> Translate some guides into Chinese

source/faq/questions/general-questions-faq.md, source/faq/questions/using-cypress-faq.md
As I understand it, we have no plans to integrate with sauce labs.
So I removed content that brought this idea.
Closes #2736
=> Removing content about integration with SauceLabs

source/_data/courses.yml
update the courses page with a new free course.
=> update the courses page with a new free course

source/_data/plugins.yml
=> remove url tag that is not interpretted in yml files

.gitignore, _config.yml, copy-english-docs.js, source/_data/languages.yml, source/es/guides/overview/why-cypress.md, themes/cypress/languages/es.yml
Adding spanish language, menu translation and "why-cypress" page translation
=> Add Spanish translation (initial)

source/api/commands/invoke.md, source/api/commands/its.md
=> Document timeout options to its and invoke commands

source/_changelogs/4.5.0.md, source/guides/references/experiments.md, themes/cypress/languages/es.yml
=> point component testing at master branches

source/guides/getting-started/installing-cypress.md, source/guides/getting-started/testing-your-app.md, source/guides/overview/why-cypress.md
=> Add references to cross-browser functionality and guides in entry point docs

source/guides/references/experiments.md
=> Update component testing table header

source/guides/getting-started/installing-cypress.md
- Fix an infobox header regression.
=> fix cross-browser info box header

source/guides/guides/continuous-integration.md
Added CentOS dependency install to documentation.
=> [docs] add CentOS dependency install script

source/guides/guides/network-requests.md
There's a difference between your and you're and this doc should respect it.
=> Fix typo in network-requests.md

source/api/commands/select.md, source/guides/core-concepts/interacting-with-elements.md
=> Update select docs to reflect changes from TR

source/_data/courses.yml, source/_data/plugins.yml
- Pluralsight course link
- Rollup preprocessor link
=> Add more links

source/_data/courses.yml
Adding my Udemy course. Hopefully I didn’t miss anything :)
=> Add my Udemy course

source/_data/courses.yml
Updating my Pluralsight course Cypress End to End testing link.
=> Updating the course with url link to pluralsight

source/guides/references/configuration.md
- close #2801
- Fixed example in config that was broken
- Update examples to include options that are probably more popularly used.
=> Update --config flag options to real wroking examples.

source/guides/references/roadmap.md
=> Roadmap update

source/api/commands/request.md
For: https://github.com/cypress-io/cypress/pull/7382
=> Update request.md, adding `encoding` option

source/_changelogs/4.6.1.md, source/_changelogs/4.7.0.md
=> 4.7.0 release

source/guides/tooling/code-coverage.md
- update instructions
- add list of videos
=> Update code coverage

source/guides/dashboard/introduction.md
=> Add dashboard intro video

source/examples/examples/tutorials.md
Added links of Cypress short videos playlists
People love Bushra's videos https://twitter.com/imBushraAlam/status/1177557719617654784
=> add video playlist links

cypress/integration/api_spec.js, cypress/integration/sidebar_spec.js, cypress/integration/table_of_contents.js, cypress/plugins/index.js
Trying to fix or identify the situation where CI times out when running long tests.
=> console log to stdout for certain long running tests

source/guides/tooling/visual-testing.md
=> Add happo to visual testing

source/guides/guides/continuous-integration.md
for https://github.com/cypress-io/cypress/pull/7791
=> docs: note updated Electron libgbm req

source/guides/getting-started/installing-cypress.md
For https://github.com/cypress-io/cypress/pull/7650
=> Node.js 10+ for install 

source/guides/references/best-practices.md
=> Fix missed parentheses for example code
