cypress-io/cypress-documentation

content/_changelogs/10.2.0.md

This updates the 10.2.0 changelog to include a link to the great blog post we released alongside 10.2.0.

docs: Updating 10.2.0 changelog to include link to M1 blog post

---

content/api/commands/session.md
content/guides/references/configuration.md
content/guides/references/legacy-configuration.md

Closes #4490
Some small documentation changes around `cy.session()` and the `experimentalSessionAndOrigin` configuration option.
- We should not recommend using sensitive information like tokens/passwords as session identifiers. This information is displayed in the reporter and can be observes/leaked in a video recording and is logged to the DevTools when the command is clicked. It's better we recommend name-spacing or using a uuid to ensure uniqueness, not tokens/passwords.
- The `experimentalSessionAndOrigin` configuration option is not a valid suite-/test-specific configuration option. Remove from docs.

Updates to `cy.session()` and the `experimentalSessionAndOrigin` configuration option

---

content/api/commands/contains.md

As noted [here](https://github.com/cypress-io/cypress/pull/21285/files#r873417446), this is an existing undocumented quirk of `cy.contains()`, so it doesn't need to go in a release branch.

docs(guides/contains): note limitation on default labels

---

content/guides/continuous-integration/bitbucket-pipelines.md

In the Kitchen Sink example repo, commit ab10094 as of Apr 14, 2022, unified "start:ci" and "start:ci:windows" run scripts and merged into "start". This documentation now correctly reflects that.

Changed the "npm run" script from "start:ci" to just "start"

---

content/guides/component-testing/events-angular.md

Based upon feedback brought up by @brian-mann during yesterday's app demo, this PR adds a warning to the angular getting start guide that the `autoSpyOutputs` flag is an experimental feature.

docs(guides): add experimental alert for autoSpyOutputs

---

content/guides/component-testing/component-framework-configuration.md

Remove a dead link from the documentation for Creating a React App with Webpack

Docs: Remove broken link from React-Webpack documentation

---

content/guides/guides/cross-browser-testing.md
content/guides/guides/launching-browsers.md
content/guides/references/experiments.md

- Closes #4058 
- Closes #4059 
- Closes #4060

docs: document experimentalWebKitSupport

---

content/guides/component-testing/writing-your-first-component-test.md

Missed the section for adding `Svelte` to the list of Getting started frameworks.

chore: add Svelte to Getting Started list of supported frameworks

---

content/guides/component-testing/component-framework-configuration.md

Docs for https://github.com/cypress-io/cypress/pull/23605

docs: add dev server function config API

---

content/guides/references/roadmap.md

For our transparency work we are opening up our github roadmap project board to the public.  I am updating our existing roadmap page to have links to this new resource.  I have removed the static resource from this page to keep the data better in sync.

docs: Update Priorities Page to Point to Project Board

---

content/_changelogs/10.8.0.md
content/_changelogs/10.9.0.md

- Adds 10.9.0 changelog
- Fixes some issues with the 10.8.0 changelog

10.9.0 Changelog

---

content/_data/plugins.json

This PR adds [Argos](https://www.argos-ci.com) to visual testing plugins list.
Here is the plugin GitHub's repo: [@argos-ci/cypress plugin](https://docs.argos-ci.com/cypress).

docs: add argos to plugin list

---

content/_changelogs/11.0.0.md
content/api/commands/origin.md
content/api/commands/session.md
content/api/cypress-api/cookies.md
content/api/cypress-api/session.md
content/faq/questions/using-cypress-faq.md

Removing documentation for `Cookies.defaults` and `Cookies.preserveOnce` which is being replaced with `cy.session()`.

docs: removing Cookies.defaults/preserveOnce

---

content/_changelogs/11.0.0.md
content/api/commands/origin.md
content/api/commands/session.md
content/api/commands/visit.md
content/guides/core-concepts/writing-and-organizing-tests.md
content/guides/references/configuration.md
content/guides/references/experiments.md
content/guides/references/migration-guide.md

Documentation changes for https://github.com/cypress-io/cypress/pull/24340

docs: remove experimentalSessionAndOrigin

---

content/guides/dashboard/introduction.md

Closes #4760 
What do we think of this? Questions:
- Do we want it before or after listing the benefits?
- Should we add some custom design element to make it pop more? I thought about putting it in a green "Premium" callout block but it's right underneath another callout (for the RWA) and I think it would be too busy

Add signup link to top of dashboard introduction page

---

content/guides/references/advanced-installation.md
content/guides/references/proxy-configuration.md

Add info about certificate authorities for cypress binary downloads and calls to the dashboard service to documentation

feat: add info about CAs to documentation

---

content/api/commands/mount.md
content/partials/import-mount-functions.md

I noticed this while reviewing https://github.com/cypress-io/cypress-documentation/pull/4759. The import should be `cypress/vue2` rather than `cypress/vue-2`

Fix vue2 import example

---

content/api/commands/mount.md
content/partials/import-mount-functions.md

[We're removing a lot of info from the adapter readme documents](https://github.com/cypress-io/cypress/pull/24590), so we shouldn't link to them from our docs page anymore.

Remove CT adapter readme links

---

content/guides/references/troubleshooting.md

"View App Data" is currently located under the "Developer Tools" menu, not "File". I didn't go back to check Cypress 9 or earlier, but this is the case in 10.0+.

Fix directions to Clear App Data

---

content/guides/references/advanced-installation.md

Related to https://github.com/cypress-io/cypress/pull/24680.
This PR adds a section to the Advanced Installation page about opting out of Cypress messaging around Cypress Cloud. If the user sets this property to `0` during a cypress run process, we won't show the new recommendation message that we are planning to show in CI after https://github.com/cypress-io/cypress/pull/24680.
One question that remains here is how this relates to ACI messages in app. The wording that I came up with here is broad enough to sound like it covers ACI banners and the like, but it doesn't.

feat: Add docs section about opting out of commercial messaging

---

content/guides/component-testing/angular/api.md
content/guides/component-testing/react/api.md
content/guides/component-testing/svelte/api.md
content/guides/component-testing/vue/api.md
content/guides/component-testing/vue/examples.md

Small updates to fix some examples to match new mount API, standardized wording around `MountReturn`.

update CT mount docs

---

content/_data/sidebar.json
content/api/commands/clearalllocalstorage.md
content/api/commands/clearallsessionstorage.md
content/api/commands/getalllocalstorage.md
content/api/commands/getallsessionstorage.md

For https://github.com/cypress-io/cypress/pull/24859

Add docs for new local/session storage commands

---

content/guides/end-to-end-testing/okta-authentication.md

Adds new cy.origin() guide for okta as primary recommendation over programmatic login. realworld-app update PR: https://github.com/cypress-io/cypress-realworld-app/pull/1293
The test cases for okta are a bit different because I could not get the onboarding workflow to load and couldn't figure out why and didn't have the time to debug the issue. The user is definitely logged in, but might not be considered a new user.

feat: update okta login guide for realworld app

---

content/_changelogs/11.0.0.md
content/_changelogs/12.0.0.md
content/guides/core-concepts/writing-and-organizing-tests.md
content/guides/references/migration-guide.md

v12 Migration Guide

---

content/_data/sidebar.json
content/api/commands/session.md
content/guides/core-concepts/test-isolation.md
content/guides/core-concepts/writing-and-organizing-tests.md
content/guides/references/configuration.md
content/guides/references/migration-guide.md

update test isolation docs & apply product review suggestions

12: update test isolation docs to use true/false instead of on/off

---

content/api/cypress-api/custom-commands.md

Update auth examples for v12 on custom commands page

---

content/guides/end-to-end-testing/testing-your-app.md

Closes #4498 
This PR changes the Testing Your App -> Logging In section to recommend using `cy.session()` to avoid repeated logins instead of programmatic login workarounds.

Update Logging In section of Testing Your App page

---

content/guides/end-to-end-testing/auth0-authentication.md

Addresses #4499
In the end I copied this pretty much verbatim from @AtofStryker 's changes to the Okta docs, thanks Bill!

Update End-to-End Testing -> Auth0 Authentication docs for v12

---

content/api/cypress-api/session.md

Cypress.Session Cypress API

---

content/guides/core-concepts/retry-ability.md

The code example is:
```js
it('creates an item', () => {
cy.visit('/')
cy.focused() // query
.should('have.class', 'new-todo') // assertion
cy.get('.new-todo') // query
.type('todo A{enter}') // action
cy.get('.todoapp') // query
.find('.todo-list li') // query
.should('have.length', 1) // assertion
})
```
But when explaining part of it, it mentions `.children`, instead of `.find`, as you can see below.
```js
cy.get('.todoapp') // query
.children('.todo-list li') // query
.should('have.length', 1) // assertion
```
This PR basically fixes that.

Fix wrong command on retry-ability guide

---

content/guides/core-concepts/retry-ability.md

Small doc fixes that I missed on my previous PR: https://github.com/cypress-io/cypress-documentation/pull/4910.
This piece of code `.children('li').should('have.length', 1)` refers to:
```javascript
cy.get('.todoapp') // query
.find('.todo-list li') // query
.should('have.length', 1) // assertion
```
And so, it should actually be `.find('.todo-list li').should('have.length', 1)`
This text _**Cypress will retry for up to 10 seconds to find a visible element of class `mobile-nav` with text containing "Home".**_ refers to this piece of code:
```javascript
// we've modified the timeout which affects default + added assertions
cy.get('[data-testid="mobile-nav"]', { timeout: 10000 })
.should('be.visible')
.and('contain', 'Home')
```
So, I suggest it to be _**Cypress will retry for up to 10 …

Small doc fixes in Retry-ability Guide

---

content/api/cypress-api/custom-queries.md

By reading the [**Validation**](https://docs.cypress.io/api/cypress-api/custom-queries#Validation) section of the Custom Queries Docs, when it mentions the commands `cy.ensureDocument(subject)` and `cy.ensureWindow(subject)`, the descriptions seem to be inverted.
This PR fixes that.
Cc. @jaffrepaul

Adjust inverted description on custom queries docs

---

content/_changelogs/12.0.0.md

**Fixes:** [issue-4936](https://github.com/cypress-io/cypress-documentation/issues/4936)
**Before changes:**
**After changes:**
https://user-images.githubusercontent.com/32891808/208301795-02c1e0ef-5690-4280-97be-93e7431bfac4.mov

fix: link format

---

content/guides/continuous-integration/introduction.md

Relates to: https://github.com/cypress-io/cypress/pull/25036
Add section explaining the new environment variables you can set to provide the cloud with context around pull request and builds.

docs: explain user provided ci provider env vars

---

content/guides/tooling/typescript-support.md

Changes: 
- Return type of custom commands:  `Chainable<Element>` => `Chainable<JQuery<HTMLElement>>`
- Removes `/// <reference types="cypress" />` as we already get these types from `tsconfig.json#compilerOptions.types`
closes cypress-io/cypress#24416

Corrects return type of custom commands

---

content/api/commands/session.md

When I copied this code to my editor, the linter expected a comma here.

[DOCS] Add missing comma in session example

---

src/components/blogs-list/index.tsx
src/components/webinars-list/index.tsx
src/css/custom.scss

Add space to list bottom, adjust grid width & add image border. 
We discussed that the whole _examples/media_ section needs to be revamped so we weren't investing a lot of time until there's a new content plan and accompanying layout. Until then, this makes it a little easier on the eyes and matches what's currently in production.

Examples section visual adjustments 

---

docs/api/cypress-api/config.mdx

The [`value` argument](https://docs.cypress.io/api/cypress-api/config#Arguments) for `Cypress.config(name, value)` is described to be a `String`, which is incorrect since it can also be `number`, `null`, `undefined`
Also, the [code block example](https://docs.cypress.io/api/cypress-api/config#Cypress-config-executes-Synchronously) set the value as `'null'` instead of `null`

fix: correct config argument and code block

---

docs/guides/references/trade-offs.mdx

Removing this statement as it is confusing taken alone and without proof of concepts to back up how to achieve this it's not helpful. 
For context, this was written in the early days of Cypress in the tone of 'this is something we experimented with and we saw it is possible' because we experimented with many things in the early days of Cypress. So there were some statements in the docs that were more experimental in nature and not actually recommended practice. With the maturity that Cypress is at, I think it's best to not make a statement in this way without a clear recommendation on how to utilize it to show our users.

Remove statement about multiple browser synchronization

---

docs/guides/references/changelog.mdx

The Microsoft Edge Binary detection addressing https://github.com/cypress-io/cypress/issues/25455 has only been partially solved, so we'll add this entry back in once the second PR has landed.

chore: remove misleading Microsoft Edge changelog entry

---

docs/guides/overview/why-cypress.mdx
docusaurus.config.js

Broken links will now error out & fail the deploy during the build instead of just warning.

Update link checker

---

docs/guides/references/best-practices.mdx

This was somewhere between using the icons from the previous site mixed with some emojis as a test but the markdown was still rendering incorrectly. I swapped out emojis for the icons with the mdx v1 workaround I discovered later. Now they render correctly.

Fix icon render issue

---

docs/guides/core-concepts/testing-types.mdx

Small documentation fix on the testing types page — more suspectable to flake -> more _susceptible_ to flake

docs: fix typo on the testing types page

---

docs/api/queries/readfile.mdx
docs/guides/references/migration-guide.mdx

Matching code PR: https://github.com/cypress-io/cypress/pull/25595
`.readFile()` will be a query in Cypress 13. This should have minimal impact on most users, but is a breaking change for anyone who was overwritting the command.

.readFile() is now a query

---

docs/guides/guides/command-line.mdx

Hi, this PR fix the command line documentation that shows how to test a single spec file. The `--` is needed to pass parameters to `npm run cy:run`.
Thanks!!!

docs: fixed command line to run single test file using npm script

---

docs/guides/references/assertions.mdx

As part of https://github.com/cypress-io/cypress-documentation/pull/5053, I was reviewing our guides, and think that the assertions reference could be improved to be more useful when writing tests.
I've done three things in this PR.
1. Added `.should()` examples of each assertion. Users should write their assertions like this in order to maintain retry-ability. Providing this as the first example in each case will help them make fewer mistakes. Also, I've always wished it were like this when I reference the page in my own test writing. I'm "users".
2. Removed the TDD style assertions list. We do not use it anywhere in our own codebase, and we have no tests around it. It also doesn't work with `.should() / .and()`, which is how we recommend users write tests.
3. Removed a contradictory …

Update assertions reference

---

docs/guides/component-testing/angular/overview.mdx

This PR wraps the current `options API` configuration and puts it inside the `devServer` option where it is suppose to live.

fix(guides): incorrect angular options API configuration

---

docs/guides/component-testing/vue/quickstart.mdx

In the `Testing Vue Components with Events` section towards the end of the document, the text should say "at sign" instead of "ampersand".

Fix a typo - should refer to at sign instead of ampersand

---

docs/guides/guides/screenshots-and-videos.mdx

The current example in the docs requires `del` and `lodash` packages to be installed.
This action can be achieved using only `Array.prototype.some()` and the Node `fs` library.

docs: delete videos without failing/retried tests

---

docs/guides/guides/cross-browser-testing.mdx

This PR updates the CircleCI Orb examples to use the new version 3 of the orb.

ref: circle orb examples to use v3

---

docs/guides/continuous-integration/github-actions.mdx

The [GitHub Actions documentation](https://docs.cypress.io/guides/continuous-integration/github-actions) currently specifies version 5.2.0 of `cypress-io/github-action`  as an example for running a specific version number of the action, however this version doesn't exist yet.
I've switched it out for the latest version of the action (5.1.0).

Correct specific version number for GitHub Action

---

docs/api/cypress-api/custom-queries.mdx

- Closes https://github.com/cypress-io/cypress-documentation/issues/5041
The example query was misleading in a couple of ways, such as relying on Cypress' internal `$dom` utilities and relying on `Commands` being passed in (which only occurs internally; it's not how users would write a query).
The example can now be copy-pasted and run exactly as written.

Fix .addQuery() example to work exactly as written

---

docs/guides/guides/debugging.mdx
docs/guides/references/changelog.mdx

cypress-fiddle project has been archived since it's not actively maintained. I removed it from the Debugging page. I left it on the plugins page since it has a 'community' flag, perhaps someone would find value from it or want to fork it, but they'd be able to clearly see it's not actively maintained from the archived repo.

Remove Cypress fiddle from debugging page

---

docs/guides/references/configuration.mdx

Removed in Cypress 8.0.0 when Firefox < 86 support was dropped. Addressed in https://github.com/cypress-io/cypress/pull/17368. 
See warning message when this configuration is passed: https://github.com/cypress-io/cypress/blob/1c5a67fa927e16620966e977f12cd8a7c3ff69fc/packages/errors/src/errors.ts#L1231

Remove invalid `firefoxGcInterval` configuration

---

docs/guides/references/changelog.mdx

add the changelog from https://github.com/cypress-io/cypress/commit/86175a95ec0b5a0dafba2c8f0b242e282f27c279

chore: add 12.8.1 CHANGELOG

---

docs/api/plugins/after-spec-api.mdx

Return value does not align with our TS definitions.
https://github.com/cypress-io/cypress/issues/26150

Update code to be valid TS

---

docs/guides/references/changelog.mdx

Typo which does not recognize the version 9.2.1 as a new section.

Typo in changelog regarding version 9.2.1

---

docs/guides/continuous-integration/github-actions.mdx

In addition to handling npm-based repositories https://github.com/cypress-io/github-action offers pnpm, Yarn Classic and Yarn Modern support. See https://github.com/cypress-io/github-action#examples
`pnpm` and `yarn` are now explicitly mentioned in 
https://docs.cypress.io/guides/continuous-integration/github-actions

add pnpm and yarn to github-action capabilities

---

docs/guides/guides/parallelization.mdx

The build id for Buildkite is being created with `BUILDKITE_BUILD_ID` when the user do not specify a custom ci-build-id

Update Buildkite CI build id env variables

---

docs/api/plugins/after-run-api.mdx
docs/api/plugins/after-spec-api.mdx
docs/api/plugins/before-run-api.mdx
docs/api/plugins/before-spec-api.mdx

I noticed that some of the Cypress plugin examples are wrapped in unnecessary `module.exports` blocks. So, I've removed them to make the examples valid.

docs: remove unneeded module.exports in plugin examples

---

docs/guides/continuous-integration/github-actions.mdx

This PR fixes and updates the example in [Guides > Continuous Integration > Github Actions](https://docs.cypress.io/guides/continuous-integration/github-actions) with the section heading [Caching Dependencies and Build Artifacts](https://docs.cypress.io/guides/continuous-integration/github-actions#Caching-Dependencies-and-Build-Artifacts).
The example is faulty.
The example `install` job shows the steps in the wrong order. It uploads the `build` folder before this has been created.
The example `cypress-run` job downloads the `build` folder, but then overwrites it with a `yarn build` command. It should not re-build.
The [needs:](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_idneeds) key is missing, so there is no guarantee that the download …

fix GHA caching dependencies and build artifacts example

---

docs/examples/docker.mdx

There is a large set of examples in the Docker examples page that are out of date or archived. We shouldn't be referencing out of date examples on our docs. We should refer everyone to the docker-images GitHub repo which has the most up to date examples in its Readme.
This PR removes all of the examples on the Docker examples page.
Likely there should be improvements on where information around docker images lives in the docs overall.

Remove very old examples from Docker examples page

---

docs/guides/references/changelog.mdx

This PR updates the `CHANGELOG` for the `12.11.0` release

chore: update changelog for 12.11.0 release

---

docs/guides/getting-started/installing-cypress.mdx

I can't imagine this info being relevant to anyone. This seems like a throwback notice to the time when we had a different npm package version than the binary? What's the value in a user knowing this at the time they install? Maybe someone else's view differs and I'm missing the point of this section - welcome to feedback.

Remove notice about the npm package and the cypress binary versions

---

docs/guides/component-testing/component-framework-configuration.mdx

* switch section on custom index html file and dev server, so it's already explained when mentioning it in the dev-server-section
* add a minimal example for the test-kickstart-script
* update documentation of the parameters
* add some explanation on the role of the dev-server

Extend docs on how to write a custom devServer

---

src/data/plugins.json

* add helper that significatly simplifies the dev-server api (cypress-ct-custom-devserver)
* add esbuild-dev-server plugins (cypress-devserver-esbuild)

Add component test devserver plugins

---

src/components/plugins-list/style.module.css

Quick fix to allow plugin list items to wrap at a mobile breakpoint
| Before | After |
| --- | --- |
| <img width="100%" alt="Screenshot 2023-05-09 at 9 22 54 AM" src="https://github.com/cypress-io/cypress-documentation/assets/1702361/cc4ff4ea-95b4-48ab-9514-9f1bf9988f61"> | <img width="100%" alt="Screenshot 2023-05-09 at 9 23 04 AM" src="https://github.com/cypress-io/cypress-documentation/assets/1702361/c5d96797-a711-4500-919e-335718aca077"> |
_Video_
https://github.com/cypress-io/cypress-documentation/assets/1702361/61bb4f8d-eb40-43ec-8b62-370f134817bb

update plugin list styles to allow wrapping

---

docs/guides/continuous-integration/ci-provider-examples.mdx
docs/guides/guides/network-requests.mdx

- Addresses #5149
- Removes Gitlab example since that repo is archived and hasn't been run in 5 months
- Updates `dashboard.cypress.io` links to `cloud.cypress.io`

Remove gitlab ci example and update cloud links

---

docs/guides/continuous-integration/gitlab-ci.mdx

This PR corrects multiple use of a non-existent script name `start:ci` in code examples in [Continuous Integration > GitLab CI](https://docs.cypress.io/guides/continuous-integration/gitlab-ci) which uses the [cypress-io/cypress-example-kitchensink](https://github.com/cypress-io/cypress-example-kitchensink) repository.
The correct script name is `start` which is already correctly referred to in the explanation text.
The command to start the server is [npm start](https://docs.npmjs.com/cli/v9/commands/npm-start). This script is defined in [cypress-io/cypress-example-kitchensink > package.json](https://github.com/cypress-io/cypress-example-kitchensink/blob/master/package.json).

fix wrong kitchensink script references in GitLab CI example

---

src/data/plugins.json

Add cypress-backoff to plugins.json

---

docs/api/commands/getallcookies.mdx
docs/api/commands/getalllocalstorage.mdx
docs/api/commands/getallsessionstorage.mdx
docs/api/commands/origin.mdx
docs/api/commands/session.mdx
docs/api/commands/task.mdx
docs/api/commands/viewport.mdx
docs/api/commands/visit.mdx
docs/api/cypress-api/require.mdx
docs/guides/core-concepts/conditional-testing.mdx
docs/guides/core-concepts/introduction-to-cypress.mdx
docs/guides/end-to-end-testing/testing-strategies/social-authentication.mdx
docs/guides/guides/cross-origin-testing.mdx
docs/guides/guides/web-security.mdx
docs/guides/overview/why-cypress.mdx
docs/guides/references/best-practices.mdx
docs/guides/references/changelog.mdx
docs/guides/references/error-messages.mdx
docs/guides/references/migration-guide.mdx

- Update visit/origin examples to not visit external sites
- Ensure wording of docs are that Cypress discourages testing sites not under your control.

Update examples so that they don't visit websites the user wouldn't control

---

docs/api/commands/exec.mdx

For exec command on Windows
------
```
cy.exec('print README.md').then((e) => console.log(e.stdout))
```
output: "**Unable to initialize device PRN**"
```
cy.exec('type README.md').then((e) => console.log(e.stdout))
```
output: "**ACTUAL contents**"

Windows uses "type" not "print" for cat

---

docs/guides/guides/module-api.mdx

- Closes #5248
This PR resolves https://github.com/cypress-io/cypress-documentation/issues/5248. It adds a note for [Yarn Plug'n'Play](https://yarnpkg.com/features/pnp) to use [yarn node](https://yarnpkg.com/cli/node) instead of [node](https://nodejs.dev/en/learn/run-nodejs-scripts-from-the-command-line/) in the
[Module API](https://docs.cypress.io/guides/guides/module-api) Guide
To verify that the instructions are correct:
- Use cypress@12.9.0 to avoid issue https://github.com/cypress-io/cypress/issues/26567 and https://github.com/cypress-io/cypress/issues/26676.
Execute:
```bash
mkdir cy-module-api-pnp
cd cy-module-api-pnp
git init
yarn set version berry
yarn init -y
yarn add cypress@12.9.0 -D -E
yarn cypress open
```
- Ignore error `ERROR:node_bindings.cc(279)` (see issue …

Add Yarn Plug'n'Play note to Module API guide

---

docs/faq/questions/using-cypress-faq.mdx
docs/guides/component-testing/overview.mdx
docs/guides/component-testing/react/overview.mdx

This PR fixes references to the bookmark `#Nextjs` referring to the section:
[Component Testing > React Component Testing > React Overview > Next.js](https://docs.cypress.io/guides/component-testing/react/overview#Nextjs)
The currently used bookmark `#Next-js` does not exist. The available bookmark is `#Nextjs`.
The PR corrects links in:
- [FAQ > Using Cypress > Can I test Next.js sites using Cypress?](https://docs.cypress.io/faq/questions/using-cypress-faq#Can-I-test-Nextjs-sites-using-Cypress) (second paragraph)
- List entry for Next.js in [Component Testing > React Component Testing > Framework Support](https://docs.cypress.io/guides/component-testing/react/overview#Framework-Support) (clicking on link has no effect)
- [Component Testing > Overview > Supported …

fix #Nextjs bookmark

---

docs/guides/component-testing/react/overview.mdx

This PR changes the link in the documentation page
[Component Testing > React Component Testing > React Overview > Framework Configuration > Next.js > Sample Next.js Apps](https://docs.cypress.io/guides/component-testing/react/overview#Sample-Nextjs-Apps) to
- [Next.js 13 with TypeScript](https://github.com/cypress-io/cypress-component-testing-apps/tree/main/react-next13-ts)
instead of it using the example of the previous Next.js version 
- [Next.js 12 with TypeScript](https://github.com/cypress-io/cypress-component-testing-apps/tree/main/react-next12-ts).
Next.js `13` is the current version (see [releases](https://github.com/vercel/next.js/releases)).

update to Next.js 13 with TypeScript example

---

src/data/plugins.json

This PR modifies the entry in the [Plugins > Development Tools](https://docs.cypress.io/plugins#Development%20Tools) list for the GitHub JavaScript action [github-action](https://github.com/cypress-io/github-action).
The definitive description of the action is taken from the top of its [README](https://github.com/cypress-io/github-action/blob/master/README.md) file (as it is published to GitHub's Marketplace as [cypress-io/github-action](https://github.com/marketplace/actions/cypress-io#cypress-iogithub-action--) and npm's JavaScript Package Registry as [@cypress/github-action](https://www.npmjs.com/package/@cypress/)github-action):
"[GitHub Action](https://docs.github.com/en/actions) for running [Cypress](https://www.cypress.io) end-to-end and component tests. Includes npm, pnpm and Yarn …

update github-action description in plugins list to include pnpm and Yarn

---

docs/faq/questions/using-cypress-faq.mdx

This PR removes a reference to a Cypress / Next.js tutorial which is a failing link to https://getstarted.sh/bulletproof-next/e2e-testing-with-cypress.
The link was last observed working on April 18, 2021 according to http://web.archive.org/web/20210715000000*/https://getstarted.sh/bulletproof-next/e2e-testing-with-cypress. Since then the site has responded with an HTTP 500 server error.
The link was included in
- [FAQ > Using Cypress > Can I test Next.js sites using Cypress?](https://docs.cypress.io/faq/questions/using-cypress-faq#Can-I-test-Nextjs-sites-using-Cypress) ("You can learn how to set good Cypress tests for a Next.js application in this [tutorial](https://getstarted.sh/bulletproof-next/e2e-testing-with-cypress)")

remove unreachable Cypress Next.js tutorial

---

src/data/plugins.json

update cypress-io plugin links to develop branch
This PR modifies cypress-io plugin links in the [Plugins](https://docs.cypress.io/plugins) list which were referring to the https://github.com/cypress-io/cypress/tree/master branch. This branch is no longer maintained and the active branch is `develop`.

update cypress-io plugin links to develop branch

---

docs/guides/tooling/typescript-support.mdx

This PR removes the reference and link to the obsolete TypeScript "find the [standalone example](https://github.com/cypress-io/add-cypress-custom-command-in-typescript)" in [Tooling > TypeScript > Examples](https://docs.cypress.io/guides/tooling/typescript-support#Examples) using Cypress `3.8.3` before native TypeScript support was released with Cypress `4.4.0`.
As stated on the Cypress documentation page [Tooling > TypeScript > History](https://docs.cypress.io/guides/tooling/typescript-support#History):
[4.4.0](https://docs.cypress.io/guides/references/changelog#4-4-0)	Added support for TypeScript without needing your own transpilation through preprocessors.
---
https://github.com/cypress-io/add-cypress-custom-command-in-typescript uses the npm module …

remove obsolete TypeScript standalone example pre Cypress 4.4.0

---

src/components/blogs-list/index.tsx

Blog posts are set up to deeplink to the noted content but also the root source as a credit within "Published on...". This fixes both areas pointing only to the root source.

fix blog deeplinks

---

src/data/courses.json

This PR corrects a link to "Test a React Todo App" in the list of [Examples > Media > Courses](https://docs.cypress.io/examples/media/courses-media).
The tutorial is located at https://docs.cypress.io/examples/tutorials#Test-a-React-Todo-App. It is a legacy tutorial using Cypress `3.5.0`.
It should be separately considered whether this tutorial should be kept online considering the old Cypress `3.5.0` version used, and the fact that there is a newer ToDo tutorial on https://github.com/cypress-io/cypress-example-todomvc using Cypress `12.12.0`.

Correct link to legacy "Test a React Todo App" tutorial

---

src/components/courses-list/index.tsx

This PR corrects a typo and adds "component testing" to the introduction text on [Examples > Media > Courses](https://docs.cypress.io/examples/media/courses-media).

correct online courses intro text

---

src/data/plugins.json

[cypress-mailhog](https://github.com/SMenigat/cypress-mailhog) is a well maintained command library that allows interaction with the MailHog RestAPI. 
Since the library is already widely used I would be very happy to see it on the official plugin list. 
Please let me know if there are any open todos to get the plugin listed.

Plugin: Adds entry for cypress-mailhog email plugin

---

docs/faq/questions/using-cypress-faq.mdx

Fixes Issue #5131 & #5282.
Changed the Broken link to "https://github.com/cypress-io/cypress/tree/develop/packages/launchpad/cypress/e2e" as suggested by @MikeMcC399

Fixed electron example link

---

docs/api/plugins/browser-launch-api.mdx

This adds a blurb about how to disable --headless=new if someone runs into issues with it.

chore: update with guidance about how to disable --headless=new

---

docs/api/cypress-api/custom-commands.mdx
docs/guides/end-to-end-testing/migration/protractor-to-cypress.mdx
src/data/plugins.json

This PR moves the [xpath](https://github.com/cypress-io/cypress/tree/develop/npm/xpath) plugin reference in the [Plugins list](https://docs.cypress.io/plugins) to the [Legacy](https://docs.cypress.io/plugins#Legacy) section.
Links to [cypress-io/cypress-xpath](https://github.com/cypress-io/cypress-xpath) on other pages are removed.
- [Plugins list](https://docs.cypress.io/plugins)
- [API > Custom Commands > See also](https://docs.cypress.io/api/cypress-api/custom-commands#See-also)
- [End-to-End Testing > Migrating from Other Frameworks > Migrating from Protractor to Cypress > Working with the DOM](https://docs.cypress.io/guides/end-to-end-testing/protractor-to-cypress#Working-with-the-DOM)
[xpath](https://github.com/cypress-io/cypress/tree/develop/npm/xpath) shows the README text …

address deprecated xpath plugin references

---

docs/api/plugins/preprocessors-api.mdx
docs/faq/questions/general-questions-faq.mdx
docs/guides/core-concepts/retry-ability.mdx
docs/guides/core-concepts/writing-and-organizing-tests.mdx
docs/guides/end-to-end-testing/migration/protractor-to-cypress.mdx
docs/guides/guides/debugging.mdx

- closes #5273
This PR updates links which are intended to point to the default branch of the [cypress-io/cypress](https://github.com/cypress-io/cypress) repository.
Previously the default branch was the [master branch](https://github.com/cypress-io/cypress/tree/master), which has been changed to be the [develop branch](https://github.com/cypress-io/cypress/tree/develop).
So links to
- https://github.com/cypress-io/cypress/tree/master are changed to
- https://github.com/cypress-io/cypress/tree/develop
(Currently 1006 commits behind `develop`.)
- https://github.com/cypress-io/cypress/tree/master/npm/webpack-preprocessor
- https://github.com/cypress-io/cypress/tree/master/npm/react
- https://github.com/cypress-io/cypress/tree/master/npm/cypress-schematic
**No** changes are made to the …

docs: update master branch links to develop branch

---

docs/guides/guides/content-security-policy.mdx
docs/guides/references/configuration.mdx
docs/guides/references/experiments.mdx

Documentation for ~~`stripCspDirectives`~~ [`experimentalCspAllowList` feature](https://github.com/cypress-io/cypress/pull/26483)

feat: Add documentation for `stripCspDirectives` and CSP information

---

docs/guides/guides/module-api.mdx

In response to this issue: https://github.com/cypress-io/cypress/issues/6646

Add example on how to programmatically control which browser to run tests in. 

---

docs/guides/guides/module-api.mdx
docs/guides/guides/screenshots-and-videos.mdx
docs/guides/references/configuration.mdx

documentation updates for removing `videoUploadOnPasses` from the documentation for v13. see https://github.com/cypress-io/cypress/pull/27010 for implementation details

BREAKING: remove the videoUploadOnPasses configuration option

---

src/components/plugins-list/style.module.css

Resubmission of https://github.com/cypress-io/cypress-documentation/pull/5320
Closes https://github.com/cypress-io/cypress-documentation/issues/5305
This PR adds css property `flex-direction: column` for the class `pluginTitle` in [src/components/plugins-list/style.module.css](https://github.com/cypress-io/cypress-documentation/blob/main/src/components/plugins-list/style.module.css), correcting a display issue on https://docs.cypress.io/plugins.
The plugin badge (`official`, `verified`, `community` or `experimental`) is now always displayed below the name of the plugin and it never overflows out of the plugin's box.
It also corrects a potential issue which has not been apparent so far, that an unhyphenated plugin name longer than 24 characters would also overflow. This is a consequence of …

fix overflowing plugins title and badge

---

docusaurus.config.js

Replaces https://github.com/cypress-io/cypress-documentation/pull/5331
This PR adds a link
https://www.cypress.io/support/
to the footer of https://docs.cypress.io/ under the **Company** heading.
The site https://www.cypress.io/ already contains a link to [Support](https://www.cypress.io/support/) under the footer **Company** heading, so adding the same link to the https://docs.cypress.io/ footer is consistent.
---
BEFORE
---
AFTER

Add support link to footer

---

docs/guides/core-concepts/variables-and-aliases.mdx

The existing example from the docs was failing with `expected undefined to deeply equal 'blue'`.
The new modified test succeeds.

fix ref in alias example

---

docs/guides/component-testing/overview.mdx
docs/guides/component-testing/third-party-definitions.mdx
docs/guides/guides/command-line.mdx

Wanted to add Qwik as a possible framework to use with component testing
figured it'll be nice to have a place where community supported framework integrations could be listed in
Thanks!

docs: add community frameworks support

---

docs/guides/tooling/visual-testing.mdx

The link was pointing to `#Visual%20Testing`

Update visual-testing.mdx anchor to point to #visual-testing

---

docs/guides/references/changelog.mdx

Added link to notifications documentation for the change log
Also updated link to Debug page in the change log to be a relative link

fix: add link to notifications documentation

---

docs/guides/guides/launching-browsers.mdx

Issue https://github.com/cypress-io/cypress/issues/27141
Newer versions do not work properly with Cypress.

docs: lock webkit version

---

docs/guides/getting-started/opening-the-app.mdx
docs/guides/guides/command-line.mdx

All currently supported versions of `npm` include `npx` integrated, so `npx` can be treated as a command which is available to all users of `npm` package management.
Historical references to the stand-alone version of `npx` and the release of `npx` integrated into `npm`, which took place 6 years ago, are removed.
The following two pages are changed:
- [Guides > Getting Started > Opening the App > `cypress open`](https://docs.cypress.io/guides/getting-started/opening-the-app#cypress-open)
- [Guides > Command Line > How to run commands](https://docs.cypress.io/guides/guides/command-line#How-to-run-commands)
- [npm 5.2.0](https://github.com/npm/cli/blob/v5.2.0/CHANGELOG.md) was the first version to include `npx` integrated into `npm`. It was released in July 2017, which is now 6 years ago.
- …

Remove references to stand-alone npx

---

src/data/plugins.json

Plugin link: [cypress-log-filter](https://github.com/Brugui7/cypress-log-filter)
Before submitting your plugin, please check to see if it fulfills these requirements:
If you have reason to believe your plugin does not need to meet certain requirements, please feel free to provide justification below:
- This plugin adds a dropdown in the Cypress UI that may not follow Cypress design style guidelines
- This plugin has a test that fails intentionally to log an error in the command logs.

Add cypress-log-filter plugin

---

docs/guides/continuous-integration/introduction.mdx
docs/guides/getting-started/opening-the-app.mdx
docs/guides/guides/command-line.mdx

- Closes #5381 
References to `$(npm bin)/cypress open` as a way of opening the Cypress app are removed or replaced with `npx cypress open`.
`$(npm bin)/cypress open` works with Node.js `16` and no longer works with Node.js `18` and `20`.
The following pages are affected:
- [Guides > Getting Started > Opening the App > `cypress open`](https://docs.cypress.io/guides/getting-started/opening-the-app#cypress-open)
- [Guides > Command Line > How to run commands](https://docs.cypress.io/guides/guides/command-line#How-to-run-commands)
- [Continuous Integration > Introduction > Official Cypress Docker Images](https://docs.cypress.io/guides/continuous-integration/introduction#Official-Cypress-Docker-Images)
- For `npm` version 9.x or higher, the command `npm bin` has been removed (see [npm v9.0.0 …

Remove references to `npm bin`; removed since npm 9.x

---

docs/guides/references/error-messages.mdx

This error is associated with seeing this error in a run. There's not really any guidance in the error message on how to troubleshoot this situation. Adding troubleshooting guidelines.

Update troubleshooting guide for seeing run finished error with groups.

---

docs/guides/references/migration-guide.mdx

Add video & test replay migration guide entries.

docs: v13 video and TR migration info

---

docs/guides/getting-started/opening-the-app.mdx
docs/guides/guides/command-line.mdx

- Closes #5382
`./node_modules/.bin/cypress open` is no longer necessary in order to open the Cypress app. It is replaced by the simpler `npx cypress open`.
For Yarn Modern configurations `./node_modules/.bin/cypress open` only works with the backwards compatible `node-modules` option, not with `pnp` or `pnpm`.
The following two pages are changed:
- [Guides > Getting Started > Opening the App > `cypress open`](https://docs.cypress.io/guides/getting-started/opening-the-app#cypress-open)
- [Guides > Command Line > How to run commands](https://docs.cypress.io/guides/guides/command-line#How-to-run-commands)
- Prior to [npm 5.2.0](https://github.com/npm/cli/blob/v5.2.0/CHANGELOG.md) there was no command in `npm` to invoke Cypress directly and `./node_modules/.bin/cypress open` was one option …

Remove `./node_modules/.bin/cypress open`

---

src/data/plugins.json

This is attempt 2: https://github.com/cypress-io/cypress-documentation/pull/5231
I have ensured the Cypress runs as part of the CI with a Cypress test that displays the plugin working
Plugin link: [Cypress-SignalR-Mock](https://github.com/JasonLandbridge/Cypress-SignalR-Mock)
Before submitting your plugin, please check to see if it fulfills these requirements:
If you have reason to believe your plugin does not need to meet certain requirements, please feel free to provide justification below:

Add Cypress-SignalR-Mock plugin

---

docs/guides/tooling/visual-testing.mdx

Fixes these:
I had to `prettier-ignore` my changes because prettier forces `<a>` tag on a new line. And because there was no config I could add to prettier for these cases, I just `prettier-ignore`d them.

Update visual-testing.mdx with breaking lines

---

docs/guides/getting-started/installing-cypress.mdx

This PR is related to [#27419](https://github.com/cypress-io/cypress/issues/27419).

docs: install cypress via pnpm

---

docs/guides/guides/web-security.mdx

According to [RFC 6335 - 6. Port Number Ranges](https://www.rfc-editor.org/rfc/rfc6335.html#section-6)
"the Dynamic Ports, also known as the Private or Ephemeral Ports,
from 49152-65535 (never assigned)"
so the value 65874 would be outside the permitted range.

Fix invalid port number in web-security.mdx

---

docs/guides/getting-started/opening-the-app.mdx

This PR adds a caution / Best Practice message to [Getting Started > Opening the App > Adding npm Scripts](https://docs.cypress.io/guides/getting-started/opening-the-app#Adding-npm-Scripts) to suggest **not** to use `cypress` as a literal script name due to its interference with the Yarn / Cypress CLI.
Defining a script in `package.json` with the name `cypress` causes ambiguity for Yarn users and should be avoided.
For instance, with the following definition
```json
"scripts": {
"cypress": "cypress open"
}
```
executing
```bash
yarn run cypress verify
```
will be executed instead as
```bash
yarn run cypress open
```
When there is a script and a binary with the same name `yarn run` (Yarn Classic and Modern) selects the script. Yarn Modern offers the `--binaries-only` option to make the …

Add caution against using cypress as name of script

---

docs/guides/references/changelog.mdx

- `webpack` was misspelled as `wepback`
- there were two instances where `it's` instead of `its` was written. (See https://www.merriam-webster.com/grammar/when-to-use-its-vs-its)

correct miscellaneous typos in changelog

---

src/css/custom.scss

Text links inside the colored callouts are slightly bold but unclear that they are links. This adds a little visual affordance to so it's clear they can be clicked.

docs: add underline styles to admonition content

---

src/css/custom.scss
src/css/markdown.scss

A few minor improvements to add visual affordance to text links in various contexts.

docs: style fixes

---

docs/guides/references/changelog.mdx

Just what it says on the tin ☝️

docs: v13 changelog summary

---

docs/guides/references/changelog.mdx

Adds the `v13.1.0` changelog to the docs site

chore: add changelog for v13.1.0

---

docs/faq/questions/cloud-faq.mdx
docs/guides/references/changelog.mdx

This PR corrects two places where [WebKit](https://www.webkit.org/) (the web browser engine used by Safari) was incorrectly rendered as "Webkit".
- https://www.npmjs.com/package/playwright-webkit
- https://www.webkit.org/

Change Webkit to WebKit

---

docs/guides/continuous-integration/github-actions.mdx

The non-root user `1001` is added to the example in [Continuous Integration > GitHub Actions > Testing with Cypress Docker Images](https://docs.cypress.io/guides/continuous-integration/github-actions#Testing-with-Cypress-Docker-Images). This aligns the example with the Cypress GitHub Action's [README > Docker image](https://github.com/cypress-io/github-action#docker-image) section.
A `caution` paragraph is also added, which refers to more detailed information in the README of the Docker repo under [Firefox not found](https://github.com/cypress-io/cypress-docker-images#firefox-not-found).
---
If this advice is not followed, then
```bash
firefox -v
```
outputs the message
> Running Firefox as root in a regular user's session is not supported.
when
```bash
id
```
shows
> uid=0(root) …

Add non-root user `1001` for Firefox in Cypress GHA with Docker

---

docs/guides/continuous-integration/ci-provider-examples.mdx

[Continuous Integration > CI Provider Examples > BitBucket](https://docs.cypress.io/guides/continuous-integration/ci-provider-examples#BitBucket) (sic) lists the link
> [See BitBucket Pipelines + Cypress Cloud in action](https://cloud.cypress.io/projects/q1ovwz).
This links to Cypress Cloud project [`q1ovwz`](https://cloud.cypress.io/projects/q1ovwz) with the name `cypress-realworld-app-bitbucket`.
- https://github.com/cypress-io/cypress-realworld-app/pull/1376 removed the Bitbucket workflow from the [cypress-io/cypress-realworld-app](https://github.com/cypress-io/cypress-realworld-app) repo on Jul 6, 2023.
- https://github.com/cypress-io/cypress-documentation/pull/5360 from @jennifer-shehane on Jul 5, 2023 noted that references to Bitbucket pipelines should be removed, however the link …

Remove link for disabled Bitbucket recording to Cypress Cloud

---

docs/guides/continuous-integration/github-actions.mdx

Update all workflow examples in [Continuous Integration > GitHub Actions](https://docs.cypress.io/guides/continuous-integration/github-actions)  to use JavaScript action [actions/checkout](https://github.com/actions/checkout) `v4`.
- The previously used `v3` runs under `node16` with [end-of-life](https://nodejs.org/en/blog/announcements/nodejs16-eol) today, Sep 11, 2023
- `v4` is the latest version, which runs under `node20`, and is under active support

update actions/checkout to v4 for GitHub Actions

---

.circleci/config.yml

- bump CirceCI resources to the next tier to help with resource failures
- remove cypress orb for now (nothing custom to test, only docusaurus + markdown content)

chore: bump circle resources

---

docs/guides/references/changelog.mdx

chore: add changelog for release 13.2.0

---

docs/guides/references/best-practices.mdx

Added missing link to the Selecting Elements section of the Best Practices guide.

chore: add link to Best Practices - Selectors

---

docs/guides/continuous-integration/aws-codebuild.mdx
docs/guides/continuous-integration/bitbucket-pipelines.mdx
docs/guides/getting-started/installing-cypress.mdx

Node.js `18` and `20 and above` are the only versions currently supported by Cypress according to [Getting Started > Installing Cypress > System requirements > Node.js](https://docs.cypress.io/guides/getting-started/installing-cypress#Nodejs) therefore examples and templates should only use these versions.
Out of range examples Node.js `12` or `14` are updated to align with existing examples using Node.js `18.x`.
- Update `cypress/base:14` to `cypress/base:18.12.1`
- in [Getting Started > Installing Cypress > Docker](https://docs.cypress.io/guides/getting-started/installing-cypress#Docker)
- (Leave references to `cypress/base:18.12.1` as they are.)
- Update `cypress/browsers:node12.14.1-chrome85-ff81` to `cypress/browsers:node18.12.0-chrome106-ff106`
- in [Continuous Integration > …

docs: update Docker image examples to supported Node.js 18

---

docs/guides/cloud/debugging/test-replay.mdx

Reword to clarify what "runner ui" refers to.

docs: clarify runner ui

---

docs/api/cypress-api/custom-commands.mdx

An updated version of https://github.com/cypress-io/cypress-documentation/pull/5454

docs: add sideEffects workaround

---

docs/guides/references/migration-guide.mdx
docs/guides/tooling/typescript-support.mdx

Closes https://github.com/cypress-io/cypress-documentation/issues/4559
Closes https://github.com/cypress-io/cypress-documentation/pull/4600
Addresses https://github.com/cypress-io/cypress/issues/22059

Adding guide around clashing types with Jest

---

docs/guides/end-to-end-testing/testing-strategies/google-authentication.mdx

Change "follow" to "following" under "Using the Google OAuth 2.0 Playground to Create Testing Credentials" instruction

Fix Google Authentication typo

---

docs/guides/references/changelog.mdx

Also note to people where the strategy has changed for test replay that they can revert the behavior by passing `--runner-ui`
I was prompted to add this after this issue was opened: https://github.com/cypress-io/cypress/issues/27993 but there have been other comments about not understanding how to turn off the new runner-ui behavior in Test Replay

Add note to changelog about --runner-ui and --no-runner-ui options

---

docs/guides/continuous-integration/introduction.mdx
docs/guides/getting-started/installing-cypress.mdx
docs/guides/references/migration-guide.mdx

This PR removes the obsolete Ubuntu/Debian `libgconf-2-4` package from the list of recommended prerequisites for Ubuntu/Debian platforms, listed under
- [Getting Started > Installing Cypress > System requirements > Linux Prerequisites > Ubuntu/Debian](https://docs.cypress.io/guides/getting-started/installing-cypress#Linux-Prerequisites) which currently reads:
```bash
apt-get install libgtk2.0-0 libgtk-3-0 libgbm-dev libnotify-dev libgconf-2-4 libnss3 libxss1 libasound2 libxtst6 xauth xvfb
```
Similarly for
- [Continuous Integration > Introduction > Advanced setup > Dependencies > Linux > Ubuntu/Debian](https://docs.cypress.io/guides/continuous-integration/introduction#Dependencies)
and for
- [References > Migration Guide > Migrating to Cypress …

Remove obsolete libgconf-2-4 from Ubuntu/Debian prerequisites

---

docs/guides/continuous-integration/github-actions.mdx

Even though this is a stub, it should have the correct syntax with the dash indicating the mapping for "uses"

docs(gh action): use correct workflow yaml syntax

---

docs/guides/getting-started/installing-cypress.mdx

- relates to issue #5444
This PR updates the Ubuntu version in the list of supported operating systems under the section [Getting Started > Installing Cypress > System requirements > Operating System](https://docs.cypress.io/guides/getting-started/installing-cypress#Operating-System)
from
- Ubuntu `12.04` and above
to
- Ubuntu `20.04` and above
[Getting Started > Installing Cypress > System requirements > Node.js](https://docs.cypress.io/guides/getting-started/installing-cypress#Nodejs) lists Node.js `18`, `20` and above as being supported.
The [Node.js 18 announcement](https://nodejs.org/en/blog/announcements/v18-release-announce) provides detailed information in the [Toolchain and Compiler Upgrades](https://nodejs.org/en/blog/announcements/v18-release-announce#toolchain-and-compiler-upgr …

Update operating system minimum version to Ubuntu 20.04

---

docs/guides/getting-started/installing-cypress.mdx

- relates to issue #5444
This PR updates the Windows version in the list of supported operating systems under the section [Getting Started > Installing Cypress > System requirements > Operating System](https://docs.cypress.io/guides/getting-started/installing-cypress#Operating-System)
from
- Windows 7 and above (64-bit only)
to
- Windows 10 and above (64-bit only)
[Getting Started > Installing Cypress > System requirements > Node.js](https://docs.cypress.io/guides/getting-started/installing-cypress#Nodejs) lists Node.js `18`, `20` and above as being supported.
The [Node.js 18 announcement](https://nodejs.org/en/blog/announcements/v18-release-announce) provides detailed information in the [Toolchain and Compiler Upgrades](https://nodejs.org/en/blog/announcements/v18-release-announce#toolcha …

Update operating system minimum version to Windows 10

---

docs/guides/references/advanced-installation.mdx

This PR fixes dead links in [Guides > References > Advanced Installation > Windows Subsystem for Linux](https://docs.cypress.io/guides/references/advanced-installation#Windows-Subsystem-for-Linux) intended to point to Linux package prerequisites for running Cypress.
Currently, clicking on the links has no effect, since they refer to non-existent bookmarks on the same page. The PR changes the links to refer to the correct page:
- https://docs.cypress.io/guides/getting-started/installing-cypress
and correct bookmark names:
- [#UbuntuDebian](https://docs.cypress.io/guides/getting-started/installing-cypress#UbuntuDebian)
- [#CentOS](https://docs.cypress.io/guides/getting-started/installing-cypress#CentOS)
The generic bookmark:
- [#Linux-Prerequisites](https://docs.cypress.io/guides/getting-sta …

Fix links to Linux package prerequisites in WSL section

---

src/css/custom.scss

- Some articles contain code blocks and tabbed code blocks that create horizontal scrolling in the document. These changes ensure the code block uses its own width (or, in the case of tabs, a max of 36rem in certain viewport sizes).
https://github.com/cypress-io/cypress-documentation/assets/8979428/df97e9f7-592f-4901-ae8c-c8c4e32cd41f
https://github.com/cypress-io/cypress-documentation/assets/8979428/bbb68b7f-1964-450d-8592-02a0a58694d2
- Visit a few articles with code blocks like [this one](http://localhost:3000/guides/references/migration-guide).
- Ensure there's no horizontal scrolling no matter which viewport you view it from.
- Ensure code blocks behave normally (you can scroll, wrap text, copy).
- Ensure code block tabs behave normally (you can switch tabs, you can scroll through …

Prevent horizontal scrolling coming from code blocks

---

docs/guides/continuous-integration/gitlab-ci.mdx

- [Continuous Integration > GitLab CI](https://docs.cypress.io/guides/continuous-integration/gitlab-ci) incorrectly advises to use a GitLab workflow on GitHub. This makes no sense.
The section referring to applying the GitLab workflow to GitHub is removed. Other inapplicable references to GitHub in a GitLab environment are also removed.
There is no equivalent live replacement repo for GitLab.  The original https://gitlab.com/cypress-io/cypress-example-kitchensink/ repo is archived and no longer maintained. Although it is possible that forking the old GitLab repo and applying the workflow to it would still work, there can be no guarantee of this, and it is better to avoid suggesting it, due to uncertain outcomes. (See https://github.com/cypress-io/cypress-example-kitchensink/issues/615#issu …

Remove incorrectly placed GitHub references in GitLab CI page

---

docs/guides/continuous-integration/aws-codebuild.mdx
docs/guides/continuous-integration/bitbucket-pipelines.mdx
docs/guides/continuous-integration/github-actions.mdx
docs/guides/continuous-integration/gitlab-ci.mdx
docs/guides/continuous-integration/introduction.mdx

This PR updates CI example workflow documentation to use Node.js `20.x`, codename 'Iron'. [Node.js v20.9.0](https://nodejs.org/en/blog/release/v20.9.0) became the Active LTS version on Oct 24, 2023.
- [Continuous Integration > Introduction > Official Cypress Docker Images](https://docs.cypress.io/guides/continuous-integration/introduction#Official-Cypress-Docker-Images)
- [Continuous Integration > AWS CodeBuild > Testing in Chrome and Firefox with Cypress Docker Images](https://docs.cypress.io/guides/continuous-integration/aws-codebuild#Testing-in-Chrome-and-Firefox-with-Cypress-Docker-Images)
- [Continuous Integration > GitHub Actions > Testing with Cypress Docker Images](http://localhost:3000/guides/continuous-integration/github-actions#Testing-with-Cypress-Docker-Images)
- [Continuous …

update ci example workflows to use Node.js 20.x LTS

---

docs/guides/cloud/flaky-test-management.mdx
docs/guides/guides/test-retries.mdx
docs/guides/references/changelog.mdx
docs/guides/references/configuration.mdx
docs/guides/references/experiments.mdx

Co-authored-by: Cacie Prins <cacieprins@users.noreply.github.com>

v13.4.0 Release

---

docs/guides/guides/test-retries.mdx

The retries example code blocks were still using the pre-v10 `.json` syntax with strings as keys. 
This better aligns with the `.js/.ts` object notation.

chore: remove json string syntax

---

docs/guides/references/changelog.mdx

Updates the changelog for the `13.5.0` release.

chore: release 13.5.0

---

docs/guides/references/changelog.mdx

CHANGELOG entry to `13.5.1` release

chore: release 13.5.1

---

docs/api/commands/intercept.mdx

It was a little tricky to read
**Before**
**After**

Makes an `intercept`-related comment more readable 

---

docs/api/actions/selectfile.mdx

The `null` should not wrapped in the `{ encoding: null }`, which would cause a type error.
reference: https://docs.cypress.io/api/commands/fixture#Syntax

docs(selectFile): readFile & fixture should use `null` instead of `{ encoding: null }`

---

docs/api/commands/mount.mdx

For vue 3 tab item, the documentation contains `options.global`. However, for vue 2 tab item, the documentation should say `options.extensions` instead of `options.global`.

Corrected doc for mount API for vue 2

---

docs/guides/guides/command-line.mdx

Noticed the description of the function of the the `--browser` flag was incorrect for `cypress open`. Tweaked a couple other things (mostly "open" vs "run").

chore: update some text for clarity

---

docs/guides/references/changelog.mdx

CHANGELOG updates for release `13.6.0`

chore: release 13.6.0

---

docs/guides/overview/why-cypress.mdx

Removing outdated "Cypress in a Nutshell" video from the page. I'll also be archiving the video on YouTube and removing other references to it.

Update why-cypress to remove nutshell video.mdx

---

docs/guides/guides/launching-browsers.mdx
docs/guides/references/trade-offs.mdx
src/data/plugins.json

- Removes trade off that states Cypress will never support multi-tab testing
- Adds note to browser launching about extra tabs closing between tests
- Adds puppeteer plugin to plugins page

Updates for puppeteer and multi-tab testing

---

docs/guides/guides/command-line.mdx

- This PR follows on from the abandoned PR https://github.com/cypress-io/cypress-documentation/pull/5467.
The example showing the combination of the `--project` and `--spec` option in [Guides > Command Line > Commands](https://docs.cypress.io/guides/guides/command-line#Commands) was inconsistently updated in the transition to Cypress `10.x`:
```shell
cypress run --project tests/e2e --spec ./tests/e2e/cypress/e2e/spec.js
```
The example is not aligned to the default [e2e tests specPattern](https://docs.cypress.io/guides/references/configuration#e2e) `cypress/e2e/**/*.cy.{js,jsx,ts,tsx}` for current versions of Cypress (`.cy` is missing in the filename) and the directory tree structure preceding the command uses the legacy directory `cypress/integration` instead of `cypress/e2e`.
1. Change …

fix cli example with project and spec options

---

docs/faq/questions/using-cypress-faq.mdx

Update the FAQ about links that open new tabs to mention the puppeteer plugin and remove language around never having support.

Update FAQ about testing new tab

---

docs/guides/continuous-integration/github-actions.mdx

This PR updates [actions/upload-artifact](https://github.com/actions/upload-artifact) from `v3` to [actions/upload-artifact@v4](https://github.com/actions/upload-artifact/releases/tag/v4.0.0) in 
[Continuous Integration > GitHub Actions > Caching Dependencies and Build Artifacts](https://docs.cypress.io/guides/continuous-integration/github-actions#Caching-Dependencies-and-Build-Artifacts) 
- This aligns with PR https://github.com/cypress-io/github-action/pull/1098
Migrating [actions/upload-artifact](https://github.com/actions/upload-artifact) from `v3` to `v4` avoids deprecation warnings which would otherwise appear if workflows continue to depend on Node.js `16` through `v3` usage.
- Blog Dec 14, 2023: [GitHub Actions – Artifacts v4 is now Generally …

update CI github action upload-artifact to v4

---

docs/guides/tooling/visual-testing.mdx

Close https://github.com/cypress-io/cypress-documentation/issues/5580
These links are old and no longer accurately explain visual regression, rolling your own.

Remove 'do it yourself' section from docs on visual testing

---

docs/api/assertions/should.mdx
docs/api/commands/intercept.mdx
docs/api/commands/task.mdx
docs/examples/recipes.mdx
docs/examples/tutorials.mdx
docs/faq/questions/using-cypress-faq.mdx
docs/guides/continuous-integration/introduction.mdx
docs/guides/tooling/visual-testing.mdx
src/data/blogs.json
src/data/courses.json
src/data/podcasts.json
src/data/screencasts.json
src/data/talks.json
src/data/webinars.json

Close https://github.com/cypress-io/cypress-documentation/issues/5581
Ran https://www.deadlinkchecker.com/website-dead-link-checker.asp and also removed some resources that are just very old or outdated.

Remove broken + old links

---

docs/api/cypress-api/custom-queries.mdx
docs/guides/guides/debugging.mdx

cy.now was an internal command and never truly documented, yet there were some references in our docs. There have been changes in recent Cypress versions that makes use of this not advisable.

Remove cy.now from documentation

---

docs/guides/references/changelog.mdx

Updates `CHANGELOG` for release `13.6.2`

chore: release 13.6.2 changelog

---

src/data/plugins.json

I added this under "Development Tools", but I wasn't sure if that's the proper section or I should add it under "Frameworks" (even though Solid is a protocol, not a framework). Let me know if you prefer it under a different category.
The documentation is written in [the README of the repository](https://github.com/NoelDeMartin/cypress-solid#cypress-solid-), and you can find a sample application working with CI here: https://github.com/NoelDeMartin/cypress-solid-sandbox/

Add cypress-solid plugin

---

docs/guides/guides/launching-browsers.mdx
docs/guides/references/troubleshooting.mdx

This service is no longer maintained: https://github.com/cypress-io/chromium-downloads

Remove references to cypress's chromium dls

---

docs/api/plugins/before-run-api.mdx

The [currently linked page](https://docs.cypress.io/guides/references/configuration#Experiments), does not list any information on the `experimentalInteractiveRunEvents` config value. This flag is explained [here](https://docs.cypress.io/guides/references/experiments#Configuration).
I also find it a bit confusing to have `experiments#Configuration` and `configuration#Experiments`. Maybe one of them should link to the other or something like that?

Fix link to 'experimentalInteractiveRunEvents'

---

docs/guides/references/experiments.mdx

While "irregardless" _is_ a word, it is probably too quirky for international readers, likely used here by mistake.

Replace "irregardless" with "regardless".

---

docs/guides/tooling/typescript-support.mdx

updatesTypeScript documentation to display new minimum version set inCypress v13 and update changelog entry.
Also add entry on values being overridden in the users `tsconfig.json` in order to make their typescript files executable inside the Cypress Node.js runtime

update TypeScript documentation

---

docs/guides/references/changelog.mdx
docs/guides/tooling/typescript-support.mdx

- adds the `13.6.3` changelog from the app.
- contains merged in https://github.com/cypress-io/cypress-documentation/pull/5604

chore: add changelog from 13.6.3

---

netlify.toml

Based on https://docs.google.com/spreadsheets/d/17u7EsUQNPjHntfqAFPLzEjiIyDMIwU5SVMYEADjLcUQ/edit#gid=0

chore: Add reroutes for routes linked from outside blogs to real URLs

---

docs/guides/core-concepts/retry-ability.mdx

URL: https://docs.cypress.io/guides/core-concepts/
I just noticed some text that is not probably in bold on the live website, this is a minor PR to fix that.
I'm not sure if this fix is already in a separate branch. This is my first time contributing, so forgive me if I am missing any steps here.

Fix bold markdown in retry-ability.mdx

---

docs/guides/continuous-integration/github-actions.mdx

This PR updates [actions/download-artifact](https://github.com/actions/download-artifact) from `v3` to [actions/download-download@v4](https://github.com/actions/download-artifact/releases/tag/v4.0.0) in
[Continuous Integration > GitHub Actions > Caching Dependencies and Build Artifacts](https://docs.cypress.io/guides/continuous-integration/github-actions#Caching-Dependencies-and-Build-Artifacts)
- PR https://github.com/cypress-io/cypress-documentation/pull/5579 only covered `upload-artifact` and it is important that upload and download both use the same version as `v4` is not cross-compatible with `v3`.
- Blog Dec 14, 2023: [GitHub Actions – Artifacts v4 is now Generally Available](https://github.blog/changelog/2023-12-14-github-actions-artifacts-v4-is-now-generally-available/)

update CI github action download-artifact to v4

---

docs/api/queries/children.mdx
docs/api/queries/closest.mdx
docs/api/queries/contains.mdx
docs/api/queries/eq.mdx
docs/api/queries/filter.mdx
docs/api/queries/find.mdx
docs/api/queries/first.mdx
docs/api/queries/focused.mdx
docs/api/queries/get.mdx
docs/api/queries/last.mdx
docs/api/queries/next.mdx
docs/api/queries/nextall.mdx
docs/api/queries/nextuntil.mdx
docs/api/queries/not.mdx
docs/api/queries/parent.mdx
docs/api/queries/parents.mdx
docs/api/queries/parentsuntil.mdx
docs/api/queries/prev.mdx
docs/api/queries/prevall.mdx
docs/api/queries/prevuntil.mdx
docs/api/queries/shadow.mdx
docs/api/queries/siblings.mdx

- This PR is a partial fix of https://github.com/cypress-io/cypress-documentation/issues/5630, addressing bad anchor links to https://docs.cypress.io/guides/core-concepts/introduction-to-cypress#Default-Assertions.
https://docs.cypress.io/guides/core-concepts/introduction-to-cypress contains no bookmark `Default-Assertions`.
- The bookmark in https://docs.cypress.io/guides/core-concepts/introduction-to-cypress was changed from `Default-Assertions` to [Implicit- Assertions](https://docs.cypress.io/guides/core-concepts/introduction-to-cypress#Implicit-Assertions) in PR https://github.com/cypress-io/cypress-documentation/pull/5315
`/guides/core-concepts/introduction-to-cypress#Default-Assertions` is changed to
[/guides/core-concepts/introduction-to-cypress#Implicit-Assertions](https://docs.cy …

Change anchor links from `Default-Assertions` to `Implicit Assertions`

---

docs/guides/references/changelog.mdx

- This PR resolves some of the incorrectly formatted anchor links listed in issue https://github.com/cypress-io/cypress-documentation/issues/5630. These are ones in the [References > Changelog](https://docs.cypress.io/guides/references/changelog) page referring to certain versions in the same Changelog page using an anchor in the form `#x.y.z` instead of `#x-y-z`.
- Additionally, a typo in the changelog [cypress@5.4.0](https://docs.cypress.io/guides/references/changelog#5-4-0) referring to implausibly fixing a regression in the non-existent and later version `cypress@5.8.0` is fixed. PR https://github.com/cypress-io/cypress/pull/8406 showed that in fact the regression was in [cypress@5.0.0](https://docs.cypress.io/guides/references/changelog#5-0-0). The link is changed to refer to …

Correct version links in Changelog

---

docs/guides/core-concepts/writing-and-organizing-tests.mdx

- This PR is related to issue https://github.com/cypress-io/cypress-documentation/issues/5630. It resolves issues with anchor links in the page [Core Concepts > Writing and Organizing Tests](https://docs.cypress.io/guides/core-concepts/writing-and-organizing-tests), in addition to those proposed for correction in https://github.com/cypress-io/cypress-documentation/issues/5630.
1. The bad link to [/guides/guides/environment-variables#Option-2-cypress-env-json](https://docs.cypress.io/guides/guides/environment-variables#Option-2-cypress-env-json) is corrected to [/guides/guides/environment-variables#Option-2-cypressenvjson](https://docs.cypress.io/guides/guides/environment-variables#Option-2-cypressenvjson) (extraneous hyphens `-` removed).
2. The bad link to …

Correct links in "Writing and Organizing Tests"

---

docs/api/commands/fixture.mdx
docs/api/commands/screenshot.mdx
docs/guides/core-concepts/writing-and-organizing-tests.mdx
docs/guides/references/error-messages.mdx
docs/guides/references/migration-guide.mdx
docs/guides/tooling/code-coverage.mdx
docs/guides/tooling/typescript-support.mdx

- This PR resolves a set of bad links listed in issue https://github.com/cypress-io/cypress-documentation/issues/5630 on various pages and related to Folders / Files configuration options.
Multiple pages link to the non-existent bookmark [/guides/references/configuration#Folders-Files](https://docs.cypress.io/guides/references/configuration#Folders-Files).
Using this link opens the correct page at the top and does not show the intended Folders / File section. Users would need to scroll down and search manually.
The multiple pages, which link to the non-existent bookmark [/guides/references/configuration#Folders-Files](https://docs.cypress.io/guides/references/configuration#Folders-Files), are changed to link instead to [References > Configuration > Options > Folders / …

Correct link to config folders / files

---

docs/guides/continuous-integration/ci-provider-examples.mdx

- Closes https://github.com/cypress-io/cypress-documentation/issues/5538
This PR removes the section in [Continuous Integration > CI Provider Examples > Guides > AWS CodeBuild](https://docs.cypress.io/guides/continuous-integration/ci-provider-examples#AWS-CodeBuild) which refers to the AWS CodeBuild example.
The example's last run was many months ago in July 2023, and according to @jennifer-shehane in https://github.com/cypress-io/cypress-documentation/issues/5538#issuecomment-1939035158 it is not expected for it to be reactivated:
> We don't intend to continue supporting running the AWS CodeBuild
---
**BEFORE**
---
**AFTER**

Remove AWS CodeBuild links for disabled example

---

docs/guides/references/changelog.mdx

This PR fixes two broken links in the [Cypress Changelog](https://docs.cypress.io/guides/references/changelog).
From [Cypress `9.5.4`](https://docs.cypress.io/guides/references/changelog#9-5-4)
- https://github.com/cypress-io/cypress/issue/18886 (404 error) should be `https://github.com/cypress-io/cypress/issues/18886` linking to https://github.com/cypress-io/cypress/issues/18886
From [Cypress `9.2.0`](https://docs.cypress.io/guides/references/changelog#9-2-0)
- [Node's maximum Buffer size](https://nodejs.org/api/buffer#bufferconstantsmax_length) https://nodejs.org/api/buffer#bufferconstantsmax_length (404 error) should be https://nodejs.org/api/buffer.html#bufferconstantsmax_length (see [issue #19140](https://github.com/cypress-io/cypress/issues/19140) which contains the correct link). …

Fix broken links in 9.2.0 and 9.5.4 changelogs

---

docs/guides/references/migration-guide.mdx

This PR fixes a dead legacy link [@cypress/react/plugins](https://github.com/cypress-io/cypress/tree/develop/npm/react/plugins) in the migration guide for [Cypress 7.0](https://docs.cypress.io/guides/references/migration-guide#Migrating-to-Cypress-70), in the section [Component Testing > 3. Update plugins file to use dev-server:start](https://docs.cypress.io/guides/references/migration-guide#3-Update-plugins-file-to-use-dev-serverstart) by redirecting it from the default branch to a Cypress legacy branch [v7.7.0](https://github.com/cypress-io/cypress/tree/v7.7.0) where the content is still available.
This involves the legacy [Cypress 7.0](https://docs.cypress.io/guides/references/migration-guide#Migrating-to-Cypress-70) version and a beta release of Component Testing, which was superseded …

Fix migration guide legacy link @cypress/react/plugins

---

docs/guides/core-concepts/cypress-app.mdx

- This PR is a partial fix of https://github.com/cypress-io/cypress-documentation/issues/5630, addressing a bad anchor link in [Core Concepts > Cypress App](https://docs.cypress.io/guides/core-concepts/cypress-app) in the section [Preview pane > Application Under Test](https://docs.cypress.io/guides/core-concepts/cypress-app#Application-Under-Test) to [E2E Testing](https://docs.cypress.io/guides/core-concepts/testing-types#What-is-End-to-end-Testing).
- PR https://github.com/cypress-io/cypress-documentation/pull/4527 changed the section header in [Core Concepts > Testing Types](https://docs.cypress.io/guides/core-concepts/testing-types) from "What is End-to-end Testing?" to [What is E2E Testing?](https://docs.cypress.io/guides/core-concepts/testing-types#What-is-E2E-Testing), changing the …

Correct anchor link to Testing Types / "What is E2E Testing?"

---

docs/guides/component-testing/angular/examples.mdx

- This PR is a partial fix of https://github.com/cypress-io/cypress-documentation/issues/5630, addressing a bad anchor link in [Component Testing > Angular Component Testing > Angular Examples](https://docs.cypress.io/guides/component-testing/angular/examples) in the section [Passing Data to a Component](https://docs.cypress.io/guides/component-testing/angular/examples#Passing-Data-to-a-Component) to [componentProperties](https://docs.cypress.io/guides/component-testing/angular/api#ComponentProperties).
There is no bookmark [#componentProperties](https://docs.cypress.io/guides/component-testing/angular/api#ComponentProperties) on the page [Component Testing > Angular Component Testing > Angular API](https://docs.cypress.io/guides/component-testing/angular/api). There is however a table …

Correct anchor link to Angular API componentProperties

---

docs/guides/cloud/integrations/source-control/gitlab.mdx

- This PR is a partial fix of https://github.com/cypress-io/cypress-documentation/issues/5630, addressing an outdated and bad anchor link in [Cypress Cloud > Integrations > Source Control > GitLab](https://docs.cypress.io/guides/cloud/integrations/source-control/gitlab) to the section [commit statuses](https://docs.cypress.io/guides/cloud/integrations/source-control/gitlab#Commit-statuses) on the same page.
- PR https://github.com/cypress-io/cypress-documentation/pull/5077 changed the section heading `Commit statuses` to [Status checks](https://docs.cypress.io/guides/cloud/integrations/source-control/gitlab#Status-checks).
The outdated reference and link to [commit statuses](https://docs.cypress.io/guides/cloud/integrations/source-control/gitlab#Commit-statuses) is changed to [status …

Correct anchor link to GitLab status checks

---

docs/guides/cloud/integrations/source-control/github.mdx
docs/guides/cloud/integrations/source-control/gitlab.mdx

- This PR is a partial fix of https://github.com/cypress-io/cypress-documentation/issues/5630, addressing bad anchor links to the FAQ bookmark [/faq/questions/cloud-faq#Im-working-at-a-restrictive-VPN-Which-subdomains-do-I-have-to-allow-on-my-VPN-for-Cypress-Cloud-to-work-properly](https://docs.cypress.io/faq/questions/cloud-faq#Im-working-at-a-restrictive-VPN-Which-subdomains-do-I-have-to-allow-on-my-VPN-for-Cypress-Cloud-to-work-properly).
- PR https://github.com/cypress-io/cypress-documentation/pull/5190 changed the title of the FAQ from
"I'm working **at** a restrictive VPN. Which subdomains do I have to allow on my VPN for Cypress Cloud to work properly?" to
"I'm working **with** a restrictive VPN. Which subdomains do I have to allow on my VPN for Cypress Cloud to work properly?"
and …

Correct anchor links to FAQ VPN subdomain IP address question

---

docs/guides/cloud/getting-started.mdx

- This PR is a partial fix of https://github.com/cypress-io/cypress-documentation/issues/5630, addressing bad anchor links on [Cypress Cloud > Getting Started](https://docs.cypress.io/guides/cloud/getting-started) to the bookmark [#Identification](https://docs.cypress.io/guides/cloud/getting-started#Identification).
- PR https://github.com/cypress-io/cypress-documentation/pull/5173 moved the Identification section from [Cypress Cloud > Getting Started](https://docs.cypress.io/guides/cloud/getting-started) to a separate new page [Cypress Cloud > Account Management > Projects](https://docs.cypress.io/guides/cloud/account-management/projects#Identification).
The bad links to `#Identification` are corrected to 
- [/guides/cloud/account-management/projects#Project-ID](https://docs.cypress.io/gu …

Correct anchor links to Cloud projects Identification

---

docs/api/queries/contains.mdx
docs/guides/references/assertions.mdx

- This PR is a partial fix of https://github.com/cypress-io/cypress-documentation/issues/5630, addressing bad anchor links relating to `/faq/questions/using-cypress-faq#How-do-I-get-an-element-s-text-contents`.
- The bad link to `/faq/questions/using-cypress-faq#How-do-I-get-an-element-s-text-contents` is corrected to [/faq/questions/using-cypress-faq#How-do-I-get-an-elements-text-contents](https://docs.cypress.io/faq/questions/using-cypress-faq#How-do-I-get-an-elements-text-contents) (extra hyphen removed).

Correct anchor links for FAQ "How do I get an element's text context"

---

docs/guides/end-to-end-testing/testing-strategies/amazon-cognito-authentication.mdx

- This PR is a partial fix of https://github.com/cypress-io/cypress-documentation/issues/5630, addressing two bad links on the [End-to-End Testing > Testing Strategies > Amazon Cognito Authentication](https://docs.cypress.io/guides/end-to-end-testing/amazon-cognito-authentication) page.
- The link to https://docs.amplify.aws/CLI returns a 404 not found error. (This is not covered in issue #5630, since it is not an anchor link. It is addressed and bundled here additionally.)
- Hardly noticeable `/guides/end-to-end-testing/amazon-cognito-authentication#Login-with-cy-origin` , which attempts to link to a bookmark just underneath it, does not match the auto-generated bookmark exactly.
In [End-to-End Testing > Testing Strategies > Amazon Cognito …

Correct links in Amazon Cognito Authentication

---

docs/guides/core-concepts/retry-ability.mdx

- This PR is a partial fix of https://github.com/cypress-io/cypress-documentation/issues/5630, addressing a bad anchor link on the [Core Concepts > Retry-ability](https://docs.cypress.io/guides/core-concepts/retry-ability) page.
- PR https://github.com/cypress-io/cypress-documentation/pull/5080 removed the section header `BDD Assertions` from the page [References > Assertions](https://docs.cypress.io/guides/references/assertions). A few lines above, the relevant section header is now [Chai](https://docs.cypress.io/guides/references/assertions#Chai).
- In [Core Concepts > Retry-ability](https://docs.cypress.io/guides/core-concepts/retry-ability), change the non-working link
`/guides/references/assertions#BDD-Assertions` to
[/guides/references/assertions#Chai](https://docs.cypress.io/guides/ …

Correct link in Retry-ability to BDD Assertions

---

docs/guides/core-concepts/introduction-to-cypress.mdx

- This PR is a partial fix of https://github.com/cypress-io/cypress-documentation/issues/5630, addressing a bad anchor link on the [Core Concepts > Introduction to Cypress](https://docs.cypress.io/guides/core-concepts/introduction-to-cypress) page.
- PR https://github.com/cypress-io/cypress-documentation/pull/3998 modified the heading "Routes" in [Core Concepts > Variables and Aliases](https://docs.cypress.io/guides/core-concepts/variables-and-aliases) to read [Intercepts](https://docs.cypress.io/guides/core-concepts/variables-and-aliases#Intercepts) instead.
- In [Core Concepts > Introduction to Cypress](https://docs.cypress.io/guides/core-concepts/introduction-to-cypress), change the non-working link
`/guides/core-concepts/variables-and-aliases#Routes` to …

Correct link in Cypress Introduction to routing alias

---

docs/guides/references/migration-guide.mdx

- This PR is a partial fix of https://github.com/cypress-io/cypress-documentation/issues/5630, addressing a few bad anchor links in the [Migration Guide](https://docs.cypress.io/guides/references/migration-guide) caused by minor changes in auto-generated bookmarks or simple typos.
- [Migrating to Cypress 12.0 > Test Isolation](https://docs.cypress.io/guides/references/migration-guide#Test-Isolation)
- [Migrating to Cypress 10.0 > Config Option Changes > `pluginsFile`](https://docs.cypress.io/guides/references/migration-guide#pluginsFile)
- [Migrating to Cypress 7.0 > Deprecated cy.route2() command removed](https://docs.cypress.io/guides/references/migration-guide#Deprecated-cyroute2-command-removed)
- [Migrating to Cypress 7.0 > Component …

Correct anchor links in Migration Guide

---

docs/guides/guides/cross-origin-testing.mdx

- This PR addresses an anchor link issue in [Guides > Cross Origin Testing](https://docs.cypress.io/guides/guides/cross-origin-testing).
- A link to `/guides/guides/web-security#Different-superdomain-per-test-requires-cy-origin-command` does not match the auto-generated bookmark exactly. This issue is one of the link issues listed in https://github.com/cypress-io/cypress-documentation/issues/5630.
In [Guides > Cross Origin Testing](https://docs.cypress.io/guides/guides/cross-origin-testing) the following link is corrected:
- Link `/guides/guides/web-security#Different-superdomain-per-test-requires-cy-origin-command` is changed to [/guides/guides/web-security#Different-superdomain-per-test-requires-cyorigin-command](https://docs.cypress.io/guides/guides/web-security#Different-superdomain-pe …

Correct anchor link in Cross Origin Testing

---

docs/guides/end-to-end-testing/testing-strategies/social-authentication.mdx

- This PR addresses link issues in [End-to-End Testing > Testing Strategies > Social Authentication](https://docs.cypress.io/guides/end-to-end-testing/social-authentication). A corresponding anchor link issue is listed in https://github.com/cypress-io/cypress-documentation/issues/5630.
- The target of the anchor link `/guides/references/best-practices#Challenges-with-Social-Connection-Authentication` does not exist on that page.
In [End-to-End Testing > Testing Strategies > Social Authentication](https://docs.cypress.io/guides/end-to-end-testing/social-authentication) the following links are corrected:
- Link `/guides/references/best-practices#Challenges-with-Social-Connection-Authentication` is corrected to [/guides/references/best-practices#Potential-Challenges-Authenticating-with-Social …

Correct anchor links in Social Authentication

---

docs/guides/end-to-end-testing/migration/protractor-to-cypress.mdx

- This PR addresses link issues in [End-to-End Testing > Migrating from Other Frameworks > Migrating from Protractor to Cypress](https://docs.cypress.io/guides/end-to-end-testing/protractor-to-cypress). The anchor link issues are listed in https://github.com/cypress-io/cypress-documentation/issues/5630.
- A link to https://github.com/cypress-io/cypress/discussions/new results in the warning "Sorry, we didn't recognize that category!".
- The target of the anchor link `/guides/core-concepts/introduction-to-cypress#Commands-Are-Not-Promises` does not exist on that page.
- The target of the anchor link `/guides/continuous-integration/introduction#CircleCI` does not exist on that page.
- The target of the anchor link `/guides/references/best-practices#Having-tests-rely-on-the-state-of-previous- …

Correct links in "Migrating from Protractor to Cypress"

---

docs/guides/guides/module-api.mdx

- This PR addresses link issues in [Guides > Module API](https://docs.cypress.io/guides/guides/module-api).
- A link to https://nodejs.org/en/learn/run-nodejs-scripts-from-the-command-line/ results in a "404 Page could not be found" error.
- The target of the anchor link `/guides/references/configuration#Configuration-file` does not match the auto-generated bookmark exactly. This issue is one of the link issues listed in https://github.com/cypress-io/cypress-documentation/issues/5630.
In [Guides > Module API](https://docs.cypress.io/guides/guides/module-api) the following links are corrected:
- Link https://nodejs.org/en/learn/run-nodejs-scripts-from-the-command-line/ is changed to https://nodejs.org/en/learn/command-line/run-nodejs-scripts-from-the-command-line.
- Links …

Correct links in Module API

---

docs/guides/overview/why-cypress.mdx

- This PR addresses a link issue in [Overview > Why Cypress?](https://docs.cypress.io/guides/overview/why-cypress). Anchor link issues are listed in https://github.com/cypress-io/cypress-documentation/issues/5630.
- The target of the anchor link `/plugins#Visual%20Testing` does not exist.
In [Overview > Why Cypress?](https://docs.cypress.io/guides/overview/why-cypress) the following link is corrected:
- Link `/plugins#Visual%20Testing` is changed to [/plugins#visual-testing](https://docs.cypress.io/plugins#visual-testing). This was caused by https://github.com/cypress-io/cypress-documentation/pull/5299 and fell between the cracks of PR https://github.com/cypress-io/cypress-documentation/pull/5354 and https://github.com/cypress-io/cypress-documentation/pull/5299 intended to correct changed …

Correct anchor link in "Why Cypress?"

---

docs/api/commands/spy.mdx
docs/api/commands/stub.mdx

- This PR corrects link issues to the documentation for the npm module [sinon](https://www.npmjs.com/package/sinon).
The following external links produce a 404 "File not found" error:
In [API > Other Commands > spy](https://docs.cypress.io/api/commands/spy):
- https://sinonjs.org/releases/v6.1.5/spies/
- https://sinonjs.org/releases/v6.1.5/sandbox/
In [API > Other Commands > stub](https://docs.cypress.io/api/commands/stub):
- https://sinonjs.org/releases/v2.0.0/sandbox/
`cypress@13.6.4` uses the npm module [sinon](https://www.npmjs.com/package/sinon) version `8.1.1`
https://github.com/cypress-io/cypress/blob/ad99300a5f1a23d336c317600e702a6406fea4a6/packages/driver/package.json#L79
The relevant documentation page is `v8` for the [Sinon.JS v8.1.1](https://sinonjs.org/releases/v8/) release. …

Correct links to Sinon.JS documentation

---

docs/api/commands/spread.mdx
docs/api/commands/spy.mdx
docs/api/commands/stub.mdx
docs/api/commands/visit.mdx

This PR addresses anchor link issues targeting versions in the [References > Changelog](https://docs.cypress.io/guides/references/changelog) document from the following pages:
- [API > Other Commands > spread](https://docs.cypress.io/api/commands/spread)
- [API > Other Commands > spy](https://docs.cypress.io/api/commands/spy)
- [API > Other Commands > stub](https://docs.cypress.io/api/commands/stub)
- [API > Other Commands > stub](https://docs.cypress.io/api/commands/visit)
Link issues are listed in https://github.com/cypress-io/cypress-documentation/issues/5630.
The target of the following links do not exist exactly:
- `/guides/references/changelog#0-5.9`
- `/guides/references/changelog#0-20.0`
- `/guides/references/changelog#0-3.3`
On the pages:
- [API > Other Commands > …

Correct anchor links to Changelog versions

---

docs/api/commands/visit.mdx
docs/api/queries/url.mdx

- This PR addresses anchor link issues targeting `/guides/references/best-practices#Setting-a-global-baseUrl`. Anchor link issues are listed in https://github.com/cypress-io/cypress-documentation/issues/5630.
In
- [API > Other Queries > url](https://docs.cypress.io/api/commands/url)
- [API > Other Commands > visit](https://docs.cypress.io/api/commands/visit)
the following link
- `/guides/references/best-practices#Setting-a-global-baseUrl` does not match its target exactly.
In
- [API > Other Queries > url](https://docs.cypress.io/api/commands/url)
- [API > Other Commands > visit](https://docs.cypress.io/api/commands/visit)
the following change is made:
| Current                                                      | Corrected …

Correct anchor links to "Setting a Global baseUrl"

---

docs/api/cypress-api/require.mdx

- This PR corrects an anchor link issue in [API > Cypress API > Cypress.require](https://docs.cypress.io/api/cypress-api/require).  Anchor link issues are listed in https://github.com/cypress-io/cypress-documentation/issues/5630.
- The anchor link `/api/commands/origin#Dependencies-Sharing-Code` does not match its target exactly.
In [API > Cypress API > Cypress.require](https://docs.cypress.io/api/cypress-api/require) the following change is made:
| Current                                          | Corrected                                                                                                                 | Comment      |
| ------------------------------------------------ | ------------------------------------------------------------------------------------------------------- …

Correct anchor link in API Cypress.require()

---

docs/api/commands/origin.mdx
docs/api/cypress-api/require.mdx

This PR addresses links to the Node.js documentation for `require()` in pages:
- [API > Other Commands > origin](https://docs.cypress.io/api/commands/origin)
- [Cypress API > Cypress.require](https://docs.cypress.io/api/cypress-api/require)
- The target of the external link https://nodejs.org/en/knowledge/getting-started/what-is-require/ does not exist.
In the following pages:
- [API > Other Commands > origin](https://docs.cypress.io/api/commands/origin)
- [Cypress API > Cypress.require](https://docs.cypress.io/api/cypress-api/require)
the following link is changed:
| Current                                                          | Corrected                                     |
| ---------------------------------------------------------------- | …

Correct links to Node.js require()

---

docs/api/commands/intercept.mdx

- This PR addresses multiple anchor link issues in [API > Other Commands > intercept](https://docs.cypress.io/api/commands/intercept).  Anchor link issues are listed in https://github.com/cypress-io/cypress-documentation/issues/5630.
- `/api/commands/intercept#staticResponse-lt-code-gtStaticResponselt-code-gt` does not match target
- `/api/commands/intercept#routeHandler-lt-code-gtFunctionlt-code-gt` does not match target
- `/api/commands/intercept#Request-Response-Modification-with-routeHandler` does not match target exactly
- `/api/commands/intercept#Aliasing-a-Route` has no matching target
- `/api/commands/intercept#aliasing-an-intercepted-route` does not match target exactly
- `/api/commands/intercept#routeHandler-lt-code-gtstring-object-Function-StaticResponselt-code-gt` has no …

Correct anchor links in API cy.intercept()

---

docs/guides/continuous-integration/introduction.mdx

As already written in this bit of the docs, `ELECTRON_RUN_AS_NODE` was never tested.
Having tested it, I'm now sure it _doesn't_ work, and I think removing it from the docs is clearer than having it in there with this note.
Essentially, when `ELECTRON_RUN_AS_NODE` is set to `1`, the `Cypress` binary starts to act as if it's a `node` binary:
When that happens, when cypress tries to call it with set-up params, `node` responds that it does not know those params:
Perhaps this used to work in the past, but seeing the 'maybe' in the docs gave me some hope that I would be able to get cypress to run without Xvfb.
Also reported in https://github.com/cypress-io/cypress/issues/23636

Remove instructions on running headless tests without Xvfb

---

docs/api/plugins/preprocessors-api.mdx

- This PR corrects an anchor link issue in [API > Plugins > Preprocessors](https://docs.cypress.io/api/plugins/preprocessors-api).  Anchor link issues are listed in https://github.com/cypress-io/cypress-documentation/issues/5630.
- The anchor link `/guides/core-concepts/writing-and-organizing-tests#Test-files` does not exist
In [API > Plugins > Preprocessors](https://docs.cypress.io/api/plugins/preprocessors-api) the following change is made:
| Current                                                         | Corrected                                                                                                                                             |
| --------------------------------------------------------------- | ----------------------------------------------------------------- …

Correct anchor link in Preprocessors API

---

docs/guides/tooling/IDE-integration.mdx
docs/guides/tooling/typescript-support.mdx

- This PR addresses anchor link issues targeting [Core Concepts > Writing and Organizing Tests > Folder structure](https://docs.cypress.io/guides/core-concepts/writing-and-organizing-tests#Folder-structure). Link issues are listed in https://github.com/cypress-io/cypress-documentation/issues/5630.
The target of the link `/guides/core-concepts/writing-and-organizing-tests#Folder-Structure` uses different case on the following pages:
- [Tooling > IDE Integration](https://docs.cypress.io/guides/tooling/IDE-integration)
- [Tooling > TypeScript](https://docs.cypress.io/guides/tooling/typescript-support)
In
- [Tooling > IDE Integration](https://docs.cypress.io/guides/tooling/IDE-integration)
- [Tooling > TypeScript](https://docs.cypress.io/guides/tooling/typescript-support)
the following link …

Correct anchor links to Folder structure

---

docs/guides/references/configuration.mdx
docs/guides/references/configuration_legacy.mdx
docs/guides/tooling/plugins-guide.mdx

- This PR addresses anchor link issues targeting [Guides > Environment Variables](https://docs.cypress.io/guides/guides/environment-variables). The link issues are listed in https://github.com/cypress-io/cypress-documentation/issues/5630.
The target of the following links differs slightly:
- `/guides/guides/environment-variables#Option-2-cypress-env-json`
- `/guides/guides/environment-variables#Option-3-CYPRESS`
On [Guides > Environment Variables](https://docs.cypress.io/guides/guides/environment-variables) the following links are changed:
| Current                                                          | Corrected                                                                                                                                           |
| …

Correct anchor links to Environment variables

---

docs/faq/questions/using-cypress-faq.mdx

- This PR addresses anchor link issues in [FAQ > Using Cypress](https://docs.cypress.io/faq/questions/using-cypress-faq). Link issues are listed in https://github.com/cypress-io/cypress-documentation/issues/5630.
The target of the following links do not exist:
- `/guides/guides/web-security#Same-superdomain-per-test`
- `/guides/core-concepts/introduction-to-cypress#Commands-Are-Not-Promises`
In [FAQ > Using Cypress](https://docs.cypress.io/faq/questions/using-cypress-faq) the following links are changed:
| Current                                                                   | Corrected                                                                                                                                                                                           |
| …

Correct anchor links in FAQ Using Cypress

---

docs/guides/tooling/plugins-guide.mdx

This PR addresses a link issue in [Tooling > Plugins](https://docs.cypress.io/guides/tooling/plugins-guide).
The target of the following link does not exist:
- https://github.com/cypress-io/cypress-realworld-app/blob/develop/cypress/plugins/index.ts
In [Tooling > Plugins](https://docs.cypress.io/guides/tooling/plugins-guide) the following link is changed:
| Current                                                                                   | Corrected                                                                                                                                  |
| ----------------------------------------------------------------------------------------- | ----------------------------------------------------------------------------------------------------------------- …

Correct link in Plugins Guide

---

docs/guides/references/configuration_legacy.mdx

- This PR addresses an anchor link issue in [References > Configuration (Legacy)](https://docs.cypress.io/guides/references/legacy-configuration). Link issues are listed in https://github.com/cypress-io/cypress-documentation/issues/5630.
- The target of the link `/guides/guides/command-line#cypress-open-config-file-lt-config-file-gt` differs.
In [References > Configuration (Legacy)](https://docs.cypress.io/guides/references/legacy-configuration) the following link is changed:
| Current                                                                  | Corrected                                                                                                                                                                             |
| …

Correct anchor link in Configuration (Legacy)

---

docs/guides/references/configuration.mdx

- This PR addresses an anchor link issue in [References > Configuration](https://docs.cypress.io/guides/references/configuration). Link issues are listed in https://github.com/cypress-io/cypress-documentation/issues/5630.
- The target of the link `/guides/references/migration-guide#Migrating-to-Cypress-version-10-0` differs.
In [References > Configuration](https://docs.cypress.io/guides/references/configuration) the following link is changed:
| Current                                                                | Corrected                                                                                                                                         |
| ---------------------------------------------------------------------- | …

Correct anchor link in Configuration

---

docs/faq/questions/cloud-faq.mdx
docs/guides/references/error-messages.mdx

- This PR addresses anchor link issues targeting [Continuous Integration > CI Provider Examples](https://docs.cypress.io/guides/continuous-integration/ci-provider-examples). Link issues are listed in https://github.com/cypress-io/cypress-documentation/issues/5630.
In
- [References > Error Messages](https://docs.cypress.io/guides/references/error-messages)
- [FAQ > Cypress Cloud](https://docs.cypress.io/faq/questions/cloud-faq)
the target of the link
- `/guides/continuous-integration/introduction#Examples` does not exist.
In
- [References > Error Messages](https://docs.cypress.io/guides/references/error-messages)
- [FAQ > Cypress Cloud](https://docs.cypress.io/faq/questions/cloud-faq)
the following link is changed:
| Current                                                | Corrected …

Correct anchor links to CI Provider Examples

---

docs/guides/references/changelog.mdx

updates the changelog with contents from 13.6.5 release

chore: update changelog for 13.6.5 release

---

docs/guides/references/changelog.mdx

- This PR addresses an anchor link issue in [References > Changelog > 6.0.0](https://docs.cypress.io/guides/references/changelog#6-0-0). Anchor link issues are listed in https://github.com/cypress-io/cypress-documentation/issues/5630.
The target bookmark for the following anchor link does not match:
- `/guides/references/migration-guide#Migrating-cy-route-to-cy-intercept`
In [References > Changelog > 6.0.0](https://docs.cypress.io/guides/references/changelog#6-0-0) the following link is changed:
| Current                                                     | Corrected                                                                                                                                 |
| ----------------------------------------------------------- | …

Correct anchor link in Changelog 6.0.0

---

docs/guides/references/changelog.mdx

- This PR addresses anchor link issues in [References > Changelog > 4.10.0](https://docs.cypress.io/guides/references/changelog#4-10-0) and earlier referring to the now superseded `experimentalShadowDomSupport` option. Anchor link issues are listed in https://github.com/cypress-io/cypress-documentation/issues/5630.
In the [Changelog](https://docs.cypress.io/guides/references/changelog) for versions:
- [Cypress 4.10.0](https://docs.cypress.io/guides/references/changelog#4-10-0)
- [Cypress 4.9.0](https://docs.cypress.io/guides/references/changelog#4-9-0)
- [Cypress 4.8.0](https://docs.cypress.io/guides/references/changelog#4-8-0)
the target bookmark for the following anchor link does not exist:
- `/guides/references/experiments#Shadow-DOM`
In
- [References > Changelog > …

Adjust experimentalShadowDomSupport links for Changelog 4.x

---

docs/guides/references/changelog.mdx

- This PR addresses an anchor link issue in [References > Changelog > 7.0.0](https://docs.cypress.io/guides/references/changelog#7-0-0). Anchor link issues are listed in https://github.com/cypress-io/cypress-documentation/issues/5630.
- `/guides/references/configuration#Node-version`
In [References > Changelog > 7.0.0](https://docs.cypress.io/guides/references/changelog#7-0-0) the following link is changed:
| Current                                                     | Corrected                                                                                                                                 |
| ----------------------------------------------------------- | …

Correct anchor link in Changelog 7.0.0

---

docs/guides/references/changelog.mdx

- This PR addresses an anchor link issue in [References > Changelog > 9.3.0](https://docs.cypress.io/guides/references/changelog#9-3-0). Anchor link issues are listed in https://github.com/cypress-io/cypress-documentation/issues/5630.
The following anchor link does not match the corresponding target bookmark:
- `/guides/getting-started/installing-cypress#Install-binary`
In [References > Changelog > 9.3.0](https://docs.cypress.io/guides/references/changelog#9-3-0) the following link is changed:
| Current                                                     | Corrected                                                                                                                                 |
| ----------------------------------------------------------- | …

Correct anchor link in Changelog 9.3.0

---

docs/guides/references/changelog.mdx

- This PR addresses an anchor link issue in [References > Changelog > 10.9.0](https://docs.cypress.io/guides/references/changelog#10.9.0). Anchor link issues are listed in https://github.com/cypress-io/cypress-documentation/issues/5630.
The following anchor link does not match the corresponding target bookmark:
- `/api/commands/origin#Dependencies-Sharing-Code`
In [References > Changelog > 10.9.0](https://docs.cypress.io/guides/references/changelog#10.9.0) the following link is changed:
| Current                                          | Corrected                                                                                                                 |
| ------------------------------------------------ | ------------------------------------------------------------------------------ …

Correct anchor link in Changelog 10.9.0

---

docs/guides/references/changelog.mdx

- This PR addresses anchor link issues in [References > Changelog > 11.0.0](https://docs.cypress.io/guides/references/changelog#11-0-0). Anchor link issues are listed in https://github.com/cypress-io/cypress-documentation/issues/5630.
The following anchor links do not match the corresponding target bookmark:
- `/guides/references/migration-guide#Migrating-to-Cypress-version-11-0`
- `/guides/references/migration-guide#React-mountHook-Removed`
- `/guides/references/migration-guide#React-unmount-Removed`
- `/guides/references/migration-guide#Vue-mountCallback-Removed`
- `/guides/references/migration-guide#Vite-Dev-Server-cypress-vite-dev-server`
- `/guides/references/migration-guide#Angular-Providers-Mounting-Options-Change`
In [References > Changelog > …

Correct anchor links in Changelog 11.0.0

---

docs/api/commands/origin.mdx

- Closes #5685. This PR corrects an anchor link issue in [API > Other Commands > origin](https://docs.cypress.io/api/commands/origin).  General anchor link issues are listed in https://github.com/cypress-io/cypress-documentation/issues/5630.
- The target of the anchor link `/guides/references/trade-offs#Multiple-tabs` does not exist.
In [API > Other Commands > origin](https://docs.cypress.io/api/commands/origin) the following change is made:
| Current                                       | Corrected |
| --------------------------------------------- | --------- |
| `/guides/references/trade-offs#Multiple-tabs` | removed   |
- The statement that `cy.origin()` cannot run commands in a different browser tab remains true according to confirmation in …

Remove dead anchor link in API cy.origin() to Trade-offs / Multiple tabs

---

docs/guides/references/changelog.mdx

- This PR addresses anchor link issues in [References > Changelog](https://docs.cypress.io/guides/references/changelog) referring to installing Cypress moved content. Anchor link issues are listed in https://github.com/cypress-io/cypress-documentation/issues/5630.
The target bookmarks for the following anchor links do not exist:
- `/guides/getting-started/installing-cypress#Mirroring`
- `/guides/getting-started/installing-cypress#Advanced`
In
- [References > Changelog > 3.1.1](https://docs.cypress.io/guides/references/changelog#3-1-1)
- [References > Changelog > 1.0.3](https://docs.cypress.io/guides/references/changelog#1-0-3)
the following links are changed:
| Current                                                | Corrected …

Correct Changelog anchor links for installing Cypress

---

docs/guides/references/changelog.mdx

- This PR addresses an anchor link issue in [References > Changelog > 3.2.0](https://docs.cypress.io/guides/references/changelog#3-2-0). Anchor link issues are listed in https://github.com/cypress-io/cypress-documentation/issues/5630.
The target bookmark for the following anchor link does not match exactly:
- `/guides/guides/module-api#cypress-run`
In [References > Changelog > 3.2.0](https://docs.cypress.io/guides/references/changelog#3-2-0) the following link is changed:
| Current                                 | Corrected                                                                                           |
| --------------------------------------- | --------------------------------------------------------------------------------------------------- |
| …

Correct anchor link in Changelog 3.2.0

---

docs/guides/references/changelog.mdx

- This PR addresses anchor link issues in [References > Changelog > 3.3.2](https://docs.cypress.io/guides/references/changelog#3-3-2). Anchor link issues are listed in https://github.com/cypress-io/cypress-documentation/issues/5630.
The target bookmarks for the following anchor links do not exist:
- `/guides/guides/debugging#Hacking-on-Cypress`
- `/guides/getting-started/installing-cypress#Opt-out-of-sending-exception-data-to-Cypress`
In [References > Changelog > 3.3.2](https://docs.cypress.io/guides/references/changelog#3-3-2) the following links are changed:
| Current                                                                                   | Corrected …

Correct anchor links in Changelog 3.3.2

---

docs/guides/references/changelog.mdx

- This PR addresses an anchor link issue in [References > Changelog > 3.8.1](https://docs.cypress.io/guides/references/changelog#3-8-1). Anchor link issues are listed in https://github.com/cypress-io/cypress-documentation/issues/5630.
- `/guides/guides/command-line#cypress-run-headless`
In [References > Changelog > 3.8.1](https://docs.cypress.io/guides/references/changelog#3-8-1) the following link is changed:
| Current                                            | Corrected                                                                                         |
| -------------------------------------------------- | ------------------------------------------------------------------------------------------------- |
| …

Correct anchor link in Changelog 3.8.1

---

docs/guides/references/changelog.mdx

- This PR addresses an anchor link issue in [References > Changelog > 3.5.0](https://docs.cypress.io/guides/references/changelog#3-5-0). Anchor link issues are listed in https://github.com/cypress-io/cypress-documentation/issues/5630.
- `/guides/guides/debugging#Patch-Cypress`
In [References > Changelog > 3.5.0](https://docs.cypress.io/guides/references/changelog#3-5-0) the following link is changed:
| Current                                            | Corrected                                                                                         |
| -------------------------------------------------- | ------------------------------------------------------------------------------------------------- |
| …

Correct anchor link in Changelog 3.5.0

---

docs/guides/references/changelog.mdx

- This PR addresses an anchor link issue in [References > Changelog > 3.4.1](https://docs.cypress.io/guides/references/changelog#3-4-1). Anchor link issues are listed in https://github.com/cypress-io/cypress-documentation/issues/5630.
The target bookmark for the following anchor link does not match exactly:
- `/guides/tooling/typescript-support#Types-for-custom-commands`
In [References > Changelog > 3.4.1](https://docs.cypress.io/guides/references/changelog#3-4-1) the following link is changed:
| Current                                                        | Corrected                                                                                                                                           |
| -------------------------------------------------------------- | …

Correct anchor link in Changelog 3.4.1

---

docs/guides/references/changelog.mdx

- This PR addresses anchor link issues in [References > Changelog > 0.18.0](https://docs.cypress.io/guides/references/changelog#0-18-0). Anchor link issues are listed in https://github.com/cypress-io/cypress-documentation/issues/5630.
- `/guides/core-concepts/writing-and-organizing-tests#Folder-Structure`
In [References > Changelog > 0.18.0](https://docs.cypress.io/guides/references/changelog#0-18-0) the following links are changed:
| Current                                                               | Corrected                                                                                                                               |
| --------------------------------------------------------------------- | …

Correct anchor links in Changelog 0.18.0

---

docs/guides/references/changelog.mdx

- This PR addresses an anchor link issue in [References > Changelog > 1.2.0](https://docs.cypress.io/guides/references/changelog#1-2-0). Anchor link issues are listed in https://github.com/cypress-io/cypress-documentation/issues/5630.
The target bookmark for the following anchor link referring to `Cypress.config()` does not exist:
- `/guides/references/configuration#Cypress-config`
In [References > Changelog > 1.2.0](https://docs.cypress.io/guides/references/changelog#1-2-0) the following link is changed:
| Current                                           | Corrected                                                                 |
| ------------------------------------------------- | ------------------------------------------------------------------------- |
| …

Correct anchor link in Changelog 1.2.0

---

docs/guides/references/changelog.mdx

- This PR addresses anchor link issues in [References > Changelog > 0.20.0](https://docs.cypress.io/guides/references/changelog#0-20-0). Anchor link issues are listed in https://github.com/cypress-io/cypress-documentation/issues/5630.
The target bookmarks for the following anchor links do not exist:
- `/examples/recipes#Form-Interactions`
- `/guides/references/assertions#TDD-Assertions`
- `/guides/references/bundled-libraries#Sinon-JS`
In [References > Changelog > 0.20.0](https://docs.cypress.io/guides/references/changelog#0-20-0) the following links are changed:
| Current                                         | Corrected                                                                                                           |
| ----------------------------------------------- | …

Correct anchor links in Changelog 0.20.0

---

docs/guides/references/changelog.mdx

- This PR addresses an anchor link issue in [References > Changelog > 13.4.0](https://docs.cypress.io/guides/references/changelog#13-4-0). Anchor link issues are listed in https://github.com/cypress-io/cypress-documentation/issues/5630.
The target bookmark for the following anchor link was flagged as an anchor link error by Docusaurus, although in practice the link works:
- [/guides/references/experiments/#Experimental-Flake-Detection-Features](https://docs.cypress.io/guides/references/experiments/#Experimental-Flake-Detection-Features)
In [References > Changelog > 13.4.0](https://docs.cypress.io/guides/references/changelog#13-4-0) the following link is changed:
| Current …

Correct anchor link in Changelog 13.4.0

---

docs/guides/references/changelog.mdx

- This PR addresses an anchor link issue in [References > Changelog > 4.11.0](https://docs.cypress.io/guides/references/changelog#4-11-0). Anchor link issues are listed in https://github.com/cypress-io/cypress-documentation/issues/5630.
The target bookmark for the following anchor link does not match:
- `/guides/core-concepts/writing-and-organizing-tests#test-configuration`
In [References > Changelog > 4.11.0](https://docs.cypress.io/guides/references/changelog#4-11-0) the following link is changed:
| Current                                                     | Corrected                                                                                                                                 |
| ----------------------------------------------------------- | …

Correct anchor link in Changelog 4.11.0

---

docs/guides/references/error-messages.mdx

- This PR addresses an anchor link issue in [References > Error Messages](https://docs.cypress.io/guides/references/error-messages). Anchor link issues are listed in https://github.com/cypress-io/cypress-documentation/issues/5630.
The target bookmark for the following anchor link was flagged as an anchor link error by Docusaurus, although in practice the link works:
- [/guides/guides/command-line/#auto-cancel-after-runs](https://docs.cypress.io/guides/guides/command-line/#auto-cancel-after-runs)
In [References > Error Messages](https://docs.cypress.io/guides/references/error-messages) the following link is changed:
| Current                                                                                                                           | Corrected …

Correct anchor link in Error messages

---

docs/guides/references/changelog.mdx

- This PR addresses anchor link issues in the [References > Changelog](https://docs.cypress.io/guides/references/changelog) for some legacy versions `3.6.0` and below. Anchor link issues are listed in https://github.com/cypress-io/cypress-documentation/issues/5630.
In the following [References > Changelog](https://docs.cypress.io/guides/references/changelog) sections:
- [3.6.0](https://docs.cypress.io/guides/references/changelog#3-6-0)
- [3.5.0](https://docs.cypress.io/guides/references/changelog#3-5-0)
- [3.1.1](https://docs.cypress.io/guides/references/changelog#3-1-1)
- [3.0.2](https://docs.cypress.io/guides/references/changelog#3-0-2)
- [0.15.0](https://docs.cypress.io/guides/references/changelog#0-15-0)
the target bookmark for the following anchor link does not exist:
- …

Correct folder/files legacy Changelog anchor links

---

docs/guides/references/changelog.mdx

- This PR addresses an anchor link issue in [References > Changelog > 8.0.0](https://docs.cypress.io/guides/references/changelog#8-0-0). Anchor link issues are listed in https://github.com/cypress-io/cypress-documentation/issues/5630.
- `/guides/continuous-integration/introduction#Running-headless-tests-without-Xvfb`
In [References > Changelog > 8.0.0](https://docs.cypress.io/guides/references/changelog#8-0-0) the following sentence containing the obsolete link is removed:
"See Running headless tests without Xvfb for more details."
- PR https://github.com/cypress-io/cypress-documentation/pull/5666 left a dangling anchor link to https://docs.cypress.io/guides/continuous-integration/introduction#Running-headless-tests-without- …

Remove Xvfb anchor link in Changelog 8.0.0

---

docs/guides/references/changelog.mdx

- This PR addresses an anchor link issue in [References > Changelog > 0.17.11](https://docs.cypress.io/guides/references/changelog#0-17-11). Anchor link issues are listed in https://github.com/cypress-io/cypress-documentation/issues/5630.
- `#01711-11162016`
There are some scrambled characters in the paragraph
> The changes in version 0.17.11 below are in preparation for Cypress ￢ﾀﾙ platform service: a portal where screenshots, videos, config, and logs of your builds are accessible.
The bad anchor link `#01711-11162016` is removed. It is unnecessary since the paragraph is already part of the the [References > Changelog > 0.17.11](https://docs.cypress.io/guides/references/changelog#0-17-11) it is apparently attempting to …

Correct anchor link in Changelog 0.17.11

---

docs/guides/references/changelog.mdx

- This PR addresses an anchor link issue in [References > Changelog > 0.16.0](https://docs.cypress.io/guides/references/changelog#0-16-0). Anchor link issues are listed in https://github.com/cypress-io/cypress-documentation/issues/5630.
- `/api/cypress-api/cookies#Defaults`
In [References > Changelog > 0.16.0](https://docs.cypress.io/guides/references/changelog#0-16-0) the following link is changed:
| Current                             | Corrected                                                                                     |
| ----------------------------------- | --------------------------------------------------------------------------------------------- |
| `/api/cypress-api/cookies#Defaults` | …

Correct anchor link in Changelog 0.16.0

---

docs/api/cypress-api/require.mdx

[Cypress.require()](https://docs.cypress.io/api/cypress-api/require) needs the experimental option `experimentalOriginDependencies`. This is mentioned lower down on the [cy.origin()](https://docs.cypress.io/api/commands/origin) page in the Notes section [Dependencies / Sharing Code](https://docs.cypress.io/api/commands/origin#Dependencies--Sharing-Code) and is missing from the [Cypress.require()](https://docs.cypress.io/api/cypress-api/require) page itself.
The need for the experimental option `experimentalOriginDependencies` should be shown clearly on the page for [Cypress.require()](https://docs.cypress.io/api/cypress-api/require).
Add a caution note
> Using `Cypress.require()` within the [`cy.origin()`](https://docs.cypress.io/api/commands/origin) callback requires enabling the …

Add experimental caution to Cypress.require()

---

docs/api/table-of-contents.mdx

- Closes #5719
An entry for [Cypress.require()](https://docs.cypress.io/api/cypress-api/require) is added to [API > Table of Contents > Cypress API > APIs](https://docs.cypress.io/api/table-of-contents#APIs) table.
| Property                                                           | Usage                                                                                                                                                                                                              |
| ------------------------------------------------------------------ | ------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------ |
| …

Add Cypress.require() to API Table of Contents

---

docs/guides/references/experiments.mdx

In the table [References > Experiments > End-to-End Testing](https://docs.cypress.io/guides/references/experiments#End-to-End-Testing) the entry for `experimentalOriginDependencies` has an outdated description. Support for `require`/`import` was removed in [Cypress 12.6.0](https://docs.cypress.io/guides/references/changelog#12-6-0).
| Option                           | Default | Description                                                |
| -------------------------------- | ------- | ---------------------------------------------------------- |
| `experimentalOriginDependencies` | `false` | Enables support for `require`/`import` within `cy.origin`. |
According to the section [Cypress.require > History](https://docs.cypress.io/api/cypress-api/require#History)
| Version …

Use Cypress.require() in experimentalOriginDependencies description

---

docs/guides/getting-started/opening-the-app.mdx

[Getting Started > Opening the App](https://docs.cypress.io/guides/getting-started/opening-the-app) instructs to use
```shell
yarn run cypress open
```
whereas [Guides > Command Line > How to run commands](https://docs.cypress.io/guides/guides/command-line#How-to-run-commands) instructs to use
```shell
yarn cypress run
```
Using these two equivalent forms (one with `run` and one without `run`) may be confusing.
Standardize on the shorter form without `run` and change this in [Getting Started > Opening the App](https://docs.cypress.io/guides/getting-started/opening-the-app) to:
```shell
yarn cypress open
```
(Reserve the use of `yarn run` for running scripts like `yarn run cy:open`.)
https://classic.yarnpkg.com/en/docs/cli/run
for background on how the two following commands are …

Harmonize yarn cypress open instructions

---

docs/guides/getting-started/opening-the-app.mdx
docs/guides/guides/command-line.mdx

[Getting Started > Installing Cypress >  `>_ pnpm add`](https://docs.cypress.io/guides/getting-started/installing-cypress#pnpm-add) includes instructions to install Cypress using the package manager [pnpm](https://pnpm.io/). Information about how to **run** Cypress using pnpm is however missing in the documentation.
Cypress run instructions for pnpm are missing from the pages:
- [Getting Started > Opening the App > `cypress open`](https://docs.cypress.io/guides/getting-started/opening-the-app#cypress-open)
- [Guides > Command Line > How to run commands](https://docs.cypress.io/guides/guides/command-line#How-to-run-commands)
Add the command
```shell
pnpm cypress open
```
to the page [Getting Started > Opening the App > `cypress open`](https://docs.cypress.io/guides/getting-started/opening-t …

Add pnpm instructions to run Cypress

---

docs/guides/guides/command-line.mdx

Two CLI command examples on the [Guides > Command Line](https://docs.cypress.io/guides/guides/command-line#auto-cancel-after-runs) page related to `autoCancelAfterFailures` are given with `npx` prefixes. Other commands omit the prefix since the introductory section [How to run commands](https://docs.cypress.io/guides/guides/command-line#How-to-run-commands) explains about how the prefix depends on the package manager and that it has been omitted for brevity.
`npx` is the correct prefix for use with npm, however it is not recommended for pnpm or Yarn. If `npx` is executed on a Yarn Modern Plug'n'Play project it does not work at all (due to the absence of a `node_modules` directory).
Remove the `npx` prefix from the examples [`cypress run --auto-cancel-after-failures …

Remove CLI autoCancelAfterFailures npx prefix command examples

---

docs/guides/references/configuration_legacy.mdx

The [Legacy configuration > nodeVersion](https://docs.cypress.io/guides/references/legacy-configuration#Node-version) section says:
> The nodeVersion configuration option is deprecated and will be removed in a future version of Cypress. Please remove this option from your configuration file.
and does not mention that the future version of Cypress ([`13.0.0`](https://docs.cypress.io/guides/references/changelog#13-0-0)), where `nodeVersion` was removed, has already been released.
This causes an interested reader to have to search elsewhere to find out if and when this event has already occurred. This is quite hard to find because the Changelog for [Cypress `13.0.0`](https://docs.cypress.io/guides/references/changelog#13-0-0) doesn't mention it, nor does the linked [Migrating to Cypress …

Note `nodeVersion` removal in Legacy Configuration for Cypress 13

---

docs/guides/references/changelog.mdx

This PR corrects multiple typos in the [Changelog](https://docs.cypress.io/guides/references/changelog).

Fix Changelog typos

---

docs/guides/references/assertions.mdx

This is to update the description regarding the calledWith assertion arguments syntax.
(Closes #5736)

fix: update calledwith assertions argument list syntax

---

src/data/plugins.json

I've added [Pixeleye](https://pixeleye.io/home) to the plugin definitions. 
You can see an example of a cypress & pixeleye project [here](https://github.com/pixeleye-io/pixeleye/tree/main/examples/cypress).
I've added it with a community badge, but I would love to get it verified. What would be the steps to make that happen?

Adding pixeleye to plugins.json

---

src/data/plugins.json

The PR adds a link to the official Allure integration with Cypress.
* Source code https://github.com/allure-framework/allure-js/tree/main/packages/allure-cypress
* E2E tests https://github.com/allure-framework/allure-js/tree/main/packages/allure-cypress/cypress/e2e
* CI https://github.com/allure-framework/allure-js/actions/workflows/build.yml
* NPM https://www.npmjs.com/package/allure-cypress
* Docs https://allurereport.org/docs/cypress/
However, since [cypress-allure-plugin](https://github.com/Shelex/cypress-allure-plugin) [isn't maintained anymore] (https://github.com/Shelex/cypress-allure-plugin/issues/220#issuecomment-1716130705) and will not support the latest Cypress version, I decided to replace it with the official one instead of adding an additional plugin.

Add official Allure reporter to the plugins.json

---

docs/guides/continuous-integration/introduction.mdx

The CircleCI runner hardware dimensioning reference in [Continuous Integration > Introduction > Machine requirements](https://docs.cypress.io/guides/continuous-integration/introduction#Machine-requirements) is out of date.
> [Cypress Documentation](https://github.com/cypress-io/cypress-documentation) and [Real World App](https://github.com/cypress-io/cypress-realworld-app) projects run tests on the default CircleCI machine using the [Docker executor](https://circleci.com/docs/2.0/executor-types/) on the [default medium size machine](https://circleci.com/docs/2.0/configuration-reference/#resource_class) with 2 vCPUs and 4GB of RAM. `cypress info` reports `System Memory: 73.8 GB free 25 GB` with CPUs reported as `Intel(R) Xeon(R) Platinum 8124M CPU @ 3.00GHz`. Note that the free memory …

Update RWA CircleCI hardware specs references

---

docs/guides/tooling/typescript-support.mdx

- This PR addresses an item in https://github.com/cypress-io/cypress-documentation/issues/5262#issuecomment-1561698982.
[Tooling > TypeScript > Examples](https://docs.cypress.io/guides/tooling/typescript-support#Examples) includes the line
- See [Adding Custom Commands](https://github.com/cypress-io/cypress-example-recipes#fundamentals) example recipe.
linking to https://github.com/cypress-io/cypress-example-recipes#fundamentals.
There are two related entries in the [cypress-example-recipes > Fundamentals](https://github.com/cypress-io/cypress-example-recipes#fundamentals) table:
| Recipe                                                                                                                            | Description …

Correct link to "Adding Custom Commands (TS)"

---

docs/guides/tooling/typescript-support.mdx

- This PR address an item in https://github.com/cypress-io/cypress-documentation/issues/5262#issuecomment-1561698982.
[Tooling > TypeScript > Examples](https://docs.cypress.io/guides/tooling/typescript-support#Examples) includes the line
- You can find an example with custom commands written in TypeScript in [omerose/cypress-support](https://github.com/omerose/cypress-support) repo.
The repo https://github.com/omerose/cypress-support was last updated 5 years ago and it is based on [cypress@3.6.0](https://docs.cypress.io/guides/references/changelog#3-6-0) (released in October 2019) and on the npm module [@bahmutov/add-typescript-to-cypress](https://www.npmjs.com/package/@bahmutov/add-typescript-to-cypress) (last updated in July 2019).
- …

Remove outdated omerose TS customer command example

---

docs/guides/continuous-integration/ci-provider-examples.mdx

[Continuous Integration > CI Provider Examples > CodeShip Pro](https://docs.cypress.io/guides/continuous-integration/ci-provider-examples#CodeShip-Pro) lists a link to the repo https://github.com/cypress-io/cypress-example-docker-codeship.
This repo demonstrates the legacy [cypress@9.4.1](https://docs.cypress.io/guides/references/changelog#9-4-1) (released on Jan 31, 2022) running in Cypress Docker image [cypress/base:10](https://hub.docker.com/layers/cypress/base/10/images/sha256-7fb73651d4a48762d5f370a497a155891eba90605ea395a4d86cafdefb153f8c?context=explore) published 4 years ago. Node.js `10` entered [end-of-life](https://github.com/nodejs/release#release-schedule) on Apr 30, 2021 and is no longer supported.
The repo https://github.com/cypress-io/cypress-example-docker-codeship was …

Remove link to archived cypress-example-docker-codeship repo

---

docs/guides/continuous-integration/introduction.mdx

The GitHub runner hardware dimensioning reference in [Continuous Integration > Introduction > Machine requirements](https://docs.cypress.io/guides/continuous-integration/introduction#Machine-requirements) is out of date.
> [Real World App](https://github.com/cypress-io/cypress-realworld-app) also executes its tests using [GitHub Actions](https://github.com/cypress-io/github-action) with the [default hosted runner](https://docs.github.com/en/actions/reference/specifications-for-github-hosted-runners) with 2 vCPUs and 7GB of RAM. `cypress info` reports  `System Memory: 7.29 GB free 632 MB` with CPUs reported as `Intel(R) Xeon(R) Platinum 8171M CPU @ 2.60GHz`.
The [RWA > Cypress Test](https://github.com/cypress-io/cypress-realworld-app/actions/workflows/main.yml?query=branch%3Adevelop) …

Update GitHub CI default hardware specs

---

docs/api/commands/screenshot.mdx

This section describes behavior changed in [this PR](https://github.com/cypress-io/cypress/pull/29038) in order to fix [#5016](https://github.com/cypress-io/cypress/issues/5016).

Adds section to cy.screenshot() about Chromium tab activation behavior

---

docs/guides/continuous-integration/introduction.mdx
docs/guides/getting-started/installing-cypress.mdx

- Closes #5749
The lists of required Linux dependencies are kept in two different locations, with differing contents:
1. [Continuous Integration > Advanced setup > Dependencies](https://docs.cypress.io/guides/continuous-integration/introduction#Dependencies)
- [Ubuntu/Debian](https://docs.cypress.io/guides/continuous-integration/introduction#UbuntuDebian)
- [CentOS](https://docs.cypress.io/guides/continuous-integration/introduction#CentOS)
2. [Getting Started > Installing Cypress > System requirements > Linux Prerequisites](https://docs.cypress.io/guides/getting-started/installing-cypress#Linux-Prerequisites)
- [Ubuntu/Debian](https://docs.cypress.io/guides/getting-started/installing-cypress#UbuntuDebian)
- [Arch](https://docs.cypress.io/guides/getting-started/installing-cypress#Arch)
- …

Consolidate Linux prerequisites

---

docs/guides/continuous-integration/github-actions.mdx
docs/guides/end-to-end-testing/testing-strategies/amazon-cognito-authentication.mdx
docs/guides/guides/launching-browsers.mdx
docs/guides/references/advanced-installation.mdx
docs/guides/references/changelog.mdx
docs/guides/tooling/plugins-guide.mdx
docs/guides/tooling/typescript-support.mdx

The repo refers to [npm](https://github.com/npm/cli/blob/latest/README.md) using both upper case "NPM" and lower case "npm".
Usage of capitalized "NPM" is however not in line with [npm branding guidelines](https://github.com/npm/cli#faq-on-branding) which state:
> **`npm`** should never be capitalized unless it is being displayed in a location that is customarily all-capitals (ex. titles on `man` pages).
Change all relevant usage of "NPM" to lower case "npm", aligning with [npm branding guidelines](https://github.com/npm/cli#faq-on-branding).
Only one of the instances of "NPM" was in a title. This was in an external blog article and this was left in place.

Refer to npm consistently

---

docs/guides/getting-started/installing-cypress.mdx
docs/guides/references/advanced-installation.mdx

1. [Getting Started > Installing Cypress > Direct Download](https://docs.cypress.io/guides/getting-started/installing-cypress#Direct-download) uses
> https://download.cypress.io/desktop/6.8.0
as an example of how to download an old Cypress version.
[cypress@6.8.0](https://docs.cypress.io/guides/references/changelog#6-8-0) is a legacy version released in March 2021.
2. [References > Advanced Installation > Download URLs](https://docs.cypress.io/guides/references/advanced-installation#Download-URLs) uses
> https://download.cypress.io/desktop/3.0.0?platform=win32&arch=x64
as an example of how to download a specific Cypress version for a given platform (Operating System).
[cypress@3.0.0](https://docs.cypress.io/guides/references/changelog#3-0-0) is a legacy version released in May 2018.
The …

Update example versions for direct downloads to 12.17.4

---

docs/guides/component-testing/angular/overview.mdx
docs/guides/component-testing/getting-started.mdx
docs/guides/component-testing/react/overview.mdx
docs/guides/component-testing/svelte/overview.mdx
docs/guides/component-testing/vue/overview.mdx
docs/guides/continuous-integration/introduction.mdx
docs/guides/end-to-end-testing/migration/protractor-to-cypress.mdx
docs/guides/end-to-end-testing/testing-strategies/amazon-cognito-authentication.mdx
docs/guides/getting-started/installing-cypress.mdx
docs/guides/guides/launching-browsers.mdx
docs/guides/guides/test-retries.mdx
docs/guides/references/migration-guide.mdx
docs/guides/tooling/code-coverage.mdx
docs/guides/tooling/reporters.mdx
docs/guides/tooling/typescript-support.mdx
docs/guides/tooling/visual-testing.mdx

- closes https://github.com/cypress-io/cypress-documentation/issues/5764
Instructions for installing [cypress](https://www.npmjs.com/package/cypress) and other npm modules are shown inconsistently throughout the website for npm, pnpm and Yarn package managers.
1. The examples vary; sometimes using a short-form optional flag and sometimes an equivalent long-form:
```shell
npm install cypress -D
npm install cypress --save-dev
```
2. Similarly varied is the positioning of an optional flag:
```shell
npm install --save-dev cypress
npm install cypress --save-dev
```
Although the different variations are correct, it can be confusing to have examples which are arbitrarily different.
1. The long-form is used for optional flags, e.g. `--save-dev`. This makes for better comprehension for readers …

Harmonize package manager install / add instructions

---

docs/guides/getting-started/installing-cypress.mdx

- relates to issue #5444
This PR updates the Debian version in the list of supported operating systems under the section [Getting Started > Installing Cypress > System requirements > Operating System](https://docs.cypress.io/guides/getting-started/installing-cypress#Operating-System)
from
- Debian 8 (x86_64 or Arm 64-bit (x64 or arm64))
to
- Debian 10 (x64 or arm64) and above
[Getting Started > Installing Cypress > System requirements > Node.js](https://docs.cypress.io/guides/getting-started/installing-cypress#Nodejs) lists Node.js `18`, `20` and above as being supported.
The [Node.js 18 announcement](https://nodejs.org/en/blog/announcements/v18-release-announce) provides detailed information in the [Toolchain and Compiler Upgrades](https://nodejs.org/en/blog/announcements/v18-release-anno …

Update requirements to Debian 10 and above

---

docs/guides/getting-started/installing-cypress.mdx

- relates to issue #5444
This PR updates the Fedora version in the list of supported operating systems under the section [Getting Started > Installing Cypress > System requirements > Operating System](https://docs.cypress.io/guides/getting-started/installing-cypress#Operating-System)
from
- Fedora 21
to
- Fedora 38 and above
[Getting Started > Installing Cypress > System requirements > Node.js](https://docs.cypress.io/guides/getting-started/installing-cypress#Nodejs) lists Node.js `18`, `20` and above as being supported.
The [Node.js 18 announcement](https://nodejs.org/en/blog/announcements/v18-release-announce) in the section [Toolchain and Compiler Upgrades](https://nodejs.org/en/blog/announcements/v18-release-announce#toolchain-and-compiler-upgrades) states:
> Node.js does not support …

Update requirements to Fedora 38 and above

---

docs/api/commands/intercept.mdx

Hi,
I'm using the docs right now to test some upload action in [Apache Jena](https://github.com/apache/jena/pull/2123), they are really great thanks! This PR fixes a small typo.
Cheers

Fix typo (was sucess, is success)

---

src/data/plugins.json

[cypress-voice-plugin](https://github.com/dennisbergevin/cypress-voice-plugin) is a Cypress plugin to announce spec result and time in Cypress Test Runner.
Tests and CI are included in the linked repository.
Please let me know what else is needed to be included in the official Cypress plugins list, thank you!

Plugin: Add voice plugin to Cypress plugins page

---

docs/api/commands/origin.mdx

Update example in section `Navigating to secondary origin with cy.visit` to correctly refer to `example.cypress.io` instead of `www.cypress.io` as `example` is the subdomain being used in the `cy.origin` command
https://github.com/cypress-io/cypress-documentation/blob/9e3cd1f9bb30fb8951512a615b7654906234a79a/docs/api/commands/origin.mdx?plain=1#L198

Fix typo for example in origin.mdx

---

docs/guides/continuous-integration/github-actions.mdx

- related to #5754
Executing the **Try it out** instructions [Continuous Integration > GitHub Actions > Basic Setup](https://docs.cypress.io/guides/continuous-integration/github-actions#Basic-Setup) causes workflow errors in exisiting workflows.
> **Try it out**
>
>To try out the example above yourself, fork the [Cypress Kitchen Sink](https://github.com/cypress-io/cypress-example-kitchensink) example project and place the above GitHub Action configuration in a newly created `main.yml` file within `.github/workflows/`.
The instructions are commented out so they are not displayed. A TODO notice is added, which is kept in the source .mdx and not published.
---
BEFORE
---
AFTER

Hide CI "try it out" instructions

---

docs/guides/references/changelog.mdx

adds the changelog for the cypress `13.7.2` release.

chore: add release 13.7.2 changelog entries

---

docs/guides/overview/why-cypress.mdx

- closes https://github.com/cypress-io/cypress-documentation/issues/5782
- PR https://github.com/cypress-io/cypress-documentation/pull/5738
deleted the following files due to their outdated content:
- `static/img/snippets/installing-cli.mp4`
- `static/img/snippets/installing-cli.png`
References to these files were overlooked in [Overview > Why Cypress? > Features > Setting up tests](https://docs.cypress.io/guides/overview/why-cypress#Setting-up-tests).
The original text claims "You can write your first passing test in 60 seconds." however the deleted video did not demonstrate that claim. Earlier versions of Cypress scaffolded E2E specs automatically. That has now changed. Nothing is automatically scaffolded and there are differences between E2E and Component Testing scaffolding.
Links to …

Remove dangling link to getting started install video

---

docs/guides/references/advanced-installation.mdx

- closes #5762
The example in [References > Advanced Installation > Install binary](https://docs.cypress.io/guides/references/advanced-installation#Install-binary) uses [cypress@2.0.1](https://docs.cypress.io/guides/references/changelog#2-0-1) and [cypress@2.0.2](https://docs.cypress.io/guides/references/changelog#2-0-2) shows the usage of the `CYPRESS_INSTALL_BINARY` environment variable.
> Install a version different than the default npm package.
```shell
CYPRESS_INSTALL_BINARY=2.0.1 npm install cypress@2.0.3
```
Cypress `2.x` are legacy versions which are not compatible with [currently supported versions of Ubuntu](https://docs.cypress.io/guides/getting-started/installing-cypress#Operating-System) where a minimum of Ubuntu `20.04` is described.
The example is updated to
```shell …
```

Update example CYPRESS_INSTALL_BINARY

---

CONTRIBUTING.md
src/components/plugins-list/style.module.css
src/data/plugins.json

The Plugins List currently contains a ton of unsupported or archived submissions. 
This change cleans up the list and explicitly labels these plugins as _deprecated_.
This was done by 
- Removing the `experimental` badge and renaming those select few plugins with `community`. In my opinion community plugins are "experimental" by nature if they aren't specifically `verified` by the Cypress team so this felt duplicated. Especially because only a handful had this distinction.
- Adding a few descriptors to what each badge represents to the best of my knowledge
- Adding the `deprecated` badge for plugins that meet **at least one of these three** following conditions
1. Npm registry deprecated
2. Source Repo Publicly Archived
3. Incompatible with v10+ (determined by inactivity over 3+ years ago …

Update Plugin List - Explicitly deprecate out-of-date plugins

---

docs/guides/getting-started/opening-the-app.mdx

The [Getting Started > Opening the App > `cypress open`](https://docs.cypress.io/guides/getting-started/opening-the-app#cypress-open) section shows how to use `npx`, `yarn` and `pnpm` as alternative ways of executing `cypress open` in a list format.
Display the alternatives using [Docusaurus Tabs](https://docusaurus.io/docs/markdown-features/tabs) for a more compact and readable side-by-side display.
---
BEFORE
---
AFTER
**Option npm**
**Option Yarn**
**Open pnpm**

Tab package manager option display in "How to run commands"

---

docs/api/cypress-api/custom-commands.mdx
docs/api/cypress-api/custom-queries.mdx
docs/api/table-of-contents.mdx
docs/examples/recipes.mdx
docs/faq/questions/using-cypress-faq.mdx
docs/guides/core-concepts/writing-and-organizing-tests.mdx
docs/guides/overview/why-cypress.mdx
docs/guides/references/best-practices.mdx
docs/guides/tooling/visual-testing.mdx

Docusaurus is flagging these anchors as broken because of a timing issue as the plugin page is dynamically generated. We've set the build process to fail if legit broken anchors are caught. This workaround swaps markdown links with anchor tags which avoid flagging them as broken. Neither a glorious or long term solution but one that bandwidth allows and will improve upon broken anchors not making it into a build.

add plugin anchor workaround

---

docs/guides/references/changelog.mdx

adds a period to the first changelog entry

chore: fix missed punctuation in changelog

---

src/data/plugins.json

[cypress-runner-themes](https://github.com/dingraham/cypress-runner-themes) is a Cypress plugin that provides alternative themes for the Cypress Test Runner
It replaces the now deprecated `cypress-dark` plugin since it supports Cypress v10+
Thanks!

Add cypress-runner-themes to Cypress plugins page

---

docs/api/actions/clear.mdx

Relates to:
* https://github.com/cypress-io/cypress/pull/29339
https://docs.cypress.io/api/commands/clear

chore: fix incorrect description of `cy.clear` command

---

docs/guides/references/changelog.mdx

Adds the changelog for Cypress 13.8.0

chore: add changelog for 13.8.0 release

---

docs/guides/end-to-end-testing/testing-strategies/working-with-graphql.mdx

Remove unused code example. https://docs.cypress.io/guides/end-to-end-testing/working-with-graphql
Removed the `const { body } = req` 
AS IS
TO BE

docs: remove unused code example

---

docs/api/cypress-api/catalog-of-events.mdx

Adds documentation for handling uncaught exceptions for within `cy.origin()`

misc: add documentation for uncaught exceptions for within cy.origin()

---

docs/guides/end-to-end-testing/introduction/testing-your-app.mdx

https://docs.cypress.io/guides/end-to-end-testing/testing-your-app#Step-2-Visit-your-server `sample.cy.js` is referenced as the file created from the previous page but the file created in https://docs.cypress.io/guides/end-to-end-testing/writing-your-first-end-to-end-test#Add-a-test-file is `spec.cy.js`
<table>
<tr>
<td>Before</td>
<td>After</td>
<tr>
<td>
</td>
<td>
</td>
</table>

updated `sample.cy.js` to correct `spec.cy.js`

---

src/data/plugins.json

[cypress-plugin-last-failed](https://github.com/dennisbergevin/cypress-plugin-last-failed) is a companion Cypress plugin for `cy-grep` that re-runs the last failed test(s).
Tests and CI are included in the linked repository.
Please let me know what else is needed to be included in the official Cypress plugins list, thank you!

Plugin: Add last-failed plugin to Cypress plugins page

---

docs/examples/applications.mdx
docs/faq/questions/using-cypress-faq.mdx
docs/guides/tooling/code-coverage.mdx

This repo is not being actively maintained and was archived. Remove references to it that are likely outdated.

Remove reference to cypress-example-todomvc-redux repo

---

src/data/plugins.json

Lightweight NPM package with quick setup that offers temporary test email accounts to facilitate end-to-end testing

add plugin `cypress-temp-mail` : Temporary email provider for cypress testing

---

docs/guides/getting-started/installing-cypress.mdx

- Node.js `21.x` reached [end-of-life](https://github.com/nodejs/Release/blob/main/README.md) on Jun 1, 2024
- [System requirements > Node.js](https://docs.cypress.io/guides/getting-started/installing-cypress#Nodejs) currently lists Node.js `18.x`, `20.x` and above, which does not exclude Node.js `21`.
Change [System requirements > Node.js](https://docs.cypress.io/guides/getting-started/installing-cypress#Nodejs) to
> Node.js `18.x`, `20.x`, `22.x` and above

Remove Node.js 21 support

---

src/data/plugins.json

cypress-temp-sms : Generates temporary mobile numbers that shall be used for SMS verification (OTP,2FA)

Add Plugin: `cypress-temp-sms` :  temporary mobile numbers that shall be used for SMS verification (OTP,2FA)

---

src/data/plugins.json

Cypress plugin for accessing mail from email servers.
The purpose of this plugin is to use existing email servers instead of deploying your own. Cymap leverages the capabilities of the IMAP protocol.
By using cymap:
- you are not dependant on an email server nor its REST API
- you have no need to deploy your own email server, you can use gmail or any other similar service
- if you have your own email server it will work with it to since IMAP is standardized
- you can access mail from multiple clients

Add cymap to plugins.json

---

docs/guides/references/changelog.mdx

- The name TypeScript should be written mixed case when generically referring to [TypeScript](https://www.typescriptlang.org/).
- When referring to the npm module [typescript](https://www.npmjs.com/package/typescript) it can be written all lower case.
`Typescript` is an incorrect rendering.
- Convert general references to `TypeScript`
- In `Dependency Updates` sections, preferably use `typescript` for consistency with quoting of other npm module names.
- https://www.typescriptlang.org/
- https://www.npmjs.com/package/typescript

Fix TypeScript capitalization in Changelog

---

docs/guides/continuous-integration/introduction.mdx

[Continuous Integration > Introduction > Common problems and solutions > In Docker](https://docs.cypress.io/guides/continuous-integration/introduction#In-Docker) states:
> If you are running long runs on Docker, you need to set the `ipc` to `host` mode. [This issue](https://github.com/cypress-io/cypress/issues/350) describes exactly what to do.
- The issue https://github.com/cypress-io/cypress/issues/350 referred to was closed in April 2021 with a reference to [Cypress 7.0.1](https://docs.cypress.io/guides/references/changelog#7-0-1) stating:
> Cypress no longer crashes in certain circumstances when running in Docker without `--ipc=host`. Fixes _ [#15814](https://github.com/cypress-io/cypress/issues/15814) and [#350](https://github.com/cypress-io/cypress/issues/350).
The issue was …

Remove obsolete --ipc=host Docker workaround

---

docs/guides/tooling/code-coverage.mdx

This section is referencing an outdated roadmap for code-coverage. Remove the future work section.

Remove future work section from code-coverage

---

docs/guides/continuous-integration/aws-codebuild.mdx
docs/guides/continuous-integration/bitbucket-pipelines.mdx
docs/guides/continuous-integration/github-actions.mdx
docs/guides/continuous-integration/gitlab-ci.mdx

The [Continuous Integration section](https://docs.cypress.io/guides/continuous-integration/introduction) contains examples for use of Cypress Docker images in CI from [Cypress on Docker Hub](https://hub.docker.com/u/cypress).
Section headings mention Chrome and Firefox, and omit Edge.
- [AWS CodeBuild](https://docs.cypress.io/guides/continuous-integration/aws-codebuild#Testing-in-Chrome-and-Firefox-with-Cypress-Docker-Images)
- [Bitbucket Pipelines](https://docs.cypress.io/guides/continuous-integration/bitbucket-pipelines#Testing-in-Chrome-and-Firefox-with-Cypress-Docker-Images)
- [GitLab CI](https://docs.cypress.io/guides/continuous-integration/gitlab-ci#Testing-in-Chrome-and-Firefox-with-Cypress-Docker-Images)
- Remove Chrome and Firefox from section headings
- Harmonize browser naming …

Harmonize CI Docker Hub references

---

docs/guides/continuous-integration/aws-codebuild.mdx
docs/guides/continuous-integration/bitbucket-pipelines.mdx
docs/guides/continuous-integration/github-actions.mdx
docs/guides/continuous-integration/gitlab-ci.mdx
docs/guides/continuous-integration/introduction.mdx
docs/guides/getting-started/installing-cypress.mdx

Cypress Docker versions used in examples in:
- [Continuous Integration section](https://docs.cypress.io/guides/continuous-integration/introduction) (based on Node.js `20.9`) and
- [Getting Started > Installing Cypress > System requirements > Linux Prerequisites > Docker](https://docs.cypress.io/guides/getting-started/installing-cypress#Docker) (based on Node.js `18.12`)
are outdated.
The outdated versions of Cypress Docker images are based on:
- [Node.js 20.9.0](https://nodejs.org/en/blog/release/v20.9.0) was released on Oct 24, 2023
- [Node.js 18.12.1](https://nodejs.org/en/blog/release/v18.12.1) was released on Nov 4, 2022
Although these versions are still supported and continue to work, users will generally experience better results by specifying up-to-date versions of Cypress Docker …

Update Docker version in examples

---

docs/guides/continuous-integration/aws-codebuild.mdx

The section [Continuous Integration > AWS CodeBuild > Cypress Real World Example with AWS CodeBuild](https://docs.cypress.io/guides/continuous-integration/aws-codebuild#Cypress-Real-World-Example-with-AWS-CodeBuild) links to a non-existent workflow https://github.com/cypress-io/cypress-realworld-app/blob/develop/buildspec.yml in the [RWA](https://github.com/cypress-io/cypress-realworld-app) Real World App.
- The workflow was removed by PR https://github.com/cypress-io/cypress-realworld-app/pull/1539 in RWA.
- PR https://github.com/cypress-io/cypress-documentation/pull/5644 then removed one reference to the removed workflow in the documentation and omitted to remove the reference in [Continuous Integration > AWS CodeBuild > Cypress Real World Example with AWS …

Remove AWS CodeBuild link for deleted RWA CI example

---

docs/examples/docker.mdx

The page https://docs.cypress.io/examples/docker
- says that the images are on GitHub, whereas they are on Docker Hub and ECR
- does not mention that `cypress/included` includes browsers
- uses lower-case names for branded products
- contains no examples, despite being listed under the Examples tab of https://docs.cypress.io
Changes to https://docs.cypress.io/examples/docker include
- Rework of Images section
- Addition of Examples section

Rework Docker examples page

---

docs/guides/continuous-integration/introduction.mdx

The section [Continuous Integration > Introduction > Setting up CI > Official Cypress Docker Images](https://docs.cypress.io/guides/continuous-integration/introduction#Official-Cypress-Docker-Images) includes one outdated example which is supposed to work, but doesn't work anymore. This is followed by an example which is not supposed to work. These are examples for running Cypress Docker images locally, not in CI.
The section does not provide an introduction into using Cypress Docker images in CI.
The first example is moved to [Docker build and run](https://github.com/cypress-io/cypress-docker-images/tree/master/base#docker-build-and-run), whilst the second example is moved to [Docker interactive](https://github.com/cypress-io/cypress-docker-images/tree/master/base#docker-interactive), …

CI Introduction - Official Cypress Docker images

---

src/data/plugins.json

- add an entry on the plugin page for cypress-mailpit plugin

docs: update plugins.json to add cypress-mailpit plugin

---

docs/guides/component-testing/angular/api.mdx
docs/guides/component-testing/angular/examples.mdx
docs/guides/references/changelog.mdx

Adds the Changelog and Angular Signals CT documentation

chore: Cypress 13.13.0 Release

---

docs/guides/getting-started/installing-cypress.mdx

- contributes to resolution of issue #5859
CentOS Linux 7 reached end of life (EOL) on June 30, 2024 (see [What to know about CentOS Linux EOL](https://www.redhat.com/en/topics/linux/centos-linux-eol)).
CentOS is listed on [Getting Started > Installing Cypress > System requirements > Linux Prerequisites > CentOS](https://docs.cypress.io/guides/getting-started/installing-cypress#CentOS). Cypress cannot support operating systems which are themselves no longer supported. Additionally [Node.js states](https://nodejs.org/en/blog/announcements/v18-release-announce#toolchain-and-compiler-upgrades)
> Node.js does not support running on operating systems that are no longer supported by their vendor.
Remove the obsolete CentOS section [Getting Started > Installing Cypress > System requirements > …

Remove obsolete centOS Linux prerequisites

---

docs/guides/cloud/test-replay.mdx

- contributes to resolution of issue #5859
[Cypress Cloud > Test Replay > Troubleshooting](https://docs.cypress.io/guides/cloud/test-replay#Troubleshooting) includes an outdated section with the following contents:
---
**CentOS users may experience errors when _using_ Test Replay**
CentOS Linux 7 has an [end of life in 2024](https://blog.centos.org/2023/04/end-dates-are-coming-for-centos-stream-8-and-centos-linux-7/). We have had these users report issues when accessing Test Replay in Cypress Cloud. This could be due to GCC version compatibility with better-sqlite3. We recommend using CentOS 8 rather than 7, or try following the steps noted in this [_installing better-sqlite3 on Centos 7_ Github Issue](https://github.com/WiseLibs/better-sqlite3/issues/648#issuecomment-1000361827).
---
The …

Remove obsolete centOS troubleshooting

---

docs/guides/getting-started/installing-cypress.mdx

The section [Getting Started > Installing Cypress > System requirements > Linux prerequisites > Docker](https://docs.cypress.io/guides/getting-started/installing-cypress#Docker) is outdated and only mentions `cypress/base`.
The use of Bun or Alpine Linux images isn't covered.
On the page [Getting Started > Installing Cypress](https://docs.cypress.io/guides/getting-started/installing-cypress)
- Change the heading from "Docker" to "Docker Prerequisites"
- Rewrite the contents
- Refer to the operating systems section for supported OS Ubuntu, Fedora and Debian
- Address Alpine and Bun without explicitly mentioning them:
- Stand-alone Alpine Linux is ruled out by referring to the supported OS list
- Bun Docker images don't have Node.js installed (Bun is supposed to be a replacement for …

Rework Docker prerequisites

---

docs/guides/continuous-integration/aws-codebuild.mdx

- [Continuous Integration > AWS CodeBuild](https://docs.cypress.io/guides/continuous-integration/aws-codebuild) includes some grammatical errors.
- Minor text corrections to [Continuous Integration > AWS CodeBuild](https://docs.cypress.io/guides/continuous-integration/aws-codebuild)

Update CI Docker AWS CodeBuild

---

docs/guides/component-testing/react/examples.mdx

As we introduce JSX syntax here, the component support file needs/should have the .jsx file extension.
Fixing this will especially be helpful to newcomers.

Component support file with .jsx extension

---

docs/guides/getting-started/installing-cypress.mdx

- closes https://github.com/cypress-io/cypress-documentation/issues/5868
- There is currently no guidance on how to install Node.js. If snap is chosen as Node.js package manager it fails when installing Cypress via snap using the regular installation command (see #5868)
>
> npm install cypress --save-dev
- Add instruction to [Getting Started > Installing Cypress > npm install](https://docs.cypress.io/guides/getting-started/installing-cypress#Nodejs) for use with snap:
>
> npm install cypress --save-dev --foreground-scripts
- Add a section to [Getting Started > Installing Cypress > System requirements](https://docs.cypress.io/guides/getting-started/installing-cypress#Nodejs) which describes how to install Node.js

Add Node.js installation and snap usage instructions

---

docs/faq/questions/cloud-faq.mdx
docs/faq/questions/using-cypress-faq.mdx
docs/guides/end-to-end-testing/testing-strategies/amazon-cognito-authentication.mdx

The FAQ does not comprehensively reflect what is supported in Test Replay. Additionally it's incorrectly saying we don't support Shadow DOm. https://docs.cypress.io/faq/questions/cloud-faq#Is-every-aspect-of-my-stack-included-in-Test-Replay
This updates the FAQ to be comprehensive and also point to issues where people can actively express and track support.

docs: Update what is not supported in Test Replay with issue links

---

docs/guides/getting-started/installing-cypress.mdx

- Closes https://github.com/cypress-io/cypress-documentation/issues/5878
- Closes https://github.com/cypress-io/cypress-documentation/issues/5879
[Getting Started > Installing Cypress > System requirements > Operating System](https://docs.cypress.io/guides/getting-started/installing-cypress#Operating-System) currently lists the supported Linux operating systems as:
> Linux Ubuntu 20.04 and above, Fedora 38 and above, and Debian 10 and above (x64 or arm64)
- According to https://wiki.debian.org/LTS Debian 10 "Buster" reached End of Life on June 30, 2024.
- According to https://docs.fedoraproject.org/en-US/releases/eol/ "Fedora Linux 38" reached End of Life on May 21, 2024.
Node.js also has a policy not to support operating systems which are no longer supported by their vendor.
Bump the …

Update minimum Linux to Fedora 39 and Debian 11

---

docs/guides/references/changelog.mdx

adds the Cypress `13.13.2` changelog

chore: add release 13.13.2 changelog

---

docs/guides/guides/launching-browsers.mdx

On [Guides > Launching Browsers](https://docs.cypress.io/guides/guides/launching-browsers) the [Linux Dependencies](https://docs.cypress.io/guides/guides/launching-browsers#Linux-Dependencies) are separated from the [WebKit (Experimental)](https://docs.cypress.io/guides/guides/launching-browsers#WebKit-Experimental) installation instructions which need them.
Move [Linux Dependencies](https://docs.cypress.io/guides/guides/launching-browsers#Linux-Dependencies) up to belong with the installation instructions and refer to them explicitly.

Improve WebKit linux dependencies instruction integration

---

docs/guides/guides/launching-browsers.mdx

- Closes https://github.com/cypress-io/cypress-documentation/issues/5446
[Guides > Launching Browsers > Chrome Browsers](https://docs.cypress.io/guides/guides/launching-browsers#Chrome-Browsers) names both Chrome 64 and Chrome 80 as minimum versions on the same page without further explanation.
- See https://github.com/cypress-io/cypress-documentation/pull/5104#issuecomment-1614637130 for dev explanation.
Clarify that Chrome 80 minimum applies to `cypress open` and make the references on the same page consistent with each other.

Clarify minimum Chrome 64 (run) / Chrome 80 (open)

---

docs/guides/guides/launching-browsers.mdx
docs/guides/references/troubleshooting.mdx

The link https://vikyd.github.io/download-chromium-history-version/ to download Chromium is obsolete. It stops at version 121.0.6141.1 from November 2023.
This link is used in:
- https://docs.cypress.io/guides/guides/launching-browsers#Download-specific-Chrome-version
- https://docs.cypress.io/guides/references/troubleshooting#Download-specific-Chrome-version
- Align with the resolution to https://github.com/cypress-io/cypress/issues/29460 and use the vanity link https://on.cypress.io/chromium-downloads instead.

Use Chromium download link https://on.cypress.io/chromium-downloads

---

src/theme/BackToTopButton/DarkModeSwitch.js

Issue : 
1. User sets dark theme and closes tab,
2. Again user visits cypress doc
3. Now the theme remains dark but button is stucked in light theme 
Fix:
The default value is now set from localstorage.
Resolution:
Darkmode switch button now remembers the user set value.

Fixed dark mode switch Button: Update DarkModeSwitch

---

docs/guides/tooling/reporters.mdx

According to the context, the below code block should be for a JSON file. However, it is rendered as `cypress.config.js/ts`:

fix: code block with incorrect language

---

docs/guides/component-testing/overview.mdx

- Closes https://github.com/cypress-io/cypress-documentation/issues/5412
[Supported Frameworks](https://docs.cypress.io/guides/component-testing/overview#Supported-Frameworks) lists framework versions with a base version and a "+" to indicate later versions.
This is not consistent with the way that Cypress detects frameworks, which works on discrete versions, rather than minimum versions. Versions which are not verified by Cypress may not work. Leaving the highest supported version open is misleading.
The table [Supported Frameworks](https://docs.cypress.io/guides/component-testing/overview#Supported-Frameworks) is reworked to conform to the supported versions specified in https://github.com/cypress-io/cypress/blob/develop/packages/scaffold-config/src/dependencies.ts.

Replace CT Supported Frameworks "+" notation with fixed version ranges

---

docs/guides/references/changelog.mdx
docs/guides/references/experiments.mdx

Adds the `experimentalJustInTimeCompile` flag for Component testing, which only compiles a specs resources before running the spec in either `open` or `run` mode. By default, Cypress compiles all specs used by Component Testing (CT) before allowing any spec to run, which can be problematic for larger CT projects due to the size of the dev servers.  Enabling this experiment will only compile assets related to the spec under test, resulting in a smaller bundle and reducing required resources to run, hopefully leading to:
* Less `chunk load error`s in webpack.
* CI machines reaching CPU and memory ceilings, causing OOM issues or other stalling
* Less painful experience developing components in `open` mode, where initial loading and hot reloading take upwards to 30-45 seconds to repaint …

adds `experimentalJustInTimeCompile` documentation for Component Testing

---

docs/guides/guides/command-line.mdx
docs/guides/references/changelog.mdx

closes [#22003](https://github.com/cypress-io/cypress/issues/22003)
Updates the behavior of the `--browser` flag when passed alone to the cli.

Updating cli docs for `--browser` flag behavior

---

docs/api/actions/type.mdx
docs/guides/guides/command-line.mdx
docs/guides/references/advanced-installation.mdx
docs/guides/references/changelog.mdx
docs/guides/references/experiments.mdx

v13.14.0 Docs

---

docs/api/table-of-contents.mdx

The second sentence in https://docs.cypress.io/api/table-of-contents#Commands doesn't read well. I think there is a typo:
> Commands can be chained commands together because Cypress manages a Promise chain on your behalf, with each command yielding a 'subject' to the next command, until the chain ends or an error is encountered.
Remove the second "commands":
> Commands can be chained together because Cypress manages a Promise chain on your behalf, with each command yielding a 'subject' to the next command, until the chain ends or an error is encountered.
Please cross-check if this correction enhances the meaning or if I have misread.

Chaining command typo

---

docs/guides/guides/module-api.mdx

doc: update module_api guide with spec error info

---

docs/guides/cloud/account-management/projects.mdx
docs/guides/cloud/recorded-runs.mdx
docs/guides/cloud/smart-orchestration/overview.mdx
docs/guides/cloud/smart-orchestration/run-cancellation.mdx

this was some old verbiage still in-use and we call it auto cancellation in all other places

Change name from Run Cancellation to Auto Cancellation

---

docs/guides/core-concepts/writing-and-organizing-tests.mdx
docs/guides/references/configuration.mdx
docs/guides/references/troubleshooting.mdx

- Closes https://github.com/cypress-io/cypress-documentation/issues/5919
- The [debug](https://github.com/debug-js/debug) log source `cypress:server:specs`, referred to on multiple documentation pages, was removed in Cypress `10.0.0` and does not work on current Cypress versions. The change came through PR https://github.com/cypress-io/cypress/pull/19319 for Cypress `10.0.0`.
The direct replacement for `cypress:server:specs` would be `cypress:data-context:sources:FileDataSource,cypress:data-context:sources:ProjectDataSource`.
To debug specs not found, use
```shell
DEBUG=cypress:cli,cypress:data-context:sources:FileDataSource,cypress:data-context:sources:ProjectDataSource
```

docs: replace debug log source cypress:server:specs

---

docs/api/commands/intercept.mdx

Closes: https://github.com/cypress-io/cypress-documentation/issues/5924

docs: update table formatting on intercept.mdx

---

docs/guides/references/troubleshooting.mdx

In [References > Troubleshooting > Print DEBUG logs](https://docs.cypress.io/guides/references/troubleshooting#Print-DEBUG-logs)
- Instructions do not work when copied and pasted into a terminal window. They are missing a package manager prefix (`npx`, `yarn` or `pnpm`).
- Instructions for Windows PowerShell are missing.
- Show explicit instructions for debugging with npm, Yarn and pnpm using tabbed display.
- Show instructions for setting `DEBUG` with Windows PowerShell.
- Harmonize the use of prefixes `npx` / `yarn` / `pnpm` in command lines.
- Correct non-working debug module names using working module names.

docs: rework print debug logs

---

docs/guides/guides/command-line.mdx

[Guides > Command Line > Debugging commands](https://docs.cypress.io/guides/guides/command-line#How-to-run-commands) partially duplicates the [Troubleshooting](https://docs.cypress.io/guides/references/troubleshooting#Print-DEBUG-logs) instructions and is not linked to the [Troubleshooting](https://docs.cypress.io/guides/references/troubleshooting#Print-DEBUG-logs) page.
- Simplify debug details in [Guides > Command Line > Debugging commands](https://docs.cypress.io/guides/guides/command-line#How-to-run-commands) and refer to [References > Troubleshooting > Print DEBUG logs](https://docs.cypress.io/guides/references/troubleshooting#Print-DEBUG-logs) to avoid duplication and to ease future maintenance.

docs: consolidate cli debug commands

---

docs/guides/guides/screenshots-and-videos.mdx

In [Guides > Screenshots and Videos > Video encoding](https://docs.cypress.io/guides/guides/screenshots-and-videos#Video-encoding) the instructions say:
> If you are an FFmpeg pro and want to see all the settings and debug messages
> during the encoding, run Cypress with the following environment variable:
> `DEBUG=cypress:server:video cypress run`
This instruction does not work as it stands, since it is missing the package manager prefix (`npx`, `yarn` or `pnpm`).
Remove `cypress run` from the text, leaving the environment variable statement `DEBUG=cypress:server:video` on its own.

Correct video recording debug statement

---

docs/guides/references/advanced-installation.mdx
docs/guides/references/troubleshooting.mdx

The documentation site lacks information on troubleshooting installation of the Cypress binary.
1. Add a "Troubleshoot installation" section to [References > Advanced Installation](https://docs.cypress.io/guides/references/advanced-installation)
2. Add a comment to the [References > Troubleshooting > Print DEBUG logs > Log sources](https://docs.cypress.io/guides/references/troubleshooting#Log-sources) to use `cypress:cli*` to debug `cypress installation`

Add troubleshooting for Cypress installation

---

docs/guides/references/troubleshooting.mdx

The example `DEBUG` value `cypress:server:browsers:*` is incomplete.
Debug output for `cypress:server:browsers` is not logged in this case.
The [debug](https://www.npmjs.com/package/debug) module does not support any hierarchy based on colon characters `:`. This is a simple string match.
To also log debug output from [packages/server/lib/browsers/index.ts](https://github.com/cypress-io/cypress/blob/develop/packages/server/lib/browsers/index.ts) which defines a debug module name `cypress:server:browsers`, the environment value is changed to
`cypress:server:browsers*`
removing the colon character `:`.
- This was an error in the correction made by PR https://github.com/cypress-io/cypress-documentation/pull/5921, which added the sub-modules of `cypress:server:browsers` and accidentally left …

Correct debug cypress:server:browsers selection

---

docs/guides/getting-started/installing-cypress.mdx

[System requirements > Operating System](https://docs.cypress.io/guides/getting-started/installing-cypress#Operating-System) lists
> - **Windows** 10 and above _(64-bit only)_.
This could be taken to mean both `x64` and `arm64`, although the intention was to rule out Windows 32-bit support only.
Microsoft provides [Windows on Arm](https://learn.microsoft.com/en-us/windows/arm/overview) and this is likely to receive more visibility due to Windows 11 24H2.
Cypress is built as `win32 x64` only. There is no `arm64` version of Cypress built.
Specify `x64` for Windows.

Specify Windows x64 as supported OS

---

docs/guides/references/troubleshooting.mdx

The table of `DEBUG` values in [References > Troubleshooting > Log sources](https://docs.cypress.io/guides/references/troubleshooting#Log-sources) is missing the value `cypress:*` to enable all debugging output.
Add `DEBUG` value `cypress:*` to the top of the table in [References > Troubleshooting > Log sources](https://docs.cypress.io/guides/references/troubleshooting#Log-sources).

Add cypress:* to table of DEBUG log sources

---

docs/guides/guides/command-line.mdx
docs/guides/references/troubleshooting.mdx

- [Guides > Command Line `cypress info`](https://docs.cypress.io/guides/guides/command-line#cypress-info) provides
> **Tip:** set [DEBUG environment variable](/guides/references/troubleshooting#Print-DEBUG-logs)
> to `cypress:launcher` when running `cypress info` to troubleshoot browser detection.
This setting however produces no debug output.
- [Troubleshooting > Launching browsers](https://docs.cypress.io/guides/references/troubleshooting#Launching-browsers) also suggests this non-working setting.
On the above-mentioned pages, add a wildcard to the DEBUG module selector so that it becomes `cypress:launcher:*`.

Correct DEBUG cypress:launcher with wildcard

---

docs/guides/guides/launching-browsers.mdx

We're not sure when 86-90 versions stopped working, but verifying versions today shows that they don't work in Cypress so just reflecting reality.

docs: Update minimum Firefox version to reflect reality

---

docs/guides/references/changelog.mdx

The [Changelog](https://docs.cypress.io/guides/references/changelog) contains links to bookmarks within the Changelog page which use:
- an absolute reference, such as `https://docs.cypress.io/guides/references/changelog#13-6-0`
- a relative reference, such as `/guides/references/changelog#13-6-3`
although linking to the same page bookmark
- such as `#13-6-3`
would provide a simpler link.
In the [Changelog](https://docs.cypress.io/guides/references/changelog)
- replace all absolute references `https://docs.cypress.io/guides/references/changelog#` with `#`, then
- replace all relative references `/guides/references/changelog#` with `#`
This increases readability and maintainability of the associated in-page links.

Simplify changelog in-page links

---

docs/guides/references/changelog.mdx

The [Changelog](https://docs.cypress.io/guides/references/changelog) contains links from one Cypress release to another Cypress release, and in some cases the version is formatted as Markdown code. This produces a sub-optimal display of the version number, which is highlighted (as a hyperlink) and underlined (as code).
The document [Cypress App - Managing the Release Changelog](https://github.com/cypress-io/cypress/blob/develop/guides/writing-the-cypress-changelog.md) specifies in [Writing Guidelines](https://github.com/cypress-io/cypress/blob/develop/guides/writing-the-cypress-changelog.md#writing-guidelines)
- If a changelog item is a regression, the description should start with `Fixed a regression in [9.1.0](#9-1-0)` with a link to the release that introduced it.
In the …

Remove linked Cypress versions Markdown as code

---

src/data/plugins.json

Adding new plugins to documentation:
- **cypress-xray-junit-reporter**
should be used by people that cannot migrate to jira cloud, attach screenshot function
- **cypress-env**
This utility simplifies the process of handling different environments (such as test, staging, and production) by providing a environment-specific settings in your Cypress tests.
- **cypress-aws-secrets-manager**
This plugin integrates AWS Secrets Manager into your Cypress tests, ensuring that sensitive data like API keys, passwords, and tokens remain secure during testing. It allows for secure loading and updating of secrets directly from your tests.

docs: update plugins.json to include new plugins (Jira ,AWS secret manager, multi-env)

---

src/data/plugins.json

Renamed the plugin to avoid any confusion between it and the official offering from Cypress. See PR https://github.com/cypress-io/cypress-documentation/pull/5942 for reference.

docs: rename cypress-accessibility plugin to cypress-a11y-report

---

src/data/plugins.json

- closes https://github.com/cypress-io/cypress-documentation/issues/5946
The [Plugins](https://docs.cypress.io/plugins) list includes some plugins which are outdated and no longer useful.
Remove all plugins which meet the following criteria for being outdated.
Outdated plugins:
- are marked as "Deprecated" and
- are based on repos which have been archived or which are otherwise declared as unsupported or
- support only legacy versions of Cypress `v9` or lower or
- have not been updated since the release of Cypress `v10` in June 2022
The full list, together with each individual status, is shown in
- issue https://github.com/cypress-io/cypress-documentation/issues/5946

Remove deprecated plugins

---

docs/app/guides/accessibility-testing.mdx

Linking to a specific project for now a opposed to the onlink.

update a11y project link

---

docs/ui-coverage/changelog.mdx
netlify.toml

- Do not bold some changelog entries in UI Cov
- Reroute ui-coverage to main ui-cov doc

More cleanup

---

docs/app/references/assertions.mdx

Link to chai guide https://www.chaijs.com/api/node-events/ on the documentation for [writing new custom assertions](https://docs.cypress.io/app/references/assertions#Adding-New-Assertions) is no longer reachable (404).

docs(assertions): update link to custom chai assertions guide

---

docs/app/continuous-integration/aws-codebuild.mdx
docs/app/continuous-integration/bitbucket-pipelines.mdx
docs/app/continuous-integration/github-actions.mdx
docs/app/continuous-integration/gitlab-ci.mdx

Node.js has now released the version [Node v22.11.0 LTS](https://nodejs.org/en/blog/release/v22.11.0) with the introduction:
> This release marks the transition of Node.js 22.x into Long Term Support (LTS) with the codename 'Jod'. The 22.x release line now moves into "Active LTS" and will remain so until October 2025. After that time, it will move into "Maintenance" until end of life in April 2027.
Cypress Docker versions in examples should transition to use the new Node.js LTS version by default.
In examples:
- `cypress/base:20.14.0` is bumped to <br>`cypress/base:22.11.0`
- `cypress/browsers:node-20.14.0-chrome-126.0.6478.114-1-ff-127.0.1-edge-126.0.2592.61-1` is bumped to<br>`cypress/browsers:node-22.11.0-chrome-130.0.6723.69-1-ff-132.0-edge-130.0.2849.56-1`

Update examples Docker version to Node.js 22.x (LTS)

---

docs/accessibility/changelog.mdx
docs/accessibility/core-concepts/how-it-works.mdx

This documents our decision about an update "buffer" and confirms the earliest axe-core version bump will happen after December 1.

Add Cloud axe-core update policy

---

docs/api/commands/intercept.mdx
docs/app/component-testing/get-started.mdx
docs/app/references/changelog.mdx
docs/app/references/migration-guide.mdx

vite 2 and 3 support is dropped in cypress 14. This updates the docs to the corresponding change

chore: update supported vite versions for cypress 14

---

docs/app/component-testing/get-started.mdx
docs/app/component-testing/react/overview.mdx

Updates Next.js supported versions to be 14 as 10, 11, 12, and 13 are no longer supported.
requires https://github.com/cypress-io/cypress-component-testing-apps/pull/25 to be merged into the `cypress-component-testing-apps` `release/14.0.0` branch

chore: update nextjs documentation to reflect Cypress 14

---

docs/app/component-testing/angular/api.mdx
docs/app/component-testing/angular/examples.mdx
docs/app/component-testing/angular/overview.mdx
docs/app/component-testing/get-started.mdx
docs/app/references/migration-guide.mdx

Updates Angular to the minimum version support (17.2.0) and adds migration docs 
Example app updates: https://github.com/cypress-io/cypress-component-testing-apps/pull/31

chore: update angular documentation with supported versions from Cypress 14

---

docs/app/component-testing/get-started.mdx
docs/app/component-testing/react/overview.mdx
docs/app/faq.mdx
docs/app/references/migration-guide.mdx

removed create-react-app from the cypress docs and reordered `next.js` to be below core react support as its built on react and contextually makes sense to appear after
accompanying component testing examples repo changes to remove CRA examples: https://github.com/cypress-io/cypress-component-testing-apps/pull/32

chore: remove CRA docs from cypress 14 and add migration guide

---

docs/app/get-started/install-cypress.mdx
docs/app/references/advanced-installation.mdx

- closes https://github.com/cypress-io/cypress-documentation/issues/5945
The documentation website contains no instructions about how to uninstall Cypress.
1. Add a section "Uninstall Cypress" to the bottom of the reference page [Advanced Installation](https://docs.cypress.io/app/references/advanced-installation)
2. Mention the availability of this description in the [Advanced Installation](https://docs.cypress.io/app/get-started/install-cypress#Advanced-Installation) section of the [Install Cypress](https://docs.cypress.io/app/get-started/install-cypress) page.

Add Cypress uninstall instructions

---

docs/app/get-started/install-cypress.mdx

Interim release [Ubuntu 24.10 (Oracular Oriole)](https://fridge.ubuntu.com/2024/10/10/ubuntu-24-10-oracular-oriole-released/), released on Oct 10, 2024, is not mentioned under [Linux Prerequisites](https://docs.cypress.io/app/get-started/install-cypress#Linux-Prerequisites). The generic instructions [Ubuntu/Debian](https://docs.cypress.io/app/get-started/install-cypress#UbuntuDebian) do not work for Ubuntu `24.10`. The ones for Ubuntu `24.04` have to be applied.
Under [Linux Prerequisites](https://docs.cypress.io/app/get-started/install-cypress#Linux-Prerequisites) change
> For Ubuntu 24.04
to
> For Ubuntu 24.04 and above
to cover the [Ubuntu 24.10 (Oracular Oriole)](https://fridge.ubuntu.com/2024/10/10/ubuntu-24-10-oracular-oriole-released/) interim release.
In practice, Ubuntu `24.04` …

Cover Ubuntu 24.10 for Linux installation prerequisites

---

docs/api/commands/mount.mdx
docs/app/component-testing/get-started.mdx
docs/app/component-testing/react/api.mdx
docs/app/component-testing/react/overview.mdx
docs/app/component-testing/vue/overview.mdx
docs/app/references/changelog.mdx
docs/app/references/migration-guide.mdx
docs/partials/_import-mount-functions.mdx

updates the `cypress/react` documentation to support react 18 and adds the migration guide to move from `cypress/react18` to `cypress/react`
see https://github.com/cypress-io/cypress-component-testing-apps/pull/36 for updating webpack in react app (react app vite updated in https://github.com/cypress-io/cypress-component-testing-apps/pull/29)

chore: update react documentation for Cypress 14

---

src/data/plugins.json

This PR fixes the broken link to the cypress quick start guide on Applitools

Fix broken link to Applitools docs

---

docs/app/tooling/reporters.mdx

- closes #6010
The [Tooling > Reporters](https://docs.cypress.io/app/tooling/reporters) page, in the section [Built in reporterts](https://docs.cypress.io/app/tooling/reporters#Built-in-reporters) links to the repo
https://github.com/cypress-io/mocha-teamcity-reporter. This is an archived repo. It is an outdated fork based on the repo
https://github.com/travisjeffery/mocha-teamcity-reporter.
Cypress currently includes the npm module [mocha-teamcity-reporter](https://www.npmjs.com/package/mocha-teamcity-reporter) which is also linked to the repo https://github.com/travisjeffery/mocha-teamcity-reporter.
Replace the outdated repo link
- https://github.com/cypress-io/mocha-teamcity-reporter
using instead
- https://github.com/travisjeffery/mocha-teamcity-reporter

Replace @cypress/mocha-teamcity-reporter with mocha-teamcity-reporter

---

docs/app/references/experiments.mdx

Some of the JIT doc updates, such as the migration guide and default flag configuration reference, already live in the release 14 branch. This PR is to remove JIT from the experimental section which I think we missed on the first passthrough

chore: update JIT docs

---

docs/app/tooling/reporters.mdx

The [Reporters > Introduction](https://docs.cypress.io/app/tooling/reporters#Introduction) section contains an invalid markdown link `[built in](#Built in reporter)` to the [Built in reporters](https://docs.cypress.io/app/tooling/reporters#Built-in-reporters) section on the same page.
In the [Reporters > Introduction](https://docs.cypress.io/app/tooling/reporters#Introduction) section fix the invalid link to the [Built in reporters](https://docs.cypress.io/app/tooling/reporters#Built-in-reporters) section.

fix incorrect built in reporters link

---

docs/app/continuous-integration/circleci.mdx

Hello.
The CircleCI configuration example in the Cypress documentation ([https://docs.cypress.io/app/continuous-integration/circleci](https://docs.cypress.io/app/continuous-integration/circleci)) is missing a colon in the `orbs` section. 
Specifically, the line defining the `cypress` orb (`cypress cypress-io/cypress@3`) lacks a colon (`:`) between the key and value. 
This commit adds the missing colon to ensure the example is correct and ready for use without modification.
A screenshot highlighting the issue is attached to provide additional context.

docs: fix missing colon in circleci.mdx

---

docs/app/references/command-line.mdx

- Follows on from https://github.com/cypress-io/cypress/issues/30661
The [cypress run Options](https://docs.cypress.io/app/references/command-line#Options) describes the effect of the  `--quiet` option as follows:
| Option          | Description                                                                                                                                     |
| --------------- | ----------------------------------------------------------------------------------------------------------------------------------------------- |
| `--quiet`, `-q` | If passed, Cypress output will not be printed to `stdout`. Only output from the configured [Mocha reporter](https://docs.cypress.io/app/tooling/reporters) will print. |
This can be misleading because Cypress includes the [Mocha …

Add built in reporter info to CLI --quiet option

---

docs/app/references/advanced-installation.mdx

[Advanced Installation > Run binary](https://docs.cypress.io/app/references/advanced-installation#Run-binary) includes instructions for using the environment variable `CYPRESS_RUN_BINARY` to override where the npm module finds the Cypress binary.
1. The instructions to run Cypress do not work as written. The package manager prefix `npx`, `yarn` or `pnpm` is missing and there is no hint that this would be needed.
2. There are no instructions about how to unzip the Cypress binary `cypress.zip`. Depending on how the extract or unzip operation is performed, there may be an extra directory level created. On Linux, for instance, this could mean that it is necessary to set the environment variable to `CYPRESS_RUN_BINARY=~/Downloads/cypress/Cypress/Cypress` instead of …

Rework CYPRESS_RUN_BINARY instructions

---

docs/app/references/advanced-installation.mdx
docs/app/references/command-line.mdx

1. [Advanced Installation > Environment variables](https://docs.cypress.io/app/references/advanced-installation#Environment-variables) lists `CYPRESS_SKIP_VERIFY` as follows:
| Name                  | Description                                             |
| --------------------- | ------------------------------------------------------- |
| `CYPRESS_SKIP_VERIFY` | Skips the `verify` command (for stable CI environments) |
It does not however say what the variable should be set to.
https://github.com/cypress-io/cypress/blob/12df40ed8c1101c5c4053a1fe63c06fcd2809bc7/cli/lib/tasks/verify.js#L261
```js
skipVerify: util.getEnv('CYPRESS_SKIP_VERIFY') === 'true',
```
shows that Cypress is specifically looking for the contents of `CYPRESS_SKIP_VERIFY` to be strictly equal to `true`.
2. …

Add Environment variable CYPRESS_SKIP_VERIFY setting

---

docs/app/continuous-integration/overview.mdx

https://docs.cypress.io/app/continuous-integration/overview contains bad links to Docker materials resulting in 404 errors
- https://docs.docker.com/app/docker-overview/
- https://docs.docker.com/app/docker-concepts/the-basics/what-is-a-container/
These links were incorrectly changed from `guides` to `app` by
- PR #5947
Update the Docker links on [docs/app/continuous-integration/overview.mdx](https://github.com/cypress-io/cypress-documentation/blob/main/docs/app/continuous-integration/overview.mdx) to their current location on the https://docs.docker.com/ site:
https://docs.docker.com/get-started/docker-overview/
https://docs.docker.com/get-started/docker-concepts/the-basics/what-is-a-container/

Correct CI overview Docker links

---

docs/accessibility/results-api.mdx
docs/ui-coverage/results-api.mdx

This pull request addresses two typos in the getResults scripts for the Results API. These typos are causing errors in the pipeline during execution.
The `console.log` statement was incorrectly written as .console.log, leading to the following error:
```
/builds/acme/acme-app/packages/ui/scripts/verifyAccessibilityResults.js:13
.console.log(`See full report at ${accessibilityReportUrl}.`);
^
TypeError: Cannot read properties of undefined (reading 'console')
at /builds/acme/acme-app/packages/ui/scripts/verifyAccessibilityResults.js:13:5
at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```
The variable rulesWithExistingViolations was being used before it was initialized, resulting in:
```
/builds/acme/acme-app/packages/ui/scripts/verifyAccessibilityResults.js:29 …
```

docs: fix results-api.mdx getResults script

---

docs/app/component-testing/angular/examples.mdx
docs/app/component-testing/angular/overview.mdx
docs/app/component-testing/get-started.mdx

Updates the angular docs to represent Angular 19
see https://github.com/cypress-io/cypress-component-testing-apps/pull/38 for Angular 19 standalone updates. Angular 18 update for non standalone was updated in https://github.com/cypress-io/cypress-component-testing-apps/pull/31

chore: update angular docs to include Angular 19

---

docs/app/tooling/IDE-integration.mdx

This PR adds a reference to a new VS Code extension https://marketplace.visualstudio.com/items?itemName=dpanshug.cypress-test-explorer
Features are mentioned in the README of the [repository](https://github.com/dpanshug/cypress-test-explorer)
I would appreciate suggestions on whether this is the appropriate way to introduce the extension in the documentation and any recommendations for improvement.

docs: adding Cypress Test Explorer extension

---

docs/app/component-testing/get-started.mdx
docs/app/component-testing/svelte/api.mdx
docs/app/component-testing/svelte/examples.mdx
docs/app/component-testing/svelte/overview.mdx
docs/app/references/migration-guide.mdx

updates docs to reflect svelte 5 update. 
repo updates can be seen in https://github.com/cypress-io/cypress-component-testing-apps/pull/40
There needs to be updates to  https://github.com/cypress-io/component-testing-quickstart-apps, which will be done independently of this work

chore: update docs to svelte 5

---

docs/cloud/features/analytics/enterprise-reporting.mdx
docs/cloud/integrations/data-extract-api.mdx
docs/cloud/integrations/slack.mdx
docs/cloud/integrations/teams.mdx

Corresponding with our November releases, we have added the following capabilities and need the docs to match:
* Enterprise reporting offers filtering by Commit Branch in the UI
* Data Extract API allow for filtering by commit branch, has some data now available near real-time, and added spec path and test names to some endpoints as requested by customers.
* Slack integration has added the ability to configure when a message is sent based on Run Groups
* Microsoft Teams integration has added the ability to configure when a message is sent based on Run Groups and Tags.  The "beta" status of Teams integration is being removed and it is now official.
Where applicable, screen captures shown in our Docs will be updated in the December release because of more UI changes coming in the next few …

Slack, Teams, and Data Extract API changes

---

docs/app/component-testing/react/overview.mdx

React 19 released yesterday, which means we no longer need to support the Release Candidate. This PR removes the warning about the RC being supported temporarily.

chore: remove react 19 rc warning

---

docs/app/get-started/install-cypress.mdx

- closes https://github.com/cypress-io/cypress-documentation/issues/6022
1. The documentation section [Get Started > Install Cypress > Operating System](https://docs.cypress.io/app/get-started/install-cypress#Operating-System) does not cover the common usage of Cypress in CI systems, where it runs on server operating systems.
2. The names of supported Microsoft Windows Server operating systems are missing.
1. Make the [Get Started > Install Cypress > Operating System](https://docs.cypress.io/app/get-started/install-cypress#Operating-System) more generic to cover usage on both Desktop and Server operating systems.
2. Add the Microsoft Windows Server operating systems which are currently offered under [GitHub Actions - Runner Images](https://github.com/actions/runner-images) and under …

Add Windows Server OS names to supported list

---

docs/app/faq.mdx

- closes https://github.com/cypress-io/cypress-documentation/issues/6025
The FAQ entry [Can I test Gatsby.js sites using Cypress?](https://docs.cypress.io/app/faq#Can-I-test-Gatsbyjs-sites-using-Cypress) contains bad links
- https://www.gatsbyjs.com/docs/end-to-end-testing/ no longer works
https://www.gatsbyjs.com/ states
> Gatsby Cloud and Netlify Cloud are uniting!
with an announcement from August 2023.
Remove the outdated FAQ entry [Can I test Gatsby.js sites using Cypress?](https://docs.cypress.io/app/faq#Can-I-test-Gatsbyjs-sites-using-Cypress) as suggested by @jennifer-shehane in https://github.com/cypress-io/cypress-documentation/issues/6025#issuecomment-2532589333.

Remove Gatsby FAQ

---

docs/app/continuous-integration/bitbucket-pipelines.mdx

- closes https://github.com/cypress-io/cypress-documentation/issues/6048
The example [Continuous Integration > Bitbucket Pipelines > Basic Setup](https://docs.cypress.io/app/continuous-integration/bitbucket-pipelines#Basic-Setup) fails to run since the Docker image `node:latest` does not provide the [Linux prerequisites for Debian/Ubuntu](https://docs.cypress.io/app/get-started/install-cypress#UbuntuDebian).
In [Continuous Integration > Bitbucket Pipelines > Basic Setup](https://docs.cypress.io/app/continuous-integration/bitbucket-pipelines#Basic-Setup) remove the code example
1. Explain that using default Bitbucket / Atlassian images requires installing [Linux prerequisites for Debian/Ubuntu](https://docs.cypress.io/app/get-started/install-cypress#UbuntuDebian).
2. Recommend instead …

Recommend Cypress Docker images for Bitbucket CI

---

docs/accessibility/results-api.mdx
docs/app/continuous-integration/aws-codebuild.mdx
docs/app/continuous-integration/bitbucket-pipelines.mdx
docs/app/continuous-integration/github-actions.mdx
docs/app/continuous-integration/gitlab-ci.mdx
docs/ui-coverage/results-api.mdx

Using the long-form tag for `cypress/browsers` Docker images, such as in 
`cypress/browsers:node-22.11.0-chrome-130.0.6723.69-1-ff-132.0-edge-130.0.2849.56-1`
causes code examples to be so wide that scrolling can be necessary to view. See for example https://docs.cypress.io/app/continuous-integration/aws-codebuild#Cypress-Amazon-Public-ECR.
Starting from the release of the Cypress Docker image `cypress/browsers:22.11.0`, a short-form tag e.g. 
`22.11.0` 
is available, which takes far less space to display than the long-form tag e.g. 
`node-22.11.0-chrome-130.0.6723.69-1-ff-132.0-edge-130.0.2849.56-1`
See [`cypress/browsers` Tags](https://github.com/cypress-io/cypress-docker-images/tree/master/browsers#tags).
Replace all long-form tags for `cypress/browser` in examples with their …

Use Docker image short-form Node.js tag in examples

---

docs/accessibility/results-api.mdx
docs/app/continuous-integration/github-actions.mdx
docs/ui-coverage/results-api.mdx

GitHub Action examples using:
- `ubuntu-22.04` are outdated
- `ubuntu-latest` run the risk of unplanned breaking changes
[Notice of upcoming releases and breaking changes for GitHub Actions](https://github.blog/changelog/2024-12-05-notice-of-upcoming-releases-and-breaking-changes-for-github-actions/), dated Dec 5, 2024, announces the move of `ubuntu-latest` from `ubuntu-22.04` to `ubuntu-24.04`
[cypress-io/github-action](https://github.com/cypress-io/github-action) has already migrated to `ubuntu-24.04`.
Update [GitHub Actions Ubuntu runner images](https://github.com/actions/runner-images) in GitHub Actions examples to use [ubuntu-24.04](https://github.com/actions/runner-images/blob/main/images/ubuntu/Ubuntu2404-Readme.md) consistently.
Update `actions/checkout@v3`(unsupported `node16` …

Update Ubuntu in GitHub Actions examples to ubuntu-24.04

---

docs/accessibility/configuration/axe-core-configuration.mdx
docs/accessibility/core-concepts/how-it-works.mdx
docs/api/commands/window.mdx
docs/api/node-events/overview.mdx
docs/app/core-concepts/best-practices.mdx
docs/app/references/changelog.mdx

This pull request removes duplicate words found in the documentation. This pull request also fixes a spacing issue found in the [accessibility testing section on the core concepts page.](https://docs.cypress.io/app/core-concepts/best-practices#Accessibility-Testing)
Note: This pull request is not tied to a feature.

Remove Duplicate Words & Fix Spacing Issue

---

docs/app/core-concepts/best-practices.mdx
docs/app/end-to-end-testing/writing-your-first-end-to-end-test.mdx

- The Anti-Pattern description [Visiting External Sites](https://docs.cypress.io/app/core-concepts/best-practices#Visiting-External-Sites) and the section in [Step 1: Visit a page](https://docs.cypress.io/app/end-to-end-testing/writing-your-first-end-to-end-test#Step-1-Visit-a-page) with the title "Testing Apps You Don't Control" are related and not linked.
- There is no bookmark to reference "Testing Apps You Don't Control".
1. Move "Testing Apps You Don't Control" down the page on [Your First Test](https://docs.cypress.io/app/end-to-end-testing/writing-your-first-end-to-end-test) to allow it to be referenced.
2. Cross-reference the two sections that refer to visiting external sites, between the two pages:
- [Best Practices](https://docs.cypress.io/app/core-concepts/best-practices)
- …

Cross-reference visiting external sites anti-pattern

---

docs/app/tooling/code-coverage.mdx

In [Tooling > Code Coverage > Introduction](https://docs.cypress.io/app/tooling/code-coverage#Introduction) there is a typo in the list:
> Code coverage - find out which lines of the application's source code were
> UI coverage - find out which parts of the UI were tested executed
The first item lacks a verb and the second item has one verb too many.
In [Tooling > Code Coverage > Introduction](https://docs.cypress.io/app/tooling/code-coverage#Introduction) move "executed" from the second list item to the first list item.
Some other minor typo corrections and minor grammatical changes on the same page are included as well.

Fix Code Coverage typos

---

src/css/custom.scss

Fixed an issue where tables within code blocks had incorrect word spacing, causing layout issues. Added `word-spacing: 0` to the code block lines.
closes #5788
- Verified table formatting in code blocks displays correctly
- Checked that the fix doesn't affect other code block content

fix: remove extra word spacing in codeblock

---

docs/api/cypress-api/require.mdx
docs/app/continuous-integration/overview.mdx
docs/app/faq.mdx
docs/app/guides/migration/protractor-to-cypress.mdx
docs/app/references/changelog.mdx

Source links stored in `*.mdx` files with the published domain name `https://docs.cypress.io/...` are not portable and may produce unexpected results when testing locally under `localhost`.
Secondly, Docusaurus does not report errors for links with external domains, meaning errors may go undetected. It only checks local links.
The following links resolve to a page, however the corresponding bookmark is missing from the page and so, when the link is used, the cursor is placed at the top of the page, leaving the reader to figure out what was intended:
- https://docs.cypress.io/faq/questions/cloud-faq#Is-everything-captured-and-replayed-in-Test-Replay resolves to https://docs.cypress.io/cloud/faq#Is-everything-captured-and-replayed-in-Test-Replay. The bookmark …

Convert https://docs.cypress.io/ links to local

---

docs/app/tooling/visual-testing.mdx

I think it would be good to add a reference to Argos in the visual testing section.

Reference Argos in Visual Testing section

---

docs/accessibility/core-concepts/how-it-works.mdx
docs/ui-coverage/get-started/introduction.mdx

- closes https://github.com/cypress-io/cypress-documentation/issues/6054
The target https://docs.cypress.io/faq/questions/cloud-faq#Is-everything-captured-and-replayed-in-Test-Replay no longer exists and the contents were moved to https://docs.cypress.io/cloud/features/test-replay#What-is-not-captured.
It is used in:
- https://docs.cypress.io/accessibility/core-concepts/how-it-works#Powered-by-Test-Replay
> Because Cypress Accessibility uses data captured through Cypress Test Replay, it is subject [Test Replay limitations](https://docs.cypress.io/faq/questions/cloud-faq#Is-everything-captured-and-replayed-in-Test-Replay).
- https://docs.cypress.io/ui-coverage/get-started/introduction#How-it-Works
> Because Cypress Accessibility uses data captured through Cypress Test Replay, it is subject …

Fix links to Test Replay and content limitations

---

docs/accessibility/changelog.mdx
docs/api/commands/get.mdx
docs/app/continuous-integration/github-actions.mdx
docs/app/continuous-integration/overview.mdx
docs/app/faq.mdx
docs/app/guides/migration/protractor-to-cypress.mdx
docs/app/references/changelog.mdx
docs/app/references/configuration.mdx
docs/app/references/error-messages.mdx
docs/app/references/troubleshooting.mdx
docs/cloud/account-management/billing-and-usage.mdx
docs/partials/_anatomy-of-an-error.mdx
docs/partials/_ci_provider_cloud_steps.mdx
docs/partials/_document-domain-workaround.mdx
docs/ui-coverage/changelog.mdx

Source links stored in `*.mdx` files with the Cypress redirect server https://on.cypress.io/ that redirect to https://docs.cypress.io/ do not allow transparent testing by Docusaurus. Incorrect redirection links, such as https://on.cypress.io/github#Pull-request-comments which produces a "HTTP 404 not found" error, go undetected as Docusaurus only checks local links.
- Convert https://on.cypress.io/, that redirect to https://docs.cypress.io/, to their current local target.
Links such as https://on.cypress.io/discord or https://on.cypress.io/cloud, that redirect to another domain, are left unchanged.
Also in code example comments, links such as `// see: https://on.cypress.io/mounting-react` are valid and left unchanged.
| From …

Convert https://on.cypress.io/ local target links to full local

---

docs/app/references/error-messages.mdx

1. The error message heading [--auto-cancel-after-failures must be a integer or false](https://docs.cypress.io/app/references/error-messages#--auto-cancel-after-failures-must-be-a-integer-or-false) contains a grammatical typo "a integer".
2. The text for the error message [You passed the --auto-cancel-after-failures flag for a run that is already in progress](https://docs.cypress.io/app/references/error-messages#You-passed-the---auto-cancel-after-failures-flag-for-a-run-that-is-already-in-progress) contains a typo "takes precedent".
In the above error message sections:
1. Change the error message heading to read "--auto-cancel-after-failures must be an integer or false"
2. Change "takes precedent" to "takes precedence" (see https://www.merriam-webster.com/dictionary/precedence)

Correct error message infos for "auto-cancel-after-failures"

---

docs/app/continuous-integration/overview.mdx

In [Continuous Integration > Overview > Solutions](https://docs.cypress.io/app/continuous-integration/overview#Solutions) there is a formatting error for `start-server-and-test` where the Markdown fenced block instruction `shell` appears as part of the command to be executed by the user.
Add newlines into the code blocks for `start-server-and-test` in [Continuous Integration > Overview > Solutions](https://docs.cypress.io/app/continuous-integration/overview#Solutions) to correct the formatting and to prevent Prettier from incorrectly reformatting the code blocks.

Correct start-server-and-test code blocks

---

docs/ui-coverage/guides/address-coverage-gaps.mdx
docs/ui-coverage/guides/identify-coverage-gaps.mdx
docs/ui-coverage/guides/ignore-elements.mdx
docs/ui-coverage/guides/ignore-views-and-links.mdx
docs/ui-coverage/guides/monitor-changes.mdx
docs/ui-coverage/guides/reduce-noise.mdx
docs/ui-coverage/guides/reduce-test-duplication.mdx

Add the new product heading since these guides went in after that was merged.

Add product headings to UI Cov guides

---

src/components/plugins-list/style.module.css

Removes 405 elements from the color-contrast a11y violation. https://cloud.cypress.io/projects/imown1/branches/a11y-fixes-2/review?changeRequest=6080&insight=accessibility-failed-elements

a11y: Update tags on plugins to be lighter color in dark mode

---

docs/partials/_viewfilters.mdx
docs/partials/_views.mdx

These were flip-flopped - `viewFilters`, not `views`, are not configurable per-product.

docs: Update notes for views/viewFilters config

---

docs/app/references/changelog.mdx

- closes https://github.com/cypress-io/cypress-documentation/issues/6085

add late bugfixes for cypress 14.0.0

---

docs/app/get-started/install-cypress.mdx

[App > Get Started > Install Cypress > System requirements > Installing Node.js](https://docs.cypress.io/app/get-started/install-cypress#Installing-Nodejs) contains text:
> Best Practice
>
> Use a [Node.js package manager](https://nodejs.org/en/download/package-manager/all) to install Node.js. Package managers for Node.js allow you to switch between different versions easily.
The link to "Node.js package manager" https://nodejs.org/en/download/package-manager/all is no longer in use by the https://nodejs.org website and so its contents, which is a list of various Node.js version managers,  need to be regarded as no longer maintained even if the page is currently still visible. Its local language translations have all been deleted.
Node.js redesigned their [Download …

Update Node.js instructions for version managers

---

docs/app/get-started/install-cypress.mdx

The Linux section of [App > Get Started > Install Cypress > System requirements > Operating System](https://docs.cypress.io/app/get-started/install-cypress#Operating-System) contains the following deprecation notices:
> - Cypress deprecated the use of Node.js `16.x` in Cypress [`13.0.0`](https://docs.cypress.io/app/references/changelog#13-0-0). We recommend that users update to at least Node.js `18.x`.
>    For related reasons, Cypress deprecates the use of Linux operating systems with library [`glibc`](https://www.gnu.org/software/libc/) versions `2.17` - `2.27`. The Linux CLI command `ldd --version` displays your glibc version.
With the release of [Cypress 14.0.0](https://docs.cypress.io/app/references/changelog#14-0-0) the deprecation notes are no longer necessary in this location as …

Remove Linux OS and Node.js deprecation notes

---

docs/app/get-started/install-cypress.mdx

- closes https://github.com/cypress-io/cypress-documentation/issues/6092
[Get Started > Install Cypress](https://docs.cypress.io/app/get-started/install-cypress) information for using package managers: npm, Yarn and pnpm is scattered and not at the same level of detail for each package manager. Developments in package management usage, such as the introduction of Corepack, are not covered. When Yarn is mentioned there is no distinction made between Yarn 1 Classic and Yarn Modern. For the latter there is no indication about which `nodeLinker` modes are supported and which do not work.
- Generalize package manager installation and refer back to each package manager's own documentation.
- For Yarn Modern prefer `node-modules` and exclude [Yarn Plug'n'Play](https://yarnpkg.com/features/pnp) …

Add package manager list and installation instructions

---

docs/api/node-events/browser-launch-api.mdx

In Chrome 132, Chrome completely removed the old `--headless` flag, so this workaround is no longer available to users.

Remove example of disabling headless new

---

docs/app/references/changelog.mdx

Adds the Cypress 14.0.2 changelog

chore: add cypress 14.0.2 changelog

---

src/data/plugins.json

Hi i create plugin  to connect with database

Update plugins.json  add @dankieu/cypress-sq

---

src/data/plugins.json

Adding two new, fantastic plugins that support expanded grep/test select functionality. 
- [cypress-plugin-grep-boxes](https://github.com/dennisbergevin/cypress-plugin-grep-boxes)
- [cypress-cli-select-plugins](https://github.com/dennisbergevin/cypress-cli-select)
@dennisbergevin

Add Plugins: cypress-plugin-grep-boxes & cypress-cli-select

---

src/data/plugins.json

I had already registered this plugin in #2250, but it was removed without my knowledge in #5946.
I also realized it had been marked as "deprecated" before, also without my knowledge. I suppose it was marked as such because it had Cypress 3 as a dependency, but that's something [I fixed 3 months ago](https://github.com/NoelDeMartin/cypress-laravel/releases/tag/v0.3.0). Would have fixed it sooner if anyone bothered to open an issue about it in my repo :).

Add cypress-laravel plugin

---

docs/app/continuous-integration/overview.mdx

In [Continuous Integration > Common problems and solutions > Missing binary](https://docs.cypress.io/app/continuous-integration/overview#Missing-binary) the linked example:
https://github.com/bahmutov/yarn-cypress-cache
is obsolete and fails to run. It was last updated 6 years ago in Nov 2019.
- The example is based on the legacy Cypress `3.6.1` version
- The action versions are outdated and are no longer available
- The application under test http://todomvc.com/examples/vue/ no longer exists and has moved to a different page
- The example CI is Travis and the build status https://travis-ci.org/bahmutov/yarn-cypress-cache no longer exists
Remove the paragraph from the [Continuous Integration > Common problems and solutions > Missing …

Remove link to obsolete yarn-cypress-cache example repo

---

docs/api/commands/shadow.mdx

This signature is just...wrong. I looked at the implementation. The .shadow command does not accept a selector.
Also added the options that are supported.

docs: Update shadow query command to correct command signature

---

docs/api/cypress-api/browser.mdx
docs/api/cypress-api/isbrowser.mdx
docs/app/references/launching-browsers.mdx

adds docs around using firefox webdriver BiDi and CDP deprecation, as well as how to enable CDP if completely necessary.

chore: add firefox webdriver bidi docs

---

docs/api/node-events/overview.mdx

[API > Node Events Overview](https://docs.cypress.io/api/node-events/overview) refers to a missing markdown link to deleted documentation `[legacypluginsfile]`
Remove obsolete references to legacy configurations. This documentation is no longer available.

Remove stranded legacy plugin links

---

docs/api/cypress-api/browser.mdx
docs/api/cypress-api/isbrowser.mdx
docs/app/references/changelog.mdx
docs/app/references/launching-browsers.mdx

* add firefox webdriver bidi docs
* add cypress `14.1.0` docs

chore: add Cypress release 14.1.0 documentation

---

docs/api/node-events/overview.mdx
docs/app/tooling/typescript-support.mdx
docs/partials/_source-maps.mdx

Adds documentation on letting users know that the `sourceMap` option should be set to `true` for TypeScript if using a custom preprocessor

chore: add documentation on recommended TypeScript sourcemap option

---

docs/api/commands/origin.mdx

This was added a while ago. Our actual Roadmap page reflects reality - that we can update as priorities change.

Remove mention of iframe support being on our current roadmap

---

docs/app/references/changelog.mdx

Adds release `14.2.1` to the app changelog

chore: add Cypress 14.2.1 changelog

---

docs/app/guides/cypress-studio.mdx

Cypress-Studio has known limitations regarding shadowdoms (https://github.com/cypress-io/cypress/issues/26146 ). The documentation should reflect that. 
This PR updates the documentation accordingly, I think.

add studio limitation regarding shadowdom

---

docs/app/continuous-integration/overview.mdx

Cypress Docker images for the `Linux/arm64` platform include Firefox >= `136.0.2` , see [cypress-io/cypress-docker-images > README](https://github.com/cypress-io/cypress-docker-images/blob/master/README.md#browsers):
- `cypress/browsers:node-22.14.0-chrome-134.0.6998.88-1-ff-136.0.2-edge-134.0.3124.68-1`
- `cypress/included:cypress-14.2.0-node-22.14.0-chrome-134.0.6998.88-1-ff-136.0.2-edge-134.0.3124.68-1`
[Continuous Integration > Cypress Docker Images > Cypress Docker Variants](https://docs.cypress.io/app/continuous-integration/overview#Cypress-Docker-variants) is now outdated, as it states:
> Currently Linux/arm64 images do not contain browsers.
Modify the text in https://github.com/cypress-io/cypress-documentation/blob/main/docs/app/continuous-integration/overview.mdx#cypress-docker-va …

Add Firefox to Linux/arm64 CI Cypress Docker usage

---

docs/app/get-started/install-cypress.mdx

- closes https://github.com/cypress-io/cypress-documentation/issues/6069
[pnpm@10.0.0](https://github.com/pnpm/pnpm/releases/tag/v10.0.0) includes a breaking change:
> Lifecycle scripts of dependencies are not executed during installation by default!
`cypress` needs to be added to the allowlist configuration for pnpm life cycle scripts.
A new sub-section "pnpm Configuration" is added to [Install Cypress > Package Manager](https://docs.cypress.io/app/get-started/install-cypress#Package-Manager).
The previous `caution` for Yarn Configuration is converted into a sub-section for better readability.

Add pnpm allow-build configuration information

---

docs/app/get-started/install-cypress.mdx

- closes https://github.com/cypress-io/cypress/issues/30821
[Get Started > System requirements > Operating System](https://docs.cypress.io/app/get-started/install-cypress#Operating-System) currently lists:
> Windows Server 2019 and 2022 (x64)
According to Microsoft's [Windows Server major versions by servicing option](https://learn.microsoft.com/en-us/windows/release-health/windows-server-release-info#windows-server-major-versions-by-servicing-option--)
- Windows Server 2025 was released for general availability on Nov 1, 2024
[GitHub Actions Runner Images](https://github.com/actions/runner-images) lists the availability of Windows Server 2025 with the YAML label `windows-2025`
Add Windows Server 2025 (x64) to [Get Started > System requirements > Operating …

Add Windows 2025 to supported OS list

---

docs/api/commands/shadow.mdx

The documentation for `Shadow` suggests that it's valid to pass `{position: 'top'}` to `cy.click()`, however `cy.click()`'s documentation suggests the `position` parameter should be passed as a standalone string outside of the `options` object, and the `options` object does not include a field for `position`.
- Update the suggestion to pass `'top'` to `cy.click()` using the API defined in `cy.click()`'s documentation.
See
https://docs.cypress.io/api/commands/click

Correct parameter usage for click() in shadow.mdx

---

docs/api/cypress-api/custom-commands.mdx

Adds the missing `s` to `Cypress.Command.overwrite()`

Correct command syntax

---

docs/app/get-started/install-cypress.mdx

- partially resolves issue https://github.com/cypress-io/cypress-documentation/issues/6147
pnpm implements a [side effects cache](https://pnpm.io/npmrc#side-effects-cache) that uses and caches the results of (pre/post)-install hooks. This does not work if the effects of running the hook are outside the package's module. This is the case for the Cypress `postinstall` hook which installs the Cypress binary in a separate cache location (see [Binary cache](https://docs.cypress.io/app/references/advanced-installation#Binary-cache)). pnpm believes that it is unnecessary to run the Cypress `postinstall` hook and skips it if the Cypress npm module is already present in the pnpm store cache.
This is not documented on https://docs.cypress.io/ and it is only briefly referred to on …

extend pnpm config instructions

---

docs/api/commands/origin.mdx

The [cy.origin() API documentation](https://docs.cypress.io/api/commands/origin) section [Yielding a value](https://docs.cypress.io/api/commands/origin#Yielding-a-value) contains the following example code:
---
Values returned or yielded from the callback function **must** be serializable
or they will not be returned to the primary origin. For example, the following
will not work:
**Incorrect Usage**
```js
cy.origin('https://example.cypress.io', () => {
cy.visit('/')
cy.get('h1') // Yields an element, which can't be serialized...
}).contains('CYPRESS') // ...so this will fail
```
Instead, you must explicitly yield a serializable value:
**Correct Usage**
```js
cy.origin('https://example.cypress.io', () => {
cy.visit('/')
cy.get('h1').invoke('textContent') // Yields a string... …
```

fix cy.origin() "yielding a value" example

---

docs/app/references/changelog.mdx

adds the cypress `14.3.1` changelog

chore: add 14.3.1 changelog

---

docs/app/references/configuration.mdx
docs/app/references/migration-guide.mdx

- PR https://github.com/cypress-io/cypress-documentation/pull/6131 changed the planning statement that the configuration option [injectDocumentDomain](https://docs.cypress.io/app/references/configuration#injectDocumentDomain) would be removed in Cypress 15 to instead state that it would be removed in a future version.
This has led to some inconsistencies in the statements:
1. The [References > Configuration > injectDocumentDomain](https://docs.cypress.io/app/references/configuration#injectDocumentDomain) section contains contradictory statements:
> This option is deprecated, and will be removed in Cypress. 15
...
> This configuration option is provided to ease the transition between cy.origin()'s behavior in Cypress 13 and the default behavior in Cypress 14. It will be removed in a future …

docs: harmonize on injectDocumentDomain removal in future version

---

docs/app/references/changelog.mdx
docs/app/tooling/typescript-support.mdx

Reflects the work done in https://github.com/cypress-io/cypress/pull/31520 which replaces `ts-node` with `tsx` to parse and run the end user `cypress.config.ts` 
I also bumped the minimum TypeScript version from 4 to 5 which I missed in https://github.com/cypress-io/cypress/pull/31492 where this covers e2e as well..
Also bumped some of the minimum targets from es5 to es6 as es6 is widely available as of 2025

chore: update typescript docs to tsx

---

docs/api/commands/origin.mdx

The [API > origin > How to Test Multiple Origins](https://docs.cypress.io/api/commands/origin#How-to-Test-Multiple-Origins) contains a link to a YouTube video
https://www.youtube.com/watch?v=8tYoopVaWLE
that says (4:53) `experimentalSessionAndOrigin` must be set to true.
`experimentalSessionAndOrigin` was however removed in release
12.0.0
Removed experimentalSessionAndOrigin and made it the default behavior. Added experimentalOriginDependencies.
Add note to refer to [Cypress 12.0.0 release notes](https://docs.cypress.io/app/references/changelog#12-0-0) that describe the removal of `experimentalSessionAndOrigin`.

Add experimentalSessionAndOrigin removed comment to origin video

---

docs/api/commands/origin.mdx
docs/app/references/configuration.mdx
docs/partials/_document-domain-workaround.mdx

The [API commands origin](https://docs.cypress.io/api/commands/origin) page refers to the configuration option `injectDocumentDomain` without linking to the [Configuration > injectDocumentDomain](https://docs.cypress.io/app/references/configuration#injectDocumentDomain) section, where additional important information, such as "Known Incompatibilities" is provided.
Similarly the [Configuration > injectDocumentDomain](https://docs.cypress.io/app/references/configuration#injectDocumentDomain) section does not link to the [cy.origin](https://docs.cypress.io/api/commands/origin) page.
Cross-link the usage of
- `injectDocumentDomain`
- `cy.origin()`
on the pages / sections
- [API commands origin](https://docs.cypress.io/api/commands/origin)
- [Configuration > …

Cross-link cy.origin and injectDocumentDomain

---

docs/app/references/changelog.mdx

adds the Cypress `14.3.2` changelog

chore: add cypress 14.3.2 changelog

---

docs/app/faq.mdx
docs/app/get-started/why-cypress.mdx
docs/app/guides/accessibility-testing.mdx
docs/partials/_accessibility-addon.mdx
docs/partials/_accessibility-premium-note.mdx
docs/partials/_ui-coverage-addon.mdx
docs/partials/_ui-coverage-premium-note.mdx
src/components/product-heading/index.tsx
src/theme/MDXComponents.js

Change 'add on' to 'premium solution' for UI Cov & a11y products

---

docs/app/references/migration-guide.mdx

Begins the migration guide for Cypress 15, which includes the node deprecations and angular 17 CT support removal and work arounds

chore: add beginning of migration guide for Cypress 15

---

docs/app/component-testing/angular/overview.mdx
docs/app/component-testing/get-started.mdx

makes Angular 18 the new minimum version

chore: update angular versioning to have 18 as minimum

---

docs/app/references/migration-guide.mdx

adds the migration guide for webpack 4 removal in Cypress 15

chore: add webpack 4 removal guide

---

docs/app/references/changelog.mdx

adds the `14.3.3` Cypress App changelog

chore: add 14.3.3 changelog

---

docs/app/continuous-integration/circleci.mdx
docs/app/guides/cross-browser-testing.mdx

- The current version of the [Cypress CircleCI Orb](https://github.com/cypress-io/circleci-orb) is [v4.1.0](https://github.com/cypress-io/circleci-orb/releases/tag/v4.1.0)
- Examples on the following pages are using Cypress CircleCI Orb v3 `cypress-io/cypress@3`:
- https://docs.cypress.io/app/continuous-integration/circleci
- https://docs.cypress.io/app/guides/cross-browser-testing
Update CircleCI pipeline examples to show `cypress: cypress-io/cypress@4` on the above pages.
No change is made to the internally used [.circleci/config.yml](https://github.com/cypress-io/cypress-documentation/blob/main/.circleci/config.yml) pipeline.
This should be addressed separately.

Bump Cypress CircleCI Orb to v4 in examples

---

docs/app/continuous-integration/overview.mdx
docs/app/references/advanced-installation.mdx

Reference is made to the introduction of the Cypress binary downloaded to the global system cache in Cypress `3.0` in:
- https://docs.cypress.io/app/references/advanced-installation#Binary-cache
- https://docs.cypress.io/app/continuous-integration/overview#Caching
The documentation concerns itself specifically with the current version of Cypress, 14, and in general only with non-legacy versions Cypress 10 and later. Describing the introduction of a feature within the stream of legacy releases < Cypress 10 is no longer relevant or necessary.
The information regarding introduction of a global binary cache per version is available for reference in the [Cypress 3.0.0 changelog](https://docs.cypress.io/app/references/changelog#3-0-0).
Remove the reference "As of version 3.0" from …

Remove binary download introduction reference to Cypress 3.0

---

docs/app/get-started/install-cypress.mdx

The [Fedora Linux Release Life Cycle](https://docs.fedoraproject.org/en-US/releases/lifecycle/) says:
> The Fedora Project releases a new version of Fedora Linux approximately every six months and provides updated packages (maintenance) to these releases for approximately 13 months.
| Fedora Linux release                                       | Status                |
| ---------------------------------------------------------- | --------------------- |
| [F42](https://www.redhat.com/en/blog/announcing-fedora-42) | Released Apr 15, 2025 |
| [F41](https://docs.fedoraproject.org/en-US/releases/f41/)  | Supported             |
| [F40](https://docs.fedoraproject.org/en-US/releases/f40/)  | EOL May 13, 2025      |
Reference [End of Life …

Bump lowest supported to Fedora Linux 41

---

docs/app/references/changelog.mdx

- [Writing Guidelines](https://github.com/cypress-io/cypress/blob/develop/guides/writing-the-cypress-changelog.md#writing-guidelines) specifies prepending the hash (`#`) character to GitHub issue and PR references
- The [Cypress Changelog 14.3.3](https://docs.cypress.io/app/references/changelog#14-3-3) contains links to PR https://github.com/cypress-io/cypress/pull/31631 that are missing the hash (`#`) character
Add the hash (`#`) to links for PR https://github.com/cypress-io/cypress/pull/31631 in the [Cypress Changelog 14.3.3](https://docs.cypress.io/app/references/changelog#14-3-3)

Add missing hash character on PR 31631 references

---

docs/app/references/launching-browsers.mdx

[References > Launching Browsers > Chrome Browsers](https://docs.cypress.io/app/references/launching-browsers#Chrome-Browsers) states:
> All Chrome* flavored browsers will be detected and are supported above Chrome 64, with the restriction that a minimum of Chrome 80 is required to use cypress open.
Higher up, on the same page, under [Browser versions supported](https://docs.cypress.io/app/references/launching-browsers#Browser-versions-supported) it states:
> Cypress officially supports the latest 3 major versions of Chrome, Firefox, and Edge. (For example, if the stable release of Chrome was 130, Cypress would officially support Chrome 128, 129, and 130.)
Given that the current [stable version of Chrome](https://chromereleases.googleblog.com/) is now `136`, the lowest version of Chrome …

Remove Chrome 64 and 80 minimum references

---

docs/api/commands/blur.mdx
docs/api/commands/clear.mdx
docs/api/commands/focus.mdx
docs/api/commands/pause.mdx
docs/api/commands/trigger.mdx
docs/api/commands/type.mdx
docs/api/commands/viewport.mdx
docs/api/cypress-api/catalog-of-events.mdx
docs/api/cypress-api/custom-commands.mdx
docs/app/tooling/code-coverage.mdx
docs/ui-coverage/guides/address-coverage-gaps.mdx

Close https://github.com/cypress-io/cypress-documentation/issues/6185

update examples to have them follow unsafe to chain conventions

---

docs/app/references/changelog.mdx

adds the app changelog for v14.4.0

chore: add app v14.4.0 changelog

---

docs/app/references/changelog.mdx

Changes [Changelog](https://docs.cypress.io/app/references/changelog) for Cypress `14.4.0`
1. Change header `14.4.0` to second level, so that it appears in the right-hand navigation and is available as a bookmark
2. Remove one space after `(`
3. Change https://docs.cypress.io/api/node-events/browser-launch-api#Add-browser-extensions to relative URL `/api/node-events/browser-launch-api#Add-browser-extensions`

Fix changelog 14.4.0

---

docs/app/get-started/install-cypress.mdx

Tried copy-pasting the command as-is, but didn't work on `pnpm 10.11.0`. Hence update to match the [docs](https://pnpm.io/cli/add#--allow-build)
```sh
~/src/nitor/nitor-com-web (run-with-kubernetes*) » pnpm --version
10.11.0
~/src/repo » pnpm --allow-build cypress add --save-dev cypress
 ERR_PNPM_ALLOW_BUILD_MISSING_PACKAGE  The --allow-build flag is missing a package name. Please specify the package name(s) that are allowed to run installation scripts.
~/src/repo » pnpm --allow-build=cypress add --save-dev cypress
```

Fix: fix pnpm --allow-build command example to actually work as is.

---

.circleci/config.yml
cypress/e2e/all_accessibility_pages.cy.ts
cypress/e2e/all_api_pages.cy.ts
cypress/e2e/all_app_pages.cy.ts
cypress/e2e/all_cloud_pages.cy.ts
cypress/e2e/all_ui_cov_pages.cy.ts

Speed up tests >8m to ~5 minutes

Break Up Tests

---

src/data/plugins.json

Hi all 👋 
Since we were faced with difficulties during our test implementation for a drag and drop related functionality, and after a lot of effort, we managed to find a solution that I thought would be great to share with the community. This plugin is especially useful when faced with problems such as:
- Trying to scroll an item within a virtual list where not all of the items are visible without scrolling
- React applications which use `react-beautiful-dnd` or similar packages which do not always pick up on mouse events (even though this package also implements a solution with mouse events, it does offer a way to consistently trigger the drag and drop functionality)
The plugin is made with an MIT license and offers two commands:
- `dragTo(targetElementLocator)`: Custom child command for …

Add "cypress-dragndrop-kit" to list of plugins

---

docs/app/continuous-integration/circleci.mdx

- The [Continuous Integration > CircleCI > Chrome Example](https://docs.cypress.io/app/continuous-integration/circleci#Chrome-Example) currently states:
> The `install-browsers` flag is used to install Firefox and Chrome to run your tests.
- Using `install-browsers: true` from the Cypress CircleCI Orb [cypress-io/cypress@4.2.0](https://circleci.com/developer/orbs/orb/cypress-io/cypress?version=4.2.0) release, and above, installs Chrome, Chrome for Testing, Edge, Firefox and the geckodriver
Update the browser list in [Continuous Integration > CircleCI > Chrome Example](https://docs.cypress.io/app/continuous-integration/circleci#Chrome-Example) to include Chrome, Chrome for Testing, Edge, Firefox and the geckodriver.

Add Chrome for Testing and Edge to CircleCI browsers

---

docs/ui-coverage/changelog.mdx
docs/ui-coverage/configuration/additionalinteractioncommands.mdx
docs/ui-coverage/configuration/allowedinteractioncommands.mdx
docs/ui-coverage/configuration/overview.mdx

Adding pages for `additionalInteractionCommands` and `allowedInteractionCommands`.

Adding pages for new UI Coverage configuration properties

---

.circleci/config.yml

- PR https://github.com/cypress-io/cypress-documentation/pull/6223 includes the text
> updates the node version in the repo to 22.15.1
Current CircleCI jobs are now running in two different Node.js environments `18.16.1` and `22.15.1`
| Job                            | image                                                   |
| ------------------------------ | ------------------------------------------------------- |
| build                          | `docker.io/cimg/node:22.15.1`                           |
| Run Algolia scraper            | `ubuntu-2204:2024.11.1` / `docker.io/cimg/node:22.15.1` |
| Lint JS/CSS/Markdown           | `docker.io/cimg/node:22.15.1`                           |
| Install & Persist To Workspace | `docker.io/cimg/node:18.16.1-browsers`                  |
| Run …

ci: update Cypress tests to Node.js 22.15.1

---

docs/cloud/account-management/data-storage-and-masking.mdx

Since intercepts are cleared before each test, update to use `beforeEach` instead of `before`.

docs: Update data-storage-and-masking.mdx

---

src/data/plugins.json

* Fix `Custom Commands` and `Custom Queries` links in description for `Custom Commands` section that was incorrectly pointing to preprocessor API docs
* `Amazon Cognito` was listed 3 times in `Authentication` section, removed the 2 duplications and added missing `Azure Active Directory` link based on: https://github.com/cypress-io/cypress-documentation/tree/main/docs/app/guides/authentication-testing

Update incorrect links in plugins.json

---

docs/app/get-started/install-cypress.mdx

- closes https://github.com/cypress-io/cypress/issues/32148
Firefox `141.0` and above is not compatible with versions of Cypress below [14.1.0](https://docs.cypress.io/app/references/changelog#14-1-0) and this is not specifically mentioned on https://docs.cypress.io/ (see https://github.com/cypress-io/cypress/issues/32148).
The [Get Started > Install Cypress > System requirements](https://docs.cypress.io/app/get-started/install-cypress#System-requirements) section lists only base system requirements without mentioning browsers. For browser information, readers have to find and consult with the page [References > Launching Browsers](https://docs.cypress.io/app/references/launching-browsers) where the Firefox version restriction is however not mentioned.
The related section [References > …

Add browser support section

---

docs/app/references/changelog.mdx

[Managing the Release Changelog](https://github.com/cypress-io/cypress/blob/develop/guides/writing-the-cypress-changelog.md#writing-guidelines) contains guidelines in the form of linked examples for formatting versions. These have not been consistently followed.
The example for dependency updates is cited as https://docs.cypress.io/app/references/changelog#7-2-0
Some [semver style versions](https://github.com/npm/node-semver/blob/main/README.md#versions) (`X.Y.Z`) in the [Changelog](https://docs.cypress.io/app/references/changelog) are written in plain text, although they are mostly enclosed in Markdown code backticks.
Regressions are inconsistently handled and do not always follow the guidelines in [Managing the Release Changelog](https://github.com/cypress-io/cypress/blob/develop/guides/ …

Harmonize changelog semver style version and range quoting

---

docs/app/references/changelog.mdx

Adds the Release `15.0.0` Changelog to the `release/15.0.0` branch

chore: add Release 15.0.0 changelog

---

docs/app/references/changelog.mdx

Fix some minor typos in the [docs/app/references/changelog.mdx](https://github.com/cypress-io/cypress-documentation/blob/main/docs/app/references/changelog.mdx) document.
- Relates to https://github.com/cypress-io/cypress/pull/32190#issuecomment-3191840019 submitted by @adamalston

Correct some changelog typos

---

docs/api/commands/press.mdx

These keys are browser shortcuts, and can cause subsequent tests/specs to fail if pressed in Firefox.
Effort towards supporting them should be made if there is high enough demand.

docs: remove F-keys from cy.press() documentation

---

docs/app/references/changelog.mdx

chore: add the 15.1.0 changelog to `release/15.1.0`

---

docs/api/commands/press.mdx
docs/app/references/changelog.mdx

contains the release `15.1.0` documentation

release: 15.1.0

---

src/css/custom.scss

fixes header styles that were working before due to `15.4.0` fixing a syntax error, which in turn applied a style we do not want

chore: fix headers
