- source/guides/references/assertions.md
#	source/guides/references/assertions.md
> Update assertion examples to use $el instead of things like $('body') in examples. #76 

- source/api/commands/clock.md
Just a small typo in the cy.clock() documentation. Comment read march when the code was for February. I changed it to match.
> Typo in Date Object

- PLATFORMS.md
#117 
[x] Add Cypress' supported OS version readme
> 117 Add supported Platforms

- source/api/events/catalog-of-events.md
- source/faq/questions/dashboard-faq.md
- source/faq/questions/general-questions-faq.md
- source/faq/questions/using-cypress-faq.md
- source/guides/references/changelog.md
- uncaught exceptions
- test failures
- page navigation
- window before load
- window confirm
- window alert
> add examples for binding to Cypress events

- source/guides/getting-started/testing-your-app.md
This should be an error when running JavaScript in ES5 "strict mode," because implicit variables in JavaScript become globals. It's a small thing, but having the declaration (const/let/var, whichever -- although I've used `const` out of preference), will hopefully reduce confusion for beginners (who should expect all variables to be declared!) and make the code more idiomatic.
> Please don't use implicit variable declarations!

- source/dashboard/overview/projects-dashboard.md
- source/dashboard/overview/runs-dashboard.md
- source/faq/questions/dashboard-faq.md
- source/guides/guides/command-line.md
- source/guides/guides/continuous-integration.md
- source/guides/references/configuration.md
- add gif of entire setup
- clean up steps to set up
- merge recording and ‘setting up to record’ into one workflow
- titleize headings
- replace ‘Desktop GUI’ wording with ‘Test Runner’
> Update 'setting up projects to record' to be more clear with the new 1.0 workflow

- circle.yml
- cy_scripts/deploy.js
- package-lock.json
- package.json
- replace gift get branch with `deploy-bits` `getBranch`
- stop making dummy commit after deploying
- update `package-lock.json` file
> Get branch without using gift

- source/tutorials/build-and-test-todo/introduction.md
- source/tutorials/build-and-test-todo/project-setup.md
- source/tutorials/build-and-test-todo/testing-inputs.md
- themes/cypress/languages/en.yml
- themes/cypress/layout/video.swig
- themes/cypress/source/css/_partial/page.scss
- add box shadow + margin to videos
- move ‘what you’ll learn below videos’
- add specific ‘video’ layout that displays videos as larger
- remove most of content from introduction :grimacing:
- add a ‘contents’ section to main page.
> Updates to tutorials structure

- source/guides/getting-started/installing-cypress.md
- source/guides/guides/continuous-integration.md
- source/guides/references/changelog.md
Document option released in 1.0.3
> document CYPRESS_BINARY_VERSION close #121

- source/tutorials/test-a-react-todo-app/introduction.md
- source/tutorials/test-a-react-todo-app/project-setup.md
- source/tutorials/test-a-react-todo-app/testing-inputs.md
- Numbered videos
- Changed "What you'll learn" to "What's covered" for individual tutorial pages
> Numbered videos and updated summary title to whats covered

- source/guides/getting-started/installing-cypress.md
closes #200, closes #218 and closes cypress-io/cypress#866
* npm install section clarification
- what is the npm package
- best practice highlighted
* direct download section precisions
- what is exactly downloaded as the user didn't knew it exactly
* new CDN Structure section
- CDN url pattern
- it give to the user enough informations to download Cypress in the wanted
version for the wanted platform (could download a linux Cypress version from
a windows workstation)
- example
* Advanced section
- warning added about CLI output when running cypress
> Installing Cypress  guide improvment

- themes/cypress/source/css/_partial/search.scss
**Issue**
In Safari, the search input field is white.  Since the text color of the search field is also white, the user cannot see the search string being entered.
**Fix**
To overcome default webkit search field styling, change the appearance property to be a textfield and then applied the same background color as the header.
> Search background in safari

- source/api/commands/fixture.md
Fixture API doc to reflect https://github.com/cypress-io/cypress/pull/924 behavior change (stop formatting and saving fixtures)
Should be merged only after PR review.
> Fixture API doc to reflect cypress PR 924

- source/api/commands/stub.md
This addresses #193. I followed the pattern of the "Stubbing window.fetch" example recipe to make the change before the app runs.
Also, thank you folks for being friendly to new contributors. The "first-timers-only" label of this issue is what made the difference for me between starting 24 pull requests or not.
> Add window.prompt stubbing example to api section

- source/api/cypress-api/custom-commands.md
> Missing comma in login parent command example

- source/_data/plugins.yml
Some users might be misled to believe they need the `watch` preprocessor for Cypress to watch their files. This makes it clearer that the `browserify` and `webpack` preprocessors watch your spec files as well as bundle them.
> Update preprocessor descriptions to specify they watch files

- source/guides/core-concepts/writing-and-organizing-tests.md
Link to the recommendation not to use the anti-pattern of cleaning up state with after()/afterEach()
> Reference recommendation not to use after(Each)

- source/guides/guides/debugging.md
Just one link for now... Can't embed with a timestamp yet, so for now, it's a link out to vimeo.
Mostly wanted to get feedback before adding more of these. I'll look into adding the Vimeo JS api to the project so we can control the embeds as a separate effort.
> Added vimeo link to debugging guide

- source/guides/core-concepts/introduction-to-cypress.md
Just a quick link update, `contains` method heads to `get` in the **Default-Assertions** https://docs.cypress.io/guides/core-concepts/introduction-to-cypress.html#Default-Assertions
> Update command link

- source/api/cypress-api/custom-commands.md
Include statement to un-comment line in index.js in order to import command.js.
Reference:  https://stackoverflow.com/questions/47695535/cypress-custom-command-is-not-recognized-when-invoked/47707642#47707642
> Remove wording that command.js is loaded automatically

- source/guides/guides/command-line.md
To enable Windows debugging, you have to set the environment variable differently. Improved documentation for Cypress (and instead of relying on looking at visionmedia/debug) will be helpful.
> update to include Windows debugging

- source/guides/core-concepts/introduction-to-cypress.md
> Missing punctuation

- source/guides/guides/continuous-integration.md
Since i get this issue in circleci
```
+
TEST
Spin up Environment00:01
Checkout code00:00
npm install02:17
$(npm bin)/cypress run --record00:09
Exit code: 1
#!/bin/bash -eo pipefail
$(npm bin)/cypress run --record
npm info it worked if it ends with ok
npm info using npm@3.10.10
npm info using node@v6.11.1
npm info ok 
It looks like this is your first time using Cypress: 1.4.2
[01:25:47]  Verifying Cypress can run /var/www/node_modules/cypress/dist/Cypress [started]
[01:25:49]  Verifying Cypress can run /var/www/node_modules/cypress/dist/Cypress [completed]
Opening Cypress...
You passed the --record flag but did not provide us your Record Key.
You can pass us your Record Key like this:
cypress run --record --key <record_key>
You can also set the key as an environment variable with the name …
```
> Improve docs continuous integration using Circleci

- source/guides/references/changelog.md
This seems to be a pattern, considering https://github.com/cypress-io/cypress-documentation/pull/411/commits/2515ede39198fcfd59e179ab3ea9b0d1aec906de 😂
> Fix 2.0.0 release date year

- source/guides/core-concepts/introduction-to-cypress.md
Maybe a bit picky, but this changes the _first_ instance of the term 'subject' to be quoted, not the second.
> Changed first instance of "subject" to be quoted

- source/guides/references/trade-offs.md
The file referenced no longer exists (so the link isn't showing at all). I couldn't find a suitable replacement so I've removed it.
> Removed broken link

- source/guides/guides/launching-browsers.md
add 'Firefox', 'Safari', and 'Internet Explorer' to Unsupported Browser heading
> add keywords to return algolia search results

- source/api/commands/route.md
This example made me think that the Method was ignored when matching the URL.
cypress-io/cypress#1471
> Add clarity to first example of Without Stubbing

- source/guides/guides/command-line.md
I found a repeated word "spec spec", and added some other clean-ups to increase the value of the PR. I've tried to avoid any opinionated changes, but please let me know if I should change something.
- No connected # issue, just maintenance.
Thanks for making Cypress; I'm very excited about it and will be increasingly using it. Keep up the good work!
> Typography update

- source/guides/guides/screenshots-and-videos.md
The "Screenshots and Videos" guide mentions setting the `trashAssetsBeforeHeadlessRun` configuration, which caused some confusion when it didn't work… Then I clicked through to the configuration guide and noticed that the option is really `trashAssetsBeforeHeadlessRuns` plural. Oops!
> Fix a configuration option typo

- source/faq/questions/using-cypress-faq.md
Just a small typo fixed in "Is is possible to catch the promise chain in Cypress?" question in FAQ.
> Small FAQ typo fix: "Is is possible..." to "Is it possible..."

- source/_data/plugins.yml
Submitting my ESLint preprocessor plugin, please see the GitHub link for information on it
https://github.com/chinchiheather/cypress-eslint-preprocessor
> Add eslint preprocessor to plugins page

- source/api/commands/eq.md
Add searchable keywords nth and row to .eq doc
> Include searchable keywords 'nth', 'row'

- source/api/commands/trigger.md
Looking for best place to land jQuery UI sortable example
The only place I can see in the `.tirgger` docs to add this is under the existing Drag and Drop header, however, we link to a recipe and I'm worried about uniformity in the doc. 
Would it be out of place to throw in an example here or would it be okay?
> add jQuery UI Sortable WIP

- source/api/cypress-api/custom-commands.md
I noticed a syntax error on the Custom Commands page, the Custom console command section, the current block states:
```javascript
cy.get('button').console('info').then($button) => {
// subject is still $button
})
```
It should read:
```javascript
cy.get('button').console('info').then(($button) => {
// subject is still $button
})
```
> [Typo] Fix syntax error in Usage example for Custom Commands page

- source/faq/questions/general-questions-faq.md
- source/faq/questions/using-cypress-faq.md
Remove article 'a' from Capybara section 
Move statements about Sauce Labs integration to the bottom, wrap in info box, and use explicit language that integration is not currently available.
This would address one half of issue #553, leaving adding a question to Using Cypress FAQ that would answer the question definitively and potentially link to this General Question and/or issue #310 
This request requires feedback. I will leave a comment on the issue requesting it.
> fix typo/rewrite Sauce Labs section to be explicit/add Q to using-cypress faq

- source/guides/getting-started/installing-cypress.md
> CLI Caching 

- _config.yml
- themes/cypress/layout/partial/head.swig
- Convention states we reference ‘cypress.io’ as ‘cypress’ when
participant is already aware of cypress product
- Add Cypress to title for help with bookmarks, etc.
- close #610
> Append config title to page title or subtitle - replace cypress.io w/ cypress

- source/guides/guides/network-requests.md
Update the 'Requests' section regarding Cypress default behavior of ignoring requests that fetch static files. Change link to direct to documentation for cy.server() options.whitelist.
> Update link in requests section

- source/faq/questions/using-cypress-faq.md
Zoops. I tested this locally, somehow that little sucker `.` jumped around 😉
> move punctuation [.] outside of hexo formatting

- source/faq/questions/using-cypress-faq.md
found `'` in url, this must be breaking formatting. need new 🤓eye glasses prescription 😧
> fix formatting

- source/api/commands/not.md
Used same html mark up from `filter` doc. Changed assertion to length instead of class, but how do you feel about that? I think it works. I wanted to use `should` and `and` but it felt too lengthy.
> add html example to .not assertion

- source/guides/guides/continuous-integration.md
need node version 10 on travis and circle v1 for the `npm ci` command
> update ci docs

- source/guides/guides/command-line.md
- source/guides/references/changelog.md
> quotes around --spec argument in examples

- source/guides/guides/continuous-integration.md
Fix broken link, maybe?
Strangely enough, my local was broken too, though the formatting was correct. Commenting out and uncommenting out the hexo link updated it on my local. 
I wasn't able to commit a change without altering a line of code, so I used  `'`single quotes`'` to make my commit, but I can't be sure it will fix this broken link since it was _always_ properly formatted.
> fix broken link

- source/api/commands/get.md
Replaced `cy.fixtures` with `cy.fixture` (as it should be)
> Closes #718 - cy.fixture typo

- source/api/commands/should.md
First of all: I recently started using Cypress and it already feels like the best solution for tests I have ever tried. Great work!
I stumbled upon something in the documentation of `.should()`:
In the "yields" section about chainers changing the subject the text speaks about a second `.should()` whilst the code example only shows one `.should()` and two usages of `.and()`. Either the code example could be adapted (as in this PR) or alternatively the text could be changed mentioning the usage of `.and()` here.
> Update should.md (fix docu about yields)

- source/api/events/catalog-of-events.md
This example causes "Assignment to constant variable" error.
> Use let instead of const in examle

- source/api/commands/eq.md
#744 
Document example referenced Index 2 of a list which is the 3rd element, not the 2nd element.
> Fix small typo

- source/guides/guides/command-line.md
- Remove duplicate example with failure
- update spec to be a spec from our kitchen-sink so they could run
right away.
- close #769
> update returned Promise of API module to reflect what data actually looks like.

- package-lock.json
- source/api/commands/log.md
Added a line to the 'Arguments' section of the 'log' documentation noting that Markdown formatted messages are valid. Closes issue #778
> Added  Markdown ability to 'log' doc

- source/api/commands/focus.md
- source/api/cypress-api/custom-commands.md
- source/guides/core-concepts/conditional-testing.md
- source/guides/core-concepts/variables-and-aliases.md
With apologies for this slow drip of typos 😳
> We're doing a lot of Cypress at the mo' and I'm reading the docs top to bottom.
> Fix typos around 'it is'

- source/guides/getting-started/writing-your-first-test.md
The videos on this page use sample_spec.js as the filename, but the doc says simple_spec.js. I updated to sample so they're consistent.
> Update sample spec filename

- cypress/integration/api_spec.coffee
- cypress/integration/guides_spec.coffee
- The initial performance issues for these tests has been resolved in
Cypress - https://github.com/cypress-io/cypress/issues/431
- creating PR to ensure headless run is :thumbsup: too
> Add back tests for Table of Contents link checks

- CONTRIBUTING.md
Address #55 _Add more detail to Contributing doc so users can easily contribute_
I've been intentionally brief here. What I've added would have been sufficient for me to crack on with the process of contributing documentation.
> This doesn't completely address #55: I haven't documented how to use Cypress to test the documentation nor how to add Hexo. One step at a time and all that.
> Document the process of contributing pages

- source/guides/guides/continuous-integration.md
- close #837 
Adds links to example repo and direct CI config file, so it looks like this
> add links to CI repos, close #837

- source/guides/references/changelog.md
- themes/cypress/source/js/toc.js
Addresses #46 
> The only remaining weirdness with menuspy is on the Changelog page. The highlighting of the righthand nav does not match the scrolling position AT ALL and requires some investigation.
Yeah. Upon investigation I found two things:
* the heading structure of the Changelog source was inconsistent.
* MenuSpy wasn't calculating the offset correctly.
I have changed:
* the Markdown source code for the Changelog to be at a consistent level.
* overridden a MenuSpy function so that offsets are calculated correctly.
This "works" in both of the browsers I've tested against: Chrome (latest `68.0.3440.106`) and Safari (`11.1.2`).
> [#46] Make MenuSpy work correctly on the Changelog page

- source/api/cypress-api/selector-playground-api.md
Addresses #468
> The Selector Playground is not showing up in the search results (something we are tweaking).
Seems to be showing up nicely now in both the Google and DuckDuckGo search engines.
> [#468] Hyperlink Selector Playground API to test runner guide

- cypress/integration/guides_spec.coffee
- themes/cypress/layout/page.swig
- themes/cypress/source/css/_partial/toc.scss
Addresses #846
* we're in the `<h3>` section _We recommend users_
* the parent `<h2>` section is **not** highlighted in the sidebar
* we're in the `<h3>` section _We recommend users_
* the parent `<h2>` section **is** highlighted in the sidebar
> [#843] TOCs h2 is highlighted when in child h3

- source/api/commands/contains.md
- source/api/commands/submit.md
Addresses #123
Kinda... the docs in that area already seemed pretty clear and complete to me. I've added another example of using the selector.
I _could_ add yet more examples but I dunno that that'd improve the existing docs... it'd just make 'em longer. Open to a steer here 😄
> [#123] Add another example of using the selector in cy.contains()

- source/api/commands/type.md
> [565] Document .type()'s supported elements

- CONTRIBUTING.md
Despite having used GitHub for years I've never used GitHub's issue tracker... it's always been JIRA wherever I've worked. As such I didn't know about the feature whereby you can add text to your PR that'll [automatically close](https://help.github.com/articles/closing-issues-using-keywords/) the attendant issue(s) if the PR is merged.
Doh! :blush: Happily, Jennifer shared the knowledge about this feature so that I no longer have to darken her inbox with folderol about _"Can this issue be closed?"_
This PR does two things:
* makes this feature explicit in the contribution guide.
* trojans this PR to close some old tickets.
> _ima kno all teh kung fu!!1!_
* closes #565 :: _Update .type doc to include list of supported type elements_
* closes #468 :: _Link SelectorPlayground API docs to …
> Add clear instruction about how to write PRs that'll close issues

- source/guides/references/configuration.md
I've been bumping against this, and stumbled across [this comment](https://github.com/cypress-io/cypress/issues/1657#issuecomment-386068530) that explains the behavior I'm seeing. It seemed worthy of a note in the docs.
> Add note about page load timeouts

- source/api/commands/route.md
- source/api/commands/server.md
closes #564
> This change isn't as trivial as I thought originally 'cos there are a few places in the docs that have "incorrect" info. I'm scare quoting there because I'm now doubting my own understanding of the behaviour in light of the docs: I'm writing some (more) tests to prove the behaviour.
I verified the behaviour locally: routes that are _not_ matched will, by default, just pass through to the server.
> [#564] Tighten docs around force404 behaviour

- source/api/commands/route.md
> [#217] Emphasize that GET is the default method for cy.route

- lib/tags/note.js
`Minor`
Adds support for using Markdown in the header of a `{% note %}` tag.
> Add support for notes with Markdown in the header

- lib/tags/url.js
- source/faq/questions/using-cypress-faq.md
Closes #663 
Right, so this is a _pragmatic_ tactical fix for an issue that's manifest on the Cypress documentation site right now: "blank" hyperlinks leading to malformed sentences.
* https://docs.cypress.io/guides/getting-started/installing-cypress.html#Continuous-Integration
Notice how the link to the `npx` module on NPM is missing from the generated text.
* https://docs.cypress.io/faq/questions/using-cypress-faq.html#How-do-I-wait-for-my-application-to-load
The following example is the one originally reported by Valerie in #663 
Notice how the link to the `wait-on` module on NPM is missing from the generated text.
With the change from this PR in place the above docs are generated correctly.
This was spotted in #663 and attributed to errant punctuation: however, the root cause is …
> [#663] Generate links even when validation fails

- source/guides/core-concepts/dashboard-service.md
A missing quote was causing a couple of sections to not be generated.
There's supposed to be a couple of sections here before the _Test Failures_ section... they're missing.
The sections are now present in the generated documentation.
> Display sections that were hidden because of missing quote

- source/404.md
- themes/cypress/source/css/_partial/base.scss
- themes/cypress/source/css/_partial/media_queries.scss
Closes #291 
I just followed @bahmutov 's instruction by adding some helpful links to the `404` page.
I also styled the `404` page for both desktop and smaller devices.
> [#291] Make the 404 page somewhat more helpful

- source/api/commands/url.md
hard-coding the url is probably not the best way to do it. is this the way it should be?
> encourage the usage of baseUrl

- themes/cypress/source/css/_partial/media_queries.scss
- themes/cypress/source/css/_partial/search.scss
closes #743
The clickable search box has been expended to fill it's wrapper by giving it explicit width (minus the width of the search icon).
The autocomplete drop-down has been made to keep the original width in screen width from 1001 - 620px since the original size can't go outside the window before the 620px breakpoint this looks better.
(The autocomplete drop-down is to far from the text without this in some screen widths because it is right aligned)
> Issue [#743] search input box misleading

- source/api/commands/route.md
- source/api/commands/should.md
- source/api/commands/then.md
- source/api/cypress-api/custom-commands.md
Noticed some inconsistency in a few of the code examples and a few syntax issues.
- Updated `=>{` to `=> {`
- Updated broken example in custom-commands example.
- Missing commas in route example
> Fixing and adjusting syntax in a few code examples

- source/api/commands/viewport.md
In the comment describing the iphone-6 width, there was a typo. This change fixes it. 
Should be 375px not 357px. 
375px is correct according to actual Cypress behavior and as widely [reported](http://viewportsizes.com/?filter=iphone) as the iPhone 6 viewport size.
> Fix incorrect iphone-6 widthin comment

- lib/tags/note.js
Right, I was sufficiently bugged by this to investigate it.
It looks to be a bug in the Markdown library that Hexo uses. ([`marked`](https://marked.js.org/#/README.md))
Even though the SmartyPants "spec" says that content inside a `<code>` block is not to be SmartyPants-ed, I have tested a small file against the library directly and it _does_ SmartyPants-ify content in such blocks:
Input
```md
--report <code>--report</code>
```
Output
```html
<p>–report <code>–report</code></p>
```
Code that is fenced in backticks doesn't exhibit the same behaviour:
Input (some Markdown)
```md
--report `--report`
```
Output
```html
<p>–report <code>--report</code></p>
```
Right, onto the Cypress code. We have content with nested tags:
```md
{% note info %}
`--report` {% url `--report` foo.html %}
{% …
```
> [#923] Fix mutton and nut substitution in notes

- source/guides/references/trade-offs.md
This generally references the [window.fetch recipe](https://github.com/cypress-io/cypress-example-recipes/tree/master/examples/stubbing-spying__window-fetch/cypress/integration) but I could see wanting to reference a specific file.
> Update dead link in trade-off reference

- source/guides/references/_best-practices.md
- source/guides/references/best-practices.md
I'm not sure why but starting a line with `{% .. %}` makes the header in its below section (`## Setting a global baseUrl`) become a normal text.
I fixed it by rephrasing the sentence so that it start with some other word. (65ba94a)
**This PR also:**
- Remove unused example page, the actual page already exist 45586a8
- Add a missing link for command reference 9066777
- Add more explanation for why command in `cy.exec` or `cy.task` has to exit e6a09d2
Before | After
--- | ---
> Fix broken link in best practice page

- source/api/commands/clearcookies.md
- source/api/commands/clearlocalstorage.md
Clarified that LocalStorage and ClearCookies only clear work on the current domain and subdomains. closes #1034
> Documented cy.clearLocalStorage and cy.clearCookies only clearing domain

- source/api/commands/clock.md
The current documentation claims that the `now` parameter should be a `Date`, but the examples (and [the test suite](https://github.com/cypress-io/cypress/blob/b2e7148dbef87289336bdbaf39020d22a5544d1f/packages/driver/test/cypress/integration/commands/clock_spec.coffee#L30)) show that it actually expects the UNIX timestamp as a `number`. When we tried to use a `Date` object, we always ended up at the start of the UNIX epoch.
> Correct API documentation for clock command

- source/_data/talks.yml
This fixes the link that should be used to go directly to the video rather that the full day stream.
closes #1057
> fix(talks): Fixes link to ReactiveConf YouTube

- source/guides/getting-started/installing-cypress.md
There were already instructions for installing Cypress with Yarn, this PR just adds instructions for running Cypress with it.
The result is similar (it runs `./node_modules/.bin/cypress open`).
> Add instructions for running Cypress with Yarn

- source/guides/core-concepts/test-runner.md
This fixes a typo in the introduction of the AUT acronym.
> Add a closing parens

- source/api/commands/route.md
The previously linked example [HTML Web Forms](https://github.com/cypress-io/cypress-example-recipes/blob/master/examples/logging-in__html-web-forms/cypress/integration/logging-in-html-web-form-spec.js) doesn't contain usage of `cy.route`.
Fixed it to point to [XHR-Web-Forms](https://github.com/cypress-io/cypress-example-recipes/blob/master/examples/logging-in__xhr-web-forms/cypress/integration/logging-in-xhr-web-form-spec.js), which has the mentioned POST using route example.
> Point to correct example project

- lib/tags/aliases.js
- package-lock.json
- scripts/tags.js
- source/guides/references/assertions.md
- themes/cypress/source/css/_partial/page.scss
Minor changes adjacent to #967 and 4.0/Chai upgrade, but none of these changes are related to changes themselves and are relevant in the current version. 
Biggest change is the addition of the aliases tag and removal of aliases in the chai TDD table. Totally down to change that back to the way it was if it seems preferable, but thought I'd give a go reducing the number of things in the table.
> Updates to assertions page

- source/api/commands/clock.md
Month numbers are 0-indexed in JS Dates, which means that `new Date(2017, 3, 14)` creates a date in **April** and not March.
> Fix wrong comment regarding new Date() in docs

- source/guides/guides/continuous-integration.md
This PR tackles few modifications to the [Continuous-Integration](https://docs.cypress.io/guides/guides/continuous-integration.html) documentation
- Update environment variables in 
- Renamed `Other Configuration Values` to `Configuration Values`
- Placed `Record Key` under `Configuration Values` (does that make sense?)
- Add section for git info in continuous-integration.md, which closes #1176
> Add instructions to collect git related info using environment variables

- source/guides/guides/continuous-integration.md
- Split into ‘setup’ ‘examples’ and ‘advanced’
- Fix some grammar
> Rearrange CI doc to have more scannable sections

- source/_data/talks.yml
- closes #1195
to include slide link in the talk video, use property `slides: <url>` in the talks.yml like 
```
- title: Testing Vue with Cypress
url: https://www.youtube.com/watch?v=uowaTHQDcKc
sourceName: VueNYC meetup
sourceUrl: https://www.meetup.com/vueJsNYC/events/254789852/
date: Dec 6, 2018
author: Gleb Bahmutov
youtubeId: uowaTHQDcKc
slides: https://slides.com/bahmutov/end-vue-end-testing
```
> include links to slides for many presentations

- scripts/helpers.js
- themes/cypress/layout/plugins.swig
so we can refer to specific types of plugins and send a link. Might look better with a little bit of styling
- closes #1257
> Add anchors to plugin types 1257

- source/api/commands/first.md
I think that the explanations should be about `first` rather than about `find`.
> Fix mistake

- source/_data/plugins.yml
- themes/cypress/layout/plugins.swig
- closes #1266 
Also adds optional description to plugins section
> add component testing plugins, close #1266

- source/api/commands/should.md
- source/guides/core-concepts/introduction-to-cypress.md
Addresses https://github.com/cypress-io/cypress/issues/205.
I'm unsure of styleguide, technical correctness etc. (see below). Changes welcome.
- I've changed the strong wording of `You **never** need to write` → `You don't need to write`, because it's not strictly true.
- I'm not sure the statement:
> When you chain `.should()` on a DOM-based command, the default `.should('exist')` assertion is skipped
is *technically* correct (I've only skimmed [`asserting.coffee`](https://github.com/cypress-io/cypress/blob/develop/packages/driver/src/cy/commands/asserting.coffee) and [`assertions.coffee`](https://github.com/cypress-io/cypress/blob/develop/packages/driver/src/cy/assertions.coffee) and haven't quite figured it out), but it seems *practically* correct.
- I haven't yet managed to run docs …
> clarify effect of should command on implicit DOM assertions

- source/api/commands/url.md
Looks like a copy and paste replacement got missed
> Update url documentation "typo"

- source/_data/plugins.yml
* Adding [Knapsack Pro Cypress](https://github.com/KnapsackPro/knapsack-pro-cypress) plugin to Development Tools.
* Keep alphabetical order of plugins.
> Add Knapsack Pro Cypress plugin

- source/guides/core-concepts/introduction-to-cypress.md
Fix an error in documentation for introduction to cypress page.
> Fix error in introduction to cypress page

- source/_changelogs/1.4.2.md
fixes duplicate issue references in one of the changelog files
> fixed duplicate issue referenced in changelog 1.4.2

- source/guides/guides/debugging.md
- source/guides/guides/launching-browsers.md
This addresses part of #1378 
This documentation will change as progress is made on cypress-io/cypress#3202, but this PR is correct for the currently released Cypress
> Add debug guidelines for browser detection on different OS's

- lib/tags/partial.js
- source/_partial/network_stubbing_warning.md
- source/api/commands/route.md
- source/api/commands/server.md
- source/api/commands/wait.md
- source/guides/guides/network-requests.md
Closes #1391
Had to modify the `partial` tag so that it would support using the `note` tag inside of a partial, so that's why that's there
> Clarify that non-XHRs won't be intercepted

- source/_data/sidebar.yml
- source/api/events/all-events.md
- source/api/events/internal-log-event.md
- source/api/events/internal-logchange-event.md
- source/api/events/log-changed-event.md
- source/guides/references/migration-guide.md
- themes/cypress/languages/en.yml
> Document log event changes

- source/_data/plugins.yml
Adds a new authentication plugin type to the list of Plugins: [cypress-social-plugins](https://github.com/lirantal/cypress-social-logins)
> feat(plugins): add cypress-social-logins

- source/_data/plugins.yml
This PR adds the Cypress + Slack plugin to the Cypress.io documentation.
> feature(plugins): add cypress-slack-healthcheck plugin to docs

- source/guides/core-concepts/conditional-testing.md
This doesn't remove `.catch()` from the code examples in the Error Handling section, but it does make it clear the code is not valid and is for demonstration purposes only.
closes #789
> Update Error Handling documentation

- source/api/commands/then.md
Adds a note to `.then()` command to prefer `.should()` for assertions.
> Add 'Note' to prefer `.should()` for assertions

- source/api/commands/url.md
example url is http://localhost:8000/index.html but code snipped used http://localhost:8000//index.html
> fix typo in example url. two slash should be one

- source/_data/plugins.yml
Added `cypress-commands` to the list of plugins as requested by @jennifer-shehane in https://github.com/cypress-io/cypress/issues/3109
> Added cypress-commands to the list of plugins

- circle.yml
brings the new `cypress/base:8.15.1` Docker image
> use node 8.15.1 base image

- source/guides/references/proxy-configuration.md
We removed this to save ~20MB in the npm package, so the docs should be updated so users know what to do.
Related: cypress-io/cypress#3897
> Indicate that CLI does not look at system-wide Windows proxy settings

- source/guides/guides/command-line.md
While trying to get tests running, the documentation wasn't clear on what was needed, so wanted to make the document hint that there are interdependencies on the flags.
I was supplying just `--group` and got this:
```
We encountered an unexpected error talking to our servers.
There is likely something wrong with the request.
The --group flag you passed was: Windows/Electron
The server's response was:
StatusCodeError: 422
{
"code": "INDETERMINATE_CI_BUILD_ID",
"message": "CI Build ID could not be generated and was not specified."
}
```
I then figured out that I needed to supply a `--ci-build-id` flag.  However the free Cypress.io plan doesn't allow for grouping, so I removed `--group` leaving only `--ci-build-id` and got this:
```
You passed the --ci-build-id flag but did not provide …
```
> Update command-line.md with notes about --group

- source/examples/examples/recipes.md
Add reference to plugin that makes file upload testing easy.
Supports upload via plain HTML input components, framework-specific file inputs, drag-n-drops, etc.
Usage recipe is located inside: https://github.com/abramenal/cypress-file-upload/tree/master/example
Cypress examples PR: https://github.com/cypress-io/cypress-example-recipes/pull/272
> Add cypress-file-upload reference

- source/guides/core-concepts/introduction-to-cypress.md
**This pull request fixes the order of arguments for .map in code example**
Details:
https://docs.cypress.io/guides/core-concepts/introduction-to-cypress.html#Explicit-Subjects - jQuery map accept callback function with arguments `( Object elementOfArray, Integer indexInArray )` (http://api.jquery.com/jQuery.map/).
So, it should be
`$p.map((el, i) => {`
instead of
`$p.map((i, el) => {`
> Fixed the order of arguments for .map in example

- source/guides/getting-started/installing-cypress.md
This documents how to download the new 32-bit builds, as well as updates the section to document only the platforms and arches which should be used going forward.
Fixes #1568
> Update installing-cypress with new download URLs

- source/examples/examples/recipes.md
The `React with Enzyme` recipe pointed to a link that threw a 404. I updated it to the example i found in the `cypress-example-recipes` repo. Not sure if this also needs to be changed elsewhere or the description needs to be updated as i get this when running locally via `npm run start`
> fix broken link to react test example recipes

- _config.yml
https://docs.cypress.io/guides/core-concepts/aliases-and-references.html is from the old version of our docs but is still indexed in Google
> Add redirect for old slug of variables-and-aliases

- source/_data/plugins.yml
A lot of StackOverflow users had some difficulties in implementing a recursive promise with Cypress just to repeatedly check for something to happen (see two of the various questions about the topic: How can i wait for each element in a list to update to a certain text? And How do I wait until a cookie is set?). 
We wrote this plugin to file this kind of issues
> Add the cypress-wait-until plugin

- source/api/plugins/browser-launch-api.md
> Add 'Chromium' and 'Canary' to browser launch api doc to imply they're also supported

- source/api/commands/should.md
- source/guides/core-concepts/introduction-to-cypress.md
- source/guides/references/assertions.md
> document new focus assertion

- source/api/commands/server.md
Document the functions described here: cypress-io/cypress#3992
Should this include an example too?
> Document cy.server({ onAny* }) functions

- source/_data/plugins.yml
Adds the Cypress Daywalker plugin to the documentation.
I'm not sure about the category this plugin falls into. I've put it in the category `Framework Tooling` which isn't entirely right.
> Add cypress daywalker plugin

- source/guides/guides/continuous-integration.md
In response to this issue in the primary repo - https://github.com/cypress-io/cypress/issues/4069
Travis build environment(s) have been updated from running Ubuntu 14 to Ubuntu 16 which requires `libgconf-2-4` (Electron dependency which might be removed in future) to be installed manually.
Also xvfb must be installed/started manually as well it seems -- though unsure if Cypress itself does this when ran headlessly so this could be moot.
> Update Travis example re: Travis env. update

- source/_data/plugins.yml
Adds https://github.com/flotwig/cypress-log-to-output to plugins page
> Add cypress-log-to-output to plugins

- source/guides/getting-started/installing-cypress.md
The download link was HTTP and the HSTS configuration for domain cypress.io doesn't include subdomains, so directing to http for download would allow a network attacker to redirect to an infected copy or other malware.
> Change download link to use HTTPS

- source/api/cypress-api/config.md
Added a note to config.md re: some values cannot be changed at run-time. Details based on @brian-mann 's comments to https://github.com/cypress-io/cypress/issues/2100
> Added a note to config.md re: some values cannot be changed at run-time.

- source/api/commands/request.md
- source/api/commands/visit.md
Closes #1648 
I wonder if we should document the nature of the request retries under the hood. Probably not, since it should be transparent to the user?
> Document retryOnStatusCodeFailure, retryOnNetworkFailure

- source/_data/plugins.yml
`cypress-plugin-snapshots` belongs in the `Visual Regression` section
> Move cypress-plugin-snapshots entry

- source/api/commands/visit.md
> Clarify that cy.visit headers are only for initial request

- source/guides/references/migration-guide.md
> Add dropping CJSX support to 4.0 migration guide

- source/guides/core-concepts/test-runner.md
- source/ja/guides/core-concepts/test-runner.md
- source/zh-cn/guides/core-concepts/test-runner.md
Order of args was causing the src to be the alt text, and vice versa
> Switch order of args for imgTag (alt text <=> src)

- scripts/helpers.js
- themes/cypress/layout/api-toc.swig
- themes/cypress/layout/page.swig
- themes/cypress/layout/plugins.swig
- themes/cypress/layout/toc-top.swig
- themes/cypress/layout/video.swig
- Addresses #1686 
- Docs for next/prev now go to translated doc if on one currently
- Docs for main menus now go to translated doc if on one currently
- Docs for 'edit doc now go to correct GitHub link. Also made this target='_blank' to open in new tab
- Docs for api table of contents now go to translated doc if on one currently
> Update links within doc to go to correctly translated doc

- source/guides/guides/debugging.md
- source/ja/guides/guides/debugging.md
- source/zh-cn/guides/guides/debugging.md
> add instructions how to run the binary by itself, close #1781

- _config.yml
- cypress/integration/i18n_spec.js
- package-lock.json
- package.json
- source/guides/guides/command-line.md
Visiting https://on.cypress.io/command-line and seeing Chinese translation for some reason
> catch Mandarin language title in "Command Line" English guide

- source/examples/examples/recipes.md
make recipes point to github page instead of url hash, organized in a table separated by categories
based on this comment
https://github.com/cypress-io/cypress-documentation/pull/1805
> update to recipes page format

- source/api/commands/click.md
Change 'ATL' to 'ALT' - typo fix
> 'ALT' typo fix

- source/zh-cn/guides/core-concepts/introduction-to-cypress.md
Fix comma typo in the `introduction-to-cypress.md`
Here's a screenshot of what I was reading:
> Fix comma typo and extra spaces in the introduction

- .textlintrc
- package-lock.json
- source/_changelogs/0.11.8.md
- source/_changelogs/0.16.4.md
- source/_changelogs/0.6.5.md
- source/api/commands/type.md
- source/api/events/catalog-of-events.md
- source/ja/_changelogs/0.11.8.md
- source/ja/_changelogs/0.16.4.md
- source/ja/_changelogs/0.6.5.md
- source/ja/api/commands/type.md
- source/ja/api/events/catalog-of-events.md
- source/zh-cn/_changelogs/0.11.8.md
- source/zh-cn/_changelogs/0.16.4.md
- source/zh-cn/_changelogs/0.6.5.md
- source/zh-cn/api/commands/type.md
- source/zh-cn/api/events/catalog-of-events.md
- Prefer American spelling over other
- Fix instances of spelling ‘cancelled’ instead of ‘canceled’
> Add textlint rule to prefer American spelling for commonly used words

- source/api/commands/parent.md
- source/api/commands/parents.md
- source/ja/api/commands/parent.md
- source/ja/api/commands/parents.md
- source/zh-cn/api/commands/parent.md
- source/zh-cn/api/commands/parents.md
- Also make a note as to the difference between parent and parents at
top of doc.
- Addresses https://github.com/cypress-io/cypress/issues/4658
> Add html examples to accompany command usage for .parent / .parents

- lib/tags/timeouts.js
> fix(docs): Added missing render method in order to render the url helper

- source/_data/plugins.yml
- source/examples/examples/recipes.md
- source/ja/_data/plugins.yml
- source/ja/examples/examples/recipes.md
- source/zh-cn/_data/plugins.yml
- source/zh-cn/examples/examples/recipes.md
Currently there is no native implementation but some custom commands to help with that
> Add Shadow DOM recipes

- source/api/commands/type.md
- source/ja/api/commands/type.md
- source/zh-cn/api/commands/type.md
Added documentation of disableSpecialCharSequences option for cy.type from https://github.com/cypress-io/cypress/pull/4744
> Added documentation for disableSpecialCharSequences option for cy.type

- .textlintrc
- source/guides/tooling/typescript-support.md
- source/ja/guides/tooling/typescript-support.md
- source/zh-cn/guides/tooling/typescript-support.md
> expand typescript and custom commands example

- source/api/commands/type.md
- source/ja/api/commands/type.md
- source/zh-cn/api/commands/type.md
As `datetime` input type got deprecated removed it from docs
close #1850
> remove datetime references from docs

- source/api/commands/type.md
- source/ja/api/commands/type.md
- source/zh-cn/api/commands/type.md
> rename `disableSpecialChars` opions

- source/faq/questions/using-cypress-faq.md
Adding example of how to check for HTML form validation to FAQ ( closes #1824 )
> Adding HTML form validation to FAQ, closes #1824

- source/_data/plugins.yml
- source/ja/_data/plugins.yml
- source/zh-cn/_data/plugins.yml
Add [elm-batteries](https://github.com/cedricss/elm-batteries) to the plugins page (_Framework tooling_ section), an elm project template that includes Parcel, Netlify and Cypress.
Changes made to documentation were also copied over to other languages:
> Add elm-batteries project template to plugins

- lib/tags/requirements.js
- source/api/commands/wait.md
- source/ja/api/commands/wait.md
- source/zh-cn/api/commands/wait.md
- close #1838 
- also alphabetize requirements methods
> update wait requirements to specify when it can be used as child / when as parent

- source/guides/dashboard/github-integration.md
- source/ja/guides/dashboard/github-integration.md
- source/zh-cn/guides/dashboard/github-integration.md
Wow, spotted the GitHub integration support from v3.4.1 changelog. Nice job!
It seems that the "Status checks" section in https://docs.cypress.io/guides/dashboard/github-integration.html#Status-checks links twice to https://help.github.com/en/articles/about-status-checks, even when it mentions "One check per run group". I suppose that `run group` link was supposed to be link to some other Cypress documentation page?
I'm not sure which page it was supposed to link to, but hey, I took a guess. Let me know what you'd like the link to be, or even do a direct update to this PR branch :relaxed:
> Improve GitHub integration "run group" link target

- cypress/integration/changelog_spec.js
- cypress/integration/main_spec.js
- cypress/support/index.d.ts
- cypress/support/index.js
- gulpfile.js
- package-lock.json
- robots.txt
> add robots.txt and copy it to public folder during build

- cypress/integration/table_of_contents.js
- package-lock.json
- themes/cypress/source/js/banners_actualization.js
Add temporary workaround for hash scroll
> Add hash scroll offset

- source/api/commands/its.md
> remove 'angular' prop example - add prop always on window

- source/_data/sidebar.yml
- source/_data/webinars.yml
- source/examples/media/webinars-media.md
- themes/cypress/languages/en.yml
- themes/cypress/languages/ja.yml
- themes/cypress/languages/zh-cn.yml
- themes/cypress/layout/media.swig
> Add webinars page to docs

- cy_scripts/should-deploy.js
> look at env var FORCE_DEPLOY

- source/guides/getting-started/installing-cypress.md
- source/zh-cn/guides/getting-started/installing-cypress.md
> Add note about how recording runs to Dashboard does not work during direct install

- cypress/integration/contentful_banners_spec.js
> Issue 2009

- source/guides/guides/module-api.md
The documentation doesn't reflect the actual API.
Related Issue: https://github.com/cypress-io/cypress/issues/2310
> Update docs for run() to reflect the actual API

- source/api/commands/fixture.md
- Adds missing function parameter
> Add Missing Param

- .textlintrc
- source/guides/tooling/intelligent-code-completion.md
Shows how to get intelligent code completion in regular JS project without using triple-slash directives.
> add jsconfig section

- CONTRIBUTING.md
- package-lock.json
- package.json
- closes #2069 
See documentation in the contributing guide on how to trigger a pipeline by creating an empty github commit on the desired branch
> trigger workflow using empty GitHub commit, close #2069

- source/_data/plugins.yml
- source/guides/getting-started/writing-your-first-test.md
- source/guides/guides/debugging.md
Let the people know about https://github.com/cypress-io/cypress-fiddle
> add cypress-fiddle link and blurb

- source/api/commands/visit.md
> Add cy.visit() qs option

- source/guides/guides/debugging.md
> change open to run

- source/guides/guides/continuous-integration.md
I wanted an answer / help to answer Xvfb questions like
- https://github.com/cypress-io/cypress/issues/5168
- https://github.com/cypress-io/cypress/issues/2698
> describe solution to xvfb problem

- source/faq/questions/dashboard-faq.md
- source/faq/questions/general-questions-faq.md
- source/faq/questions/using-cypress-faq.md
- source/guides/core-concepts/conditional-testing.md
- source/guides/core-concepts/interacting-with-elements.md
- source/guides/core-concepts/retry-ability.md
Fixes some grammar/typo nits:
- Join independent clauses with semi-colon instead of comma
- "find value out of" -> "find value in" (or could be "get value out of")
- "js-dom" -> "jsdom"
- misc.
Your excellent documentation and "thought-of-everything" project motivated me to contribute back these very minor fixes. Thanks you for all your hard and thoughtful work!
> Grammar nits

- index.js
Reverts cypress-io/cypress-documentation#2072
Needs to be re-worked due to the latest changes
> Revert "issue 2071"

- source/guides/guides/continuous-integration.md
- source/guides/overview/why-cypress.md
- source/guides/tooling/code-coverage.md
- source/guides/tooling/visual-testing.md
> Add supplementary videos to relevant doc articles

- source/examples/examples/recipes.md
Add new entry to the blog table in `recipes.md` for automating Angular project using CI. Linking to our blog entry at [https://www.cypress.io/blog/2019/08/02/guest-post-angular-adding-cypress-ui-tests-to-your-devops-pipeline](https://www.cypress.io/blog/2019/08/02/guest-post-angular-adding-cypress-ui-tests-to-your-devops-pipeline)
close #2113
> Add Angular CI example to recipes

- _config.yml
Adds alias to redirect `guides/references/known-issues.html` to `404.html`
This page is a remnant of older docs and no longer needed. 
close #2114
> redirect old known-issues to 404

- source/guides/guides/command-line.md
- source/guides/guides/continuous-integration.md
Update the `cypress open --browser` docs to clarify the difference b/t how its different from `cypress run --browser`
close #2125
> Update cypress open --browser section

- source/guides/tooling/typescript-support.md
closes #1110
I added a warning note about potential IDE TS server issues that may throw off TS setups.
> Add note about potential IDE TS server issues

- themes/cypress/source/css/_partial/highlight.scss
Code block corners were so sharp they were piercing my soul. IMO this looks better
before -> after
> fix(style): add border-radius to code blocks

- source/api/cypress-api/custom-commands.md
> Remove function signature that accepted options into Cypress.Commands.overwrite

- source/guides/dashboard/projects.md
Added more details about the consequences of exposing a record key to `guides/dashboard/projects.ms`
closes  #2151
> update projects.md record key

- source/api/commands/url.md
* Fix broken image URL in https://docs.cypress.io/api/commands/url.html#Timeouts section.
* Titleize `Command log`.
> Fix broken imgTag url

- source/guides/guides/continuous-integration.md
I often see people struggling to understand the "binary is missing" CI error. This adds an explanation and advice to our CI giude.
> add advise on what to do when binary is missing on CI

- source/api/commands/get.md
for get() command page (.../api/commands/get.md), added an example that shows how one can find an element with an attribute (ex: href) given a partial value (ex: questions)
closes #2092
> added an example for partial match selector

- source/faq/questions/using-cypress-faq.md
This closes #2170 
Current FAQ links to old GH issue. Needs to point to current parallelization docs.
> update link in FAQ to parallelization

- source/api/commands/next.md
- source/api/commands/type.md
> Added datalist examples in next() and type() documentation

- source/guides/tooling/reporters.md
When I tried to set up multi-reporters, I found out that mocha-multi-reporters is broken for mocha 6+, which is what users will get if they run the suggested command:
```
npm install --save-dev mocha mocha-multi-reporters mocha-junit-reporter
```
However, there's a maintained fork of mocha-multi-reporters which supports mocha v6+, cypress-multi-reporters.  This commit changes the docs to suggest that newer package instead of the broken one.
I also made a tweak to the suggested npm script, to actually use the reporter.
> Suggest cypress-multi-reporters

- source/guides/guides/continuous-integration.md
#2204 
added documentation for no color env var
> added no_color env var documentation:

- source/_data/plugins.yml
add cypress-cy-select plugin (https://www.npmjs.com/package/cypress-cy-select)
data-cy shorthand notation for cypress get and find functions
> add cypress-cy-select plugin to documentation

- source/api/commands/writefile.md
The yielded value is either a string, or a javascript object that was
stringified to the file, in short - contents parameter. The examples
already reflect contents parameter is yielded.
> Update cy.writeFile() yields description

- .eslintignore
- .eslintrc
- circle.yml
- lib/tags/assertions.js
- lib/tags/partial.js
- package-lock.json
- package.json
- test/jest-coffee-preprocessor.js
On platforms without a decent grep, it seems stop-only does a poor
job of correctly detecting focused tests. There's an eslint plugin
which is much more suitable, use that instead.
While changing eslint config, tidy up the lint commands and fix a
couple of minor issues in files that were not being linted.
Exclude the themes/ folder from lint, cover everything else.
> Use eslint plugin to catch exclusive tests

- cypress/integration/notes_spec.js
- lib/tags/note.js
- package.json
#2196 introduced #2234; where no notes were rendered throughout the docs site. This PR addresses this; primarily by actually returning the parsed notes' value.
The issue is may be seen on the [configuration page of the docs site](https://docs.cypress.io/guides/references/configuration.html#Options) or [locally](http://localhost:2222/guides/references/configuration.html)
Before screenshot (without notes)
and, correctly working, after:
> Issue 2234 notes missing

- source/guides/tooling/code-coverage.md
Hi, I was looking for an Angular code coverage example and didn't find one on the docs website. Later I found that there were [examples](https://github.com/cypress-io/code-coverage#examples) in the [cypress-io/code-coverage repo](https://github.com/cypress-io/code-coverage), and these docs included an Angular example.
This PR adds the examples from cypress-io/code-coverage to the docs page.
> docs: add examples to code-coverage

- .github/workflows/automerge-pr-develop-master.yml
- .github/workflows/create-pr-develop-to-master.yml
- closes #2233 
- we have to land this into master so all the new PRs would go through this new workflow
> Auto-merge develop to master after successful PR merges into develop

- source/api/cypress-api/screenshot-api.md
Fixed wording on cypress documentation regarding blackout of features when taking a screenshot
close #2239
> docs: fix screenshot blackout wording in documentation 

- .github/workflows/automerge-pr-develop-master.yml
- .github/workflows/create-pr-develop-to-master.yml
Switched to using the auto-generated GITHUB_TOKEN instead of using the personal token of GH_TOKEN so the PR merges are attributed properly.
> Use auto-generated GitHub token for GH automerge actions

- source/faq/questions/dashboard-faq.md
> what is a test recording? faq item

- cypress/integration/projects_spec.js
- source/_data/projects.yml
- source/_data/sidebar.yml
- source/examples/examples/projects-media.md
- themes/cypress/languages/en.yml
- themes/cypress/languages/ja.yml
- themes/cypress/languages/pt-br.yml
- themes/cypress/languages/zh-cn.yml
- themes/cypress/layout/media.swig
- closes #2267
Adds one more page with links to open source projects that use Cypress
> Add example projects page

- source/_data/plugins.yml
Submits [cypress-har-generator](https://github.com/NeuraLegion/cypress-har-generator) plugin into the official list of Cypress plugins. It allows the users to record network requests while running tests.
> docs(plugins): add cypress-har-generator plugin

- source/guides/tooling/code-coverage.md
The documentation explains how to setup the babel-plugin-istanbul plugin, but doesn't provide any examples or guidance for how to serve the application with the instrumented code without an intermediate folder, once the plugin is setup. 
I've also separated the Instrumenting code section into the two parts, which should make it easier to read. 
Potential limitation of this specific example is that it assumes the application was build using create-react-app.
> Added example for serving instrumenting code

- source/_data/plugins.yml
Submitting [cypress-redux]() as a plugin, which allows users to assert against Redux stores w/ custom commands. It's fully tested [here](https://circleci.com/workflow-run/ba27f44c-47f9-4e97-8df7-f76fcb867923). Thanks, and LMK if you have any questions!
> docs(plugins): add cypress-redux

- source/_data/plugins.yml
https://github.com/bahmutov/cy-spok
validates complex objects in a single shot. For example, in our network assertions recipe
```js
const spok = require('cy-spok')
it('asserts multiple XHR properties at once using cy-spok', () => {
cy.visit('index.html')
// before the request goes out we need to set up spying
// see https://on.cypress.io/network-requests
cy.server()
cy.route('POST', '/posts').as('post')
cy.get('#load').click()
cy.contains('#output', '"title": "example post"').should('be.visible')
// Spok https://github.com/thlorenz/spok is a mix between schema and value assertions
// Since it supports nested objects, in a single "should()" we can verify desired
// properties of the XHR object, its request and response nested objects.
cy.get('@post').should(spok({
status: 201,
url: …
```
> add cy-spok plugin

- source/api/commands/click.md
I think the key to this original issue is that I honestly can't tell where they were originally looking and what failed. Did they find the click doc and they just didn't know how to write a css selector? Or did they never make it to the click doc? 
I expanded the css selectors cause I think this is helpful anyways - added the other examples to See Also section.
- close #2293
> add more diverse css selector examples to click

- source/guides/guides/network-requests.md
Adds a little bit more to the Network requests guide that is missing assertion examples
> add network request example and recipe link

- source/api/cypress-api/custom-commands.md
Removed the inner curly braces in the getSessionStorage example in order to make it yield the value from session storage.
> Fixed getSessionStorage command example

- source/guides/tooling/reporters.md
- `cypress-multi-reporters` config file expects camel-casing of reporter name (i.e., `mochaJunitReporterReporterOptions`) in place of bare `reporterOptions`
- `mochawesome-merge` now only accepts directory as main argument
- `mochawesome-report-generator` only has the binary `marge`.
> Update Mochawesome commands in reporters documentation

- source/guides/tooling/code-coverage.md
Hi.
I've found a spelling that might be a typo of `crucial`.
> Fix a typo of "crucial"

- source/guides/guides/web-security.md
- source/guides/references/configuration.md
- source/guides/references/error-messages.md
- source/guides/references/trade-offs.md
- close #2364 
This was written to clear up confusion in this issue over visiting HTTP url after visiting an HTTPS url. https://github.com/cypress-io/cypress/issues/6048 and to supplement this PR in the Test Runner.  https://github.com/cypress-io/cypress/pull/6118
> Update explanation of cross-origin domain docs

- source/guides/guides/continuous-integration.md
I was updating the dependency list from this docker image: https://github.com/cypress-io/cypress-docker-images/blob/master/base/12.13.0/Dockerfile#L3 (mentioned from this issue https://github.com/cypress-io/cypress/issues/5965)
Is this correct? I would prefer a better source of truth for this because I feel like this will get out of date quickly and be forgotten.
> update ci deps based off of docker image

- source/api/commands/server.md
Addressing this fundamental flaw in our `cy.server()` doc - that it does not affect `cy.request()`. https://github.com/cypress-io/cypress/issues/6244#issuecomment-580375345
> remove mention of cy.request() from cy.server()

- source/guides/core-concepts/introduction-to-cypress.md
There's a small typo in the documentation. Instead of taking the reader to the `then` documentation page, it would direct them to the `type` page.
> Change .then() url from type to then

- source/guides/tooling/typescript-support.md
> Add section to TypeScript doc for plugins

- lib/tags/assertions.js
- lib/tags/timeouts.js
- source/api/commands/invoke.md
As mentioned in this issue https://github.com/cypress-io/cypress-documentation/issues/495 the `cy.invoke` function will await if the invoked function returns a promise but it is not yet documented. 
This PR expands the documentation to reflect exactly this behaviour
**Issue: https://github.com/cypress-io/cypress-documentation/issues/495**
**First seen in: https://github.com/cypress-io/cypress-example-recipes/issues/133**
> Documented that cy.invoke will wait for promises

- source/guides/references/configuration.md
I've noticed the http://globtester.com website has dead for a while. https://globster.xyz seems the be a good replacement.
> Replace broken globtester.com link

- source/guides/references/migration-guide.md
Add new section to migration guide to cover new error when no test title defined. Mentioned in https://github.com/cypress-io/cypress/issues/6371
> Add breaking change in migration guide covering mocha change of behavior.

- source/api/commands/then.md
Closes https://github.com/cypress-io/cypress-documentation/issues/2349
Replaces
`$btn.class()`
with
`$btn.attr('class')`
> docs: fix jquery get class snippet [Issue #2349]

- source/api/plugins/browser-launch-api.md
- Add more realistic examples
- Remove examples that make no sense to ever use in Cypress.
- Honestly, I couldn't get a single browser launch preference to take effect for Chrome or Firefox, so I don't know if this even works or I'm doing it wrong. There is no real example provided here.
> Add links for browser launch options

- source/guides/guides/environment-variables.md
The current doc has two different naming conventions for setting the baseUrl via the environment
1) CYPRESS_baseUrl 
2) CYPRESS_BASE_URL
Both the values are able to overwrite the baseUrl configuration value.
Since it's an environment variable the convention should be to use CYPRESS_BASE_URL and not CYPRESS_baseUrl.
> Update environment-variables.md CYPRESS_baseUrl

- CONTRIBUTING.md
I think it's good to have a fast way to access this section
> Add link to "Translating" section

- source/faq/questions/dashboard-faq.md
> adds FAQ for tests failing in CI but passing locally

- source/guides/references/migration-guide.md
Add note about another breaking change to our migration guide from Chai due to discussion from https://github.com/cypress-io/cypress/issues/6626
> Add note about 'include' checking for strict equality to migration guide

- source/guides/guides/cross-browser-testing.md
Hello,
I've just noticed that on the two examples of `runOn` and `ignoreOn` is missing a closing parenthesis, this PR addresses the typo
> Add two closing parenthesis on runOn ignoreOn

- source/guides/tooling/code-coverage.md
Suggested by our user in https://github.com/bahmutov/cra-ts-code-coverage-example/issues/2#issuecomment-600715989
> add link to the code coverage examples in the repo

- cypress/integration/i18n_spec.js
- Previously this was comparing the entire url - which would fail when these tests were run in staging because it would compare `docs-staging.io` to `docs.io`. Should only compare paths. 
- Close #2634
> Compare paths for urls in i18n tests

- source/api/commands/select.md
I like having "Read ..." in the list to give the reader a sense of what the URL is: a blog post, a video, a slide deck, etc
> add link to working with select elements blog post

- source/api/commands/hover.md
links to Chrome remote debugging recipe which is being added in #2642 
https://github.com/cypress-io/cypress-documentation/pull/2645 must merge first for link to make sense. It's not broken, but the recipe referenced isn't there yet :)
Closes #2617
> adds link to workaround for hover command entry

- source/api/commands/getcookie.md
- source/api/commands/getcookies.md
- source/api/commands/setcookie.md
- source/guides/references/configuration.md
> Document `sameSite` support for cookies commands

- source/_changelogs/4.3.0.md
In the current changelog, the link to the netlify plugin is missing a closing %}.
> Fix URL for netlify plugin in 4.3 changelog

- source/guides/core-concepts/introduction-to-cypress.md
The Commands Run Serially section references an example test that's quite far away, now that there are several other examples in the previous section. Including the example again makes it easier for the reader to understand the concepts described in this section.
> remind the reader of the referenced example in Commands Run Serially

- source/guides/references/migration-guide.md
We had an engineer at Airbnb follow the migration guide and remove the return statement thinking it wasn't needed. Turns out that it's a crucial piece and it would be good to keep things consistent and include it everywhere.
Happy to add more details here as well! @lencioni @madicap
> update Plugin Event migration docs to always return launchOptions

- source/guides/guides/stubs-spies-and-clocks.md
Who knows why this happened. Hexo doesn’t like the url tags at the beginning of the sentences.
- close #2722
> Fix formatting of spies/stubs page so it displayed code and headers in proper code blocks

- source/api/plugins/browser-launch-api.md
Couldn’t find this in docs to link to someone https://github.com/cypress-io/cypress/issues/6049#issuecomment-612805204
> Add example for setting screen size on headless chrome browsers

- source/_data/courses.yml
This is not an issue but I've recently recorded a *free* collection "Add e2e tests with cypress to a React application" on egghead.io and I'd love to see it featured in cypress docs!
> Update courses.yml to include 'Add e2e tests with cypress to a React application' on egghead.io

- source/zh-cn/guides/getting-started/installing-cypress.md
I found there is a 404 for `/img/guides/select-browser.png` in Chinese doc, and it has already updated to `/img/guides/browser-list-dropdown.png` in English doc.
> Update image url for switching browser in Chinese doc

- source/guides/guides/network-requests.md
Hey I added some citations about cy.request() at Network Request documentation.
Aiming to close #2538 
The top info note seems like this:
And the bottom:
> Sugesting cy.request() as a resource.

- source/api/commands/select.md
- source/guides/core-concepts/interacting-with-elements.md
- close #2775 
Passing `{force: true}` to `.select()` will not override selecting disabled options or optgroups. This notes this behavior in the docs.
> Add warnings that passing force: true to select does not disable some checks

- source/guides/guides/debugging.md
Fix a small typo in Debugging guide.
"Toubleshooting" -> "T**r**oubleshooting"
> Fix typo - missing "r" in "Troubleshooting"

- source/guides/references/best-practices.md
Fix typo in `Best Practices`, chapter `Web Servers`
> Fix typo in best practices

- source/api/commands/check.md
It was not completely clear from the examples what the structure of the HTML was for .check examples. 
Someone was trying to select by label, which is not supported https://github.com/cypress-io/cypress/issues/7379
> Add HTML to accompany .check examples to demonstrate selecting by value

- source/api/commands/request.md
For the [encoding option](https://github.com/cypress-io/cypress-documentation/pull/2805), and for anyone facing [this issue](https://github.com/cypress-io/cypress/issues/3576) or [this issue](https://github.com/cypress-io/cypress/issues/2029) or similar ones, it might be a good idea to include in the official documentation of `cy.request()` a couple of clear and useful examples/use cases utilizing the `encoding` option.
> Add example use-cases of `encoding` option in `cy.request()`

- source/guides/tooling/typescript-support.md
Remove section "Additional information", that shows links that are partially dead (https://basarat.gitbooks.io/typescript/docs/testing/cypress.html) or not relevant anymore due to the native typescript support of Cypress@4.4.0
> Remove dead links & misleading information from typescript-support.md

- source/guides/references/configuration.md
- source/guides/references/error-messages.md
Just something I noticed about the support file not mentioning supporting TypeScript.
> Expand support files to include TypeScript file ext

- source/guides/references/experiments.md
- Add `experimentalShadowDomSupport` description to experiments page.
> Add shadow dom experimental flag

- source/api/cypress-api/config.md
- source/guides/references/configuration.md
I found a couple typos, including a code block with invalid code, in the test configuration sections. While fixing those, I went ahead and updated the prose a bit to make it a little clearer and standardize use of plurals.
> Improve test configuration section

- source/guides/references/assertions.md
- The `key` assertion would have failed if run, should include a passing example.
- From https://github.com/cypress-io/cypress/issues/7665
> Update example to include a passing 'keys' assertion

- source/guides/references/experiments.md
I realize we will likely improve upon this later, but these were just some quick fixes from our docs meeting discussion. 
- Move main explanation above ‘configuration’ section
- Link to relevant sections from within configuration table
- Link to main ‘configuration’ page to show how they set configuration
- Add sections to component testing - linking to libraries that are supported
- Remove ‘comparison’ table from component testing
- Make it more clear that cross-boundary selectors are not supported.
> Improve 'Experiments' page

- source/guides/references/experiments.md
Fix a typo on the Experiments page
> Fix typo on experiments.md

- source/guides/core-concepts/writing-and-organizing-tests.md
thanks to @JessicaSachs for noticing it!
> docs: fix incorrect syntax in example

- source/guides/guides/command-line.md
- source/guides/guides/module-api.md
> docs: add `quiet` cli arg/module api flag

- source/api/cypress-api/isbrowser.md
- source/guides/guides/continuous-integration.md
- source/guides/guides/cross-browser-testing.md
- source/guides/guides/environment-variables.md
Followup from https://github.com/cypress-io/cypress-documentation/pull/2896
> Fix more instances of incorrect test configuration

- source/api/cypress-api/cookies.md
Seems like a couple of opening parentheses are missing in the `before` and `beforeEach` hooks in the example on the cookies doc page.
> Add missing parens

- source/api/commands/clock.md
- source/api/commands/tick.md
- source/guides/guides/stubs-spies-and-clocks.md
- closes #2910
By making examples first-class, adds them to the navigation bar
> Document clock restore better

- source/guides/guides/network-requests.md
This seemed to me to be a mixed-message, the title **Don't Stub responses** is confusing as suggests you shouldn't stub, but then you're actually encouraging stubbing within the same page.
Also doesn't seem accurate to claim this is "Guaranteed to work in production".
> Don't Stub responses

- source/_partial/linux_dependencies.md
- source/guides/getting-started/installing-cypress.md
- source/guides/guides/continuous-integration.md
- based on feedback from https://github.com/cypress-io/cypress/issues/1526, I think people aren't finding the Linux deps easily, so this adds them to the initial system requirements for the install doc.
- add partial to be shared for linux deps
> Update system requirements to also display Linux deps

- source/api/commands/server.md
- source/api/cypress-api/cookies.md
- source/api/cypress-api/cypress-server.md
- source/faq/questions/using-cypress-faq.md
For https://github.com/cypress-io/cypress/pull/7782
> Rename uses of whitelist for renamed options.

- source/guides/tooling/typescript-support.md
For https://github.com/cypress-io/cypress/pull/7806
> Update typescript doc to specify minimum required TS version

- source/api/plugins/browser-launch-api.md
Based off feedback from https://github.com/cypress-io/cypress/issues/4675#issuecomment-656340599
> exclude electron from downloads directory workaround that only applies to Chrome

- source/guides/dashboard/introduction.md
- source/guides/guides/continuous-integration.md
- source/guides/guides/parallelization.md
- source/guides/guides/screenshots-and-videos.md
- source/guides/overview/why-cypress.md
- themes/cypress/source/css/_mixins.scss
- themes/cypress/source/css/_partial/button.scss
- themes/cypress/source/css/_partial/page.scss
- themes/cypress/source/css/_partial/utilities.scss
- themes/cypress/source/css/_variables.scss
Tried doing this with a partial but it kept rendering random `<br>` elements.
> docs: add dashboard CTAs

- source/_changelogs/4.11.0.md
- source/api/commands/scrollto.md
> 4.11.0 Release

- source/api/cypress-api/screenshot-api.md
- source/api/plugins/writing-a-plugin.md
- source/guides/guides/debugging.md
- source/guides/guides/screenshots-and-videos.md
- source/guides/references/configuration.md
- source/guides/references/error-messages.md
Related to https://github.com/cypress-io/cypress/pull/8083
> Add screenshotOnRunFailure to configuration option

- source/guides/tooling/typescript-support.md
The example `.spec` uses `.js` as a file-ending which I assume should reflect the use of typescript so I propose the change to `.ts`
Also as far as I understand it would make sense to keep all your configuration files in `.ts` format if you use typescript and the docs suggest otherwise.
Please correct me if I am wrong.
Thank you for your work and best regards
David
> docs: Change fileEnding to ts instead of js in Typescript guide

- source/api/plugins/browser-launch-api.md
- Close #3034
- Got options for Electron and Firefox now
- Add note about retina screens with Chrome
- Add warning about how this doesn't have to do with `viewportHeight` and `viewportWidth`
- Also add note about us being in cypress/plugins/index.js file since people
just jump to the section they need and don’t know where to add the code.
> Update options for all headless browsers to change screen size

- source/_data/plugins.yml
- This has been replaced by experimental feature + the plugin is shown as deprecated by the creator.
> Remove deprecated shadow-dom plugin

- themes/cypress/languages/es.yml
I found this error in the live documentation and just fixed it in github itself. I didn't find any open issue or PR regarding this.
> Fix typo in spanish translation

- source/guides/references/migration-guide.md
Related to https://github.com/cypress-io/cypress/pull/8143
> Add section to migration guide about esModuleInterop change 

- source/_changelogs/1.1.2.md
- source/api/plugins/preprocessors-api.md
- source/faq/questions/using-cypress-faq.md
- source/guides/core-concepts/writing-and-organizing-tests.md
- source/guides/tooling/plugins-guide.md
Related to https://github.com/cypress-io/cypress/pull/7982 (Change default preprocessor to webpack).
>  Update default preprocessor references from browserify to webpack

- source/guides/guides/launching-browsers.md
- We don’t support Chrome less than 64 as shown in this line https://github.com/cypress-io/cypress/blob/develop/packages/server/lib/browsers/chrome.ts#L461:L461
> Add note about Chrome not being supported below 64 in Cypress

- source/guides/guides/environment-variables.md
- source/guides/guides/module-api.md
- There’s nothing in the Module API that actually explains that you have to execute the file through `node`. Updated to explain this.
- Based off of this issue: https://github.com/cypress-io/cypress/issues/8316
> Add instructions on how to execute Module API

- _config.yml
- Fix on.cypress.io/test-retries not going to correct route
> Create reroute for guides/test-retries.html to correct route

- source/api/commands/route.md
A comma is missing in the code sample here:
This PR fixes it.
> Fix incorrect JS in "Change headers" paragraph

- source/guides/core-concepts/retry-ability.md
- source/guides/references/assertions.md
See discussion at https://github.com/cypress-io/cypress/issues/7651#issuecomment-642442799
"Existence" might be ambiguous: you may want an element to be removed, but you may also check that an element never existed. For example check that a loader does not appear immediately, or that a server-side render was successful.
> Add instruction to check if element never existed

- source/_partial/linux_dependencies.md
Dependencies in a single line would be easier to copy and paste in the terminal though might need to ignore the 70/84 character limit per line. Not sure if the right way to make this change, but let me happy to fix up as you wish.
> Convert dependencies to a single line in Getting Started

- source/guides/tooling/IDE-integration.md
- source/guides/tooling/typescript-support.md
- Adds yarn install
- Removes `strict: true` from tsconfig recommendation. It has no effect since Cypress only transpiles spec files, so it's confusing to have it recommended.
- Removes `baseUrl: '../node_modules'` from tsconfig recommendation. It can causes issues such as [this one](https://github.com/cypress-io/cypress/issues/8380).
> Improve TypeScript doc

- source/guides/core-concepts/interacting-with-elements.md
- source/zh-cn/guides/core-concepts/interacting-with-elements.md
Adds documentation for `opacity: 0` now being considered invisible, with additional explanation regarding the exception for actionability.
Chinese roughly translates to "There is a special exception. The element of `opacity:0` is invisible but interactive” which I feel communicates the message well enough.
Contingent on https://github.com/cypress-io/cypress/pull/8244 being merged in a future major release
> Add docs for  visibility check

- source/_data/plugins.yml
Adds [cypress-fill-command plugin](https://github.com/DanielFerrariR/cypress-fill-command) to the Cypress documentation.
> Add cypress-fill-command to plugins list

- source/_data/plugins.yml
Adds [cypress-rollup-preprocessor](https://github.com/lmarqs/cypress-rollup-preprocessor) plugin to the Cypress documentation.
> Add cypress-rollup-preprocessor to plugins list

- source/api/cypress-api/cookies.md
Because this doc is for cypress' module for cookies, the phrase "log out" can be confusing as cookies are commonly used for auth - login/log-out but in this context "log out" means logging...
Making just one change for now even though multiple changes are required in this doc. Want to confirm if maintainers agree with me on this or not.
> Phrase "log out" can be confusing in this doc

- source/guides/guides/parallelization.md
`$CODEBUILD_BUILD_ID` should not be use as a CI Build ID to the Cypress Dashboard.
The newly released [batched feature of AWS CodeBuild](https://aws.amazon.com/about-aws/whats-new/2020/07/aws-codebuild-now-supports-parallel-and-coordinated-executions-of-a-build-project/) allows for parallel runs.
Per [Environment variables in build environments - AWS CodeBuild](https://docs.aws.amazon.com/codebuild/latest/userguide/build-env-ref-env-vars.html)
`$CODEBUILD_INITIATOR` provides the entity that started the build which is unique and can be used as the `--ci-build-id` sent to the Cypress Dashboard.  e.g. `awsCodeBuild-cypress-kitchen-sink/AWSCodeBuild-a14fc8e3-b5d6-42f9-9067-345d48a8f0fd`
Reference:
- https://github.com/cypress-io/cypress-example-kitchensink/pull/450
- …
> Update environment variable for AWS CodeBuild to be $CODEBUILD_INITIATOR

- source/_changelogs/5.0.0.md
Related to https://github.com/cypress-io/cypress/issues/8683
> Update docs to mention exclamation marks not being supported.

- source/api/commands/route2.md
Hi there! The route2 glob example has the same comment twice. So I removed the extra one. That's it. This PR is not very interesting.
> docs: remove duplicate comment in route2.md

- source/api/commands/route2.md
- themes/cypress/source/css/_partial/base.scss
Rewrote the route2 docs from scratch with a little more emphasis on the functionality of route2. Previously, it still closely followed the cy.route docs, which were completely different.
I think the general layout of these new docs is much more intuitive. Also, this fixes several technical errors in the route2 docs which I didn't notice when it was initially created.
> docs: route2 docs v2

- source/api/plugins/browser-launch-api.md
> document how to forward key/value pairs to electron args

- source/api/commands/type.md
Awaiting some clarification on how this is different from end and home special chars https://github.com/cypress-io/cypress/pull/7970
> document movetoend and movetostart special chars for type

- source/_changelogs/3.3.2.md
Fixes a small typo: "paramater" -> "parameter"
> Fix typo in changelog 3.3.2

- source/api/commands/route2.md
```js
cy.route2({
url: 'http://example.com/search',
query: { q: 'expected terms' },
}).as('login')
// once a POST request to http://example.com/login with a querystring containing
// 'q=expected+terms' responds, this 'cy.wait' will resolve
cy.wait('@login')
```
The alias name and comments sound wrong.
* url uses `search` but the comment says `http://example.com/login`
* By default, routeMatcher uses `GET` method, not `POST`.
* The better name for the alias is search, not login. 
I changed 3 of them.
> Make route2 routeMatcher example clearer.

- source/_changelogs/5.4.0.md
- source/api/commands/viewport.md
- source/guides/guides/command-line.md
- source/guides/guides/launching-browsers.md
- source/guides/references/troubleshooting.md
> 5.4.0 Release

- source/api/commands/route2.md
One difference that was not described before. Took me a moment to find out why my migration to `route2` failed ;).
> Added mention about lack of default method

- source/guides/guides/test-retries.md
Fix the missing closing quotes in the example tests in the section test-suites
> Close test description strings in test-retries.md

- lib/tags/usage.js
- source/api/commands/check.md
- source/api/commands/clear.md
- source/api/commands/click.md
- source/api/commands/dblclick.md
- source/api/commands/rightclick.md
- source/api/commands/select.md
- source/api/commands/trigger.md
- source/api/commands/type.md
- source/api/commands/uncheck.md
Document `animationDistanceThreshold` and `waitForAnimations` as available options for the commands below. Found while investigating https://github.com/cypress-io/cypress/issues/8854 
- .click()
- .dblclick()
- .rightclick()
- .type()
- ~.clear()~
- ~.check()~
- ~.uncheck()~
- ~.select()~
- .trigger()
Also alphabetized the options list.
**Preview**
> Document animationDistanceThreshold and waitForAnimations options to actionable commands.

- source/api/commands/viewport.md
Add macbook-16 model in viewportPresets.
Documentation for  https://github.com/cypress-io/cypress/pull/8892 @close #8889 issue
> added macbook-16 viewport preset

- package-lock.json
- source/api/commands/type.md
- source/api/cypress-api/cookies.md
- source/guides/references/configuration.md
close #3278 
docs for https://github.com/cypress-io/cypress/pull/8411
I would have liked to style the `* Firefox doesn't support the beforeinput event` as a smaller caption, but didn't want to complicate things with a new hexo tag
> support beforeinput event

- source/_data/plugins.yml
The British government has been investing in enhancing their quality approaches to their digital applications. One of the areas the departments have been investing on is visual testing. After carefully studying the available options, we've decided to create a plugin which would allow us to scale and enhance along the road, and we felt we would be unable to accomplish this using the current open source plugins created by the community.
We also feel that having the community provide feedback and give them a platform to contribute will keep this plugin up to date so it could keep being useful in the long term not only for the government but whomever wishes to use it.
> Add visual regression open source plugin

- source/guides/tooling/reporters.md
To make clear what the API of such reporters is.
We were trying to write a custom cucumber reporter, not adhering to the requirements of Mocha reporters. We go an error "Could not load reporter by name" even though the correct paths was listed in "We searched for the reporter in these paths".
> Add link to Mocha custom reporters docs

- source/api/commands/type.md
docs for https://github.com/cypress-io/cypress/pull/8499
> docs for shortcut syntax in cy.type()

- _config.yml
- source/_changelogs/5.1.0.md
- source/_changelogs/5.2.0.md
- source/_changelogs/5.3.0.md
- source/_changelogs/5.4.0.md
- source/_changelogs/5.5.0.md
- source/_data/sidebar.yml
- source/_partial/network_stubbing_warning.md
- source/api/commands/http.md
- source/faq/questions/using-cypress-faq.md
- source/guides/references/experiments.md
- themes/cypress/languages/en.yml
for https://github.com/cypress-io/cypress/pull/9182
> docs(net-stubbing): rename cy.route2 to cy.http

- source/guides/tooling/IDE-integration.md
While reading through the documentation at https://docs.cypress.io/guides/tooling/IDE-integration.html#File-Opener-Preference I noticed a minor grammatical mistake:
> If your preferred editor is not **list**, you can specify ...
I'm no English major, but being a native English speaker, that above sentence doesn't read well. This PR attempts to improve how that reads:
> If your preferred editor is not **listed**, you can specify ...
> Improve grammar in IDE integration document

- source/_changelogs/6.0.0.md
- source/guides/guides/continuous-integration.md
- For https://github.com/cypress-io/cypress/pull/9242
> docs: Disable dev shm usage by default

- source/guides/tooling/reporters.md
If you put a hexo link at the beginning of a paragraph, sometimes it renders all the following markdown raw. 🤷‍♀️🤷‍♀️🤷‍♀️
- close #3334
> Fix markdown rendering issue within custom reporters section

- source/api/commands/intercept.md
Fix original aliasing example (`req.body.includes("mutation") to req.body.hasOwnProperty("mutation")`) since `req.body.includes` throws an "includes is not a function" error if run in Cypress.
Rename section to be GraphQL specific and add variations of `routeMatcher` for queries and mutations with and without an `operationName` attribute.
> The operation name is a meaningful and explicit name for your operation. It is only required in multi-operation documents, but its use is encouraged because it is very helpful for debugging and server-side logging.
[Operation Name | GraphQL](https://graphql.org/learn/queries/#operation-name)
> Fix example aliasing example; Add "Aliasing individual GraphQL requests" section with additional examples

- source/faq/questions/using-cypress-faq.md
> Correct spelling: covert => convert

- source/faq/questions/general-questions-faq.md
Since linked issue was closed I took the [closing comment](https://github.com/cypress-io/cypress/issues/346#issuecomment-530967799) and made it the new answer (with minimal wording tweaks suitable in the context of this document).
I left the related resources in, since they still seems to be helpful and related to "coverage" in general. But I slightly modified the wording to
- no longer sound like code coverage is not there
- invite more links should anybody have one
> Update answer about code coverage

- source/guides/guides/test-retries.md
seems like plugins writers might need this information, I needed it to write https://github.com/cypress-io/cypress-repeat-retry
> describe how to access the retry counter from the test

- source/_changelogs/1.1.0.md
- source/_changelogs/5.0.0.md
- source/_data/plugins.yml
- source/api/plugins/preprocessors-api.md
- source/faq/questions/general-questions-faq.md
- source/guides/core-concepts/writing-and-organizing-tests.md
- source/guides/guides/debugging.md
https://github.com/cypress-io/cypress-webpack-preprocessor becomes https://github.com/cypress-io/cypress/tree/master/npm/webpack-preprocessor
> Fix broken links to old cypress-webpack-preprocessor

- source/_changelogs/6.0.0.md
- source/_partial/xhr_stubbing_deprecated.md
- source/api/commands/intercept.md
- source/api/commands/route.md
- source/guides/references/migration-guide.md
TR-553
- Added a section to the migration guide for migration cy.route() to cy.intercept(). 
- I think these examples are pretty minimal and I'd probably like more complicated examples added.
- Mostly to just allow us to have a place to link and share with people, but I imagine this section will move into the 7.0 migration guide when that is released.
> Add section for migration cy.route to cy.intercept

- source/_data/plugins.yml
TestRail Reporter which auto-set status for specific TestRun for Cypress.
> Add autoset-status-cypress-testrail-reporter plugin

- source/_data/sidebar.yml
- source/api/plugins/before-spec-api.md
- source/api/plugins/writing-a-plugin.md
- source/guides/references/experiments.md
- themes/cypress/languages/en.yml
For https://github.com/cypress-io/cypress/pull/9646
When I implement the `after:spec` event and add a doc for that, I'll add a 'Spec Events' section to the [Plugins Guide](https://github.com/cypress-io/cypress-documentation/blob/develop/source/guides/tooling/plugins-guide.md).
> Add doc for before:spec event

- source/_data/plugins.yml
- source/_data/sidebar.yml
- source/api/plugins/after-spec-api.md
- source/api/plugins/before-spec-api.md
- source/api/plugins/writing-a-plugin.md
- source/guides/references/experiments.md
- source/guides/tooling/plugins-guide.md
- themes/cypress/languages/en.yml
For https://github.com/cypress-io/cypress/pull/14178
**Note**: Before merging this, wait for https://github.com/cypress-io/cypress-documentation/pull/3393 to be merged and change the base branch to `6.2.0-release`
> Add doc for after:spec event

- source/guides/guides/launching-browsers.md
closes #3410
I moved the troubleshooting link into its own section because I completely missed it trying to send it to the user. Now it will be obvious where to look
> move launching browsers troubleshooting into explicit section

- source/api/commands/contains.md
- source/api/commands/filter.md
- source/faq/questions/using-cypress-faq.md
verified by adding tests in https://github.com/cypress-io/cypress-fiddle/commit/9dec37dbbefa0572dcdb3c3b63bb1cfaab43eecd
answers questions like https://github.com/cypress-io/cypress/issues/9531 and https://github.com/cypress-io/cypress/issues/9530
> add notes about contains and non-breaking space

- source/guides/guides/environment-variables.md
seems people ask about `dotenv` a lot, and our pages are less than clear and just jump from page to page
> add example to the plugins file with environment variables

- source/_changelogs/6.2.0.md
- source/_data/sidebar.yml
- source/api/commands/intercept.md
- source/api/plugins/after-run-api.md
- source/api/plugins/after-spec-api.md
- source/api/plugins/before-run-api.md
- source/api/plugins/before-spec-api.md
- source/api/plugins/writing-a-plugin.md
- source/guides/references/experiments.md
- source/guides/tooling/plugins-guide.md
- themes/cypress/languages/en.yml
> 6.2.0 Release

- source/_data/plugins.yml
I created a new plugin to assist with filling Stripe Elements inputs, as this seemed to be a large-ish problem people were having!
> Add cypress-plugin-stripe-elements to plugins list

- .eslintrc
- circle.yml
- cypress/.eslintrc
- cypress/integration/main_nav_spec.js
- cypress/integration/plugins_spec.js
- package-lock.json
- package.json
- test/.eslintrc
Removes an additional external dependency and uses the standard rules that are already present in `@cypress/eslint-plugin-dev`. Changes are in line with https://github.com/cypress-io/cypress/pull/14422
> build: update eslint rules for tests

- source/api/events/catalog-of-events.md
- source/examples/examples/recipes.md
- source/faq/questions/using-cypress-faq.md
- add links to the fundamentals recipes
- add links to the errors recipe to the events
- explain the unhandled promise rejection
> error handling links and answers

- source/api/utilities/promise.md
To clarify confusion for the client
> add notes about rejected promises in test code

- source/guides/tooling/reporters.md
Some minor changes:
- clarify which reporter is the default
- fix description of "Spec to `STDOUT`, save JUnit XML files" (mentioned mochawesome before, probably copy / paste error from the next section)
- note why we need to install mocha-junit-reporter. I was confused why I couldn't use the junit reporter built into Cypress with the multi reporter setup
> Clarifications for reporters

- source/_changelogs/6.3.0.md
- source/api/plugins/browser-launch-api.md
- source/guides/core-concepts/writing-and-organizing-tests.md
- source/guides/references/configuration.md
- source/guides/references/roadmap.md
Initially addressing docs for https://github.com/cypress-io/cypress/pull/14431 but I think we can leave this open to see if more work will merge in for 6.3.0, to further update the download docs.
- I added a new section to 'writing and organizing tests' explaining 'Asset files'. 
- I wonder if the 'Screenshots and Videos' page should be repurposed to 'Asset Files' doc? I've always leaned against doing that because I felt people would search and understand screenshots/videos more easily.
- Change download directory: https://docs.cypress.io/api/plugins/browser-launch-api.html#Change-download-directory @chrisbreiding is this still relevant? Will this example work?
- FAQ about file download: https://docs.cypress.io/faq/questions/using-cypress-faq.html#Is-there-a-way-to-test-that-a-file-got-dow …
> File download updates

- source/guides/references/migration-guide.md
There is a mistake in one of the examples (there should be `intercept` instead of `route` command)
> Fix example in the route -> intercept migration guide

- source/guides/references/experiments.md
Adds `experimentalStudio` option to experiments page since this was just released in 6.3.0
> Add experimentalStudio to experiments page

- source/_changelogs/6.3.0.md
- source/api/commands/route.md
- source/api/commands/server.md
- source/guides/core-concepts/cypress-studio.md
- source/guides/references/roadmap.md
- add deprecated history to route and server (just noticed it)
- clarifying that ‘describe’ and ‘context’ blocks are required to
create a test
- linking to other docs
- being more specific about configurable files
- Add history table
> Updates to cy studio docs

- circle.yml
- closes #3450 
- seems every machine during parallel testing spins faster and a lot closer together in time
Before
The difference _when_ the specs start on each machine is due to attaching the workspace (and how long it takes to spin the container at first). By default, it can be very very different to attach workspace, see the 4 machines below. 
https://user-images.githubusercontent.com/2212006/105229055-5acf6b00-5b31-11eb-8242-e766539026e3.mp4
From CircleCI reply, the difference is due to the disk IO on CI machines being busy
After
Look at the attached workspace difference - it is a lot more uniform (and shorter), because the workspace is stored and used in memory via RAM disk
https://user-images.githubusercontent.com/2212006/105229149-7dfa1a80-5b31-11eb-9d02-603345d745c2.mp4
The …
> use ram disk on circleci

- source/guides/component-testing/introduction.md
I've updated links to example folders in the component section of the documentation: https://docs.cypress.io/guides/component-testing/introduction.html#What-is-Cypress-Component-Testing
The examples still pointed to the old cypres-vue-unit-test package, while that package was adopted by the `@cypress` organization a short time ago.
The "install" command for `yarn add` was also outdated, so it points to `@cypess/vue` too.
> Update cypress-vue-unit-test links to @cypress/vue

- source/_data/plugins.yml
Add cypress-msteams-reporter plugin to Cypress documentation.
> Add cypress-msteams-reporter to plugin.yml

- source/api/commands/intercept.md
https://github.com/cypress-io/cypress/pull/14822
> docs: delayMs -> delay

- source/guides/references/troubleshooting.md
Because users need help running Cypress with the debug logs
> add section explaining DEBUG areas

- source/api/commands/viewport.md
just noticed that we don't have this link, but the blog post is a really good demonstration of using viewport
> add link to the viewports blog post

- source/api/commands/writefile.md
we see this question periodically
tested in https://glebbahmutov.com/cypress-examples/6.5.0/commands/files.html#writing-combined-json-object
> add example appending json files

- source/guides/tooling/visual-testing.md
On the `toMatchImageSnapshot` example for visual testing, the documentation places the image settings on the top level of the configuration, like this:
```
cy.get('.todoapp').toMatchImageSnapshot({
threshold: 0.001,
})
```
The image settings must be inside the `imageConfig` object:
```
cy.get('.todoapp').toMatchImageSnapshot({
imageConfig: {
threshold: 0.001,
},
})
```
> Fix `toMatchImageSnapshot` example with image settings

- source/api/commands/submit.md
For https://github.com/cypress-io/cypress/pull/14965 (cy.submit validates inputs before sending data).
> Add note to submit doc about form validation

- content/guides/component-testing/getting-started.md
Some minor changes:
- the rest of the docs use npm, not yarn. I made this consistent in the CT guide.
- minor grammar improvements
- configuration for CT goes in `plugins/index.js` by default, not `support.js`.
> chore(docs): update CT docs

- source/api/commands/intercept.md
Reverts cypress-io/cypress-documentation#3526
See https://github.com/cypress-io/cypress/pull/15255 for reasoning
> docs: revert "delayMs -> delay"

- content/guides/component-testing/getting-started.md
- Highlight ‘Alpha’ stage more prominently in alert
- Be more specific about who is ‘we’, them’, ‘our’, ‘your’, ‘it’, in each sentence, remove when unnecessary.
- Don’t capitalize ‘component testing’ in any situation - it is not a brand name. I spoke with Amy to confirm this is the way we want to go.
- sourceMaps -> SourceMaps
- <alert> blocks have to have blank lines around them or the styles do not apply accurately. https://github.com/cypress-io/cypress-documentation/issues/3635
- set up vs setup
- other minor edits to improve readability or to be very clear during instructions.
> Some editing of content

- .circleci/config.yml
- .gitignore
- cy_scripts/scrape.js
- package.json
- yarn.lock
This will trigger the docsearch-scraper to run on each deploy from the next-docs branch. We will need to change this to only run on `master` once the next-docs branch is merged.
> feat: docsearch scraper running on next-docs branch

- content/settings.json
The previously used index name was meant for dev-only.
This uses the new index that the docsearch-scraper is updating.
> fix: algolia search index name

- package.json
- patches/github-slugger+1.3.0.patch
- yarn.lock
When icons were added to headers like so:
```md
```
the generated hash for the header appeared as `#icon-namearrow-hello-world`.
We don't want those icon things in hashes, so this patches the [`github-slugger`](https://github.com/Flet/github-slugger) package which is used by [`remark-autolink-headings`](https://github.com/remarkjs/remark-autolink-headings) to create the hashes from the markdown headers.
This strips the icon bits from headers that are preceded and/or followed by an icon.
The markdown content is parsed with [mdast-util-to-string](https://github.com/syntax-tree/mdast-util-to-string) then it is sluggified with `github-slugger`.
You can see that the `github-slugger` is creating these not-so-friendly hashes with this script:
```js
// index.js
var unified = require('unified') …
```
> fix: add patch for github-slugger to remove icons from hashes

- pages/guides/references/best-practices.vue
- pages/guides/references/changelog.vue
- pages/guides/references/error-messages.vue
Fixed:
`/guides/references/` pages now have appropriate meta tags
`/guides/references/` pages now appear selected in the sidebar when the user is currently on a references page
> fix: references pages sidebar

- source/api/commands/trigger.md
The existing example says to simulate a "Long Press" by triggering `mousedown` followed by a `wait` and then `mouseleave`. It should be `mousedown`, the `wait`, then `mouseup`.
> docs: correct Long Press example

- source/_partial/errors_anatomy.md
Removes a sentence that is repeated twice in the doc (see the line below).
ps: Congrats, your documentation is really good, it's such a pleasure to read and follow :tada:
> Remove duplicated sentence

- source/_partial/code_runs_in_node.md
- source/api/plugins/after-run-api.md
- source/api/plugins/after-screenshot-api.md
- source/api/plugins/after-spec-api.md
- source/api/plugins/before-run-api.md
- source/api/plugins/before-spec-api.md
- source/api/plugins/browser-launch-api.md
- source/api/plugins/configuration-api.md
- source/api/plugins/preprocessors-api.md
- source/api/plugins/writing-a-plugin.md
- source/guides/core-concepts/writing-and-organizing-tests.md
- source/guides/tooling/plugins-guide.md
- the plugin section was completely wrong, it was copy/paste error from support file :(
- added warnings for most of the pages that talk about plugins that the code is running in Node
> add partial to warn people that code in plugin file runs in Node

- content/faq/questions/using-cypress-faq.md
- content/guides/references/configuration.md
- added `cypress.json` section heading and rewrite that intro, since it was confusing
- added `findByTestId` to the answer
- partial solution to #3451
> add good result for cypress.json text search

- content/api/commands/wait.md
Update per `responseTimeout` in https://docs.cypress.io/guides/references/configuration#Timeouts
Closes DX-34
> Correct responseTimeout to proper default

- content/guides/dashboard/smart-orchestration.md
> Remove duplicated alert message regarding cancel test run on first failure

- content/guides/dashboard/introduction.md
- cypress/integration/guides.spec.js
Changes front matter title from "Introduction" to "Dashboard" on the dashboard introduction doc so the `docsearch-scraper` can index this page better for when users search "Dashboard"
> docs: change front matter header from Introduction to Dashboard

- content/api/commands/intercept.md
Updates per https://github.com/cypress-io/cypress-realworld-app/pull/676/commits/17741f7b66058036f823870d9d06e39131ee99d9
> fix: Update matching of RWA middleware intercept examples to match subroutes

- content/guides/references/migration-guide.md
Fix some broken links in the 7.x migration guide due to incorrect markdown.
> fix: update links in migration guide

- content/_changelogs/5.5.0.md
- content/_changelogs/6.1.0.md
- content/_changelogs/6.2.0.md
- content/_changelogs/6.4.0.md
- content/_changelogs/6.5.0.md
- content/_changelogs/6.7.0.md
- content/_changelogs/7.0.0.md
Several issues that were closed without a release are missing from the changelog. After landing this change, I will go through the relevant releases in our GitHub repo and will update them
> Document issues pending release and missing from the changelog

- content/api/commands/fixture.md
- closes #3814
- fixtures are loaded once
- JSON objects can use `import` instead of `cy.fixture` command for simplicity
> Add notes to the fixture command

- content/guides/getting-started/installing-cypress.md
Gleb pointed me to this undocumented feature: direct downloading an old version of Cypress. This commit aims to document it.
> Add the direct link for old version

- content/api/commands/get.md
Related with cypress-io/cypress#15020
> fix: Add doc for selecting an element with id that uses CSS characters.

- CONTRIBUTING.md
- content/guides/overview/snippet.md
- nuxt.config.js
- package.json
- scripts/remarkPartialPlugin.js
- yarn.lock
This PR introduces the concept of ✨  **partials** :sparkles: to the docs.
Partials are reusable markdown files that can be injected into other markdown files!
```md
<Alert type="info">
This is my partial.
</Alert>
```
If you want to import this partial into another markdown file, you can use the following syntax:
```md
::include{file=path/to/partial.md}
```
This is similar to the custom Hexo tags that existed in the previous docs: `{% partial foo %}`
For more info, see the updates to `CONTRIBUTING.md`.
The previous custom Hexo tags allowed users to pass arguments. The current partial system can be extended to allow users to pass arguments into the template. This could theoretically look like: `::include{file=path/to/file, $1=foo, $2=bar}` which can be handled inside …
> feat: reusable partials for markdown files

- cypress/support/index.js
ever since the move to `nuxt`, firefox tests (which run on TR CI on develop)have been failing:
looks like some uncaught exception that periodically gets thrown, but isn't under our control, so let's just ignore it
> chore: fix firefox uncaught:exception sometimes failing test

- content/faq/questions/using-cypress-faq.md
- Close #3879 
This is easily fixed but wondering how this happened to begin with and whether other links are affected.
> Fix: gh link with hash that has quotes around it.

- content/api/plugins/browser-launch-api.md
- content/api/plugins/configuration-api.md
- content/guides/tooling/plugins-guide.md
Looks like a bad merge occurred, resulting in duplicated warnings on several pages.
> fix: Removed duplicate plugin warnings

- content/guides/references/troubleshooting.md
After releasing v7.3.0 explains the new log source
https://github.com/cypress-io/cypress/pull/16238
> 7.3.0: add log source for ci info

- content/guides/tooling/visual-testing.md
Apologies if this is supposed to be reflected in the changelog. From what I interpreted since the change in documentation isn't due to a behavioural change this doesn't need to be in the changelog but let me know if that's wrong and I'll fix that!
While reading the docs on visual testing under this section: https://docs.cypress.io/guides/tooling/visual-testing#Application-state
I noticed this block of code:
```js
cy.intercept('/api/items', { fixture: 'items' }).as('getItems')
// ... action
cy.wait('@getUsers')
cy.mySnapshotCommand()
```
Almost certain the intention was to have `cy.wait('@getItems')`.
> Fix typo in visual testing guide

- content/guides/getting-started/installing-cypress.md
```
[ ] Bug report
[x] Content update
[ ] Process update (build, deployment, ... )
```
I was trying to get started with cypress (thanks for the great talk at VueConf2021!). 
https://docs.cypress.io/guides/getting-started/installing-cypress#System-requirements
I wanted to use docker, which took me to:
```
We also have an official cypress/base Docker container with all of the required dependencies installed.
```
Which goes to:
https://hub.docker.com/r/cypress/base/
On that page in the Sample Dockerfile it shows:
```
cypress/base:10
```
Seems obvious now (rookie mistake!), but I didn't catch that the suffix corresponds to the version of node. Node 10 isn't compatible with the latest version of cypress, so when I tried to add cypress in the container with `yarn add cypress --dev`, it failed. …
> update docker usage notes

- nuxt.config.js
- package.json
- yarn.lock
See: https://github.com/harlan-zw/nuxt-build-optimisations
I'm the author of the above module. While submitting a PR for a windicss fix (https://github.com/cypress-io/cypress-documentation/pull/3903), I noticed the build was really slow.
This speeds it up a bit, the biggest improvement is via esbuild running for local builds. You can get even better speeds if you were to put it in risky mode in development and use windi css over the tailwind module.
Some stats on my machine:
**Original - Cold**
**After Module - Cold**
**After Module - Hot**
> feat: add nuxt-build-optimisations module

- nuxt.config.js
- package.json
- yarn.lock
See: https://github.com/windicss/windicss-webpack-plugin/issues/42
There is an additional issue minus the vue-processor, windi does not have first-class support for scss files, when you import the content in your vue style blocks it doesn't allow the @apply's to be passed .
Not sure if there's a specific reason why the page layouts are setup the way they are, but I would recommend creating new layout file and have the windi classes used within the template, this would reduce a lot of boilerplate and simplify your styling.
> chore: remove windi vue-preprocessor

- nuxt.config.js
- package.json
- plugins/fullstory.client.js
- yarn.lock
Closes [DX-220](https://linear.app/cypress/issue/DX-220/add-fullstory-to-docs-site).
PR adds `@fullstory/browser` so that we can see user sessions in FS. Before merging, a new env variable will need to be added `FULLSTORY_ORG_ID=ZVWG5`
> feat: add fullstory to documentation site

- content/guides/continuous-integration/gitlab-ci.md
Cypress by default caches its binaries to `~/.cache`, but since this can't be cached by GitLab CI the docs suggests to change the cache directory like this: `CYPRESS_CACHE_FOLDER: "$CI_PROJECT_DIR/cache/Cypress"`.
It then tells you to cache the new cache directory: `- cache/Cypress`. This means that caching `.cache/*` is superfluous.
> Remove superfluous reference to .cache

- content/guides/core-concepts/writing-and-organizing-tests.md
Adds a missing s in Cypress to the writing and organizing tests page
> fix: typo on writing and organizing tests page

- content/guides/migrating-to-cypress/protractor.md
This todo was meant to be a temporary note-to-self while writing the Protractor migration guide. Oops. This can be safely removed.
> fix: remove todo comment in protractor guide

- content/guides/guides/screenshots-and-videos.md
- content/guides/guides/test-retries.md
I’ve had people open this issue a few times now, asking for a feature to also upload videos for retried tests:
- https://github.com/cypress-io/cypress/issues/16377
- https://github.com/cypress-io/cypress/issues/16672
- https://github.com/cypress-io/cypress/issues/16681
This is actually already possible, but I don’t think people are finding it since it’s in the [‘after:spec’ API page](https://docs.cypress.io/api/plugins/after-spec-api#Examples). Why would anyone look there?
- This adds the example to the ‘Screenshots & Videos’ page as well as ‘Test Retries’. 
- It also frames the example as ‘upload video on test retries’ instead of ‘delete videos that didn’t pass’, which is less direct on the intent. 
- **Question:** Is there a way to reuse snippets of the docs? We have this same exact …
> Add examples for how to upload videos for retried tests

- content/_data/plugins.json
I don’t think the `cypress-plugins-retries` should be listed in our plugins as a verified plugin anymore. 
- The plugin is archived and no longer maintained.
- We have test retries built in and recommend people migrate off of this plugin from our migration guide.
> Remove cypress-plugin-retries from plugins

- content/_changelogs/7.5.0.md
> 7.5.0 Release

- content/_changelogs/7.6.0.md
- content/_data/en.json
- content/_data/sidebar.json
- content/api/commands/type.md
- content/api/cypress-api/keyboard-api.md
- content/guides/core-concepts/writing-and-organizing-tests.md
- cypress/integration/api.spec.js
For https://github.com/cypress-io/cypress/pull/15683. Requires changes for `on.cypress.io` in https://github.com/cypress-io/cypress-services/pull/3859 to be deployed.
> Add Cypress.Keyboard doc

- content/guides/component-testing/framework-configuration.md
- content/guides/component-testing/introduction.md
- content/guides/references/migration-guide.md
Due to changes in https://github.com/cypress-io/cypress/pull/16885
> Remove examples where returning config should no longer be necessary

- content/guides/guides/web-security.md
- content/guides/references/client-certificates.md
- content/guides/references/configuration.md
- Fix links that did not go to client-certificates doc
- Add History to client certs and config pages to specify when this feature is added
- Fix reference of where this should live (should be cypress.json, not cypress.env.json)
- Rearrange Syntax
I’m on the fence about my updates to the Syntax section. I like tables for the properties, but maybe this isn’t clearer than  the  list before? Thoughts?
> docs: Update client certificates docs

- content/guides/core-concepts/test-runner.md
- nuxt.config.js
copy and crosshairs icons were missing from test runner page.
> fix: add two missing icons to test runner docs

- content/api/commands/exec.md
> <img width="713" alt="image" src="https://user-images.githubusercontent.com/12410942/125421918-8778e246-3b19-49b4-95b3-7bab82bef4bd.png">
>
> https://docs.cypress.io/api/commands/exec#Options
> fix typo for cy.exec() example

- package.json
- yarn.lock
Just wanted to trigger a new run with the new Cypress version to see if there are performance improvements in specfile runtimes.
> Update to Cypress 8.1.0

- content/guides/component-testing/framework-configuration.md
This PR updates the documentation that was originally resulting in the following error:
PS: It's also based on: https://github.com/cypress-io/cypress-component-examples/blob/main/nuxt-vue-2-cypress/cypress/plugins/index.js
```
Error [TypeError]: Promises are not supported
at mergeWithOptions (/Users/jonathan/Documents/xxxx/node_modules/webpack-merge/dist/index.js:67:19)
at Object.merge (/Users/jonathan/Documents/xxxx/node_modules/webpack-merge/dist/index.js:52:35)
at Object.<anonymous> (/Users/jonathan/Documents/xxxx/node_modules/@cypress/webpack-dev-server/dist/makeWebpackConfig.js:89:46)
at Generator.next (<anonymous>)
at /Users/jonathan/Documents/xxxx/node_modules/@cypress/webpack-dev-server/dist/makeWebpackConfig.js:27:71
at new Promise (<anonymous>)
at __awaiter …
```
> Nuxt config example: Wait for getWebpackConfig() to resolve

- content/_data/en.json
- content/_data/sidebar.json
- content/api/cypress-api/currenttest.md
- cypress/fixtures/sidebar-overrides.json
Add page to explain what Cypress.currentTest does technically. For https://github.com/cypress-io/cypress/pull/16652
I’d love this to have better examples of *why* someone would use this. Could likely look at https://github.com/cypress-io/cypress/issues/2972 for examples.
> Add page for Cypress.currentTest

- content/guides/guides/screenshots-and-videos.md
Setting `videoCompression` to 0 results in a broken video. It’s a bug and we shouldn’t show it as an example of usage: https://github.com/cypress-io/cypress/issues/5191
> Remove example of videoCompression 0

- content/guides/references/migration-guide.md
This fixes a small typo, where the Migration Guide for 8.0 erroneously references migration to Cypress 7.0
`This guide details the changes and how to change your code to migrate to Cypress 7.0. See the full changelog for 8.0.`
`This guide details the changes and how to change your code to migrate to Cypress 8.0. See the full changelog for 8.0.`
> fix(migration-guide): typo migration guide for 8.0 references 7.0

- content/faq/questions/using-cypress-faq.md
The current link goes to an issue that was closed as a duplicate. The currently open issue has recent activity on it, might as well link straight there :)
> Update iframe open issue link

- components/AppHeaderMobileSection.vue
The broken links in the mobile nav were caused by the link items in the `_data/sidebar.json` not having a slug property. I updated the `AppHeaderMobileSection.vue` component to also render items if they have a redirect property to fix the broken links.
> fixed broken links in mobile nav

- content/guides/references/best-practices.md
Hello, I found Markdown markup errors on [Best Practices | Cypress Documentation](https://docs.cypress.io/guides/references/best-practices#Real-World-Example-1).
> Fix markup errors on `best-practices.md`

- package.json
This is to ensure that json files that are modified will be formatted properly before commit.
> added json files to lint-staged 

- content/api/commands/click.md
Looks like the folder structure changed at some point. This link points to the first of the `click()` examples.
> Fixes broken link on click.md

- content/api/commands/intercept.md
- content/guides/core-concepts/writing-and-organizing-tests.md
- content/guides/guides/network-requests.md
After https://github.com/cypress-io/cypress-documentation/pull/4092 was merged it occurred to me that there might be more instances of that link needing updating. Found some with a quick search that I wish I'd performed sooner! 😄 Also noticed that some text and the example folder structure did not reflect the new ways.
Hopefully the rest of the wording on [Writing and Organizing Tests](https://github.com/cjbramble/cypress-documentation/blob/212f996ee194139d5d0708a6b39eda0bf02bfca7/content/guides/core-concepts/writing-and-organizing-tests.md) is still sound with the updates. Seemed fine to me from my skimming.
> Update more kitchensink links and folder structure example.

- content/api/commands/select.md
Link to implementation: https://github.com/cypress-io/cypress/pull/18201
Updated docs to reflect new argument `index` which can be used to select an option by index within the `select()` command.
> Add Select By Index

- content/guides/dashboard/users.md
closes #4112 
Adding step-by-step instructions for Basic and Social login. Redirects to [Enterprise SSO Guide](https://docs.cypress.io/guides/dashboard/organizations#Enterprise-SSO) for SSO instructions
> adding Sign Up instructions

- scripts/remark-directives.js
- scripts/remark-directives.test.js
Because the alternative is to wait a really long time between pressing `Ctrl-C` and waiting for `yarn start` to complete
> Allow reloading directives while developing with `yarn start`

- content/guides/guides/environment-variables.md
This PR has 2 goals:
1. Show that the plugins stuff is deprecated and update the config example
2. Move as much of the Configuration -> Overriding Options -> Environment content into the CYPRESS_* section of this document so the former can be simplified and just link here and also because these docs were pretty confusing TBQH
Preview https://deploy-preview-4130--cypress-docs.netlify.app/guides/guides/environment-variables
> [UNIFY-411] Improve environment variables guide

- content/guides/component-testing/framework-configuration.md
- scripts/directives/cypress-config-plugin-example.js
- scripts/directives/helpers/example-helpers.js
- scripts/remark-directives.js
Update all Component Testing Framework Configuration examples to have **cypress.config.js** / **cypress.config.ts** / **cypress.json & plugins file** tabs via a new `:::cypress-config-plugin-example` directive, which will allow us to show _all_ CT configuration in a single tabbed example.
Note that this does not address any issues with or examples on the CT Introduction page. That will likely need a significant rewrite.
Preview
https://deploy-preview-4137--cypress-docs.netlify.app/guides/component-testing/framework-configuration
> [UNIFY-416] Update Component Testing docs

- content/guides/testing-strategies/auth0-authentication.md
> Fix docs(auth0): fix typo in auth0 guide

- content/api/commands/select.md
Link to related PR: https://github.com/cypress-io/cypress/pull/18329
Update `cy.select()` command to accept an empty array argument. This enables users to clear all selected options for a multi-value select.
> Add note about unselecting all selected options with cy.select([])

- content/guides/guides/command-line.md
Since it's section about `cypress open` the `open` command should be used instead of `run`. Related issue: https://github.com/cypress-io/cypress/issues/18712
> Change `run` to `open` Cypress command

- content/api/plugins/writing-a-plugin.md
- content/faq/questions/using-cypress-faq.md
- content/guides/references/configuration.md
- content/guides/tooling/plugins-guide.md
As a part of issue [#18684](https://github.com/cypress-io/cypress/issues/18684), This PR updates the documentation to declare the `nodeVersion` config as deprecated as well as explain the default `system` and behaviour, to use the same node binary that was used to launch cypress from the cli.
> Deprecation updates for the `nodeVersion` config option 

- components/sidebar/CollapsibleSidebarSection.vue
- content/_data/sidebar.json
- content/guides/getting-started/component-framework-configuration.md
- content/guides/getting-started/creating-a-cy-mount-command.md
- content/guides/getting-started/getting-components-to-work.md
- content/guides/getting-started/rendering-components-correctly.md
- content/guides/getting-started/writing-your-first-component-test.md
- content/guides/getting-started/writing-your-first-end-to-end-test.md
- cypress/fixtures/sidebar-overrides.json
- cypress/integration/test-utils/index.js
https://cypress-io.atlassian.net/browse/UNIFY-393
Preview:
https://deploy-preview-4193--cypress-docs.netlify.app/guides/getting-started/component-framework-configuration
Notes:
* Updated sidebar to render items without `slug` or `redirect` as subheaders (styling needed, we can also totally rework this, I just needed a starting point)
* Tweaked titles of the existing E2E Getting Started content
* Moved existing Component Testing > Framework Configuration content to the Getting Started section
* Created stub pages for other Getting Started pages
> UNIFY-393 CT Getting Started Guide page 1: Framework Selection & Configuration

- content/guides/references/migration-guide.md
Modify to correct link
https://docs.cypress.io/guides/references/migration-guide#Migrating-to-Cypress-7-0
> docs: fix broken link

- content/guides/core-concepts/retry-ability.md
This section (https://docs.cypress.io/guides/core-concepts/retry-ability#Merging-queries) mentions applying a `cy.get()` followed by a `.find()`. However, the code sample following that text doesn't use `.find()`.
So I updated the text to match the example.
> clarify text to match the example that follows.

- scripts/remark-directives.js
Quick fix to rectify a borked merge when `UNIFY-506` came into `unification`.
> Post UNIFY-506 merge fix

- patches/github-slugger+1.3.0.patch
- patches/github-slugger.test.js
I was hoping for a more generic solution, but our patch to github-slugger is quite involved. I just added a few extra things to it to remove these anchors.
Examples:
- https://deploy-preview-4229--cypress-docs.netlify.app/api/commands/session#Where-to-call-cy-visit
- https://deploy-preview-4229--cypress-docs.netlify.app/api/commands/session#Where-to-call-cy-mount
TODO:
> UNIFY-619 Remove E2EOnlyBadge and ComponentOnlyBadge from anchors

- content/guides/guides/command-line.md
https://discord.com/channels/755913899261296641/763114122065739818/912481091582050354
```shell
$ yarn open
yarn run v1.22.10
error Command "open" not found.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```
```shell
$ yarn cypress open
yarn run v1.22.10
$ ./node_modules/.bin/cypress open
```
> fix yarn command in command-line guide

- content/_changelogs/1.0.2.md
- content/_changelogs/1.0.3.md
- content/_changelogs/3.3.2.md
We use to attribute some users, but these generated links no longer work and we don’t do this anymore.
> Remove user links which no longer work from old contributing guides.

- content/_changelogs/6.2.0.md
- content/_changelogs/6.7.0.md
This section was displaying weird in the changelog
> Fix display of links in changelog

- content/api/cypress-api/dom.md
- content/api/plugins/writing-a-plugin.md
- This fixes a couple of broken links caused by the typescript migration
closes #4232
> docs: fix broken links caused by ts migration

- content/guides/getting-started/installing-cypress.md
- content/guides/guides/command-line.md
New docs are associated with: https://github.com/cypress-io/cypress/issues/18290
> Adding info for CYPRESS_VERIFY_TIMEOUT

- content/api/commands/intercept.md
> docs: Correct `Cypress.minimatch()` examples.

- content/_changelogs/9.0.0.md
Changes:
On changelog version 9.0.0, the link is incorrect when clicked from the changelog page (error 404 page not found). Corrected the link path link from `issues` to `pull`:
https://github.com/cypress-io/cypress/pull/17496
> fix: incorrect link in changelog 9.0.0

- content/api/commands/visit.md
basUrl should be changed to baseUrl
See https://github.com/cypress-io/cypress-documentation/issues/4290
> docs: fix basUrl misspelling

- content/api/commands/visit.md
I stumbled across a very minor typo as I was reading the documentation for `visit`. 
basUrl should be baseUrl
> Fix typo in visit.md

- content/_data/sidebar.json
- content/api/commands/intercept.md
Not sure what happened, but it looks like we missed this:
https://github.com/cypress-io/cypress-documentation/pull/4000/files#diff-ab25dcf4c3f26cce920439aa09a12fddb2bc64146d5d7411e174f30daf65d448L771-L774
Thanks to @jaffrepaul for spotting this!
> Fix a few minor issues

- content/guides/references/migration-guide.md
We've discovered an oversight with selectFIle(), and want to add the fact that it's not supported to the migration guide. For more details, see https://github.com/cypress-io/cypress/issues/19751.
This is a quick-fix while we work on an actual solution (supporting mimeType)
> Updates to selectFile migration guide

- content/api/commands/selectfile.md
Matching code PR: https://github.com/cypress-io/cypress/pull/19794
`.selectFile()` automatically infers the mime type of files based on their extension, and allows users to set it explicitly using the `mimeType` property on files.
In addition, users can specify the file contents with any `TypedArray` instance. Previously only instances of `Cypress.Buffer` were supported.
Example:
```
cy.get('input[type=file]').selectFile({
contents: Uint8Array.from('567'),
mimeType: 'text/plain',
})
```
> Add mimeType property and ArrayBuffer support

- content/api/commands/selectfile.md
- content/guides/references/migration-guide.md
Matching code PR: https://github.com/cypress-io/cypress/pull/19820
I struggled a bit to find a good way to document this change, mostly because it "just works" the way you expect, whereas the previous behavior was the surprising bit.
> Issue-19803: Use filename on disk when referring to fixtures

- content/_data/plugins.json
Updates the Nx plugin, adjusting the tagline and links to the docs covering Cypress :)
> plugins: update Nx tagline and links

- content/api/commands/shadow.md
Related with cypress-io/cypress#19260. 
It's an `awaiting external fix` problem that won't be fixed soon. So, I added this known issue section.
> Add the known issue section for `cy.shadow()` and `cy.click()` problem.

- content/api/commands/screenshot.md
- content/guides/core-concepts/writing-and-organizing-tests.md
This PR updates the docs to reflect the new generated asset file saving behavior
Closes UDX-6
> docs: update how screenshots and videos are stripped of common ancestors

- content/guides/core-concepts/writing-and-organizing-tests.md
This PR removes the "Run All" tests and "Run Filtered Specs" references since those are features no longer supported in `10.0` and removed from the Cypress App.
> docs: remove run all and run filtered specs documentation

- content/examples/examples/applications.md
- content/guides/dashboard/introduction.md
Once cypress-io/cypress#20186 merges, phonecat and piechopper will be archived. Since we will not be maintaining them going forward our docs should not reference them.
> docs: remove piechopper/phonecat references

- content/faq/questions/using-cypress-faq.md
https://cypress-documentation-git-fix-broken-cucumber-link-cypress-io.vercel.app/faq/questions/using-cypress-faq
> fix: remove link to example repo that no longer exists

- content/guides/testing-strategies/google-authentication.md
This PR:
- fixes a small typo in the google auth testing strategy guide
> fix(guides): fix typo in google auth testing strategy

- content/_data/courses.json
I am the author of the cypress class on Udemy - Cypress: From Zero To Hero
Adding the reference to this class to the Courses page. For some reason didn't do it earlier.
Thank you
>  docs: udemy class added to the courses list

- content/guides/testing-strategies/auth0-authentication.md
1. Fix `Cypress.env` args in the example `cy.loginByAuth0Api` usage to match the keys suggested in the plugins/index.js file
2. Remove extraneous `D` from `process.env.AUTH0_CLIENT_SECRET`
> Fix Cypress.env args and typo

- content/guides/getting-started/installing-cypress.md
> docs: remove note about clearing cache when installing pre-releases

- styles/content.css
https://cypress-io.atlassian.net/browse/UDX-132
Reset CSS that is squishing h3 & h4 subheaders that include content wrapped in back ticks.
> UDX-132-fix-subheader-styles

- content/api/commands/and.md
- content/api/commands/should.md
- content/api/commands/then.md
- content/partials/then-should-and-difference.md
https://cypress-io.atlassian.net/browse/UDX-133
Content cleanup/streamline maneuver to move repeated content into small partials.
> UDX-133-content-partials

- content/guides/getting-started/installing-cypress.md
This was recently changed to improve the experience for users trying out the 10.0-release pre-releases.
> docs: update pre-release expiry info

- content/guides/continuous-integration/ci-provider-examples.md
LayerCI is now webapp.io, changing the reference in the docs here & adding some more documentation on how to use webapp.io with cypress.
> Updating CI Integrations in docs - LayerCI is now webapp.io :)

- content/_data/plugins.json
This PR adds the Cypress Chrome Recorder that was released today to our plugins page
> feat(plugins): add cypress chrome recorder to plugins page

- content/guides/core-concepts/cypress-app.md
- content/guides/core-concepts/retry-ability.md
- content/guides/core-concepts/variables-and-aliases.md
- content/guides/core-concepts/writing-and-organizing-tests.md
- content/guides/getting-started/writing-your-first-end-to-end-test.md
- content/guides/overview/why-cypress.md
- content/guides/references/best-practices.md
https://cypress-io.atlassian.net/browse/UDX-161
First pass at updating selectors in code examples to align with our best practices. Specifically, [this issue](https://github.com/cypress-io/cypress-documentation/issues/4227).
> UDX-161-example-selector-updates

- content/api/commands/session.md
Fixed what looks like a typo in the cy.session docs - as far as I can tell, `cy.setup()` is not a method that exists - I think the author meant `cy.session()`?
> Fixed typo in session.md

- content/_changelogs/9.6.2.md
- content/_changelogs/9.7.0.md
- content/api/cypress-api/cookies.md
Note: The Electron 18 dependency upgrade bumps this release version to 9.7.0. The git branch does not reflect the correct release version.
> 9.7.0 Release

- content/_data/sidebar.json
- content/guides/references/experiments.md
Note that this PR does not remove the `Cypress Studio` page itself, as specified by the referenced ticket.
> UDX-201: Remove Studio from docs

- content/_data/sidebar.json
- content/guides/core-concepts/cypress-studio.md
It's been decided to put Cypress Studio back in the sidebar & add a warning alert to the top of the page noting its removal.
> UDX-201: Restore studio to sidebar & add removal notice

- components/global/NavGuide.vue
This PR fixes a bug where the NavGuide buttons (e.g. at the bottom of the Vue Component Testing pages) had a dotted bottom border.
> Fix bug in NavGuide bottom border styling

- content/_data/sidebar.json
- content/api/commands/session.md
- content/api/commands/stub.md
- content/api/cypress-api/testing-type.md
- content/api/plugins/configuration-api.md
- content/guides/component-testing/component-framework-configuration.md
- content/guides/component-testing/events-vue.md
- content/guides/component-testing/mounting-react.md
- content/guides/component-testing/mounting-vue.md
- content/guides/continuous-integration/aws-codebuild.md
- content/guides/core-concepts/cypress-app.md
- content/guides/core-concepts/testing-types.md
- content/guides/core-concepts/writing-and-organizing-tests.md
- content/guides/getting-started/opening-the-app.md
- content/guides/guides/debugging.md
- content/guides/references/best-practices.md
- content/guides/references/configuration.md
This PR attempts to regularize usage of the terms "end-to-end" and "E2E" across the docs. This required some subjective and possibly tendentious linguistic calls. My reasoning is as follows:
- The proper noun referring to the **practice** is "E2E Testing"
- The name of the Cypress **feature** is also "E2E Testing"
- The adjective used to denote the type of a test or tests is "end-to-end"
- "end-to-end" in title case is "End-to-End"
- When explaining the concept to people who may not have heard it, prefer "end-to-end", possibly with the acronym in brackets
Examples of correct usage:
- "Choose the E2E Testing option"
- "Writing your first end-to-end test"
- "What is End-to-End (E2E) Testing?"
There are some exceptions, but these are the principles I've tried to follow. I've also avoided …
> UDX-165: Correct usage of end-to-end vs E2E across docs

- content/_changelogs/10.0.0.md
- content/_data/sidebar.json
This PR lints the `10.0 changelog` as it is causing circle to fail.
> chore: lint 10.0 changelog

- .prettierrc
Not sure how config defaults work but maybe this is getting overridden by people's personal settings? Can't hurt anyway.
> Specify line length in prettier config

- content/guides/references/migration-guide.md
This PR adds the fantastic v10 migration walkthrough video by Jordan to the top of the Migration Guide page. This should be removed once the next guide is added to this page.
> Add Migrating to v10 video to Migration Guide
